### ISSUE TITLE
Installing: /bin/sh: 1: redis-server: not found

### ISSUE THREAD

**Issue by emcniece** [frappe/frappe_docker#1]
Following the setup instructions in the README. Looks like the script is expecting to find Redis at a particular hostname that is not aliased in the Docker stack. At the `bench init frappe-bench` step:

```
# [... pip upgrade, git clone, NPM install etc]

Wrote css/frappe-web.css - 65.05 KB
Wrote js/frappe-web.min.js - 137.98 KB
Wrote js/dialog.min.js - 104.44 KB
Wrote css/desk.min.css - 291.98 KB
Wrote css/frappe-rtl.css - 32.37 KB
Wrote js/libs.min.js - 815.22 KB
Wrote js/desk.min.js - 510.13 KB
Wrote js/d3.min.js - 380.17 KB
Wrote css/module.min.css - 2.08 KB
Wrote css/form.min.css - 4.47 KB
Wrote js/form.min.js - 192.87 KB
Wrote css/list.min.css - 14.43 KB
Wrote js/list.min.js - 139.01 KB
Wrote css/report.min.css - 7.89 KB
Wrote js/report.min.js - 257.16 KB
Wrote js/web_form.min.js - 247.22 KB
Wrote css/web_form.css - 24.42 KB
Wrote js/print_format_v3.min.js - 23.39 KB
/bin/sh: 1: redis-server: not found
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench-repo/bench/commands/make.py", line 21, in init
    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)
  File "/home/frappe/bench-repo/bench/utils.py", line 78, in init
    redis.generate_config(path)
  File "/home/frappe/bench-repo/bench/config/redis.py", line 39, in generate_config
    "redis_version": get_redis_version(),
  File "/home/frappe/bench-repo/bench/config/redis.py", line 59, in get_redis_version
    version_string = subprocess.check_output('redis-server --version', shell=True).strip()
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'redis-server --version' returned non-zero exit status 127

# Just seeing what's available...
frappe@9761a4d8f053:~/frappe-bench$ ping redis
ping: unknown host redis

frappe@9761a4d8f053:~/frappe-bench$ ping redis-cache
PING redis-cache (192.168.48.4) 56(84) bytes of data.
64 bytes from redis-cache.frappedocker_default (192.168.48.4): icmp_seq=1 ttl=64 time=0.304 ms
64 bytes from redis-cache.frappedocker_default (192.168.48.4): icmp_seq=2 ttl=64 time=0.083 ms
^C
--- redis-cache ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.083/0.193/0.304/0.111 ms
```

Which of the 3 Redis instances is `redis-server` supposed to be?

**Comment by emcniece** [comment]
`redis-server` is perhaps expecting `redis` to be installed locally.

`bench init frappe-bench/ --skip-redis-config-generation` works - continuing with install to see if it functions.

**Comment by emcniece** [comment]
After executing `bench start` an error is thrown:

```
frappe@1955d87ea4ab:~/frappe-bench/frappe-bench$ bench start
2017-08-21 22:16:39 [135] [WARNING] Your terminal is not configured to receive UTF-8 encoded text. Please adjust your locale settings or force UTF-8 output by setting PYTHONIOENCODING="utf-8".
22:16:39 system           | socketio.1 started (pid=166)
22:16:39 system           | redis_queue.1 started (pid=157)
22:16:39 redis_queue.1    | /bin/sh: 1: redis-server: not found
22:16:39 system           | redis_queue.1 stopped (rc=127)
22:16:39 system           | redis_cache.1 started (pid=167)
22:16:39 redis_cache.1    | /bin/sh: 1: redis-server: not found
22:16:39 system           | redis_cache.1 stopped (rc=127)
22:16:39 system           | worker_long.1 started (pid=159)
22:16:39 system           | redis_socketio.1 started (pid=152)
22:16:39 redis_socketio.1 | /bin/sh: 1: redis-server: not found
22:16:39 system           | redis_socketio.1 stopped (rc=127)
22:16:39 system           | watch.1 started (pid=156)
22:16:39 system           | worker_default.1 started (pid=164)
22:16:39 system           | worker_short.1 started (pid=165)
22:16:39 system           | schedule.1 started (pid=163)
22:16:39 system           | web.1 started (pid=162)
22:16:39 system           | sending SIGTERM to worker_long.1 (pid 159)
22:16:39 system           | sending SIGTERM to watch.1 (pid 156)
22:16:39 system           | sending SIGTERM to web.1 (pid 162)
22:16:39 system           | sending SIGTERM to schedule.1 (pid 163)
22:16:39 system           | sending SIGTERM to worker_default.1 (pid 164)
22:16:39 system           | sending SIGTERM to socketio.1 (pid 166)
22:16:39 system           | sending SIGTERM to worker_short.1 (pid 165)
22:16:39 system           | schedule.1 stopped (rc=-15)
22:16:39 system           | watch.1 stopped (rc=-15)
22:16:39 system           | worker_default.1 stopped (rc=-15)
22:16:39 system           | worker_long.1 stopped (rc=-15)
22:16:39 system           | worker_short.1 stopped (rc=-15)
22:16:39 system           | web.1 stopped (rc=-15)
22:16:39 system           | socketio.1 stopped (rc=-15)
```

This highlights two problems: first that `redis-server` is not installed, and second that `Procfile` expects to find config files at `config/redis_*.conf`.

Since `bench init` was run with the `--skip-redis-config-generation` I'm guessing these config files were not generated.

**Comment by sunhoww** [comment]
Using _Procfile_docker_ and _sites/common_sites_config_docker.json_ contained in the _frappe-bench_ volume fixed this for me.

**Comment by emcniece** [comment]
@sunhoww how exactly do you specify these files?

**Comment by sunhoww** [comment]
It's in _~/frappe-bench_ of the frappe container. You would have to rename both files to the proper names.
Just removing the __docker_ from the filenames would do.

**Comment by emcniece** [comment]
Confirmed - copying the files over makes the app run properly within the container environment.

However the install step still fails when `redis-server` is not present. `Command 'redis-server --version' returned non-zero` means that it's checking for the existence of this package, so it must be installed in the Dockerfile with the other packages.

**Comment by sunhoww** [comment]
Yes. _redis_cache_, _redis_socketio_, _redis_queue_ are already containers and linked to the frappe container.

Instead of the _~/frappe_bench_ directory, I `cd ..` to _~_ and the command I used was actually

```
bench init --skip-bench-mkdir --skip-redis-config-generation frappe-bench
```

**Comment by emcniece** [comment]
Aha, good to know. Thank you @sunhoww for confirming this!

**Comment by vishalseshagiri** [comment]
Yes --skip-redis-config-generations points frappe to the redis containers(cache, queue and socket-io) instead of running a redis-server instance in your container

**Comment by emcniece** [comment]
@vishalseshagiri The bigger problem is that the documentation for this repo does not detail this to users.

**Comment by vishalseshagiri** [comment]
The bench init command has been updated on the README, pls check it out @emcniece and thanks for bringing it to our notice.

**Comment by emcniece** [comment]
@vishalseshagiri I have a bad feeling about the `--skip-bench-mkdir` flag. @sunhoww was using this because they already installed the app, but people going through these steps for the first time may not have directories created properly.

I haven't confirmed this yet - these steps need to be tested!

**Comment by vishalseshagiri** [comment]
This repo already has the template for frappe-bench with the Procfile and the sites directory inside it. One needs to use this as is, no modifications required

**Comment by sunhoww** [comment]
`docker exec -it frappe bash` drops into _~/frappe_bench_. This happens to be the **WORKDIR** set in _Dockerfile_. So if you `bench init frappe_bench` here, you'd end up with _~/frappe_bench/frappe_bench_ as the your bench directory. I was just suggesting that maybe it's much cleaner to execute the init from _~_.

The **WORKDIR** also happens to be a volume shared with the host, so it should be available to new users as well when you clone this repo.

**Comment by emcniece** [comment]
@sunhoww indeed - and this is exactly what the README tells users, who (like myself) end up with the `~/frappe-bench/frappe-bench/` structure, which fails to install.

Also, the recent commit of `bench init --skip-bench-mkdir --skip-redis-config-generation frappe-bench` needs a `&& cd frappe-bench` at the end.

**Comment by vishalseshagiri** [comment]
@sunhoww the WORKDIR contains all your app and site installations. Sharing them as a part of the repo is  very counter intuitive.

**Comment by sunhoww** [comment]
@vishalseshagiri oh. I meant the _/frappe_bench_ already in _this_ repo, which is being shared as volume with the frappe container.

**Comment by carlos22** [comment]
I strictly followed the documentation (as of today) using `bench init --skip-bench-mkdir --skip-redis-config-generation frappe-bench && cd frappe-bench`, still getting the same error. Any hints?

**Comment by vishalseshagiri** [comment]
@carlos22 could you post a screenshot of your error here?

**Comment by carlos22** [comment]
```
frappe@36826e694208:~/frappe-bench$ bench start
2017-08-28 09:48:53 [31] [WARNING] Your terminal is not configured to receive UTF-8 encoded text. Please adjust your locale settings or force UTF-8 output by setting PYTHONIOENCODING="utf-8".
09:48:53 system           | worker_long.1 started (pid=53)
09:48:53 system           | redis_socketio.1 started (pid=51)
09:48:53 redis_socketio.1 | /bin/sh: 1: redis-server: not found
09:48:53 system           | redis_socketio.1 stopped (rc=127)
09:48:53 system           | schedule.1 started (pid=58)
09:48:53 system           | watch.1 started (pid=56)
09:48:53 system           | worker_default.1 started (pid=60)
09:48:53 system           | web.1 started (pid=59)
09:48:53 system           | redis_queue.1 started (pid=57)
09:48:53 redis_queue.1    | /bin/sh: 1: redis-server: not found
09:48:53 system           | redis_queue.1 stopped (rc=127)
09:48:53 system           | socketio.1 started (pid=61)
09:48:54 system           | worker_short.1 started (pid=62)
09:48:54 system           | redis_cache.1 started (pid=63)
09:48:54 system           | sending SIGTERM to worker_long.1 (pid 53)
09:48:54 system           | sending SIGTERM to watch.1 (pid 56)
09:48:54 system           | sending SIGTERM to web.1 (pid 59)
09:48:54 system           | sending SIGTERM to schedule.1 (pid 58)
09:48:54 system           | sending SIGTERM to worker_default.1 (pid 60)
09:48:54 system           | sending SIGTERM to socketio.1 (pid 61)
09:48:54 system           | sending SIGTERM to redis_cache.1 (pid 63)
09:48:54 system           | sending SIGTERM to worker_short.1 (pid 62)
09:48:54 redis_cache.1    | /bin/sh: 1: redis-server: not found
09:48:54 system           | redis_cache.1 stopped (rc=127)
09:48:54 system           | schedule.1 stopped (rc=-15)
09:48:54 system           | web.1 stopped (rc=-15)
09:48:54 system           | socketio.1 stopped (rc=-15)
09:48:54 system           | worker_short.1 stopped (rc=-15)
09:48:54 system           | worker_long.1 stopped (rc=-15)
09:48:54 system           | watch.1 stopped (rc=-15)
09:48:54 system           | worker_default.1 stopped (rc=-15)
```

**Comment by sunhoww** [comment]
@carlos22 I think it's because you are using the _Procfile_ that got installed with `bench init`. You need to use the _Procfile_ and _sites/common_site_config.json_ that came with this repo.

@vishalseshagiri the `--skip-bench-mkdir` flag does not use the *__docker_ files. We still need to manually rename them.

**Comment by carlos22** [comment]
@sunhoww how can i define which are used?

**Comment by sunhoww** [comment]
Rename files _Procfile_docker_ and _sites/common_site_config_docker.json_ to _Procfile_ and _sites/common_site_config.json_.

**Comment by carlos22** [comment]
Ok this works. But it should be mentioned in the Readme.md.

**Comment by emcniece** [comment]
@carlos22 @sunhoww I started a Docker-Compose overhaul at https://github.com/emcniece/frappe_docker/tree/feat/docker-optimization

The documentation isn't done yet, but try editing the `docker-compose.yml` and running `docker-compose up -d`. 

Lots of the container configuration can be moved into environment variables - the MariaDB and Redis files can be eliminated and config can be specified in the `docker-compose.yml` file. 

I have added an `entrypoint.sh` script here to take care of first-run setup as well, so we don't have to spend time messing around and hitting these errors.

**Comment by Olawale1** [comment]
Hi 

Following the hitchhiker’s guide to buiding the frappe docker image, I am at the point where I run the below command for creating a new bench:

cd .. && bench init frappe-bench --skip-bench-mkdir --skip-redis-config-generation && cd frappe-bench

but it returns the following error:

Error: no such option: --skip-bench-mkdir

Any help here will be greatly appreciated

Thanks

**Comment by Olawale1** [comment]
Thanks a lot @sunhoww. Someone gave me a great deal of assistance with this and other related issues on the forum 

Cheers

**Comment by chabad360** [comment]
This issue has since been fixed. Can it be closed?

**Comment by mingfang** [comment]
This issue needs to be re-opened.
It's 2021 and I got exactly this same error.
