### ISSUE TITLE
Readme - Administrator password / setup

### ISSUE THREAD

**Issue by spacehaven** [frappe/frappe_docker#10]
I might've missed something, although I tried twice. I wasn't prompted for a password while setting up the new site, and wasn't able to login to ERPNext, or go through the setup.

**Comment by spacehaven** [comment]
I also tried adding --admin-password to bench new-site, but it didn't seem to work.

**Comment by vishalseshagiri** [comment]
U shouldn't be prompted for a password while creating a new site. Its already been set in common_site_config.json inside the frappe-bench/sites directory. Check if you have a admin_password key inside the json file.

**Comment by vishalseshagiri** [comment]
You can just remove the admin_password from your common_site config and it will prompt you to enter one every time you create a new site.
