### ISSUE TITLE
Unable to login to Traefik Dashboard even after providing Correct password in Basic Auth.

### ISSUE THREAD

**Issue by AnkurThakur** [frappe/frappe_docker#1002]
## Description of the issue

Unable to login to Traefik Dashboard even after providing Correct password in Basic Auth.

## Context information (for bug reports)

During the installation, when we setup Traefik, it uses the Docker Environment file `traefik.env`. It contains `HASHED_PASSWORD` which is used for Traefik login. It contains the encrypted password, e.g `$apr1$TzHiJVlu$d3bQf1d8IgV2X2x625GMB1`. The `$` is considered as variable by Compose which results in incorrect password.

## Steps to reproduce the issue

1. After setting up the `traefik.env` file, try installing Traefik using Docker Compose and it will throw warnings.

### Observed result

```
$ docker compose --project-name traefik \
  --env-file ~/erp_next_ops/traefik.env \
  -f docs/compose/compose.traefik.yaml up -d
WARN[0000] The "apr1" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TzHiJVlu" variable is not set. Defaulting to a blank string. 
WARN[0000] The "d3bQf1d8IgV2X2x625GMB1" variable is not set. Defaulting to a blank string. 
WARN[0000] The "apr1" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TzHiJVlu" variable is not set. Defaulting to a blank string. 
WARN[0000] The "d3bQf1d8IgV2X2x625GMB1" variable is not set. Defaulting to a blank string. 
WARN[0000] The "apr1" variable is not set. Defaulting to a blank string. 
WARN[0000] The "TzHiJVlu" variable is not set. Defaulting to a blank string. 
WARN[0000] The "d3bQf1d8IgV2X2x625GMB1" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container traefik-traefik-1  Started
```

### Expected result

```
$ docker compose --project-name traefik   --env-file ~/erp_next_ops/traefik.env   -f docs/compose/compose.traefik.yaml up -d
[+] Running 1/1
 ⠿ Container traefik-traefik-1  Started
```

**Comment by AnkurThakur** [comment]
# Solution #

We need to wrap the password in single quotes.

### References ###

- https://github.com/docker/compose/issues/8607
- https://deploy-preview-13474--docsdocker.netlify.app/compose/env-file/#compose-2x

**Comment by revant** [comment]
send pr 
i don't use compose files

I'm using helm chart

**Comment by felixalguzman** [comment]
@AnkurThakur thanks for your solution, but I can't access traefik even with this change, i followed the [steps from tutorial](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md#install-traefik). Is there anything I am missing ?

**Comment by kurtrottmann** [comment]
It works for me, but I have to use: `openssl passwd -apr1 changeit | sed 's/\$/\\$$/g'` instead of `openssl passwd -apr1 changeit | sed 's/\$/\\\$/g'` when I create the hashed password for Traefik.

**Comment by revant** [comment]
forget environment variables

hard code it in yaml and replace `$` with `$$`

example.

```shell
❯ openssl passwd -apr1 "Secret"
$apr1$lou.E/tO$tcnqp1gKiz5G/EVvhIQtD0
```

`$apr1$lou.E/tO$tcnqp1gKiz5G/EVvhIQtD0` will become `$$apr1$$lou.E/tO$$tcnqp1gKiz5G/EVvhIQtD0`

**Comment by revant** [comment]
re open new if needed, closing this.

**Comment by sinhpn92** [comment]
> forget environment variables
> 
> hard code it in yaml and replace `$` with `$$`
> 
> example.
> 
> ```shell
> ❯ openssl passwd -apr1 "Secret"
> $apr1$lou.E/tO$tcnqp1gKiz5G/EVvhIQtD0
> ```
> 
> `$apr1$lou.E/tO$tcnqp1gKiz5G/EVvhIQtD0` will become `$$apr1$$lou.E/tO$$tcnqp1gKiz5G/EVvhIQtD0`
> 
> In some cases I don't even expose and load balance traefik dashboard to public with basic auth.

Thank you so much. It's working.
