### ISSUE TITLE
Nginx not waiting for other services to be up

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#101]
There is a very common problem: nginx starts up very quickly, and when it does the other containers are not ready yet.

A wait-for script should be added to the nginx container entrypoint script so that the container waits for other services to be running.

**Comment by ddavidebor** [comment]
example of such script https://github.com/eficode/wait-for/blob/master/wait-for

another solution https://github.com/dadarek/docker-wait-for-dependencies

**Comment by revant** [comment]
In case of docker-compose up. It does wait?

I'm using following in other place

```shell

function checkConnection() {
  echo "Connect MongoDB . . ."
  timeout 10 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' $DB_HOST 27017
}
```

**Comment by ddavidebor** [comment]
> In case of docker-compose up. It does wait?

you mean the old dockerfile?



> I'm using following in other place
> 
> ```shell
> function checkConnection() {
>   echo "Connect MongoDB . . ."
>   timeout 10 bash -c 'until printf "" 2>>/dev/null >>/dev/tcp/$0/$1; do sleep 1; done' $DB_HOST 27017
> }
> ```

Love it I'm testing & PR

**Comment by mingfang** [comment]
In general the best way to deal with dependencies is to let it fail and let the system auto restart until it eventually stops failing
