### ISSUE TITLE
Is "FRAPPE_SITE_NAME_HEADER" in compose.yml / pwd.yml the same as "host_name"? 

### ISSUE THREAD

**Issue by rorar** [frappe/frappe_docker#1010]
My PDF header and footer were not showing up and added it with these [instruction](https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#edit-configs) and adding
```
"host_name":"YOURSERVERIP:PORTNUMBER",
```
to the file.

If I want to rebuild the docker, can I just add my serveripto FRAPPE_SITE_NAME_HEADER and is this the same as host_name ?

**Comment by revant** [comment]
add if it works for you?

**Comment by rorar** [comment]
Thanks for getting back @revant 
Let me clearify my question:

You've got the variable inside the yml file:
"FRAPPE_SITE_NAME_HEADER"
and inside the common_site_config.json you've got 
"host_name"

are these the same settings?

**Comment by revant** [comment]
No these are not same settings.

host_name is used by python code as `frappe.conf.host_name`

FRAPPE_SITE_NAME_HEADER is used in nginx config to serve site, pass as header

https://github.com/frappe/frappe_docker/blob/45c6401da9083b4b53dc7660c5303f339e77e73e/images/nginx/nginx-template.conf#L43-L79

**Comment by rorar** [comment]
Thanks!
Three last questions:
1. For what is the FRAPPE_SITE_NAME_HEADER?
2. Should I set it the same like host_name?
3. How can I set the host_name over the yml file?

**Comment by revant** [comment]
> 1. For what is the FRAPPE_SITE_NAME_HEADER?

Check nginx config, it is only used there. It is the site name by which the directory to serve site files are resolved. It is also passed to socketio and gunicorn as header to identify which site to serve

> 2. Should I set it the same like host_name?

No. It needs to be the directory name from which site will be served or it will result in 404 site not found. You can set it to `$host` in nginx config and it will pick up the site from Host header.

> 3. How can I set the host_name over the yml file?

check the create-site service in pwd.yml it is run once container that runs a bash script to create site.
use command `bench --site {site-name} set-config host_name "https://erp.example.com"`
