### ISSUE TITLE
Using something like supervisord to run in a single Dockerfile

### ISSUE THREAD

**Issue by sudo-sand** [frappe/frappe_docker#1018]
Is there a way to use a single Dockerfile that will contain both the backend and frontend?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/858

**Comment by revant** [comment]
it's not possible using this repo.

you'll have to build your own unsecure 3-4 gb image.

it's recommended to use vm instead. check community you'll find alternative docker images that you can try.

nothing to expect from this repo
