### ISSUE TITLE
Proposal for single image production containers

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#1028]
Reasons:

- At this moment we have 3 images built to run ERPNext or any frappe app. Images are `nginx`, `worker`, `socketio`.
- Size of 3 images is greater than or equal to size of 1 image with everything. 
- Assets need to be mounted for python containers as they are part nginx container.
- Building decoupled images diverges from upstream `bench` tooling.

Pros:

- Only one image to maintain (erpnext)
- One image downloaded on container host, no need to download 3 images.
- Least divergence from upstream `bench` tooling
- Continue with container best practices of immutable app code.

Cons:

- One big image. Any container host will need to download 1 big image irrespective of which container it needs to start.
- Major refactor to builds needed
- Refactor needs to consider backward compatibility.

Info:

- frappe + payments + erpnext + india_compliance: nginx image - 553MB; worker image - 1.77GB; frappe/frappe-socketio - 184MB; Total ~2.5GB
- Same build in single image: ~1.75GB took 8.23 minutes
- Check source here: https://github.com/castlecraft/frappe_containers

**Comment by revant** [comment]
It also means no more frappe images.

following images will be available:

 - `frappe/bench:latest`
 - `frappe/erpnext:latest`
 - `frappe/erpnext:v13` and version tag
 - `frappe/erpnext:v14` and version tag

Custom apps will be built from base anyway. So no need of frappe images.

**Comment by revant** [comment]
#1032

**Comment by sdfateh** [comment]
@revant Thank you for this great effort!

But I think the current setup of 3 images is better than this, especially for custom app building, and management.

This single image will make it a server application, I like the current images which seem to be simple microservices-like setup

I think we have to discuss this proposal more...

**Comment by revant** [comment]
> This single image will make it a server application, I like the current images which seem to be simple microservices-like setup

I don't use any VM. I use kubernetes. So it'll be microservices based. also, it'll be migration friendly.

**Comment by revant** [comment]
Move discussion to PR
