### ISSUE TITLE
Installing containerized erp next with containarized maria db and letsencrypt

### ISSUE THREAD

**Issue by nipunklk** [frappe/frappe_docker#1030]
HI I am trying to follow the below link and install ERPNext on ubuntu and docker
https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md#create-first-site

I installed it with the .env file as below for the variable.
![image](https://user-images.githubusercontent.com/29424955/209584929-3fa8830f-5f25-432b-85f2-3a954cc328ca.png)

is the above correct? I used my subdomain to the digital ocean droplet as above. And I used the site name as erp.mydomain.com as well. But When i try to access the ERP next i get a security SSL issue as well. The let's encrypt is not working properly. And also it gives page not found error as well like below.| All containers are running and i get frappe front end receiving browser inputs when i access my domain. 
![image](https://user-images.githubusercontent.com/29424955/209585292-73e7f2bb-c0f8-4a42-aaf3-61341071018f.png)

my .env file is like this
![image](https://user-images.githubusercontent.com/29424955/209585178-6cae8f6f-c3fa-4c3c-918f-5362e0c9e06d.png)

Please help on this. I tried the compact branch as well but i get the same issue.

**Comment by revant** [comment]
`Not found, {site} does not exist` means you've to create site exactly one in url. e.g. erp.domain.com

use command `bench new-site erp.domain.com --admin-password=...`

**Comment by revant** [comment]
re open if needed. closing this.
