### ISSUE TITLE
V13 Assets Builder issue

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#1034]
## Description of the issue
After the latest push on the docker hub for assets builder images, All build failed 
## Context information (for bug reports)
```
$ FRAPPE_ENV=production node rollup/build.js --app CUSTOM_APP
Production mode
internal/fs/utils.js:332
    throw err;
    ^
Error: ENOENT: no such file or directory, mkdir '/frappe-bench/sites/assets/js'
    at Object.mkdirSync (fs.js:1014:3)
    at /frappe-bench/apps/frappe/rollup/build.js:171:7
    at Array.forEach (<anonymous>)
    at ensure_js_css_dirs (/frappe-bench/apps/frappe/rollup/build.js:169:8)
    at Object.<anonymous> (/frappe-bench/apps/frappe/rollup/build.js:39:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/frappe-bench/sites/assets/js'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to reproduce the issue

1. build a custom app from dockerfile with 2 apps using the install_app script
2. the first app will succeed, and the second will release the error 
3. I try to put app2 first, it builds. and the app1 (which success on the first try failed with the error)

I don't know what changed, because no files for the build process, If you can let us know before doing changes like this in the future it would be thanks.

**Comment by sdfateh** [comment]
@revant 
your input is needed here, which is a high-priority issue!
Thanks.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/1033#issuecomment-1367813428

**Comment by sdfateh** [comment]
@revant why did you delete the old way?
It works well with only 4 min build !

This took 20 min and I have an exited (1) error when starting the frontend container:
```
frontend-1  | touch: cannot touch '/var/www/html/sites/.build': No such file or directory
```

**Comment by revant** [comment]
> It works well with only 4 min build !

which version you want? I'll upload

**Comment by revant** [comment]
The single image PR takes 8 min. Try it for v13 / py 3.9 / node 14 combination.

https://github.com/revant/frappe_docker/blob/refactor-single-image/docs/custom-apps.md

Note the clone command before merge `git clone -b refactor-single-image https://github.com/revant/frappe_docker`

**Comment by sdfateh** [comment]
@revant Any hints for how to use apps export commands in GitLab-ci?

**Comment by revant** [comment]
> @revant Any hints for how to use apps export commands in GitLab-ci?

which apps export?

> https://github.com/revant/frappe_docker/blob/refactor-single-image/docs/custom-apps.md

This one? You can directly set CI variable APPS_JSON_BASE64 and pass it?

**Comment by sdfateh** [comment]
@revant 
This makes the thing toooo static!

We have to be more patient for this migration to make it professional.

**Comment by revant** [comment]
You can take your time. I'm using my fork.

**Comment by revant** [comment]
> This makes the thing toooo static!

What do you mean by that?

I'm way ahead in building bench based PaaS on K8s, so I'm not going to comment on anything. Worst case I give someone right to maintain this repo and helm chart and I maintain my own, anyway PaaS without support makes no sense.
 
https://k8s-bench.castlecraft.in if anyone understands.

**Comment by sdfateh** [comment]
> [#1033 (comment)](https://github.com/frappe/frappe_docker/issues/1033#issuecomment-1367813428)
> 
> follow this for building v13

Solved using this way.
