### ISSUE TITLE
Why HR Menu not show when following instruction on single server

### ISSUE THREAD

**Issue by gieboyz** [frappe/frappe_docker#1035]
Hello everyone.

i still learning how to using frappe, I just want to ask, why i can't get HR menu after following all steps in this path
https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

here is what i get
![all fresh menu](https://user-images.githubusercontent.com/9793593/210744896-743650ff-be69-4d53-a236-ade0f5e2cc35.png)

**Comment by sdfateh** [comment]
Frappe makes `HR` and `Healthcare` and more modules in version-14 as separate apps.
so until now, ERPNext image doesn't have an HR app.

**Comment by sdfateh** [comment]
As you are new to this repo, check this PR #1032 ,
 we are planning to change the structure of the images.

**Comment by gieboyz** [comment]
> As you are new to this repo, check this PR #1032 ,
> we are planning to change the structure of the images.

Ah i see, thank you for your answer.
