### ISSUE TITLE
No data received.http://127.0.0.1:8000/

### ISSUE THREAD

**Issue by AkiM1ta** [frappe/frappe_docker#105]
I did the README.md/Installation Process/Setting up Frappe/ERPNext Docker+Setup Environment Variables+Start Frappe/ERPNext Services+Setup New Sites;
then in aki_erpnext-python_1 container i got:

![image](https://user-images.githubusercontent.com/18052598/75845121-1a7cd680-5e13-11ea-90b5-6503a4047d85.png)

what's wrong?

**Comment by revant** [comment]
The ymls in installation directory are meant to be production deployments only.

It is not for local development.

It can setup local instance to try out and things locally.

**Comment by AkiM1ta** [comment]
yes,infact i want to access it by public ip.
now,it's ok.
refer this: https://discuss.erpnext.com/t/sorry-we-will-be-back-soon-after-instal-https-in-ubuntu-16-using-bench/20984/4
