### ISSUE TITLE
nginx frontend permissions issue migrating to single image

### ISSUE THREAD

**Issue by put3r-r00t3r** [frappe/frappe_docker#1050]
## Description of the issue
Frontend contanier does not start up migrating from multi image to single image. This is on version-13. I am including one custom app (check_run).

## Context information (for bug reports)
Here is my apps.json:
```
{
  "url": "https://github.com/frappe/erpnext",
  "branch": "version-13"
},
{
  "url": "https://github.com/agritheory/check_run",
  "branch": "version-13"
}
```

## Steps to reproduce the issue

1. create new single images according to new custom image document: https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
2. Modify docker-compose.yml as recommended in the migration document: https://github.com/frappe/frappe_docker/blob/main/docs/migrate-from-multi-image-setup.md
3. start up the project
4. check docker-compose logs

### Observed result
frontend container does not start up, specific error is:

```
$ docker compose -p frappe_docker -f docker-compose.yml logs frontend
frappe_docker-frontend-1  | standard_init_linux.go:230: exec user process caused: permission denied
frappe_docker-frontend-1  | standard_init_linux.go:230: exec user process caused: permission denied
```

### Expected result
frontend container should start up and serve the site

### Additional information:
```
$ docker compose -p frappe_docker -f docker-compose.yml run -it frontend /bin/bash
...
frappe@a98903ed1ba7:~/frappe-bench$ ls -l /usr/local/bin/nginx-entrypoint.sh
-rwx------ 1 root root 1502 Jan 19 20:27 /usr/local/bin/nginx-entrypoint.sh

```
```
$ cat docker-compose.yml
...
  frontend:
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: trustedcomputer/erpnext-single-image:1.0.0
    command:
      - nginx-entrypoint.sh
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
...
```

**Comment by put3r-r00t3r** [comment]
This is the migration document I was following: https://github.com/frappe/frappe_docker/blob/main/docs/migrate-from-multi-image-setup.md along with the relevant snippit. Maybe there is something assumed that I'm not picking up on or something that I missed somehow?

> Example change:
> 
> # ... removed for brevity
> frontend:
>   image: frappe/erpnext:${ERPNEXT_VERSION:?ERPNext version not set}
>   command:
>     - nginx-entrypoint.sh
>   environment:
>     BACKEND: backend:8000
>     SOCKETIO: websocket:9000
>   volumes:
>     - sites:/home/frappe/frappe-bench/sites
> # ... removed for brevity

**Comment by revant** [comment]
move discussion to PR
