### ISSUE TITLE
How to allow Frappe or ERPNext's socket to be used by other web application

### ISSUE THREAD

**Issue by jrGabrillo** [frappe/frappe_docker#1059]
I am currently developing a web application that is currently using Frappe's REST APIs. All is **working** fine using REST API but I want to get **real-time** updates using socket.io from ERPNext to my web app. 

My ERPNext website is working fine including socket.io.

I installed socket.io in my web application is written in React Js but I am receiving this error. 

<img width="440" alt="Screenshot 2023-01-26 at 10 45 12 AM" src="https://user-images.githubusercontent.com/19164950/214747659-5ce00f39-59ad-4da6-a5e3-badc115f6147.png">

I hope you can help me. 
Thanks.

**Comment by sdfateh** [comment]
Is your site have Public access?

**Comment by jrGabrillo** [comment]
Yes, my site is public.

**Comment by revant** [comment]
https://github.com/frappe/frappe/blob/db9b25ec0e529ffb654faa97ff833b64442f78c5/socketio.js#L12

it's releated to Frappe development in general, not just containers.

cors seems to be already enabled. try the requests from curl if you get any other response?

cors may prevents error codes response

**Comment by jrGabrillo** [comment]
> cors seems to be already enabled. 
cors is already configured 

>  try the requests from curl if you get any other response?
Yes, calls using fetch in JS is working fine. 
I have another app that is already working. 

I am currently developing another app that needs to be real time.

**Comment by revant** [comment]
Enable cors with traefik or ingress-nginx

traefik: https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers

```
        - "traefik.http.middlewares.serviceheaders.headers.accesscontrolalloworiginlist=*"
        - "traefik.http.routers.am-nginx-staging-https.middlewares=serviceheaders"
```

ingress-nginx: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors

add annotation:

```
nginx.ingress.kubernetes.io/enable-cors: "true"
```

If you read my previous message, I said the issue is with frappe.

Adding a middleware on proxy will solve it anyway. It doesn't solve it for non-containerized setup.

**Comment by jrGabrillo** [comment]
Thanks @revant . I will try this.

I will update you whatever the output
