### ISSUE TITLE
What is `<name of assets volume>` on the setup-options page?

### ISSUE THREAD

**Issue by maovidal** [frappe/frappe_docker#1061]
Hi everyone!

On the page https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md#updating-images it mentions one step where the volume `<name of assets volume>` is removed.

```
# Remove assets volume for repopulation
docker volume rm <name of assets volume>
```

To which one does that refers to? I haven't changed the names of the volumes on the default configuration for my deployment and I don't seem to find a volume that makes sense to remove when using the current proposed configuration when selecting `ERPNext using containerized MariaDB and Redis with Letsencrypt certificates`.

Thanks in advance

**Comment by sdfateh** [comment]
Hello !

There is no need to do this command because this volume has been removed with the latest updates
We will update the document to delete this line.
