### ISSUE TITLE
Docker play link in README runs out of disk space

### ISSUE THREAD

**Issue by nikkilocke** [frappe/frappe_docker#1072]
## Description of the issue

I followed the link in your readme to docker play, to try out erpnext.

After building for some time, I got the message
`failed to register layer: Error processing tar file(exit status 1): write /home/frappe/frappe-bench/env/lib/python3.10/site-packages/google/protobuf/descriptor.py: no space left on device`

Not sure what you can do about that, other than remove the link?

**Comment by revant** [comment]
I can't do anything about it.
try it on local machine instead of PWD.

I'll keep the issue open if anyone has any alternative.
