### ISSUE TITLE
No Let's Encrypt SSL Certificate on Traefik

### ISSUE THREAD

**Issue by alvinmio10** [frappe/frappe_docker#1075]
## Context information (for bug reports)
No Let's Encrypt SSL Certificate on Traefik upon installation of container, traefik seems to have an error.

## Steps to reproduce the issue

1. Standard Container Installation on Ubuntu LTS OS
2.
3.

### Observed result
No SSL Certificate resulting in HSTS Error for Clients

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
share more information,

did you set SITES in Host() router labour label for traefik?

if you used easy install there is a pending pr, test it.

**Comment by alvinmio10** [comment]
Hi Revant, got this rolling, but just asking what version would you rather choose to run at the moment from your version list at https://github.com/frappe/erpnext/releases for best stability?

**Comment by revant** [comment]
I'll prefer latest v14 and keep it up to date.

I don't know if this wiki is actively updated or not https://github.com/frappe/erpnext/wiki/Supported-Versions
