### ISSUE TITLE
Frequently Asked Questions

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#1079]
[Frequently Asked Questions](https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions)

URL: `https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions`

**Comment by revant** [comment]
> Any sample method for creating the custom app image? cause iam new into frappe , i dont undertand anything from the forums

Hope someone helps you. I can point things on forum and FAQ which you'll not understand.

**Comment by aldo-o** [comment]
> Any sample method for creating the custom app image? cause iam new into frappe , i dont undertand anything from the forums

This is a staring point [Custom Apps](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) . I would first suggest to setup out of the box environment. If you are able to, then start building with Custom apps.

**Comment by M7mdMostafa5eer** [comment]
i`ve a problem with runtime when install the erpnext from docker ,the image that i built was
https://github.com/revant/frappe_docker/tree/main/images/production

and i used this docker comppose file
https://github.com/revant/frappe_docker/blob/main/pwd.yml

without and overrides

the fortend container worked well except runtime "socketio"

any help

**Comment by revant** [comment]
> the fortend container worked well except runtime "socketio"

socketio needs the host header and site name to be same.

**Comment by M7mdMostafa5eer** [comment]
> > the fortend container worked well except runtime "socketio"
> 
> socketio needs the host header and site name to be same.

they are the same
![Screenshot 2023-09-28 172817](https://github.com/frappe/frappe_docker/assets/32681895/719dbc4c-2f50-40d1-adfb-d57bde051f65)

**Comment by mrchenxxx** [comment]
How to install custom app?
After I deploy erpnext with the pwd.yml file, how do I install the custom app? Do I need to install it in the container?

**Comment by revant** [comment]
> How to install custom app?

https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-install-official-or-custom-apps

**Comment by M7mdMostafa5eer** [comment]
> > > the fortend container worked well except runtime "socketio"
> > 
> > 
> > socketio needs the host header and site name to be same.
> 
> they are the same ![Screenshot 2023-09-28 172817](https://user-images.githubusercontent.com/32681895/271318489-719dbc4c-2f50-40d1-adfb-d57bde051f65.jpg)

@revant

**Comment by revant** [comment]
@M7mdMostafa5eer create new issue, I'll delete all posts unrelated to FAQ after you create your issue.

**Comment by revant** [comment]
In general, frappe community uses hijack unrelated posts and start conversation about their problems.

E.g. the post will be ERPNext 20 released!

Someone will post, "I'm trying to import employee data from v13 to v15 and I'm getting this error."

We can't do anything about it. No one can.

**Comment by SDcompanies** [comment]
I have a question.

I want to test an installation to use later in production if everything is successful.

I want to install on a Debian 12 (Raspberry Pi 5) machine through Docker. I've read the instructions about it [here](https://github.com/frappe/frappe_docker#to-run-on-arm64-architecture-follow-this-instructions) 
My questions are the followings:
(1)--on the same machine I have many other Docker containers and the ports 8000, 8080, 3306, etc... are already used. How to change all of them without any issue?  I just need to change them on the file pwd.yml? Or should I edit other files accordingly?
(2)--The system should work like a server reachable from remote through a website assigned like https://mydomain.provedns.org . The redirection on the machine works through Apache2, the same that manages the other web sites for the other servers running like docker containers. Where should I set this address in the pwd.yml file?
(3)--Should I follow some other useful recommendations? Any hints?

**Comment by Vicory75** [comment]
I have a question.

I want to test an installation to use later in production if everything is successful.

I want to install on a Debian 12 (Raspberry Pi 5) machine through Docker. I've read the instructions about it here
My questions are the followings:
(1)--on the same machine I have many other Docker containers and the ports 8000, 8080, 3306, etc... are already used. How to change all of them without any issue? I just need to change them on the file pwd.yml? Or should I edit other files accordingly?
(2)--The system should work like a server reachable from remote through a website assigned like https://mydomain.provedns.org . The redirection on the machine works through Apache2, the same that manages the other web sites for the other servers running like docker containers. Where should I set this address in the pwd.yml file?
(3)--Should I follow some other useful recommendations? Any hints?

**Comment by dawoodjee** [comment]
How do you update frappe_docker to the latest version?

I see that there are new releases but the docs answer how to update the underlying frappe apps.

**Comment by DanielRadlAMR** [comment]
Want to update the installed apps? Just build a new image or pull one with the latest versions, then start your Compose setup using that new image.

Note that our releases don’t align with Frappe releases. We bump our release only when there are changes in the setup. This doesn’t necessarily mean the apps are updated, and vice versa.
