### ISSUE TITLE
How to enable Realtime (socket.io) in production

### ISSUE THREAD

**Issue by ideenkreise** [frappe/frappe_docker#1087]
How to enable socket io for custom apps. Its not working by default in production setup (in main branch). It is working in compat-2022 branch

**Comment by revant** [comment]
I think the inter-container and intra-container connections with site name don't work as expected. It cannot resolve the site names in case of https domain is not used. In that case I was able to add `extra_hosts` for the services trying to access each other and socketio worked (all frappe services). I use it for development when there is no live access (add `extra_hosts` to `frappe` service from devcontainer).

**Comment by revant** [comment]
- check ssl for probelms if it's not automated letsencrypt
- check proxies if any

**Comment by ideenkreise** [comment]
> In that case I was able to add `extra_hosts` for the services trying to access each other and socketio worked

can you give me an example of how you added extra_hosts?

**Comment by ramonus** [comment]
I also have not been able to make socket.io work on production, I can in my development setup but it's simpler composition.
I've tried the pwd, and with the compose+overrides without proxy. The thing is that it does not show any error, websocket connects OK but it is not working.

On the other hand, in my development setup (bench start) I have a nginx reverse proxy that handles https connections, I have it working with socket.io but I have not been able to make it work in production.

**Comment by revant** [comment]
> can you give me an example of how you added extra_hosts?

https://docs.docker.com/compose/compose-file/compose-file-v3/#extra_hosts

**Comment by ramonus** [comment]
I traced down the problem to the socketio.js file in the get_url function:

```
function get_url(socket, path) {
	if (!path) {
		path = "";
	}
	return socket.request.headers.origin + path;
}
```

It tried to connect to port 80 on host but I had it with port 8080. (It showed no error btw)

One thing I wonder, it is supposed to conect through internet instead of docker network (conect to frontend container)?

**Comment by revant** [comment]
> One thing I wonder, it is supposed to conect through internet

The site is identified by host header in frappe. You can override it in some proxy to serve default site.

And generally site name is a domain name, do yes we connect through internet.

In case there's a dns service, it can point the site to internal service. Happens for Kubernetes setup.

**Comment by elhananjair** [comment]
Hello @revant 
I was looking for any solutions to connection issues with WebSocket container and I couldn't find general solution. I am using caddy as reverse proxy with local TLS support for testing purposes. 

I have different sites on a single bench site1.local, site2.local, and I have entry for those in caddy config file. The erpnext works fine but the browser still shows an error regarding connecting to the WebSocket. I spent two days but I couldn't figure out yet.

I am using podman with Quadlets and everything is working fine except this issue.

**Comment by DanielRadlAMR** [comment]
@elhananjair Since this issue is already closed, I recommend opening a new one and including a link to this one for context.

Additionally, it would be helpful to know the exact error you’re seeing and more details about your setup. For example, if you’re using self-signed certificates, that could make a big difference.
