### ISSUE TITLE
Custom Image not working, Error: exist status 125

### ISSUE THREAD

**Issue by vpanchal-code** [frappe/frappe_docker#1096]
## Description of the issue
I am trying to build a custom image for frappe v14 with the following command:
```
buildah bud \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-14 \
  --build-arg=PYTHON_VERSION=3.10.5 \
  --build-arg=NODE_VERSION=16.18.0 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=ghcr.io/user/repo/custom:1.0.0 \
  --file=images/custom/Containerfile .
```

I keep getting the following error:
```
STEP 1: FROM python:3.10.5-slim-bullseye AS base
error creating build container: short-name "python:3.10.5-slim-bullseye" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
ERRO exit status 125
```
## Context information (for bug reports)
My apps.json file contents:
```
export APPS_JSON='[
    {
        "url": "https://github.com/frappe/payments",
        "branch": "develop"
    },
    {
        "url": "https://github.com/frappe/erpnext",
        "branch": "version-14"
    },
    {
        "url": "https://github.com/frappe/hrms.git",
        "branch": "develop"
    },
    {
        "url": "https://github.com/the-bantoo/expense_request.git",
        "branch": "main"
    },
    {
        "url": "https://github.com/frappe/wiki.git",
        "branch": "master"
    }
]'
  export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 --wrap=0)
```

I have also tried to update the python version but recieved the same error.

## System info:
Docker version: 23.0.1
Docker compose version: 2.16.0
buildah version: 1.19.6 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
machine: x86_64

## Steps to reproduce the issue

1. Cloned repo and updated/created apps.json to have the contents as above
2. Ran the buildah command as listed above

**Comment by revant** [comment]
figure out how to use docker hub as registry for buildah/podman

**Comment by vpanchal-code** [comment]
Are you saying that the issue is that I am not using a docker hub? is it required? a little more detail would be appreciated.

**Comment by revant** [comment]
https://unix.stackexchange.com/q/701784

i searched your error and landed in this link

**Comment by vpanchal-code** [comment]
Thank you for your help, I was able to get past this error by updating `/etc/containers/registries.conf` with the following line `unqualified-search-registries = ["docker.io"]` as per the link in your message!
