### ISSUE TITLE
PWD password wrong

### ISSUE THREAD

**Issue by zageshrathod** [frappe/frappe_docker#1097]
## Description of the issue
The password for PWD is showing wrong
username : Administrator
password: admin

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by Sakh1l** [comment]
I was able to login yesterday and it was working fine. You have to wait for 5 mins to get the site running. 
Hope you are referring to the erpnext web interface login!

**Comment by revant** [comment]
PWD working as expected.

wait for the `create-site` task to complete.
