### ISSUE TITLE
Managing two sites - Problem

### ISSUE THREAD

**Issue by Ciangi** [frappe/frappe_docker#11]
Hello,

I created two sites: site1.local and erpnext.dev
Each of them have installed erpnext app.

Now i want to connect to each of this sites but i think that i only can connect to just one of them.
Inside site_config.json (each of them) i added:
"host_name": "http://erpnext.test:8000"    # inside site1.local
"host_name": "http://erpnextdev.test:8000" # inside erpnext.dev

When i type "http://erpnext.test:8000" or "http://erpnextdev.test:8000" i know that i connect just to the site1.local, but i want to connect erpnext.dev when i type "http://erpnextdev.test:8000".

How to configure that i be able to connect each of them?

ps. sorry for my english.

**Comment by Ciangi** [comment]
Small update.
I installed Nginx inside frappe container. added nginx.conf generated by bench set-nginx-port sitename .... and added this nginx.conf inside /etc/nginx/sites-enabled/ and run nginx:

`upstream frappe-bench-frappe {
    server 127.0.0.1:8000 fail_timeout=0;
}

upstream frappe-bench-socketio-server {
    server 127.0.0.1:9000 fail_timeout=0;
}



# setup maps


# server blocks





server {
        listen 80;
        server_name
                site1.local
                ;

        root /home/frappe/frappe-bench/sites;





        location /assets {
                try_files $uri =404;
        }

        location ~ ^/protected/(.*) {
                internal;
                try_files /site1.local/$1 =404;
        }

        location /socket.io {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Frappe-Site-Name site1.local;
                proxy_set_header Origin $scheme://$http_host;
                proxy_set_header Host $host;

                proxy_pass http://frappe-bench-socketio-server;
        }

        location / {
                try_files /site1.local/public/$uri @webserver;
        }

        location @webserver {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Frappe-Site-Name site1.local;
                proxy_set_header Host $host;
                proxy_set_header X-Use-X-Accel-Redirect True;
                proxy_read_timeout 120;
                proxy_redirect off;

                proxy_pass  http://frappe-bench-frappe;
        }

        # error pages
        error_page 502 /502.html;
        location /502.html {
                root /home/frappe/bench-repo/bench/config/templates;
                internal;
        }

        # optimizations
        sendfile on;
        keepalive_timeout 15;
        client_max_body_size 50m;
        client_body_buffer_size 16K;
        client_header_buffer_size 1k;

        # enable gzip compresion
        # based on https://mattstauffer.co/blog/enabling-gzip-on-nginx-servers-including-laravel-forge
        gzip on;
        gzip_http_version 1.1;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types
                application/atom+xml
                application/javascript
                application/json
                application/rss+xml
                application/vnd.ms-fontobject
                application/x-font-ttf
                application/font-woff
                application/x-web-app-manifest+json
                application/xhtml+xml
                application/xml
                font/opentype
                image/svg+xml
                image/x-icon
                text/css
                text/plain
                text/x-component
                ;
                # text/html is always compressed by HttpGzipModule
}


server {
        listen 82;
        server_name
                erpnext.dev
                ;

        root /home/frappe/frappe-bench/sites;





        location /assets {
                try_files $uri =404;
        }

        location ~ ^/protected/(.*) {
                internal;
                try_files /erpnext.dev/$1 =404;
        }

        location /socket.io {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Frappe-Site-Name erpnext.dev;
                proxy_set_header Origin $scheme://$http_host;
                proxy_set_header Host $host;

                proxy_pass http://frappe-bench-socketio-server;
        }

        location / {
                try_files /erpnext.dev/public/$uri @webserver;
        }

        location @webserver {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Frappe-Site-Name erpnext.dev;
                proxy_set_header Host $host;
                proxy_set_header X-Use-X-Accel-Redirect True;
                proxy_read_timeout 120;
                proxy_redirect off;

                proxy_pass  http://frappe-bench-frappe;
        }

        # error pages
        error_page 502 /502.html;
        location /502.html {
                root /home/frappe/bench-repo/bench/config/templates;
                internal;
        }

        # optimizations
        sendfile on;
        keepalive_timeout 15;
        client_max_body_size 50m;
        client_body_buffer_size 16K;
        client_header_buffer_size 1k;

        # enable gzip compresion
        # based on https://mattstauffer.co/blog/enabling-gzip-on-nginx-servers-including-laravel-forge
        gzip on;
        gzip_http_version 1.1;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types
                application/atom+xml
                application/javascript
                application/json
                application/rss+xml
                application/vnd.ms-fontobject
                application/x-font-ttf
                application/font-woff
                application/x-web-app-manifest+json
                application/xhtml+xml
                application/xml
                font/opentype
                image/svg+xml
                image/x-icon
                text/css
                text/plain
                text/x-component
                ;
                # text/html is always compressed by HttpGzipModule
}
`

And even if i type erpnext.test:80 or erpnext.test:82 or erpnextdev.test:80 or erpnextdev.test:82 i still only login to site1.local.

I added also to /etc/hosts file:
127.0.0.1 erpnext.test
127.0.0.1 erpnextdev.test

Help please...

**Comment by vishalseshagiri** [comment]
Hi @Ciangi really sorry for the delay. frappe_docker was meant only for dev setup and not production, so production has'nt really been tested on it. Having said that I have run frappe_docker in production mode as multi port and not multi-tenant (I think your case is a mix of the two). It works for multi port , so essentially all you would have to do is type localhost:80 to access erpnext.test and localhost:82 to access erpnextdev.test on your browser window outside the docker container(ie. on the host machine). I'll give production multitenant a try and let you know.

**Comment by chabad360** [comment]
Please close as this is no longer relevant.
