### ISSUE TITLE
Simplest setup for ERPNext?

### ISSUE THREAD

**Issue by SaturnusDJ** [frappe/frappe_docker#1109]
Followed https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md. Thanks. It is a complex system. In the end, many containers are running but I cannot reach the ERPNext on `one.ip`.
EDIT: The issue that applies in my case: https://stackoverflow.com/questions/21499467/how-to-access-the-subdomain-of-an-ip-address-in-the-browser So, I would have to use ports instead of domains.

But before getting technical, what is actually the best way to set up a minimal ERPNext? On my side there is no need for load balancing, proxies, etc. just ERPNext.

Thanks.

**Comment by revant** [comment]
read this to understand the setup
https://github.com/frappe/frappe_docker/blob/main/docs/single-compose-setup.md

the frontend serves one of

- site from host header
- or site specified in FRAPPE_SITE_NAME_HEADER env var

to make it port based, keep adding frontend like services that publish different ports. and set the env var FRAPPE_SITE_NAME_HEADER to the site to be served from that port.

to make it dns based, set the env var FRAPPE_SITE_NAME_HEADER to `$host` (internal config for nginx)

in any case the site directory for requested site must be available under bench
