### ISSUE TITLE
Add override for docker app containers restart policy

### ISSUE THREAD

**Issue by alimalkhalifa** [frappe/frappe_docker#1116]
**Is your feature request related to a problem? Please describe.**
It is a common use case to run the frappe_docker setup in production, where a restart policy is commonly required.

**Describe the solution you'd like**
Create an override with restart: unless-stopped for all app containers, similar to mariadb-shared and traefik overrides

**Describe alternatives you've considered**
I do this locally, but believe the community could benefit from this

**Comment by revant** [comment]
you can send the changes you did as PR.

**Comment by alimalkhalifa** [comment]
@revant thanks for the reply. I'll clean it up and send across next couple of days. Thanks!
