### ISSUE TITLE
Problem setup ERPNext

### ISSUE THREAD

**Issue by virendra-chouhan** [frappe/frappe_docker#1117]
Hi Team,
We are trying to setup in ubuntu server so for this we are using docker 
we have cloned github repository then followed instruction which are defined in read me but facing some problem please help check below screen shot
![image](https://user-images.githubusercontent.com/85293050/232396798-562b87a2-74dc-45b6-be8b-266751faae25.png)

**Comment by revant** [comment]
make sure the configuration task / container successfully completed. It should update the common_site_config.json from where the redis host values are picked.

**Comment by KaiBoos** [comment]
Even though it aint my Issue:
My Configurator_1 throws this error:

Usage: bench set-config  [OPTIONS] KEY VALUE
Try 'bench set-cofig --help' for help
Error: Missing argument 'VALUE'
Usage: bench set-config  [OPTIONS] KEY VALUE
Try 'bench set-cofig --help' for help
Error: Missing argument 'VALUE'

**Comment by KaiBoos** [comment]
> make sure the configuration task / container successfully completed. It should update the common_site_config.json from where the redis host values are picked.

Even though it aint my Issue:
My Configurator_1 throws this error:

Usage: bench set-config  [OPTIONS] KEY VALUE
Try 'bench set-cofig --help' for help
Error: Missing argument 'VALUE'
Usage: bench set-config  [OPTIONS] KEY VALUE
Try 'bench set-cofig --help' for help
Error: Missing argument 'VALUE'

**Comment by revant** [comment]
> Even though it aint my Issue

configuration container must end with exit code 0. Your common site config is not properly set, that causes the problem

make sure you've correct volume permission

**Comment by KaiBoos** [comment]
Where is the common site config?
Running docker-compose as sudo, so the permission should be okay. 
I'm not that talented to grasp the problem here. Can I maybe change the redis port from 6379 to something else?

**Comment by revant** [comment]
common site config is in ~/frappe-bench/sites directory

read this https://discuss.frappe.io/t/container-basics/99306#volumes-5

it has info about volumes and permissions
