### ISSUE TITLE
Issue in Frappe_docker 

### ISSUE THREAD

**Issue by nestorbird** [frappe/frappe_docker#1124]
Hi,

I was following frappe docker to containerized frappe and erpnext but facing issue while using this documentation. I tried to fix this issue but unable to do it. 

When i tried to follow the steps for production setup , all containers get up but in that two webserver containers are up one is Traefik and the other one is of Nginx. 

If i stop Traefik container i'm getting 
<img width="592" alt="image" src="https://user-images.githubusercontent.com/121154920/233614277-a492a18a-32ea-42b4-afed-bb72d90f1597.png">

And if i stop nginx container i'm getting 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/121154920/233614552-560e9898-f8ad-4b3a-8dcf-9cf0ff3d46df.png">

And if both the containers are running i'm getting Internal Server Error
<img width="373" alt="image" src="https://user-images.githubusercontent.com/121154920/233614745-ea4cfd22-b065-4256-b25f-b96bff46e097.png">

So, please look into this and suggest me how can i resolve this.

Thank You

**Comment by revant** [comment]
did you create the site? did you miss `--no-mariadb-socket` while creating new site?

**Comment by nestorbird** [comment]
Yes i have created the site and also did not miss --no-mariadb-socket

**Comment by nestorbird** [comment]
I'm trying to do setup again but this time my configurator container is getting failed due to which another container is also not getting up.
Below is the error which is getting:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/bench/cli.py", line 71, in cli
    cmd_from_sys = get_cmd_from_sysargv()
  File "/usr/local/lib/python3.10/site-packages/bench/utils/__init__.py", line 554, in get_cmd_from_sysargv
    if sys_argv.index(arg) == 0 and arg in Bench(".").apps:
  File "/usr/local/lib/python3.10/site-packages/bench/bench.py", line 67, in __init__
    self.apps = BenchApps(self)
  File "/usr/local/lib/python3.10/site-packages/bench/bench.py", line 175, in __init__
    self.set_states()
  File "/usr/local/lib/python3.10/site-packages/bench/bench.py", line 180, in set_states
    self.states = json.loads(f.read() or "{}")
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 21 column 1 (char 450)

**Comment by revant** [comment]
I have no clue how to fix it.

I have done countless installations before and after this issue got created and never faced it.

tests also not failing. So let the issue be open if someone else has any solution 

i guess you've some issue with volume permission that prevents any unprivileged process from container to create files in volume with root permission. Container Basics post on forum has some details related to volumes.
