### ISSUE TITLE
It won’t install/run in WSL2 running Ubuntu 22.04

### ISSUE THREAD

**Issue by laportem** [frappe/frappe_docker#1125]
## Description of the issue
When I open VSCode from WSL terminal  and click "Reopen in Container". VSCode throws the error "An error occurred setting the container" and does nothing

## Steps to reproduce the issue

1. In WSL terminal, get clone the frappe_docker.git repo
2.  ```cd frappe_docker```
3. ```cp -R devcontainer-example .devcontainer```
4. ```cp -R development/vscode-example development/.vscode```
5.  ```code --install-extension ms-vscode-remote.remote-containers```
6.  ```code .``
7. When vscode open click "Reopen in Container" in the bottom right

### Observed result
Vscode throws "An error occurred setting the container" and does nothing
### Expected result
The docker-compose runs
### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
I don't use windows. Hope someone helps.

**Comment by laportem** [comment]
Ok, I solved the issue
For anyone else facing similar issues

1. In your home dir in WSL (cd ~)
2. cd to the .docker folder (cd .docker)
3. Nano the config.json
4. And rename “credsStore” to “credStore”

And now you good to go
