### ISSUE TITLE
How to access the site in the `Create second bench ` 

### ISSUE THREAD

**Issue by skanel** [frappe/frappe_docker#1130]
Hi,
Reference document: https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

I have followed the document and everything running successfully, except when I am doing the ` Create second bench ` section
the containers also up running, but I don't know to to access the site ran by second bench, do i need to change or update the IP address or Port to the second bench?

Thanks

**Comment by revant** [comment]
I recently mentioned this in a reply here https://discuss.frappe.io/t/erpnext-docker-how-to-run-site-in-second-bench/104260

If traefik labels are configured properly, access the site from browser with site url.
