### ISSUE TITLE
Is there any way to specify a commit for custom images?

### ISSUE THREAD

**Issue by azwalzaman** [frappe/frappe_docker#1131]
I'm encountering a bug on Frappe/ERPNext v14 that doesn't seem to be on an older image I made. Can I somehow specify the commit used in that image?

**Comment by revant** [comment]
you can only specify forks and branches.

- fork ERPNext
- create a tag or branch on your fork's commit
- use your fork as url and your branch or tag as branch in apps.json

**Comment by azwalzaman** [comment]
> you can only specify forks and branches.
> 
> * fork ERPNext
> * create a tag or branch on your fork's commit
> * use your fork as url and your branch or tag as branch in apps.json

Thanks, I'll try doing that. How do I check what commit the apps I got with `get-app` are at? They do not seem to be git repos

**Comment by azwalzaman** [comment]
@revant Hello. It seems that changing repos for ERPNext breaks the migrate command. And when I reinstall it still uses version-14 instead of the branch from my forked repo. I replaced Frappe's ERPNext repo with my own fork when creating the custom image. And then took down all the containers, pulled the new image, ran the containers and then ran the migrate command

**Comment by revant** [comment]
you cannot migrate back to old version. you can only migrate to newer version

**Comment by azwalzaman** [comment]
> you cannot migrate back to old version. you can only migrate to newer version

Okay that makes sense. Are the other steps I did correct? Because they seem to still use the latest version even if I clear everything

**Comment by revant** [comment]
can you share the steps?

**Comment by azwalzaman** [comment]
> can you share the steps?

When making the custom image:
- Fork ERPNext
- Make branch with commit from old repo
- Replace the URL for ERPNext in `apps.json` from the guide to my fork and use my new branch
- Build Image

When deploying it:
- Follow the steps for the single server example
- Replace container image with custom container image
- Deploy containers using the commands shown in the example with the .yaml file used in the example

**Comment by azwalzaman** [comment]
Okay I've noticed something. This is the sites/apps.json from my new container image with the new branch

```
 "erpnext": {
        "is_repo": true,
        "resolution": {
            "commit_hash": "e271935673f1e27d7bd8ab7b7e1731a22b2e0bee",
            "branch": "stable-version"
        },
        "required": [],
        "idx": 2,
        "version": "14.19.0"
    },

```

And this is from the old one: 

```
 "erpnext": {
        "is_repo": true,
        "resolution": {
            "commit_hash": "e271935673f1e27d7bd8ab7b7e1731a22b2e0bee",
            "branch": "version-14"
        },
        "required": [],
        "idx": 2,
        "version": "14.19.0"
    },
```

Why do they both have the same hash, different branch and the same release version? I know for a fact the old image did not have the bug and it was made some time in April. The Second apps.json is from an image built this month

**Comment by revant** [comment]
can you share your fork? is the custom created branch of your fork pointing to correct commit?

**Comment by azwalzaman** [comment]
> can you share your fork? is the custom created branch of your fork pointing to correct commit?

Here's a [link](https://github.com/azwalzaman/erpnext/tree/stable-version) to the fork at my new branch. And yes, it is pointing to the correct commit

**Comment by azwalzaman** [comment]
@revant Can you please confirm if the branch was correct

**Comment by revant** [comment]
```json
[
  {
    "url": "https://github.com/azwalzaman/erpnext",
    "branch": "stable-version"
  }
]
```

You need to pass this as apps.json

There 3 apps.json

1. Passed to bench init --apps_path
2. One created on bench init located in sites directory
3. Parsed by installer.sh sample script under frappe_docker/development

For building image we use the first one which is array of objects with branch and url as keys

**Comment by azwalzaman** [comment]
> ```json
> [
>   {
>     "url": "https://github.com/azwalzaman/erpnext",
>     "branch": "stable-version"
>   }
> ]
> ```
> 
> You need to pass this as apps.json
> 
> There 3 apps.json
> 
> 1. Passed to bench init --apps_path
> 2. One created on bench init located in sites directory
> 3. Parsed by installer.sh sample script under frappe_docker/development
> 
> For building image we use the first one which is array of objects with branch and url as keys

Was able to fix it thanks.
