### ISSUE TITLE
issue with building docker container using arm processor

### ISSUE THREAD

**Issue by guocity** [frappe/frappe_docker#1132]
issue with building docker container using arm processor
no matching manifest for linux/arm64/v8 in the manifest list entries
m1@mini frappe_docker % docker-compose -f pwd.yml up -d
[+] Running 1/9
 ⠹ create-site Pulling                                                                             5.1s 
 ⠹ configurator Pulling                                                                            5.1s 
 ⠹ scheduler Pulling                                                                               5.1s 
 ⠹ queue-long Pulling                                                                              5.1s 
 ⠹ queue-default Pulling                                                                           5.1s 
 ⠹ queue-short Pulling                                                                             5.1s 
 ⠙ websocket Pulling                                                                               5.1s 
 ⠙ backend Pulling                                                                                 5.1s 
 ✘ frontend Error                                                                                  5.1s 
no matching manifest for linux/arm64/v8 in the manifest list entries
m1@mini frappe_docker % docker-compose -f pwd.yml up -d
[+] Running 1/9
 ⠸ scheduler Pulling                                                                               4.4s 
 ⠼ queue-default Pulling                                                                           4.4s 
 ⠼ queue-short Pulling                                                                             4.4s 
 ⠼ backend Pulling                                                                                 4.4s 
 ⠼ websocket Pulling                                                                               4.4s 
 ✘ frontend Error                                                                                  4.4s 
 ⠸ queue-long Pulling                                                                              4.4s 
 ⠸ configurator Pulling                                                                            4.4s 
 ⠸ create-site Pulling                                                                             4.4s 
no matching manifest for linux/arm64/v8 in the manifest list entries
m1@mini frappe_docker % docker-compose -f pwd.yml up -d
[+] Running 1/9
 ⠹ websocket Pulling                                                                                       5.1s 
 ⠹ backend Pulling                                                                                         5.1s 
 ⠹ queue-short Pulling                                                                                     5.1s 
 ⠹ create-site Pulling                                                                                     5.1s 
 ⠹ scheduler Pulling                                                                                       5.1s 
 ⠹ frontend Pulling                                                                                        5.1s 
 ⠹ queue-default Pulling                                                                                   5.1s 
 ⠹ configurator Pulling                                                                                    5.1s 
 ✘ queue-long Error                                                                                        5.1s 
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-build-arm64-images
