### ISSUE TITLE
Is it possible to use pwd.yml with custom apps?

### ISSUE THREAD

**Issue by srivoidsys** [frappe/frappe_docker#1133]
If I build a custom image with the required apps, using the instructions at [custom-apps.md](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md), can I then simply replace the images in the pwd.yml with my custom image manually and then run using docker compose?

Theoretically I don't think there should be an issue, am I overlooking something?

**Comment by revant** [comment]
it should work. try it.

https://github.com/frappe/frappe_docker/blob/main/docs/single-compose-setup.md#adaptation

**Comment by Z4nzu** [comment]
Hi @srivoidsys, I wanted to ask you regarding your custom image with the PWD.yml file. Is this working for you ?

If not please let me know if you are able to run with docker-compose.yaml file or not ? 


Thanks,
Hardik Zinzuvadiya
