### ISSUE TITLE
Versioning for the bench image

### ISSUE THREAD

**Issue by amalpaul54111** [frappe/frappe_docker#1135]
**Is your feature request related to a problem? Please describe.**
Hi, recently the frappe/bench had a breaking bug in the code. In such situations when the bench image is build it includes the same bug and this does break a lot of other dependent images build from this image as a base. The bench image is always pushed with the latest tag. So when a new image is pushed the old latest image get orphaned without any specific tag. 

**Describe the solution you'd like**
Build the bench image on release of a version of the bench itself and associate it with that version no. This would help people to easily find a alternative image they could use in case the latest image has a serious bug that causes huge failures.

**Additional context**
Even though the only the latest image that could be seen at https://hub.docker.com/r/frappe/bench. From the GitHub Actions build log, I was able to find some tags with hash of the previous images https://github.com/frappe/frappe_docker/actions/runs/4867010254/jobs/8679149437#step:7:1954. This allowed to pull and use those images. This means the old images are still stored on DockerHub, but just orphaned without any tags to be used.

**Comment by revant** [comment]
Can you send a PR. Allow edits for maintainers.

**Comment by amalpaul54111** [comment]
Yeah, will try to get something ready by this weekend.

**Comment by revant** [comment]
Just for a workaround, you can use git commit history to move back commits as bench is installed using git repo in the image. It is not installed as pip package.

It's installed as pip package in production image only
