### ISSUE TITLE
Not able to install Custom App

### ISSUE THREAD

**Issue by nestorbird** [frappe/frappe_docker#1136]
Hi,

Trying to install a custom app and it was installed in a container but when trying to install that custom app in a site then getting INTERNAL SERVER ERROR also scheduler container get into a stopped state.

Thanks

**Comment by nestorbird** [comment]
No, its not the error of custom app because i'm getting INTERNAL SERVER ERROR for every custom app i'm installing in a site.

**Comment by revant** [comment]
May be someone else can help.

My custom apps for v12, v13, v14 working with containers as expected.

**Comment by azwalzaman** [comment]
> No, its not the error of custom app because i'm getting INTERNAL SERVER ERROR for every custom app i'm installing in a site and also scheduler container get stopped whenever i tried to install a custom app on a site and if i uninstall a custom app then scheduler container gets UP.

I've had this happen sometimes. Try reinstalling the site, taking down the containers, putting them up again.

**Comment by revant** [comment]
Custom apps in production image are added during image build.

Custom apps in development can be added using bench new-app
