### ISSUE TITLE
No more container upgrade

### ISSUE THREAD

**Issue by jbtruffault** [frappe/frappe_docker#1141]
Dears,
Thank you for your work of maintaining frappe and the docker containers to deploy it. 
My update system relies on the tags of the containers, and I noticed that there are not any new tags since January: https://hub.docker.com/r/frappe/frappe-worker/tags

I don't want to complain or put any kind of pressure, but do you know if you're planning to publish new tags in the future or if I should change my update system ? 

Regards

**Comment by revant** [comment]
After 16th Jan 2023 this repo only builds frappe/bench and frappe/erpnext images. https://github.com/frappe/frappe_docker/pull/1032

1. recommended to use single image https://github.com/frappe/frappe_docker/blob/main/docs/migrate-from-multi-image-setup.md
2. Use compat branches and build your own images. https://github.com/frappe/frappe_docker/issues/1039

FAQ: https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions
