### ISSUE TITLE
Using version tags instead of branches

### ISSUE THREAD

**Issue by codezart** [frappe/frappe_docker#1143]
https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md

The above link shows how to install custom apps. Is there a way to use version tags (v14.16.0) of custom apps instead of branches?

Can we have this feature if it isn't present?

**Comment by revant** [comment]
Yes version tags will also work.

example: https://discuss.frappe.io/t/how-do-i-install-the-human-resources-module-in-a-docker-setup/102555/17
