### ISSUE TITLE
Devcontainer bench init command fails due to incompatible nodejs version

### ISSUE THREAD

**Issue by IMS94** [frappe/frappe_docker#1162]
## Description of the issue
Please refer to the following error:
![MicrosoftTeams-image](https://github.com/frappe/frappe_docker/assets/11285165/c0f7dde7-cd09-4368-a786-620e8e17299c)

I have been using frappe devcontainer on a different machine with an old frappe bench image and it worked fine. Recently I wanted to install the devcontainer on a new machine. I used the `frappe/bench:latest` image.

When I run the `bench init` command, the above error occurs now. I can see that the nodejs version is `16.x` in the dockerfile: https://github.com/frappe/frappe_docker/blob/main/images/bench/Dockerfile#L126. IMO, need to update that to `18.x`.

## Context information (for bug reports)
See above

## Steps to reproduce the issue

1. Spin up a devcontainer with latest frappe bench docker image
2. Run `bench init` command

### Expected result
`bench init` command to be successful

**Comment by revant** [comment]
18.x is used by frappe 15.
16.x is used by frappe 14
14.x is used by frappe 13

I'll add 18.x for v15/develop

Try installing frappe version-14 or install nodejs 18 using `nvm` available. Then you can install frappe develop

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/1163
