### ISSUE TITLE
ERPNext v14 with Custom Apps (Docker)

### ISSUE THREAD

**Issue by Bumbleboss** [frappe/frappe_docker#1167]
I have been trying to figure out how to add custom apps to ERPNext via docker.

The instance was deployed using `pwd.yml` in this repository, with the change of the image reference to a url built in accordance to the [documentation](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md)

The docker runs fine but I can't find the apps that were built in the image.

Apps.json
```json
[
  {
    "url": "https://github.com/frappe/education",
    "branch": "develop"
  },
  {
    "url": "https://github.com/frappe/health",
    "branch": "develop"
  },
  {
    "url": "https://github.com/frappe/erpnext",
    "branch": "version-14"
  }
]
```

Cannot be found here either.
![image](https://github.com/frappe/frappe_docker/assets/22979938/56888467-d154-4c62-b3d3-503cfd31f4d9)

**Comment by revant** [comment]
You need to install them on to site, at site creation or later.

`bench new-site ... --install-app=erpnext --install-app=payments --install-app=education --install-app=health`

Make sure you use tags instead of branches and use version-14 branch for `health` with erpnext version-14

**Comment by Bumbleboss** [comment]
Could you please elaborate more on how the command will be used?

I thought the documentation mentioned above the the only required steps to install custom apps, so why was that step not mentioned?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/69fbc2ed91a24a2e8c6324314260807533a818f9/pwd.yml#L71-L71

This line uses the command. Check the erpnext part of the command.

You can add multiple --install-app to install other apps from image

Check command help for more info

`bench new-site --help`
