### ISSUE TITLE
Simple way to add Apps

### ISSUE THREAD

**Issue by abhay-ramesh** [frappe/frappe_docker#1179]
Is there a way to get and install apps by just editing `pwd.yml`

**Comment by revant** [comment]
Build your image and replace it in pwd.yml.

No other way.

**Comment by abhay-ramesh** [comment]
can i know which part of it needs to be replaced?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L5

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L14

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L42

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L93

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L115

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L129

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L143

https://github.com/frappe/frappe_docker/blob/df3daac8ad276543ce3e1eacdc0979ea5c896fe4/pwd.yml#L192
