### ISSUE TITLE
Custom apps Assets not loading in frontend (/sites/assets) 

### ISSUE THREAD

**Issue by hardik-limendo** [frappe/frappe_docker#1185]
Hello Team,
I have created one custom app and in that I have added **/public/js/tabulator.min.js** file. And the same I am using in page JS. 
It's working perfectly in the local system(Without Docker). But this assets not getting loaded in the docker. 

### Local System Frappe Version
- ERPNext: v14.23.3 (version-14)
- Frappe Framework: v14.35.0 (version-14) 

### Docker Enviroment Frappe Version
- ERPNext: v14.30.3
- Frappe Framework: v14.35.0

I am using **pwd.yml** and custom docker image that I have created with payments and hr module. [Custom Image Reference](https://hub.docker.com/layers/hardiklimendo/frappe-payments/v14.35.0/images/sha256-f2095a167177e6454fe04441da7d7bcbbe8b87d2226587ab6e9592ab873c515e?context=repo)

- Added file in hooks.py 
![image](https://github.com/frappe/frappe_docker/assets/130674899/a6c6a5ac-4072-451f-8894-be756a67c15c)

Steps I tried to solve this error.

- Executed Bench Build command (Same issue)
- Created build.json file, bundle.js and mentioned in hooks.py (Same Issue)
![image](https://github.com/frappe/frappe_docker/assets/130674899/ac81e269-c51c-4c25-8c6a-7cbc7c8eb1fc)
- Installed node modules directly using `yarn add tabulator-tables` (Not worked)

#### Below image is for reference from docker where assets is not getting loaded

![image](https://github.com/frappe/frappe_docker/assets/130674899/90f16eaa-b682-452c-aa8c-426b78056507)

#### Below image is for reference from local system where assets is getting loaded.

![image](https://github.com/frappe/frappe_docker/assets/130674899/72c6f09b-2180-48fd-b160-736ada398ace)
.

**Comment by revant** [comment]
assets are mounted in unnamed volume. it means for assets to update

- the unnamed need to be pruned and containers restarted so it creates new volume with new assets
- or containers pruned and restarted, new containers mount new volume with fresh assets.

https://discuss.frappe.io/t/best-way-to-deploy-new-versions-of-custom-app-in-self-hosted-docker-setup/96317

**Comment by revant** [comment]
Share your list of apps so I can try locally.

**Comment by Z4nzu** [comment]
> Share your list of apps so I can try locally.

Hi @revant, 

Thankyou for your response. 

I have installed ERPNext, HRMS, Payments and one new app which contains PAGE only with tabulator.min.js in public. And that I'm trying to use the inside page js. 

Let me know if you want that app so I can create an app and share it here. Also, as I'm checking it's not loading HRMS and payments JS that's also you can see in the screenshots mentioned above. 

Thankyou,
Hardik

**Comment by revant** [comment]
> Let me know if you want that app so I can create an app and share it here

Yes, at least share a repo/app which can reproduce your issue

**Comment by hardik-limendo** [comment]
HI @revant,

Here is the repo link it contains Tabulator and related code. [Tabulator-Test](https://github.com/hardik-limendo/tabulator_test.git)
If assets getting loaded and if table is not showing inside page then refresh page it will loaded.
Please let me know if anything else is required. I am available for a meeting as well. 

Thankyou,
Hardik

**Comment by revant** [comment]
Docs for change in new build system: https://github.com/frappe/frappe/wiki/Migrating-to-Version-14#new-build-system-based-on-esbuild

**Comment by hardik-limendo** [comment]
Hi @revant,
Thanks for your help!

As per document I need to make a bundle and need to mentioned inside page JS. Is there anything else is required to do with Docker? Do I need to remove **`"/home/frappe/frappe-bench/sites/assets"`** from Dockerfile. or It should work without removing. 

I apologise but I am new to ERPNext. 

Thanks,
Hardik

**Comment by revant** [comment]
> Do I need to remove **`"/home/frappe/frappe-bench/sites/assets"`** from Dockerfile. or It should work without removing.

No need to change `Dockerfile`

The assets are unnamed/anonymous volumes. On container restart they should be re-created. That happens when new container is created.

```shell
cd frappe_docker
export APPS_JSON='[               
  {
    "url": "https://github.com/frappe/erpnext",
    "branch": "version-14"
  },
  {
    "url": "https://github.com/hardik-limendo/tabulator_test",
    "branch": "main"
  } 
]'
export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)
docker build \   
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-14 \
  --build-arg=PYTHON_VERSION=3.11.4 \
  --build-arg=NODE_VERSION=16.20.1 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=delete-me:latest \
  --file=images/custom/Containerfile .
```

I used above command to create custom image.

**Comment by hardik-limendo** [comment]
Hi @revant, 
Thank you. It's working now. I just want to ask one more thing what if I am doing some changes in the source code of the custom app. And I want to push in the docker environment. Do I need to create new docker image every time and create new stack or it should directly works from **Pull and Redeploy** (I am using Portainer). And then Data should be there after doing this steps. I am right?

Also, I have another question, What if I made assets as persistent volume? Does this works without creating new image every time. Because I have made apps folder as Persistent because Every developer is pushing and testing there own code.  

Thanks,
Hardik

**Comment by hardik-limendo** [comment]
Hi @revant,

I have some problem with Docker Containers. Current issue, I have exiting live system with database. What I did I just created a new Image with all the custom apps (same as in the live system). Now, I have changed image name to the latest image then save settings and click on the **Pull and Redeploy** button. Without selecting **Re-pull image and redeploy** means my data will be there just Image gets changed. 
![image](https://github.com/frappe/frappe_docker/assets/130674899/e7963d47-6076-4e79-8b00-cb4a530f6dac)

Now, I have restarted the containers and opened Tabulator page but I have same issue now Assets not getting loaded. I am not understanding the structure of Frappe Docker. It should works or not? Because currently It's not working then I need to do fresh  setup using docker-compose file and there I need to transfer Database and other things.

I really would like to get your support here. As, We have many ERPNext systems which is already in Docker and In development stage as well as in Production. 

Thanks,
Hardik

**Comment by revant** [comment]
There are some people using it.
You may have to learn both containers and frappe framework.

Share access to your docker swarm/portainer

**Comment by hardik-limendo** [comment]
Hi @revant,
I need to create a Portainer for you and some stacks there. Then, I will share access with you.
Also, Can you please confirm why assets is not getting loaded with the new Image? 

Thanks,
Hardik

**Comment by revant** [comment]
> Also, Can you please confirm why assets is not getting loaded with the new Image?

They are getting built in my image. I really can't help you much. Tests pass, my images work.

I can't say about others because no one comments here if their setup works, people only post anything if things don't work.

As I can't depend on humans to comment if it works, I depend on tests.

**Comment by hardik-limendo** [comment]
Yes, I agree with your view. What I want you to test is First use the any of the ERPNext image and create a stack using Docker-compose file. Then use the image which has Assets files. Then Redeploy the same stack but with using the latest image only. You will see that assets is not getting loaded there. I am available for a call as well. I can demonstrate the issue as well.

Thankyou,
Hardik

**Comment by revant** [comment]
If you are using dockerswarm and portainer try this.

https://github.com/castlecraft/custom_containers/blob/main/docs/docker-swarm.md

> https://discuss.frappe.io/t/best-way-to-deploy-new-versions-of-custom-app-in-self-hosted-docker-setup/96317

It is mentioned in the post.

**Comment by hardik-limendo** [comment]
Hi @revant, Sorry for the late response! And Thank you for your support.
