### ISSUE TITLE
Is this the same image used in Helm Erpnext?

### ISSUE THREAD

**Issue by philgin** [frappe/frappe_docker#1188]
If I managed to install ERPNext on Kubernetes using ERPNext Chart on HELM. 

But I need to add custom apps. Is the guide here https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md all I need to follow to build a docker image for Helm? Will it be the same image for workers?

Or maybe you have a guide somewhere for adding Custom Apps to ERPNext Helm Chart?

Any guidance is much appreciated.

**Comment by revant** [comment]
If you use the mentioned doc to build your image you can just replace it in `values.yaml` (`image.repository` and `image.tag`).

If it is image from private registry you may need to mention `imagePullSecrets` as array object specified here https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret. e.g.

```yaml
  imagePullSecrets:
    - name: regcred
```
