### ISSUE TITLE
Run docker not working

### ISSUE THREAD

**Issue by aryasoni98** [frappe/frappe_docker#1189]
## Description of the issue
Run Docker command `docker-compose -f ./pwd.yaml up`

## Steps to reproduce the issue

1. Remove the ./pwd.yml `a`
2.
3.

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by aryasoni98** [comment]
I would like to work on it .

**Comment by revant** [comment]
Wait for the `create-site` to complete

https://github.com/frappe/frappe_docker/assets/1040161/05648094-4f91-46ab-b64a-0dc99068ba84
