### ISSUE TITLE
devmode [78227 ms] Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link /bin/sh: 1: /sbin/ifconfig: not found /bin/sh: 1: /sbin/ip: not found

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#119]
Error:

```
[78227 ms] Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/bin/sh: 1: /sbin/ifconfig: not found
/bin/sh: 1: /sbin/ip: not found
```
on vscode container provisioning

**Comment by revant** [comment]
does manual setup for containers work?

I'm not getting this on linux + https://docs.docker.com/install/linux/linux-postinstall

Which OS are you using?

![reopen-incontainer](https://user-images.githubusercontent.com/1040161/76103770-44432280-5ff8-11ea-82bd-a5580a88e077.png)

![in-container](https://user-images.githubusercontent.com/1040161/76103937-8b311800-5ff8-11ea-9468-215168f57a56.png)

**Comment by ddavidebor** [comment]
I was on MacOS, seems a mac-only issue, I've opened a PR with the fix
