### ISSUE TITLE
How to create a generic domain setup?

### ISSUE THREAD

**Issue by sinhpn92** [frappe/frappe_docker#1193]
Hello,

I have set up Frappe ERPNext for my production on Docker with traefik-ssl, mariadb, and multi-bench-ssl. My domain is managed under CloudFlare, and I have set up the A record with a wildcard to point to the server as follows:
`A | *-pro-erp | xxx.x.yyy.yy`

In the `gitops/erpnext-one.yaml` file, I made changes to the `traefik.http.routers.erpnext-one-http.rule: Host(...)` labels under the frontend service to `traefik.http.routers.erpnext-one-http.rule: HostRegexp(^.+-erp.mydomain.com$)`.

Additionally, in the `gitops/erpnext-one.env `file, I configured the sites as follows:
`SITES=`*-erp.mydomain.com``

After starting the Docker service with the command:
`docker compose --project-name erpnext-one -f gitops/erpnext-one.yaml up -d`

I created a new site using the following command:
```
docker compose --project-name erpnext-one exec backend \
bench new-site one-pro-erp.mydomain.com --no-mariadb-socket --mariadb-root-password "12345" --install-app erpnext --admin-password "12345"
```
However, when I access my site using the domain `one-pro-erp.mydomain.com`, it returns an error `404 page not found`.

Could you please review the steps above and suggest a solution to solve this problem? Thank you for taking the time to read and assist.

**Comment by revant** [comment]
> ```
> bench new-site one-pro-erp.mydomain.com --no-mariadb-socket --mariadb-root-password "12345" --install-app erpnext --admin-password "12345"
> ```

Someone complained `--no-mariadb-socket` didn't work when placed after `site-name`

> 404 page not found

It seems to be from traefik. If it is from frappe-bench it says:

```
Not Found
one-pro-erp.mydomain.com does not exist
```

You need to check traefik dashboard for any errors or check any incorrect configurations.

**Comment by sinhpn92** [comment]
Thank you so much @revant 
I checked the traefik dashboard and all success:

<img width="1439" alt="Screenshot 2023-07-28 at 14 16 20" src="https://github.com/frappe/frappe_docker/assets/9253441/545f267d-a053-4b9f-ace7-26308a084e79">
<img width="1443" alt="Screenshot 2023-07-28 at 13 44 46" src="https://github.com/frappe/frappe_docker/assets/9253441/1c47c34b-9987-4a05-8ac2-72c675307f38">

**Comment by sinhpn92** [comment]
You are right @revant 
My traefik configs with `HostRegexp` has not valid. Change to `HostRegexp(`{subdomain:[a-z]+}-pro-erp.mydomain.com`)` will working.

Thank you so much
