### ISSUE TITLE
Unclear local dev documentation, suggestion to update

### ISSUE THREAD

**Issue by naufalafif** [frappe/frappe_docker#1194]
**Is your feature request related to a problem? Please describe.**
Yes, the local development documentation mostly explains how to set things up manually using the bench CLI, and the provided examples use a site with the name "mysite" which points to `mysite.localhost`. However, there is an option to use the `installer.py` script to set up the site automatically, but the generated site uses `development.localhost` instead. This can cause confusion for someone new to Frappe, as they won't be able to check the running sites without exploring the code or CLI.

**Describe the solution you'd like**
Update the manual setup documentation to use `development.localhost` 

**Describe alternatives you've considered**
Update the installer to use `mysite.localhost` as the default site name.

**Additional context**

**Comment by revant** [comment]
Please send PR, I'll prefer change to docs over change to script.

Change to script is also fine.

You can do anything you wish I'll merge.
