### ISSUE TITLE
bench init takes too much time inside devContainer

### ISSUE THREAD

**Issue by umair313** [frappe/frappe_docker#1199]
## Description of the issue
while setting up with docker `bench init` command takes to much time 
## Context information (for bug reports)
bench init seems like stuck there 
`$ /workspace/development/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /workspace/development/frappe-bench/apps/frappe ` took almost more then 30 minutes, some time it also show error like when the node version is not compatible or yarn issue also takes large amount of time. 

## Steps to reproduce the issue

1. clone the frappe_docker repo
2.reopen in devcontainer
3. create frappe-bench with skipping redis config

### Expected result
should take less amount of time and provide logs 
### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
1. mac and windows are slow. It is OS + Virtualization + docker on mac and win. On linux it's OS + docker.
2. internet speed?

It takes 10 min to clone frappe_docker and get into first site to with wizard if you use linux on amd64.
