### ISSUE TITLE
getting error while cloning docker repository on docker

### ISSUE THREAD

**Issue by ManishKumar1989** [frappe/frappe_docker#1201]
## Description of the issue
- Trying to create a dev environment in docker desktop, however, getting error while cloning the git repository
## Context information (for bug reports)
- Trying to create a dev environment in docker desktop, however, getting error while cloning the git repository
## Steps to reproduce the issue

1. create a dev environment
2. choose source - git repo

### Observed result
Preparing to clone inside a volume
Installing credential helpers... 
done
Cloning into '/com.docker.devenvironments.code'...
Detecting main repo language...
Migration: no config.json detected
Migration: no .docker/docker-compose.yaml detected
Unsupported language "Python" - using default base image
loading project: invalid interpolation format for x-customizable-image.image.
You may need to escape any $ with another $.
required variable ERPNEXT_VERSION is missing a value: No ERPNext version set
### Expected result
installation completed
### Stacktrace / full error message if available

Preparing to clone inside a volume
Installing credential helpers... 
done
Cloning into '/com.docker.devenvironments.code'...
Detecting main repo language...
Migration: no config.json detected
Migration: no .docker/docker-compose.yaml detected
Unsupported language "Python" - using default base image
loading project: invalid interpolation format for x-customizable-image.image.
You may need to escape any $ with another $.
required variable ERPNEXT_VERSION is missing a value: No ERPNext version set

**Comment by revant** [comment]
You cannot create dev env from repo.

You need to copy example files first. Which site git ignored

.devcontainer and files in it need to exist first.

Check documentation
