### ISSUE TITLE
Where does the images/custom/Containerfile get the other variables values from?

### ISSUE THREAD

**Issue by aldo-o** [frappe/frappe_docker#1202]
So I am building a Custom Container. So far it's working great, but I was scrolling through `images/custom/Containerfile` and I found some other variables that are not passed during build and I want to have a better understanding. For reference this is the docker build command:

```bash
docker build \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-14 \
  --build-arg=PYTHON_VERSION=3.10.12 \
  --build-arg=NODE_VERSION=16.20.1 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=ec/erpnext:v1.0.0 \
  --file=images/custom/Containerfile .
```

The Dockerfile that I'm looking is [https://github.com/frappe/frappe_docker/blob/main/images/custom/Containerfile](https://github.com/frappe/frappe_docker/blob/main/images/custom/Containerfile)

The variables that I want to know where this Dockerfile gets from are:

- `${DEBIAN_BASE}`
- `${PATH}`
- `${NVM_DIR}`
- `${WKHTMLTOPDF_VERSION}`
- `${WKHTMLTOPDF_DISTRO}`
- `${ARCH}`
- `${APP_INSTALL_ARGS}`

Thank you in advance!

**Comment by revant** [comment]
`${DEBIAN_BASE}`: bookworm as default, can use old bullseye
`${PATH}`: it is NOT a build `ARG`, it is just an `ENV`. PATH env var.
`${NVM_DIR}`: it is NOT a build `ARG`, it is just an `ENV` NVM_DIR env var.
`${WKHTMLTOPDF_VERSION}`: changes as per bookworm or bullseye
`${WKHTMLTOPDF_DISTRO}`: changes as per bookworm or bullseye
`${ARCH}`: it is another env var not a build `ARG`. Used in script to install arm64 or amd64 deps.
`${APP_INSTALL_ARGS}`: it is another env var not a build `ARG`. Used in build script in case apps.json as base64 env var is passed.
