### ISSUE TITLE
refactor for v15

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#1204]
- [ ] merge redis-socketio into redis-queue
- [ ] merge default and short as short worker
- [ ] pwd.yml
- [ ] single server setup docs
- [ ] changes to command to start containers (if any)

Reference: https://frappe.io/blog/engineering/reducing-memory-footprint-of-frappe-framework

**Comment by o314** [comment]
Hi erpnext people
Sensitive information (eg. db password, etc.) should be transmitted via docker secrets too ...

**Comment by revant** [comment]
> Hi erpnext people Sensitive information (eg. db password, etc.) should be transmitted via docker secrets too ...

Not really possible.

Add issue to frappe to deprecate site_config.json for storing secrets.

Custom apps also store secrets in site_config.json.

site_config.json is updated using code, it dynamically changes configs. 

ConfigMap mounted will become read only.

**Comment by ibrahimjamil** [comment]
basically, setup_for_linux_mac is also buggy in docs/images also if we just go through the docs of that it also just show running for some time then when we hit the backend its kind of crash

**Comment by revant** [comment]
> basically, setup_for_linux_mac is also buggy in docs/images also if we just go through the docs of that it also just show running for some time then when we hit the backend its kind of crash

setup_for_linux_mac was contributed and update by community. You can update it if you have and fix.

**Comment by o314** [comment]
> > Hi erpnext people Sensitive information (eg. db password, etc.) should be transmitted via docker secrets too ...
> 
> Not really possible.
> 
> Add issue to frappe to deprecate site_config.json for storing secrets.
> Custom apps also store secrets in site_config.json.
> site_config.json is updated using code, it dynamically changes configs.
> ConfigMap mounted will become read only.

Thanks for your (very) quick answer .
This represents certainly some amount of work.
One can control docker secret thru the cli from python.
I will not take the responsability of opening an issue about that since i have not enough time ressource to track it and follow any kind of progress for now. If someone wants to make things change, you give them some good tips already.
Thanks for your reactivity again
