### ISSUE TITLE
Remote-Containers: Reopen in Container

### ISSUE THREAD

**Issue by AhmadReda** [frappe/frappe_docker#1206]
After this step Remote-Containers: Reopen in Container
i get this message error : 
![image](https://github.com/frappe/frappe_docker/assets/26819123/7ed1df27-0912-474d-bcda-12e1d3e3e4f3)

**Comment by revant** [comment]
Edit compose file and change ports, you'll need to change bench ports as well after bench init.

Or make sure ports from `.devcontainer/docker-compose.yml` are available before starting devcontainer.

**Comment by AhmadReda** [comment]
> Edit compose file and change ports, you'll need to change bench ports as well after bench init.
> 
> Or make sure ports from `.devcontainer/docker-compose.yml` are available before starting devcontainer.

Thanks it's working
