### ISSUE TITLE
Could not convert from development to production

### ISSUE THREAD

**Issue by AhmadReda** [frappe/frappe_docker#1207]
when I try to do this command " sudo bench setup production frappe "
I get this reply : sudo: bench: command not found
so what is the right way to do that?
![image](https://github.com/frappe/frappe_docker/assets/26819123/4022f45a-f802-4bfc-86a3-d7cc088e5966)

**Comment by revant** [comment]
Read FAQ
https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions
