### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by sinhpn92** [frappe/frappe_docker#1213]
Hello,
I encountered an error while attempting to install the HRMS module.

I successfully set up and launched ERPNext by following the instructions provided in this guide: https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

My ERPNext instance is up and running smoothly. However, I'm facing an issue while trying to install the HRMS module on my site. I followed these steps:
```
$ sudo docker compose --project-name erpnext-one exec backend bench get-app hrms
$ sudo docker compose --project-name erpnext-one exec backend bench --site mysite.com install-app hrms
```
Although the HR menu now appears in the side menu, I'm encountering an error indicating that the HR module is not found.
<img width="1800" alt="Screenshot 2023-08-19 at 16 31 41" src="https://github.com/frappe/frappe_docker/assets/9253441/bc841cd0-81d9-409f-8cbc-eb9ec7722985">

I checked the docker logs and identified the following error message: `App hrms not in apps.txt`.

Could you kindly advise on what might be causing this issue? Do you have any suggestions on how to resolve it?

Thank you very much for your assistance.

**Comment by revant** [comment]
You can't get app in production image. Build your own image.

https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions
