### ISSUE TITLE
Authentication problem when running podman

### ISSUE THREAD

**Issue by jrgabrillo** [frappe/frappe_docker#1229]
**Description:**
I am encountering authentication problems while attempting to run podman following the instructions in the frappe_docker custom apps documentation. Despite successfully completing the steps for cloning the repo, building the image, and performing a Docker login, I consistently face authentication issues when running podman. Please refer to the attached screenshots for additional details.

**Steps to Reproduce:**
- Clone the repository using the provided instructions.
- Build the Docker image as per the provided command.
- Perform a Docker login with the required credentials.
- Execute the podman command, which consistently results in an authentication error.

**Screenshots:**
apps.json configuration
> [
>   {
>     "url": "https://github.com/frappe/payments",
>     "branch": "develop"
>   },
>   {
>     "url": "https://github.com/frappe/health",
>     "branch": "develop"
>   },
>   {
>     "url": "https://github.com/frappe/erpnext",
>     "branch": "version-14"
>   }
> ]

Build image command:
> docker build \
>   --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
>   --build-arg=FRAPPE_BRANCH=version-14 \
>   --build-arg=PYTHON_VERSION=3.10.12 \
>   --build-arg=NODE_VERSION=16.20.1 \
>   --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
>   --tag=ghcr.io/jrgabrillo/frappe_docker/health_app:1.0.0 \
>   --file=images/custom/Containerfile .
> 

Podman command that consistently throws authentication error
![Screenshot 2023-09-18 192831](https://github.com/frappe/frappe_docker/assets/19164950/1bcd072e-87a7-4f96-b2cc-818289cd2e23)

**Expected Behavior:**
The podman command should execute successfully without any authentication errors.

Additional Information:
- Operating System: _Centos 9_
- Podman Version: _4.6.1_
- Docker Version (if applicable): _24.0.6, build ed223bc_
- Docker Hub (or other registry) Username: _rufongabrillojr_

I also tried this command but still throws the error:

> echo [PAT Token] | docker login ghcr.io -u jrgabrillo --password-stdin

Please help me resolve this authentication issue with podman. Thank you!

**Comment by revant** [comment]
Do you wish to run kaniko?

Use docker build or buildah.

In case of kaniko use debug image tag instead of latest.

**Comment by jrgabrillo** [comment]
im just following the instructions here. 
![Screenshot 2023-09-18 232438](https://github.com/frappe/frappe_docker/assets/19164950/c8cd14e1-1d04-4ba1-886d-7a230307c335)

I changed some arguments. This is my commands:
> podman run --rm -it \
>   -v "$HOME"/.docker/config.json:/kaniko/.docker/config.json \
>   gcr.io/kaniko-project/executor:latest \
>   --dockerfile=images/custom/Containerfile \
>   --context=git://github.com/frappe/frappe_docker \
>   --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
>   --build-arg=FRAPPE_BRANCH=version-14 \
>   --build-arg=PYTHON_VERSION=3.10.12 \
>   --build-arg=NODE_VERSION=16.20.1 \
>   --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
>   --cache=true \
>   --destination=ghcr.io/jrgabrillo/frappe_docker/health_app:1.0.0 \
>   --destination=ghcr.io/jrgabrillo/frappe_docker/health_app:latest

I am not sure about kaniko. if this is not required to add custom app like health app, then, how to exclude it?

**Comment by revant** [comment]
If you scroll up on the same document you'll find this https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md#build-image

```shell
buildah build \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=version-14 \
  --build-arg=PYTHON_VERSION=3.10.12 \
  --build-arg=NODE_VERSION=16.20.1 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=ghcr.io/user/repo/custom:1.0.0 \
  --file=images/custom/Containerfile .
```

Search forum for "docker hrms", I've answered few posts.

**Comment by jrgabrillo** [comment]
Thanks @revant 

Thanks to your efforts, I was able to successfully install the custom app by following the instructions provided in the GitHub issue: https://github.com/frappe/frappe_docker/issues/1129. Your guidance and support were instrumental in making this happen.

While we're still working on resolving the authentication error with Podman, your assistance has been invaluable. Your dedication to helping the community is greatly appreciated.

Once again, thank you.
