### ISSUE TITLE
update dev container

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#123]
You can assign this issue to me
update development container to use debian as close as possible to the one of the production containers

**Comment by revant** [comment]
- Lock the python 3 versions to the ones in official frappe and erpnext travis tests
- Keep 2 versions of nodejs (v10 & v12) with nvm. ERPNext v11 and v12 development support is already there. If you are able to add ERPNext v10 support it'll be awesome.
- Install nvm in user's $HOME and with user ownership. It allows users to do `npm i <package> -g` without `sudo`.

If anyone can try windows 10 + docker desktop and vs code containers it will help in improving the image

**Comment by ddavidebor** [comment]
Opened #133 to complete before this issue to have more insight
Opened #132 to simplify work a little bit on stuff like this one for production containers

**Comment by ddavidebor** [comment]
@revant I'm not great with virtualenvs if you have suggestions on how to implement your point I'm listening

> * Lock the python 3 versions to the ones in official frappe and erpnext travis tests

**Comment by ddavidebor** [comment]
Opened issue https://github.com/frappe/frappe_docker/issues/137 regarding VSCode testing in Windows, as it's better to do it after the various PR are merged and the container updated

**Comment by ddavidebor** [comment]
> * Lock the python 3 versions to the ones in official frappe and erpnext travis tests
I'm not great with virtualenvs, do you have recommendations?
> * Keep 2 versions of nodejs (v10 & v12) with nvm. ERPNext v11 and v12 development support is already there. If you are able to add ERPNext v10 support it'll be awesome.
Done ! #135 
> * Install nvm in user's $HOME and with user ownership. It allows users to do `npm i <package> -g` without `sudo`.
Done ! #135
