### ISSUE TITLE
How to install dockerized ERPNext on Ubuntu in EC2?

### ISSUE THREAD

**Issue by harshdeepkanhai** [frappe/frappe_docker#1232]
I tried running the docker compose using pwd.yml Its architecture is aarch64
. I am getting this error on the docker logs:
![image](https://github.com/frappe/frappe_docker/assets/61924625/e8546f52-f10a-46bc-9b89-131c4ac98335)
![image](https://github.com/frappe/frappe_docker/assets/61924625/73d84987-11e2-4ae8-a08e-e182676a3a08)

**Comment by revant** [comment]
Container images are built for amd64. Any other arch you'll have to build your own images.

Similar issue #1208

**Comment by marcaurelios** [comment]
@revant does this mean a server with Intel x86_64 (e.g. Intel Xeon) is not supported, AMD only?
