### ISSUE TITLE
Docker build fails for custom image 

### ISSUE THREAD

**Issue by vishwajeetaspl** [frappe/frappe_docker#1237]
## Description of the issue
When trying to run docker build for images/custom/Containerfile it fails with following error
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code

## Steps to reproduce the issue

1. Clone the docker repo
2. Execute the following command docker build   --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe.git   --build-arg=FRAPPE_BRANCH=v14   --build-arg=PYTHON_VERSION=3.10.12   --build-arg=NODE_VERSION=16.20.1   --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64   --tag=ghcr.io/user/repo/custom:1.0.0   --file=images/custom/Containerfile .
3. Fails with error

### Observed result
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code

### Expected result
Docker image should be created 

### Stacktrace / full error message if available

```
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code

```

**Comment by revant** [comment]
> 2\. --build-arg=FRAPPE_BRANCH=v14

There is no such frappe branch or tag.

**Comment by vishwajeetaspl** [comment]
Even if you change the branch it fails , its not failing at that step.

**Comment by vishwajeetaspl** [comment]
@revant Did you even tried to look at the shared error and what it relates to or you just found one in the command and rushed through closing it ?

**Comment by revant** [comment]
Hope someone else helps you close the issue.

**Comment by revant** [comment]
I'll upgrade my images over weekend and they'll work because tests are passing.

https://gitlab.com/castlecraft/cepl-erpnext-images/-/pipelines

I'll post the job log here when I update the images.

**Comment by revant** [comment]
Here is the runner log https://gitlab.com/castlecraft/cepl-erpnext-images/-/jobs/5234966829

It built the image with latest debian bookworm, python 3.11.6, nodejs 16.20.2, frappe/erpnext v14 and india-compliance app.

Hope someone who faces your error helps you, I'll keep the issue open.

**Comment by vishwajeetaspl** [comment]
Hi Revant , 
Thank you for the confirmation. 
 It seems to be specific to my environment which is running Ubuntu 18.04 on my laptop. I tried with a ec2 instance with latest Ubuntu it seems to be working fine.  I will close this issue as it's specific to an environment. 

Thank you for your support  much appreciated.
