### ISSUE TITLE
Docker PWD.YML issue

### ISSUE THREAD

**Issue by syncbricks** [frappe/frappe_docker#1252]
Missing argument 'VALUE'.
 return self.main(*args, **kwargs)
v = self.invoke(ctx)
File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py"
 return f(get_current_context(), *args, **kwargs)
 set-config [OPTIONS] KEY VALUE
 Error: Missing argument 'VALUE'.

**Comment by revant** [comment]
`./installer.py` script works for me for in devcontainers. It is using bench commands including `bench set-config`

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/assets/1040161/0c925f30-60a0-4afc-a5e1-3530c2d12216

Tried pwd.yml locally
