### ISSUE TITLE
Cannot migrate from v14 to v15 module not found redissearch

### ISSUE THREAD

**Issue by sudhegan** [frappe/frappe_docker#1254]
## Description of the issue
I tried migrating to v15, but when i run bench --site all migrate it shows module not found redissearch error
the setup is in docker swarm, with portainer
## Context information (for bug reports)
i also use custom apps listed below
```
[
  {
    "url": "https://github.com/frappe/erpnext.git",
    "branch": "version-15"
  },
  {
    "url": "https://github.com/frappe/hrms.git",
    "branch": "version-15"
  },
  {
    "url": "https://github.com/frappe/education.git",
    "branch": "develop"
  },
  {
    "url": "https://github.com/frappe/payments.git",
    "branch": "version-15"
  },
  {
    "url": "https://github.com/frappe/non_profit.git",
    "branch": "develop"
  },
  {
    "url": "https://github.com/frappe/changemakers.git",
    "branch": "develop"
  },
  {
    "url": "https://github.com/frappe/print_designer.git",
    "branch": "main"
  },
  {
    "url": "https://github.com/frappe/builder.git",
    "branch": "master"
  },
  {
    "url": "https://github.com/resilient-tech/india-compliance.git",
    "branch": "version-15-beta"
  }
]

```
## Steps to reproduce the issue

1. change the version of erpnext conter from v14 to v15
2. then deploy with repull image and deploy in portainer
3. then run bench --site all migrate

### Observed result
previosly the migrate didn't complete successfully, but the it completed with warning module not found redissearch

then when loading the site in browser it says internal server error
when inspected logs the module not found redissearch eroor in backend service
### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
If you're building images with latest and branch based tags then try things with --no-cache.

Also make sure you've pulled latest image is you've pushed it to container registry and pulling from there. You can skip this is you're building and using image locally.

**Comment by sudhegan** [comment]
I found the problem, 

> If you're building images with latest and branch based tags then try things with --no-cache.

actually i did it with --no-cache already but the error is still there
but when i run bench version after update it shows the v14 for all apps.

> Also make sure you've pulled latest image is you've pushed it to container registry and pulling from there. You can skip this is you're building and using image locally.

 (this i thought after u mention to make sure i repull the image thanks for that) as i used persistent volume for apps and assets (/apps and /sites/assets in frappe-bench directory) the update of the image didn't update the persistent volume so removed those volume then repulled the image problem solved thanks by the way.

and to mention i found the backups made by the swarm corn job doesn't show in download backup page, then found that it is because of the timezone +5.30 in browser and UTC in container, so it shows the backup after 5.30 hours to solve this i added TZ environment for all container, it would be nice to have it as a variable in compose file by default

**Comment by revant** [comment]
> it would be nice to have it as a variable in compose file by default

Send a PR if it is necessary for you.

**Comment by sudhegan** [comment]
I don't know hiw to do those things, i just added the TZ evironment in the docker compose file, i will give a pr once learn how to do it ( after kwoimg how to give PR and which file i need to edit in the repositry)
