### ISSUE TITLE
I made similar experiences as @jreduar. Either the password changed or the host ip changed. Inside the Frappe-bench container:

### ISSUE THREAD

**Issue by sudhegan** [frappe/frappe_docker#1256]
I made similar experiences as @jreduar. Either the password changed or the host ip changed. Inside the Frappe-bench container:
* Connect to mysql metatable with: `mysql -h mariadb -u root -prootpass mysql`
* Use `select * from user;` to identify user names.
* Change password with `ALTER USER 'username'@'%' IDENTIFIED BY 'newpass';`, eg. `ALTER USER '_ab9080ba42f22828'@'%' IDENTIFIED BY 'password_from_site_config.json';`
* If USER@HOST does not yet exist `CREATE USER '_ab9080ba42f22828'@'%' IDENTIFIED BY 'password_from_site_config.json';`
* Delete all other USER@HOST entries with `DROP USER '_ab9080ba42f22828'@'172.20.0.4';`
* Make sure the user has the priviliges for the database: `GRANT ALL PRIVILEGES ON database_name.* TO 'username'@'localhost';`, eg. `GRANT ALL PRIVILEGES ON _41da75e60133e6ed.* TO '_41da75e60133e6ed'@'%';`

_Originally posted by @rangerjo in https://github.com/frappe/frappe_docker/issues/448#issuecomment-1157359094_

**Comment by sudhegan** [comment]
the problem still exists as the permission for the user created by bench depends on the ip of the container, we have to change it ( rename user) to make it accessible. it will good to make it accessable by default for the subnet or all IP's as container don't have static IP

**Comment by revant** [comment]
Following works for me:

```shell
bench new-site --no-mariadb-socket --db-root-password=secret --admin-password=admin --install-app=erpnext site.name.com
```

Following may cause problem

```shell
bench new-site site.name.com --no-mariadb-socket --db-root-password=secret --admin-password=admin --install-app=erpnext
```

**Comment by sudhegan** [comment]
So i have to mention the flags before the site name is that correct,, if so pls update it in the docs site operation in this repostry so it helps all
