### ISSUE TITLE
HRMS module breaks installation

### ISSUE THREAD

**Issue by EmmanuelLM** [frappe/frappe_docker#1257]
Hi, successfully installed ERPNEXT 15 on ARM64 and the site is running fine (restored a backup from V14 and migrated with no issued).

Tried to install the HRMS module using the following

`$ bench get-app hrms
$ bench --site [sitename] install-app hrms`

and this does not produce any errors, however the site immediately goes done with "Service unavailble" and the backend reports it cannot find the hrms module, any suggestions?

**Comment by revant** [comment]
Please read FAQ
