### ISSUE TITLE
Redis socketio inadvertently omitted in docker-compose file

### ISSUE THREAD

**Issue by Optimsol** [frappe/frappe_docker#1258]
## Redis socketio inadvertently omitted in docker-compose file in the .devcontainer-example in frappe_docker.

##This leads to "Error: connect ECONNREFUSED 127.0.0.1:13000" when "bench start" command is issued for the container terminal

## Steps to reproduce the issue

1. Clone frappe_docker container and follow instructions for installing frappe docker container for development
2. Run bench start in vscode terminal
3.

### Observed result
error message per below
### Expected result
server start up and available via localhost
### Stacktrace / full error message if available

```
Error: connect ECONNREFUSED 127.0.0.1:13000
```

**Comment by revant** [comment]
you missed set-config part? https://github.com/frappe/frappe_docker/blob/main/docs/development.md#setup-hosts

for v14 you also need to add `redis_socketio` key. Updated docs.
