### ISSUE TITLE
How to build HRMS in ERPNEXT Docker with Buildx

### ISSUE THREAD

**Issue by EmmanuelLM** [frappe/frappe_docker#1259]
Hi, I am building Erpnext via Docker Buildx for an ARM64 platform for version 15 with minor adjustments to the default files... so far so good.

I tried get-app, install-app of HRMS on my site, which failed (seprate issue) because I need to build the HRMS image to include, I am unsure how to do that with Buildx however.

I have looked here (https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) but this doesn't really tell me how to do it with docker buildx - am I right that:
1. Load custom apps through json (as per the URL that finishes with export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0))
2. I rerun docker buildx --no-cache
3. I do docker compose -f pwd.yml up -d
4. I then do bench install-app hrms --site [my site]
?

**Comment by revant** [comment]
Refer: https://discuss.frappe.io/t/how-do-i-install-the-human-resources-module-in-a-docker-setup/102555/17

Today it becomes:

```shell
git clone https://github.com/frappe/frappe_docker && cd frappe_docker

export APPS_JSON='[
  {
    "url": "https://github.com/frappe/erpnext",
    "branch": "v15.0.0"
  },
  {
    "url": "https://github.com/frappe/hrms",
    "branch": "v15.0.0"
  }
]'

export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)

docker build \
  --build-arg=FRAPPE_PATH=https://github.com/frappe/frappe \
  --build-arg=FRAPPE_BRANCH=v15.0.1 \
  --build-arg=PYTHON_VERSION=3.12.0 \
  --build-arg=NODE_VERSION=18.18.2 \
  --build-arg=APPS_JSON_BASE64=$APPS_JSON_BASE64 \
  --tag=custom/hrms:1.0.0 \
  --file=images/custom/Containerfile .

sed -i 's|frappe/erpnext:v15.0.0|custom/hrms:1.0.0|g' pwd.yml

sed -i 's|--install-app erpnext|--install-app erpnext --install-app hrms|g' pwd.yml

docker compose -p pwd -f pwd.yml up -d

docker logs pwd-create-site-1 -f
```
