### ISSUE TITLE
Email with link http://127.0.0.1 installation by docker

### ISSUE THREAD

**Issue by verdnaxeland** [frappe/frappe_docker#1264]
Hi guys, I need some help

I installed it using Docker, but when I send a welcome email when registering a new user, the link to register a password comes as http://127.0.0.1, I'm using a Linux server installed by Docker, can anyone help me please?

![image](https://github.com/frappe/frappe_docker/assets/137925008/dd03346c-e8c9-4db1-9733-fcce7107794a)

Note: all emails come with this link, not just the welcome one, even the unsubscribe one takes you to http://127.0.0.1

**Comment by revant** [comment]
If you're using pwd try changing site name to host/domain name. https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#socketio-does-not-work-with-pwdyml
