### ISSUE TITLE
Why site can't be accessed from the IP address 

### ISSUE THREAD

**Issue by vishwajeetaspl** [frappe/frappe_docker#1267]
Hi , 
I used pwd.yaml to launch a site using docker compose up. But site can only be accessed with the site name used in compose file to create the site. Ideally I should be able to access the site using localhost or IP address but that throws error as doesn't exist. 

Is there any additional step needed to enable this ? Please do suggest a way out for this as people may not have domains mapped while trying this out ?

Let me know in case more details are needed.

**Comment by revant** [comment]
Check this https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md

**Comment by vishwajeetaspl** [comment]
Hi , Not sure if you fully understood what I was trying to say. I am not looking to setup multi tenancy but a single site which should be accessible by the public ip as it doesn't have a domain associated with it.

**Comment by revant** [comment]
> I am not looking to setup multi tenancy

It's describes how to have ip:port based setup for sites.
