### ISSUE TITLE
Can I use pwd.yml as production site? 

### ISSUE THREAD

**Issue by haramishra** [frappe/frappe_docker#1271]
Is using pwd.yml for production safe and how can I connect to an IP address instead of using a port? I am very new to dev ops, I would really appreciate any help.

**Comment by revant** [comment]
Check these:

https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md

https://github.com/frappe/frappe_docker/blob/main/docs/single-compose-setup.md
