### ISSUE TITLE
install a module

### ISSUE THREAD

**Issue by rvmadeit** [frappe/frappe_docker#1277]
Hi,

I have frappe docker everything alright but when I try to install the module HRMS it keeps getting "Internal Server Error" on the webpage here how I install it:

Frappe/erpnext:
1. Download pwd.yml
2. change port 8080 because already use and sudo docker compose up -d
3. open with new port and do the first basic configuration (admin, name, country...)
4. shell to the docker backend and do a bench version:
    erpnext 15.3.0
    frappe 15.2.1
5. Use the command "bench get-app hrms" and successfully install
6. Use the command "bench --site frontend install-app hrms"
8. and now I have an "internal server error" on webpage

9. I try migrate to hrms v.15 with in the app directory the command "git fetch upstream version-15:version-15" and "cd ../.." then "bench update" or "bench --site frontend migrate" but i keep getting the same errors

**Comment by rvmadeit** [comment]
Hi, why closing without giving answers ?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-install-official-or-custom-apps

Answered before here:

- `https://github.com/frappe/frappe_docker/issues/1239`
- `https://github.com/frappe/frappe_docker/issues/1169`
- `https://github.com/frappe/frappe_docker/issues/1144`
- `https://github.com/frappe/frappe_docker/issues/1129#issuecomment-1528697986`

**Comment by revant** [comment]
> Hi, why closing without giving answers ?

Was replying, I tried to search previous issues before reply to find out link.

More on forum here: https://discuss.frappe.io/search?q=https%3A%2F%2Fgithub.com%2Ffrappe%2Ffrappe_docker%2Fwiki%2FFrequently-Asked-Questions

**Comment by rvmadeit** [comment]
oh sorry. ok thanks for help
