### ISSUE TITLE
Restore a backup from S3 storage

### ISSUE THREAD

**Issue by rvmadeit** [frappe/frappe_docker#1280]
Hi, 

I recently configure my s3 bucket storage for backup, everything works fine, but how can I restore my backup with docker because I don't find in the ui the restore option for S3 bucket ?

**Comment by revant** [comment]
> how can I restore my backup with docker because I don't find in the ui the restore option for S3 bucket ?

There's is no ui to restore backups that I know of. If someone else knows, they may help.

Search forum for restoring backup
