### ISSUE TITLE
Install frappe production mode on Azure VM successful but can't access from web browser

### ISSUE THREAD

**Issue by chonlanotr** [frappe/frappe_docker#1300]
Dear Developer.
I install frappe production mode on Azure VM successfully but can't access from web browser

https://github.com/frappe/bench#installation

$ wget https://raw.githubusercontent.com/frappe/bench/develop/easy-install.py
$ python3 easy-install.py --prod --email your@email.tld

all container running

frappeprd:~$ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS                   PORTS                                                                      NAMES
262093a4d85b   frappe/erpnext:v15.7.0   "nginx-entrypoint.sh"    6 minutes ago   Up 5 minutes                                                                                        frappe-frontend-1
3ef31121140b   frappe/erpnext:v15.7.0   "bench worker --queu…"   6 minutes ago   Up 5 minutes                                                                                        frappe-queue-long-1
9e9afc5525a3   frappe/erpnext:v15.7.0   "node /home/frappe/f…"   6 minutes ago   Up 5 minutes                                                                                        frappe-websocket-1
12faef97f583   frappe/erpnext:v15.7.0   "/home/frappe/frappe…"   6 minutes ago   Up 5 minutes                                                                                        frappe-backend-1
b027276e1def   frappe/erpnext:v15.7.0   "bench worker --queu…"   6 minutes ago   Up 5 minutes                                                                                        frappe-queue-short-1
3f9354ff8c88   frappe/erpnext:v15.7.0   "bench schedule"         6 minutes ago   Up 5 minutes                                                                                        frappe-scheduler-1
d61a04e60983   traefik:2.5              "/entrypoint.sh --pr…"   6 minutes ago   Up 6 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   frappe-proxy-1
b58605ee7981   redis:6.2-alpine         "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes             6379/tcp                                                                   frappe-redis-cache-1
7b5175dbbe97   mariadb:10.6             "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes (healthy)   3306/tcp                                                                   frappe-db-1
0c34aea052d8   redis:6.2-alpine         "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes             6379/tcp                                                                   frappe-redis-queue-1

I setup open port 80, 443 from Azure VM already but
can't  access from web browser 

404 page not found****

please suggest me. 
Thanks

**Comment by revant** [comment]
Try specifying site name with --sitename

**Comment by chonlanotr** [comment]
Thks. 
I try this command. 
 python3 easy-install.py --sitename frappeprd.com --prod
but still get "404 page not found"
I install on Azure VM (Ubuntu) and try access from browser on my computer.

**Comment by zamtin2021** [comment]
I am also getting the same 404 on a local VM running Ubuntu 22.04. The log indicates no issues the docker containers appear to be running properly however the IP of the VM returns a 404

**Comment by zqq-nuli** [comment]
I can run and access the

but i will receive

Your connection is not private
