### ISSUE TITLE
"less" package missing in "Dockerfile"

### ISSUE THREAD

**Issue by 0xD0M1M0** [frappe/frappe_docker#1301]
## Description of the issue
When creating the docker images using the "Dockerfile"s in images/ and then using the command "bench --site xyz mariadb" the output of any SQL command returns that "less" is missing.

## Steps to reproduce the issue

1. Create image using e.g. images/custom/
2. Start image and use bench command: bench --site xyz mariadb
3. Enter: show tables;

### Observed result
Error that "less" package is missing

### Expected result
List of tables

### Fix

Add "less \" to the Dockerfiles.

**Comment by revant** [comment]
Send a PR.
make sure it pass pre-commit.
