### ISSUE TITLE
Unable to install frappe-docker to kubernetes, server not responding.

### ISSUE THREAD

**Issue by abhay649** [frappe/frappe_docker#1307]
As suggested, I used helm templates to deploy all the deployments, nfs and ds and service account. However, gunicorn server is not responding to any curl or healthchecks, neither from localhost nor from nginx proxy. 

>frappe@frappe-bench-erpnext-gunicorn-5f57dbc8d4-dpfvq:~$ curl -vkH "host: <SITE_NAME>" 0.0.0.0:8000/
>   Trying 0.0.0.0:8000...
> Connected to 0.0.0.0 (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: <SITE_NAME>
> User-Agent: curl/7.88.1
> Accept: */*
>`

I'm able to connect to database from the pod, so does not looks like connectivity issue.

**Comment by Rishi-NF** [comment]
Hi is there any documentation on deploying this using kubernetes?

**Comment by revant** [comment]
https://github.com/frappe/helm/blob/main/erpnext/README.md

I'm not actively answering same questions anymore, so both frappe and helm repos will have many issues now.

**Comment by Rishi-NF** [comment]
> https://github.com/frappe/helm/blob/main/erpnext/README.md
> 
> I'm not actively closing issues anymore, so both frappe and helm repos will have many issues now.

Sorry was this a reply to me or @abhay649, I just need help with finding resources to deploy erpnext on aws eks cluster, there isnt much i found, please can u share any resources?

**Comment by revant** [comment]
https://gitlab.com/castlecraft/aws-eks-erpnext

You have to read and figure out AWS docs for latest changes.
