### ISSUE TITLE
Feature: autoprovision containers with vscode

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#131]
You can assign this feature request  to me

Automatically provision now manual steps in containers through VScode, de-facto allowing to get started with development with one-click

**Comment by revant** [comment]
`frappe-bench` with frappe and erpnext develop branch installed can be basic thing which is bootstrapped. Debugger is and vscode files in `development` directory are configured such that bench with name `frappe-bench` will be used to attach debugger and python environment

related issues and PRs:

- https://github.com/frappe/bench/issues/949 (issue that can help in automating things)
- https://github.com/frappe/frappe/pull/9649 (this will make it easy to execute queries as bench command)
- https://github.com/frappe/bench/pull/950 (new site will skip redis even in Procfile when the `--skip-redis-config-generation` is used)

Wishlist:
- javascript with vscode chrome debugger

**Comment by ddavidebor** [comment]
Thank you for the info

**Comment by ddavidebor** [comment]
Better to wait for #123

**Comment by ddavidebor** [comment]
My intention is to completely automate the steps that I've not more accurately described in #136

**Comment by revant** [comment]
when new bench is created it serves default site. `sites/common_site_config.json` has entry `"serve_default_site": true,` and also the file `sites/currentsite.txt` exists.

for the bench to serve multiple sites it needs minimum configuration changes after bench init is complete

**Comment by ddavidebor** [comment]
I think then there is a wrong step in the dev documentation, I will check and update it

**Comment by ddavidebor** [comment]
I am closing this because it's best to leave it partially manual so the developer can better understand
