### ISSUE TITLE
erpnext-one_frontend_1 container failing - invalid variable name in /etc/nginx/conf.d/frappe.conf:34

### ISSUE THREAD

**Issue by oscarfono** [frappe/frappe_docker#1311]
I have been attempting to build ERPNext by following [these instructions](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md) , which I have attempted to convert and run in an [Ansible Playbook](https://github.com/oscarfono/configuration_management/blob/main/ansible/roles/erpnext/tasks/main.yml).

I appear to be failing at the last hurdle as you can see here:

`TASK [erpnext : Deploy ERPNext-one containers] ***********************************************************************************************************************************************************************************
changed: [erp.oscarfono.com]

TASK [erpnext : Create sites for ERPNext-one] ************************************************************************************************************************************************************************************
failed: [erp.oscarfono.com] (item=one.erp.oscarfono.com) => {"ansible_loop_var": "item", "changed": true, "cmd": ["docker-compose", "--project-name", "erpnext-one", "exec", "backend", "bench", "new-site", "--no-mariadb-socket", "--mariadb-root-password", "supersecretrootpass", "--install-app", "erpnext", "--admin-password", "supersecretadminpass", "one.erp.oscarfono.com"], "delta": "0:00:00.526435", "end": "2024-01-16 03:12:46.195287", "item": "one.erp.oscarfono.com", "msg": "non-zero return code", "rc": 1, "start": "2024-01-16 03:12:45.668852", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
failed: [erp.oscarfono.com] (item=two.erp.oscarfono.com) => {"ansible_loop_var": "item", "changed": true, "cmd": ["docker-compose", "--project-name", "erpnext-one", "exec", "backend", "bench", "new-site", "--no-mariadb-socket", "--mariadb-root-password", "supersecretrootpass", "--install-app", "erpnext", "--admin-password", "supersecretadminpass", "two.erp.oscarfono.com"], "delta": "0:00:00.769702", "end": "2024-01-16 03:12:48.511070", "item": "two.erp.oscarfono.com", "msg": "non-zero return code", "rc": 1, "start": "2024-01-16 03:12:47.741368", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
erp.oscarfono.com          : ok=18   changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   `

When I log into the Linode host I am attempting to deploy these containers on I note the following:

`root@localhost:~# docker ps -a
CONTAINER ID   IMAGE                     COMMAND                  CREATED       STATUS                      PORTS                                                                      NAMES
d478af719581   frappe/erpnext:v15.10.1   "nginx-entrypoint.sh"    2 hours ago   Exited (1) 29 minutes ago                                                                              erpnext-one_frontend_1
e9b64cfae852   frappe/erpnext:v15.10.1   "/home/frappe/frappe…"   2 hours ago   Up 2 hours                                                                                             erpnext-one_backend_1
d5f07e95bd01   frappe/erpnext:v15.10.1   "bench worker --queu…"   2 hours ago   Up 2 hours                                                                                             erpnext-one_queue-long_1
c20d5293e3f2   frappe/erpnext:v15.10.1   "bench schedule"         2 hours ago   Up 2 hours                                                                                             erpnext-one_scheduler_1
34b9af861edc   frappe/erpnext:v15.10.1   "node /home/frappe/f…"   2 hours ago   Up 2 hours                                                                                             erpnext-one_websocket_1
9e27db3101e9   frappe/erpnext:v15.10.1   "bench worker --queu…"   2 hours ago   Up 2 hours                                                                                             erpnext-one_queue-short_1
c04f46f49da1   frappe/erpnext:v15.10.1   "bash -c 'ls -1 apps…"   2 hours ago   Exited (0) 29 minutes ago                                                                              erpnext-one_configurator_1
2bda09b905e2   redis:6.2-alpine          "docker-entrypoint.s…"   2 hours ago   Up 2 hours                  6379/tcp                                                                   erpnext-one_redis-queue_1
67e958444d96   redis:6.2-alpine          "docker-entrypoint.s…"   2 hours ago   Up 2 hours                  6379/tcp                                                                   erpnext-one_redis-cache_1
d29077fb9331   mariadb:10.6              "docker-entrypoint.s…"   2 hours ago   Up 2 hours (healthy)        3306/tcp                                                                   mariadb-database
7aa1626d139d   traefik:v2.6              "/entrypoint.sh --pr…"   2 hours ago   Up 2 hours                  0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   traefik_traefik_1`

Inspecting the logs for the failed container I see this:

`root@localhost:~# docker logs d478af719581
PROXY_READ_TIMEOUT defaulting to 120
2024/01/16 01:43:24 [emerg] 8#8: invalid variable name in /etc/nginx/conf.d/frappe.conf:34
PROXY_READ_TIMEOUT defaulting to 120
2024/01/16 01:46:16 [emerg] 8#8: invalid variable name in /etc/nginx/conf.d/frappe.conf:34
PROXY_READ_TIMEOUT defaulting to 120
2024/01/16 01:53:32 [emerg] 7#7: invalid variable name in /etc/nginx/conf.d/frappe.conf:34
PROXY_READ_TIMEOUT defaulting to 120
2024/01/16 02:22:32 [emerg] 8#8: invalid variable name in /etc/nginx/conf.d/frappe.conf:34
PROXY_READ_TIMEOUT defaulting to 120
2024/01/16 03:12:44 [emerg] 8#8: invalid variable name in /etc/nginx/conf.d/frappe.conf:34`

I can't seem to catch this container up long enough in order to see what exactly it is crying about.

Is there someone who has experienced similar issues that might know what's up or can enlighten me as to how best to investigate this?  

Any help appreciated. 

Cheers.

**Comment by revant** [comment]
`FRAPPE_SITE_NAME_HEADER` needs to be set to `$host` so it renders into the nginx.conf.

In case of compose yaml `$` needs to be escaped with `$$`. Check if it is related to that.

**Comment by oscarfono** [comment]
specifying that in my config certainly progressed this along thank you.
