### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by zqq-nuli** [frappe/frappe_docker#1312]
https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

I performed the installation test based on this document
I strictly followed the document process step by step
After I installed it and started the Traefik container
When I use a domain name to access this panel, a browser-native account and password box will pop up.
I tried like crazy and couldn't find the correct password.
I'm surprised that it's not the password set by my Traefik env file.
Nor is it my server’s ssh password.
I can't log in normally

**Comment by revant** [comment]
set the traefik password manually instead of `echo 'HASHED_PASSWORD='$(openssl passwd -apr1 changeit | sed 's/\$/\\\$/g') >> ~/gitops/traefik.env`

sed command created issues for some users.

**Comment by revant** [comment]
note is added here now 
https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md#install-traefik

> If Container does not deploy put the HASHED_PASSWORD in ''.
