### ISSUE TITLE
Docker Shim Deprecated in Kubernetes

### ISSUE THREAD

**Issue by sharad740** [frappe/frappe_docker#1317]
From official Documentation of Kubernetes ! 

![image](https://github.com/frappe/frappe_docker/assets/48079990/b05df142-4e23-4596-8b3e-7769711349ea)

**Comment by revant** [comment]
I'm using containerd on scalway. I've used CRI-O for someone else.
Just the repo name is `frappe_docker`.

Try buildah, podman.
