### ISSUE TITLE
Database password 

### ISSUE THREAD

**Issue by EsakkiSundar** [frappe/frappe_docker#1319]
I installed ERPNext via docker. I wanted to connect to the database through MySQL Workbench/DBeaver. Please let me know where I can find the the database password to connect from the client. Also please suggest the steps for accessing the database which is running inside a container to be accessed from a MYSql client.

**Comment by revant** [comment]
It is the `DB_PASSWORD` variable you've set.

exec into mariadb container and check the value of `MYSQL_ROOT_PASSWORD` env var.

**Comment by EsakkiSundar** [comment]
> It is the `DB_PASSWORD` variable you've set.
> 
> exec into mariadb container and check the value of `MYSQL_ROOT_PASSWORD` env var.

I haven't set anything. Just downloaded the docker image and brought the application.  So what will be the default password which the image has
