### ISSUE TITLE
How to integrate with Bench/ERPNext Docker Compose setup

### ISSUE THREAD

**Issue by MatthewReed303** [frappe/frappe_docker#1324]
Hi, I can't find any documentation on how to install on Bench/ERPNext that's running with docker. I looks like it's a complete standalone builder so only Bench is needed to install. Do I just execute shell on Bench container and do bench install and then expose port 8000 via docker compose? Don't want to break anything, so just asking before I give it a go. Thanks

**Comment by revant** [comment]
pwd.yml uses production images. You need to build your own image using the documentation here https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
