### ISSUE TITLE
Bad Gateway Error

### ISSUE THREAD

**Issue by vamagithub** [frappe/frappe_docker#1325]
## Description of the issue
I am following the [single server example] guide (https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md)
My newly created site runs fine once i complete the installation of Frappe and ERPNext.
The moment i do a migrate or installation of any other custom app using the following command it fails and either goes into Internal Server Error (saying the custom app not found) or 502 Bad gateway error. (Logs on backend, mariadb container shows no error )

```
docker compose --project-name erpnext-one exec backend bench --site example.com install-app my-custom-app
```

Help me debug this problem.

**Comment by revant** [comment]
App must be built as part of image.

apps.txt must have list of all apps from frappe-bench/apps directory. Execute `ls -1 apps > sites/apps.txt` to add all apps to apps.txt.

**Comment by vamagithub** [comment]
Hi @revant 
Thank you for replying
I have custom-app name added in the Apps.txt
Should i restart container once i install-app on the site ?
Can you please elaborate on 
> App must be built as part of image.
 Can you please share the command

**Comment by revant** [comment]
If you can reproduce the error on open source repo I can check.

We're using multiple apps on different setups without app installation errors.

**Comment by vamagithub** [comment]
Ok, basically i have to create an image from the custom app and then install it ?

**Comment by insatiable-foo** [comment]
we should build an image with custom app, we followed this [https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) to install custom apps it worked
