### ISSUE TITLE
Help installing frappe/erpnext V15 on Ampere A1 Compute (ARM)

### ISSUE THREAD

**Issue by MrGiveItAway-TPK** [frappe/frappe_docker#1328]
Hello there,
im have an Ampere A1 Compute (ARM) Oracle Cloud Free Server and i want to install frappe / erpnext the issues is that installing via tutorials like D-Code Tutorials or Offfical Frappe Tutorials or Via Docker is not working for me and ive been searching the internet for 3 days without luck even the stuff i found regarding arm on github issues or internet didnt help me at all so please can someone guide me out on how to install frappe and erpnext version 15 in this type of server Ampere A1 Compute (ARM) Running Ubuntu 22.04 i dont mind a script or docker or anyway just please provide a method

**Comment by revant** [comment]
Arm images are not built

**Comment by MrGiveItAway-TPK** [comment]
ok can you help me build one @revant

**Comment by revant** [comment]
build your own image on an ARM VM https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md

then push it to registry and use.

**Comment by MrGiveItAway-TPK** [comment]
ill test the steps out if i face any issue ill revert back here to you and if it works ill make this solved and maybe make a video guide to help out other people @revant

**Comment by MrGiveItAway-TPK** [comment]
ok i built it successfuly via the steps with docker and put the tag in the compose.yaml
after that i ran docker compose up -d and in docker ps:
```bash
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS     NAMES
95769e1e2627   mrgiveitawaytpk/frappe_arm:1.0.0   "nginx-entrypoint.sh"    15 minutes ago   Up 15 minutes             frappe_docker-frontend-1
846f2423c4b0   mrgiveitawaytpk/frappe_arm:1.0.0   "bench schedule"         15 minutes ago   Up 15 minutes             frappe_docker-scheduler-1
3bb7d84b949b   mrgiveitawaytpk/frappe_arm:1.0.0   "/home/frappe/frappe…"   15 minutes ago   Up 15 minutes             frappe_docker-backend-1
```
now how can i see the frappe instance where is it running this is on my server i tried my server ip and my server ip :8000
it just showed nginx main page how can i setup the site and the port and so on

**Comment by MrGiveItAway-TPK** [comment]
nvm managed to do it ill make a tutorial shortly for anyone and put it online

**Comment by atulnavadiya** [comment]
Hello @MrGiveItAway-TPK Can you share the tutorial on how you managed to install it ?
