### ISSUE TITLE
Where are backups saved when using pwd.yml?

### ISSUE THREAD

**Issue by vinn2010** [frappe/frappe_docker#1335]
I used [this guide to install erpnext on linux](https://github.com/frappe/frappe_docker/blob/main/docs/setup_for_linux_mac.md). It works perfectly. Inside settings I have set the backup to `3` and encrypted. 

Where do these backups get saved? 

Inside various documentation files, I see mention of the `sites/` folder. But I cannot see this folder anywhere.

The docker volumes have the following files:

```
24K	161bb736204bbb55a8d65d9836918d49b1b098950f69d445beb532ceefcf2a2c
24K	1be19d489a15e0a5225230f8d4fa880fc252164a795e98fbc365c0f6b8dac724
24K	6a723125f4b89d9384561a195bcfc28082008e198d354592c785e2f0071a3931
24K	a8c3f3816394914c9d42f0a6d45a4eff0079669efeef606fe1deee842b4fe94b
24K	bdebec5c963b1ce7232bb4cd71db17eb89e47eb217efb867377fbf41a532f0e0
24K	c06122dbbfde87d8a403404fb509a1f60c22e44bdd80b24a067861724d8faf49
24K	c259ca08db31bfccb75fb492080d669c303cc3460590e771528d74d9b0ba36a8
24K	e10dadbe18d43646bfff8e0d5a2655314648e61180468ba173622063bb9ac7a3
32K	frappe_docker_redis-queue-data
32K	metadata.db
712K	frappe_docker_sites
1.3M	frappe_docker_logs
2.0M	frappe_docker_redis-cache-data
314M	frappe_docker_db-data
```

Are any of these the backups?

With this install, I did not make any changes to any ENV variables. Is this a suitable install style for production?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/main/docs/backup-and-push-cronjob.md

First setup a cron job for executing backup command.
