### ISSUE TITLE
Websocket Container cannot Establish a connection to Port 6379

### ISSUE THREAD

**Issue by siegan-g** [frappe/frappe_docker#1348]
## Description of the issue
When following the instructions outlined in the `setup-options.md` documentation or attempting to run the Docker containers using the default `compose.yaml`, the `websocket`, `short-queue`, and `long-queue` containers encounter errors and terminate unexpectedly. The stacktrace seems to show that the websocket container cannot establish a connection to port 6379. If I run a netstat` it seems the port is not being listened on.

Utilizing the default `pwd.yml` configuration file with Docker Compose successfully initializes the Docker containers, and the application can be accessed as intended via localhost:8080.

## Context information (for bug reports)
I've attached the compose log file as `container-logs.txt` below which shows the respective Errors thrown.
## Steps to reproduce the issue

1. Pull the main branch of frappe_docker
2. Create an `.env` variable by coping the example docker environment file `cp example.env .env`  and leave values as default.
3. Create a `gitops` directory in user home directory: `mkdir ~/gitops` 
4.  Run the container stack with docker compose: `docker compose --project-name test-project -f ~/gitops/docker-compose.yml up`

### Observed result
- Creates the following containers: `configurator`, `websocket`, `queue-short`, `backend`, `queue-long`. `scheduler,frontend` 
- The `websocket` container throws a ECCONNREFUSED Error when connecting to port 6379. This seems to effect the RedisClient Instance.
- The queue containers

### Expected result
- Create and run the create-site container
### Stacktrace / full error message if available

[container-logs.txt](https://github.com/frappe/frappe_docker/files/14478744/container-logs.txt)

**Comment by revant** [comment]
`bench set-config` command is failing. Some env vars are not set properly?

**Comment by siegan-g** [comment]
Hi 
Sorry for the late reply. I'm using the default .env file - though judging from the comments in the file most seem optional?
I've attached it here just in case.
[env.txt](https://github.com/frappe/frappe_docker/files/14617625/env.txt)

**Comment by revant** [comment]
try passing using `docker compose --env-file=/path/to/env ...`

If the correct variables are set, the configuration container that runs `bench set-config` commands should not fail because it finds incorrect params. Incorrect number of params means variable is blank, shell assumes param as missing.
