### ISSUE TITLE
Replace Redis with Valkey due to redis licensing changes

### ISSUE THREAD

**Issue by cwooldridge** [frappe/frappe_docker#1364]
This is a request to replace Redis in the environment with https://github.com/valkey-io/valkey
due to license changes by Redis. It is no longer under the  BSD-3-Clause license.  Valkey is a fork that is being maintained by the Linux Foundation.  https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community

**Comment by revant** [comment]
We'll follow https://github.com/valkey-io/valkey-container. Once official images are ready we'll change.

**Comment by parasiteoflife** [comment]
Sorry to reopen but is this still the case? The override files are using redis and as far as I know they are not fully compatible anymore

**Comment by DanielRadlAMR** [comment]
Yeah, we’re still using Redis. Since Redis 8 is also available under AGPLv3, it should be fine for us to use. Where did you run into compatibility issues?
