### ISSUE TITLE
ModuleNotFoundError after trying bench install-app in production setup

### ISSUE THREAD

**Issue by ristein** [frappe/frappe_docker#1366]
Hi there.
I accidentally used:

> bench get-app hrms
bench --site frontend install-app hrms
bench migrate

in both backend and frontend container.
Now nothing is working anymore, it only says "Internal Server Error"
I tried recreating containers.
I tried using commands "bench uninstall-app" and "bench remove-app".
sites/apps.txt does not list hrms.
In backend container I deleted block mentioning hrms from sites/apps.json.
What can I do?
[error.txt](https://github.com/frappe/frappe_docker/files/14854452/error.txt)

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/1327#issuecomment-1925305399

Read https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions

You need to build custom image to install additional apps.

**Comment by ristein** [comment]
yes, but can I fix this without installing?
