### ISSUE TITLE
Documentation variables outdated

### ISSUE THREAD

**Issue by r1ckr** [frappe/frappe_docker#1369]
## Description of the issue
In the documentation mentions the variable FRAPPE_VERSION, but in the example.env file it doesn't exists, instead it is ERPNEXT_VERSION.

I think the change is pretty simple, just change the variable in the example file to FRAPPE_VERSION.

**Comment by revant** [comment]
Please send PR.

**Comment by gparent** [comment]
My understanding is that `ERPNEXT_VERSION` is version of the ERPNext Docker image that is pulled when you are not building your own, whereas `FRAPPE_BRANCH` and `FRAPPE_PATH` are used for the Frappe framework repo and version. Is this correct?

**Comment by r1ckr** [comment]
Then the documentation is the one that needs to be updated?
