### ISSUE TITLE
Test images on Windows

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#137]
Opened from @revant suggestion in #123 

Test development images with VSCode on windows
You can assign this issue to me unless you develop on Windows. I will use VMs to test it.

**Comment by revant** [comment]
Needs Docker Desktop. Won't work on Docker Toolbox. 

> Windows: Docker Desktop 2.0+ on Windows 10 Pro/Enterprise. (Docker Toolbox is not supported. Windows container images are not supported.)
https://code.visualstudio.com/docs/remote/containers#_system-requirements

User of Docker Toolbox can fallback to manually starting containers and opening the `development` directory in any editor.

**Comment by ddavidebor** [comment]
I'm testing on windows

**Comment by ddavidebor** [comment]
Everything works on windows
