### ISSUE TITLE
Make compose compatible with newer Apple Silicon

### ISSUE THREAD

**Issue by r1ckr** [frappe/frappe_docker#1370]
**Is your feature request related to a problem? Please describe.**
Yeah, the compose file doesn't work in MacOS with Apple Silicon

**Describe the solution you'd like**
To be able to run docker compose up -d in arm based chips

**Solution**
To add the `platform: linux/amd64` in the compose template, to indicate docker to download the linux version of the image instead of looking for the arm manifest.

**Comment by Zirma** [comment]
it's not a full compatibility as there is performance issue. Please, provide docker image for platform: linux/arm64
