### ISSUE TITLE
Restoring database in development containers

### ISSUE THREAD

**Issue by meaziz** [frappe/frappe_docker#1386]
In development container 
Restoring database to site throws that file command is not found

## Context information (for bug reports)
running 
```
bench --site [site name] restore sql_path
```
It throws file command not found..

remedied with a temp fix.. 
```
sudo apt-get update
sudo apt-get install -y file
```

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/4be1624641aabe51033a4743a0f6735ea2c4b2be/images/bench/Dockerfile#L72

Pull latest image and rebuild dev container
