### ISSUE TITLE
Starting development setup using honcho command does not work

### ISSUE THREAD

**Issue by khadijazaki2** [frappe/frappe_docker#140]
As mentioned that we should use honcho instead of bench start it does not start, what could be the issue?

**Comment by revant** [comment]
Are you using vscode or manual startup of containers?
Are you inside the container before executing the command?
Are you in `frappe-bench` directory?

I'm not able to reproduce the issue.

![working-honcho](https://user-images.githubusercontent.com/1040161/76316836-3ac00000-6301-11ea-8632-95b2e77cc252.png)

**Comment by ddavidebor** [comment]
Also, maybe @khadijazaki2 please post the commands you ran and the errors you receive

**Comment by khadijazaki2** [comment]
I am following the [readme](https://github.com/frappe/frappe_docker/blob/develop/development/README.md) of development using vscode, on the last its written:
We need to start bench separately through the VSCode debugger. For this reason, instead of running bench start you should run the following command inside the frappe-bench directory:

honcho start \
    socketio \
    watch \
    schedule \
    worker_short \
    worker_long \
    worker_default

This command starts all processes with the exception of Redis (which is already running in separate container) and the web process. The latter can can finally be started from the debugger tab of VSCode.

I ran the above honcho command the way its written, It starts the processess but localhost:8000 does not load

**Comment by khadijazaki2** [comment]
![Screenshot from 2020-03-10 18-38-57](https://user-images.githubusercontent.com/55739397/76317808-950b9180-62fe-11ea-81c7-284256845bc1.png)
![Screenshot from 2020-03-10 18-39-35](https://user-images.githubusercontent.com/55739397/76317813-976deb80-62fe-11ea-9c80-f865c5fb294d.png)

**Comment by khadijazaki2** [comment]
If I write just `honcho start` it loads the website but then I have issue that sockets are still not working. As mentioned in the readme to start using given command it should that way.

**Comment by revant** [comment]
did you miss the last part?

https://github.com/frappe/frappe_docker/blob/develop/development/README.md#visual-studio-code-python-debugging

> This command starts all processes with the exception of Redis (which is already running in separate container) and the web process. The latter can can finally be started from the debugger tab of VSCode.

"The latter can can finally be started from the debugger tab of VSCode."

![manual-debug-start](https://user-images.githubusercontent.com/1040161/76319259-fa628100-6304-11ea-8552-e8a1fc5abf2c.png)

**Comment by revant** [comment]
Reopen of issue persists

**Comment by khadijazaki2** [comment]
Yes I missed that part now its working
