### ISSUE TITLE
How to Dockerize a project with Customised configuration

### ISSUE THREAD

**Issue by snehaenola** [frappe/frappe_docker#1418]
I have a project which uses pre existing apps namely frappe, erpnext, hrms and payments
I have made customisation in those apps by adding doctypes, fields for the existing doctypes and API endpoints 
Now i want to Dockerize the whole project with these customisations added, there are lots of resources for dockerising custom apps, but didnt find any similar to my issue

**Comment by revant** [comment]
You need to start with git first. The changes in code need to be pushed to your git fork.

Use your fork and branch for frappe and other apps.

for frappe it is set as FRAPPE_PATH build arg and for apps use the apps.json.
