### ISSUE TITLE
how to secure docker container (custom images) 

### ISSUE THREAD

**Issue by hieuNV0871** [frappe/frappe_docker#1431]
i custom images docker frappe
and i do not want anyone who pull image and run container can change administrator password when use docker exec

**Comment by sudhegan** [comment]
i dont understand the question, u don't want others to pull the image or dont want to change password (change which password, frappe administrator password is configured in yaml)

**Comment by revant** [comment]
- do not share vm access.
- create and use private registry.
- do not share kubernetes or docker host access. 
- keep images updated.
