### ISSUE TITLE
how to customize db name/password with freshing install by docker?

### ISSUE THREAD

**Issue by Kingwayer** [frappe/frappe_docker#1440]
I want deploying nexterp with docker but want customize db name/password(also about database root password)

How can I able do it? I saw example.env may do it:https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md
but not successes, so I am looking for help here.

**Comment by revant** [comment]
We're using mariadb docker image, https://hub.docker.com/_/mariadb. Check the environment variables for image to configure.

Check `bench new-site --help` for site db options available.
