### ISSUE TITLE
Docker containers for development, vuejs SPA and port 9000 cors issues

### ISSUE THREAD

**Issue by sduenasg** [frappe/frappe_docker#1449]
Hi,

We have a development frappe docker environment deployed locally on Linux (using dev containers in vscode), and we created a vue.js app inside one of our apps using Doppio. We built the SPA (bench build) and access it from development.localhost:8000/dashboard_name. This vue js app shows up, but keeps getting these errors trying to access port 9000 (socketio)

![image](https://github.com/user-attachments/assets/32429abd-84ea-4baf-b45d-0cc8603a0b6d)

![image](https://github.com/user-attachments/assets/cfd00f7f-13d5-43b8-af7c-fe6054fe8547)

Can anyone help? seems like there is some kind of CORS problem, but not really sure how to troubleshoot and fix this. We added to site_config.json the following to no avail::

```
 "allow_cors": [
  "*"
 ],
```

**Comment by sduenasg** [comment]
Ok, if i disable the socket (from the example app that doppio creates), the error stops. For now we'll leave it like that.

**Comment by indusworks-io** [comment]
you need to enable csrf for this
