### ISSUE TITLE
WebSockets / socket.io issue with docker install

### ISSUE THREAD

**Issue by oleynikd** [frappe/frappe_docker#1456]
Hello,
Websockets are not working with docker instal. I tried both pwd.yml and custom images with `docker compose config` - same result. When I open the app in browser I see error in logs:
```
socketio_client.js:49 WebSocket connection to 'wss://xxxx/socket.io/?EIO=4&transport=websocket&sid=elHjhjQeQBL4OM48AAAv' failed: WebSocket is closed before the connection is established.
```

As you can imagine, live data updates doesn't work. If I ask console `frappe.realtime.socket.connected` it says `false`.
 
<img width="1369" alt="Screenshot 2024-08-09 at 02 11 18" src="https://github.com/user-attachments/assets/54af96c6-b724-445b-8a66-189313c49f1c">

All my containers are working. websocket container is up and healthy. 
Here's the `common_site_config.json`:
```json
{
 "db_host": "db",
 "db_port": 3306,
 "default_site": "myerp",
 "redis_cache": "redis://redis-cache:6379",
 "redis_queue": "redis://redis-queue:6379",
 "redis_socketio": "redis://redis-queue:6379",
 "socketio_port": 9000
}
```
It is not a local install. This runs on remote server with SSL enabled. 
Installed apps:
```
ERPNext: v15.32.1
Frappe Framework: v15.37.0
Frappe HR: v15.25.2
```

Please help me to figure out what is wrong.
Thanks. 🙏

**Comment by oleynikd** [comment]
The problem was with the `FRAPPE_SITE_NAME_HEADER` env variable. I set it to a custom name like `myerp`, but I had to use full domain name (which is actually [described here](https://github.com/frappe/frappe_docker/blob/main/docs/environment-variables.md#frappe_site_name_header)).
This value will be used (among others) by nginx proxy to pass requests to socket.io server [here](https://github.com/frappe/frappe_docker/blob/624fc2ea83ce96d7e7cd3f352f45494d39b7a263/resources/nginx-template.conf#L41).
Once I changed it and recreated my site - everything is working.

**Comment by LinoBert** [comment]
@oleynikd I'm experiencing the exact same issue you were dealing with, but with the default configuration.


`  frontend:
    image: frappe/erpnext:v15.37.0
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"`
      
      When using the page  on localhost, I can't establish a websocket connection.  Does anyone have an idea why the default setup doesn't work out of the box?
      
![image](https://github.com/user-attachments/assets/af12d13c-5359-4875-9c4f-e26bc31c96e0)
