### ISSUE TITLE
docker compose -f pwd.yml up -d 

### ISSUE THREAD

**Issue by dulkifal** [frappe/frappe_docker#1460]
docker compose -f pwd.yml up -d

[+] Running 10/11
 ⠦ queue-short Pulling                            2.5s
 ✘ frontend Error      context...                 2.5s
 ✘ db Error            context cance...           2.5s
 ✘ queue-long Error    conte...                   2.5s
 ✘ backend Error       context ...                2.5s
 ✘ redis-queue Error   cont...                    2.5s
 ✘ websocket Error     contex...                  2.5s
 ✘ redis-cache Error   cont...                    2.5s
 ✘ scheduler Error     contex...                  2.5s
 ✘ create-site Error   cont...                    2.5s
 ✘ configurator Error  con...                     2.5s
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by dulkifal** [comment]
finally i found this
frappe_docker/docs/setup_for_linux_mac.md at main · frappe/frappe_docker
(github.com)
<https://github.com/frappe/frappe_docker/blob/main/docs/setup_for_linux_mac.md>

**Comment by dulkifal** [comment]
how to reverese that issue

**Comment by revant** [comment]
Closing the issue. Reopen if needed.

**Comment by dulkifal** [comment]
Thanks, it worked.
