### ISSUE TITLE
Front End doesn't load: Ubuntu 22.04.4 LTS

### ISSUE THREAD

**Issue by EasternIndustries-IT** [frappe/frappe_docker#1463]
The instrucionts in the read me doesn't work with ubuntu. But it works with windows docker desktop.

## Steps to reproduce the issue

1. Follow readme instructions 
2.wait for the configuration container to exit
3. on a separate computer whiles watching the  logs of ubuntu docker, go to the ip at port 8080

### Observed result
`frappe_docker-backend-1       | [2024-09-06 19:43:24 +0000] [7] [ERROR] Error handling request /
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
frappe_docker-backend-1       |     init_request(request)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 195, in init_request
frappe_docker-backend-1       |     frappe.local.http_request = HTTPRequest()
frappe_docker-backend-1       |                                 ^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 43, in __init__
frappe_docker-backend-1       |     self.set_session()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 77, in set_session
frappe_docker-backend-1       |     frappe.local.login_manager = LoginManager()
frappe_docker-backend-1       |                                  ^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 119, in __init__
frappe_docker-backend-1       |     self.make_session(resume=True)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 205, in make_session
frappe_docker-backend-1       |     frappe.local.session_obj = Session(
frappe_docker-backend-1       |                                ^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
frappe_docker-backend-1       |     self.resume()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 290, in resume
frappe_docker-backend-1       |     self.validate_user()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 223, in validate_user
frappe_docker-backend-1       |     frappe.throw(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 652, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 617, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.ValidationError: User Guest is disabled. Please contact your System Manager.
frappe_docker-backend-1       |
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       |
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
frappe_docker-backend-1       |     endpoint, renderer_instance = path_resolver.resolve()
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
frappe_docker-backend-1       |     resolve_redirect(self.path, request.query_string)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 118, in resolve_redirect
frappe_docker-backend-1       |     redirects += frappe.get_all(
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2064, in get_all
frappe_docker-backend-1       |     return get_list(doctype, *args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2039, in get_list
frappe_docker-backend-1       |     return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 185, in execute
frappe_docker-backend-1       |     self.columns = self.get_table_columns()
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 546, in get_table_columns
frappe_docker-backend-1       |     return get_table_columns(self.doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 73, in get_table_columns
frappe_docker-backend-1       |     return frappe.db.get_table_columns(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 1190, in get_table_columns
frappe_docker-backend-1       |     raise self.TableMissingError("DocType", doctype)
frappe_docker-backend-1       | pymysql.err.ProgrammingError: ('DocType', 'Website Route Redirect')
frappe_docker-backend-1       |
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       |
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
frappe_docker-backend-1       |     keepalive = self.handle_request(req, conn)
frappe_docker-backend-1       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
frappe_docker-backend-1       |     respiter = self.wsgi(environ, resp.start_response)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 79, in application
frappe_docker-backend-1       |     app(environ, start_response),
frappe_docker-backend-1       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 190, in application
frappe_docker-backend-1       |     resp = f(*args[:-2] + (request,))
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 132, in application
frappe_docker-backend-1       |     response = handle_exception(e)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 395, in handle_exception
frappe_docker-backend-1       |     response = get_response("message", http_status_code=http_status_code)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
frappe_docker-backend-1       |     response = ErrorPage(exception=e).render()
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
frappe_docker-backend-1       |     html = self.get_html()
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
frappe_docker-backend-1       |     html = func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
frappe_docker-backend-1       |     self.init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
frappe_docker-backend-1       |     super().init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
frappe_docker-backend-1       |     self.context.update(get_website_settings())
frappe_docker-backend-1       |                         ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 174, in get_website_settings
frappe_docker-backend-1       |     settings: "WebsiteSettings" = frappe.get_cached_doc("Website Settings")
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1214, in get_cached_doc
frappe_docker-backend-1       |     doc = get_doc(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1340, in get_doc
frappe_docker-backend-1       |     doc = frappe.model.document.get_doc(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
frappe_docker-backend-1       |     controller = get_controller(doctype)
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
frappe_docker-backend-1       |     site_controllers[doctype] = import_controller(doctype)
frappe_docker-backend-1       |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 95, in import_controller
frappe_docker-backend-1       |     module = load_doctype_module(doctype, module_name)
frappe_docker-backend-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 248, in load_doctype_module
frappe_docker-backend-1       |     app = get_module_app(module)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 273, in get_module_app
frappe_docker-backend-1       |     frappe.throw(_("Module {} not found").format(module), exc=frappe.DoesNotExistError)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 652, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 617, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.DoesNotExistError: Module Core not found
frappe_docker-backend-1       |
frappe_docker-frontend-1      | 192.168.1.247 - - [06/Sep/2024:19:43:24 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
frappe_docker-backend-1       | [2024-09-06 19:43:25 +0000] [7] [ERROR] Error handling request /favicon.ico
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 99, in application
frappe_docker-backend-1       |     init_request(request)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 195, in init_request
frappe_docker-backend-1       |     frappe.local.http_request = HTTPRequest()
frappe_docker-backend-1       |                                 ^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 43, in __init__
frappe_docker-backend-1       |     self.set_session()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 77, in set_session
frappe_docker-backend-1       |     frappe.local.login_manager = LoginManager()
frappe_docker-backend-1       |                                  ^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 119, in __init__
frappe_docker-backend-1       |     self.make_session(resume=True)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/auth.py", line 205, in make_session
frappe_docker-backend-1       |     frappe.local.session_obj = Session(
frappe_docker-backend-1       |                                ^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 214, in __init__
frappe_docker-backend-1       |     self.resume()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 290, in resume
frappe_docker-backend-1       |     self.validate_user()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 223, in validate_user
frappe_docker-backend-1       |     frappe.throw(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 652, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 617, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.ValidationError: User Guest is disabled. Please contact your System Manager.
frappe_docker-backend-1       |
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       |
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 19, in get_response
frappe_docker-backend-1       |     endpoint, renderer_instance = path_resolver.resolve()
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 38, in resolve
frappe_docker-backend-1       |     resolve_redirect(self.path, request.query_string)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 118, in resolve_redirect
frappe_docker-backend-1       |     redirects += frappe.get_all(
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2064, in get_all
frappe_docker-backend-1       |     return get_list(doctype, *args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 2039, in get_list
frappe_docker-backend-1       |     return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 185, in execute
frappe_docker-backend-1       |     self.columns = self.get_table_columns()
frappe_docker-backend-1       |                    ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 546, in get_table_columns
frappe_docker-backend-1       |     return get_table_columns(self.doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 73, in get_table_columns
frappe_docker-backend-1       |     return frappe.db.get_table_columns(doctype)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 1190, in get_table_columns
frappe_docker-backend-1       |     raise self.TableMissingError("DocType", doctype)
frappe_docker-backend-1       | pymysql.err.ProgrammingError: ('DocType', 'Website Route Redirect')
frappe_docker-backend-1       |
frappe_docker-backend-1       | During handling of the above exception, another exception occurred:
frappe_docker-backend-1       |
frappe_docker-backend-1       | Traceback (most recent call last):
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 282, in handle
frappe_docker-backend-1       |     keepalive = self.handle_request(req, conn)
frappe_docker-backend-1       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
frappe_docker-backend-1       |     respiter = self.wsgi(environ, resp.start_response)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 79, in application
frappe_docker-backend-1       |     app(environ, start_response),
frappe_docker-backend-1       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/werkzeug/wrappers/request.py", line 190, in application
frappe_docker-backend-1       |     resp = f(*args[:-2] + (request,))
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 132, in application
frappe_docker-backend-1       |     response = handle_exception(e)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 395, in handle_exception
frappe_docker-backend-1       |     response = get_response("message", http_status_code=http_status_code)
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 28, in get_response
frappe_docker-backend-1       |     response = ErrorPage(exception=e).render()
frappe_docker-backend-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
frappe_docker-backend-1       |     html = self.get_html()
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
frappe_docker-backend-1       |     html = func(*args, **kwargs)
frappe_docker-backend-1       |            ^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 92, in get_html
frappe_docker-backend-1       |     self.init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 14, in init_context
frappe_docker-backend-1       |     super().init_context()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/base_template_page.py", line 15, in init_context
frappe_docker-backend-1       |     self.context.update(get_website_settings())
frappe_docker-backend-1       |                         ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_settings/website_settings.py", line 174, in get_website_settings
frappe_docker-backend-1       |     settings: "WebsiteSettings" = frappe.get_cached_doc("Website Settings")
frappe_docker-backend-1       |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1214, in get_cached_doc
frappe_docker-backend-1       |     doc = get_doc(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1340, in get_doc
frappe_docker-backend-1       |     doc = frappe.model.document.get_doc(*args, **kwargs)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
frappe_docker-backend-1       |     controller = get_controller(doctype)
frappe_docker-backend-1       |                  ^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
frappe_docker-backend-1       |     site_controllers[doctype] = import_controller(doctype)
frappe_docker-backend-1       |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 95, in import_controller
frappe_docker-backend-1       |     module = load_doctype_module(doctype, module_name)
frappe_docker-backend-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 248, in load_doctype_module
frappe_docker-backend-1       |     app = get_module_app(module)
frappe_docker-backend-1       |           ^^^^^^^^^^^^^^^^^^^^^^
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 273, in get_module_app
frappe_docker-backend-1       |     frappe.throw(_("Module {} not found").format(module), exc=frappe.DoesNotExistError)
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 652, in throw
frappe_docker-backend-1       |     msgprint(
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 617, in msgprint
frappe_docker-backend-1       |     _raise_exception()
frappe_docker-backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 568, in _raise_exception
frappe_docker-backend-1       |     raise exc
frappe_docker-backend-1       | frappe.exceptions.DoesNotExistError: Module Core not found
frappe_docker-backend-1       |
frappe_docker-frontend-1      | 192.168.1.247 - - [06/Sep/2024:19:43:25 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://192.168.1.191:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"`

### Expected result
Front end web page to Load

**Comment by oldwang12** [comment]
what's your docker version?

**Comment by adeebabdulsalam** [comment]
got the same error, from the same steps. did you update docker version ? which version ?

**Comment by EasternIndustries-IT** [comment]
sorry for the late response. 
Even after a fresh install it seems some files doesn't get complete cleaned out even with the purge command. 
The docker version is Docker version 27.3.1, build ce12230
but doing an uninstall and reinstall seems to be the only way i was able to get rid of this error.
