### ISSUE TITLE
unable to access http://development.localhost:8000 in dev development

### ISSUE THREAD

**Issue by sourabhmandal** [frappe/frappe_docker#1469]
## Description of the issue
Trying to access [http://development.localhost:8000](http://development.localhost:8000) from browser loads infinitely when running dev-container

## Context information (for bug reports)
I followed the steps mentioned in [Development container](https://github.com/frappe/frappe_docker/blob/main/docs/development.md). However after running the bench start command I am not able to access the website in host machine. However if I do a `curl http://development.localhost:8000` **inside container itself** I am getting a response with HTML page.

**PS: I am using MacOS as host machine**

## Steps to reproduce the issue

1. Take a macOS laptop
2. `cp -R devcontainer-example .devcontainer`
3. `cp -R development/vscode-example development/.vscode`
4. open `.devcontainer/docker-compose.yml` and comment out `MariaDB and its volume` and uncomment `PostgresDB and its volume`
5. Run dev container in VS code with appropriate extensions as mentioned
6. Inside container run `bench init --skip-redis-config-generation frappe-bench && cd frappe-bench`
7. setup host
```
bench set-config -g db_host mariadb
bench set-config -g redis_cache redis://redis-cache:6379
bench set-config -g redis_queue redis://redis-queue:6379
bench set-config -g redis_socketio redis://redis-queue:6379
```
8. Create new site `bench new-site --db-type postgres --db-host postgresql development.localhost`
9. set root password
```
bench config set-common-config -c root_login postgres
bench config set-common-config -c root_password '"123"'
```
10. set dev mode in site
```
bench --site development.localhost set-config developer_mode 1
bench --site development.localhost clear-cache
```
11. `bench start`
12. go to [http://development.localhost:8000](http://development.localhost:8000) in host machine

### Observed result
- No HTTP call is received from HOST machine by the app inside docker container.

### Expected result
- http://development.localhost:8000 serving frappe login page

**Comment by revant** [comment]
I'll not be able to help anyone using Mac or windows.
