### ISSUE TITLE
How to Install a Specific Version of ERPNext and Frappe Using a Custom Docker Image?

### ISSUE THREAD

**Issue by edardev** [frappe/frappe_docker#1472]
Hi everyone,

I'm trying to install specific versions of ERPNext and Frappe (ERPNext v15.34.1 and Frappe v15.40.3) using a custom Docker image. I need to specify these versions during the Docker build process due to compatibility issues with the latest releases (ERPNext v15.36.1 and Frappe Framework v15.41.0).

The issue I'm facing with the latest versions is that custom Print Formats are no longer working correctly, and I’m unable to print them. However, these functionalities were working fine in the previous versions mentioned above.

Could someone please guide me on how to modify the Dockerfile or any other configuration to install the exact versions I need? Any advice or examples would be greatly appreciated!

Thank you in advance!

**Comment by revant** [comment]
Mention git tags instead is git branches in apps.json

https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md#load-custom-apps-through-json
