### ISSUE TITLE
How to Add custom HRMS app or Other apps on synology NAS using docker

### ISSUE THREAD

**Issue by KBP-Civil** [frappe/frappe_docker#1476]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I refer [https://mariushosting.com/how-to-install-erpnext-on-your-synology-nas/](url) documentation to install ERPNext on NAS and it works fine. However, I'd like to use HRMS or Non-Profit apps on ERPNext. how I can add these apps?

**Additional context**

**Comment by revant** [comment]
https://discuss.frappe.io/t/erpnext-installation-issues-docker/133109/6

Build your custom image.
