### ISSUE TITLE
manifest unknown error for Version-12

### ISSUE THREAD

**Issue by jigneshpshah** [frappe/frappe_docker#148]
Hi ,

Kudos to the great effort for official docker.  

I tried deployment for production 

Added DNS Record

Below is my .env file

```
VERSION=version-12
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=mysql
SITES=abc.domain.in
LETSENCRYPT_EMAIL=letsencryptemail@gmail.com
```

on executing the command
`docker-compose     --project-name erpnextgc     -f installation/docker-compose-common.yml     -f installation/docker-compose-erpnext.yml     -f installation/docker-compose-networks.yml     --project-directory installation up -d`

faced below error

```
Pulling erpnext-nginx (frappe/erpnext-nginx:version-12)...
ERROR: manifest for frappe/erpnext-nginx:version-12 not found: manifest unknown: manifest unknown
```

**Comment by revant** [comment]
For now can you try with VERSION=edge

Other images will be built. I'll update here and close the issue once all images are built successfully

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/104#issuecomment-599642093

**Comment by revant** [comment]
@chabad360 can you fix it?

https://hub.docker.com/r/frappe/erpnext-nginx/tags tag version-12 is also missing

**Comment by revant** [comment]
third attempt here 
https://github.com/frappe/frappe_docker/pull/155

I don't trust travis.py and install_app

**Comment by revant** [comment]
finally tags are pushed.

https://hub.docker.com/r/frappe/erpnext-nginx/tags

solved the tag issue. 

Let's see what all crop up because of wrapper scripts in future
