### ISSUE TITLE
Speficic commits for custom-apps

### ISSUE THREAD

**Issue by marcramser** [frappe/frappe_docker#1482]
Hi

I found your documentation on custom apps (https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) to be very helpful.

From what I understand, specifying the "url" and "branch" during the Docker image build pulls the latest version of the specified branch. However, I was wondering if there is a way to specify a specific commit for the build, instead of always pulling the latest version.

Is there an undocumented method for this, or any other approach to prevent automatically pulling the latest changes whenever a Docker image is built?

For example, something like adding a "commit" field in the configuration:

export APPS_JSON='[
  {
    "url": "https://github.com/frappe/erpnext",
    "branch": "version-15",
    "commit": "df3267ad3cf5bf4f2ca62588f0656db57c45ea3b"
  }
]'

Or is there another way to have a more "strict" versioning that just branches?

Thank you for your time and assistance!

**Comment by revant** [comment]
You can use branch or tag.

In case you need specific commit, you'll need to fork like this https://github.com/frappe/wiki/issues/279#issue-2558454710
