### ISSUE TITLE
Error happened when Connected with mariadb

### ISSUE THREAD

**Issue by TsadikuKibru21** [frappe/frappe_docker#1506]
^^^^^^^^^^^^^^^^^^^^
backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
backend-1       |     conn = self._get_connection()
backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^
backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
backend-1       |     return self.create_connection()
backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^
backend-1       |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
backend-1       |     return pymysql.connect(**self.get_connection_settings())
backend-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 361, in __init__
backend-1       |     self.connect()
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 669, in connect
backend-1       |     self._request_authentication()
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 957, in _request_authentication
backend-1       |     auth_packet = self._read_packet()
backend-1       |                   ^^^^^^^^^^^^^^^^^^^
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
backend-1       |     packet.raise_for_error()
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
backend-1       |     err.raise_mysql_exception(self._data)
backend-1       |   File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
backend-1       |     raise errorclass(errno, errval)
backend-1       | pymysql.err.OperationalError: (1045, "Access denied for user '_5e5899d8398b5f7b'@'172.18.0.7' (using password: YES)")

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/main/docs/troubleshoot.md#fixing-mariadb-issues-after-rebuilding-the-container
