### ISSUE TITLE
App's assets not found : net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by bilalbayasut** [frappe/frappe_docker#1507]
Im Installing helpdesk (or any other app) from main branch into my self-hosted VM in GCP of my production frappe installation via frappe_docker (following single server example). but when I open my frontpage of the helpesk I got asset 404 not found
```
GET https://myapp.com/assets/helpdesk/desk/assets/index-afe95341.js net::ERR_ABORTED 404 (Not Found)
helpdesk:203 
       GET https://myapp.com/assets/helpdesk/desk/assets/index-fc83c5d5.css net::ERR_ABORTED 404 (Not Found)
helpdesk:204       
       GET https://myapp.com/assets/helpdesk/desk/registerSW.js net::ERR_ABORTED 404 (Not Found)
manifest.webmanifest:1 
       GET https://myapp.com/assets/helpdesk/desk/manifest.webmanifest 404 (Not Found)
```
The static files are built in the app public folder, but not copied to `sites/assets` , perhaps this is why, but not sure why that happends? 

I couldn't use this frappe_docker to install any apps

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-install-official-or-custom-apps
