### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by hsrai** [frappe/frappe_docker#1510]
From [List of containers](https://github.com/frappe/frappe_docker/blob/main/docs/list-of-containers.md) it says:

> There are 3 images that you can find in /images directory:
>
> bench. It is used for development. [Learn more how to start development](https://github.com/frappe/frappe_docker/blob/main/development/README.md).

However link https://github.com/frappe/frappe_docker/blob/main/development/README.md does not exist.

**Comment by revant** [comment]
Send PR, I'll merge. Everything in this repo is contributed by community.
