### ISSUE TITLE
Can not connect to MariaDB database

### ISSUE THREAD

**Issue by ilcxyz** [frappe/frappe_docker#1535]
When I tried to connect to MariaDB database with phpAdmin, I found that I could not log in successfully with the username root and password admin. What went wrong? Please help me check it. Thank you.

**Comment by revant** [comment]
Check this if it works for you

https://discuss.frappe.io/t/connecting-mariadb-docker-instance-from-mysql-workbench/71541

**Comment by ilcxyz** [comment]
> Check this if it works for you
> 
> https://discuss.frappe.io/t/connecting-mariadb-docker-instance-from-mysql-workbench/71541

Thank you so much, according to your guidance, it is already possible to connect.
