### ISSUE TITLE
Help with Frappe/ERPNext access

### ISSUE THREAD

**Issue by svrfremont** [frappe/frappe_docker#167]
Hi 

Previously I used to be able to access ERPNext by accessing the login page at locahost:8000. Now there is an NGINX running. I get an internal server error when I try the same. I know this is a simple question of forming my request correctly. I have published the port 80 from the container (I think). 

d73d8d108b98        frappe/erpnext-nginx:edge     "/docker-entrypoint.…"   2 hours ago         Up 2 hours          0.0.0.0:80->80/tcp   erp_erpnext-nginx_1. 

How do I access the Login page of Frappe/ERPNext now? 

Thanks
Ramesh

**Comment by revant** [comment]
what are the logs of other containers? `erpnext-python` , `frappe-woker`(s) `erpnext-nginx`

**Comment by svrfremont** [comment]
docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                NAMES
d73d8d108b98        frappe/erpnext-nginx:edge     "/docker-entrypoint.…"   5 hours ago         Up 5 hours          0.0.0.0:80->80/tcp   erp_erpnext-nginx_1
324e799f5ea4        frappe/frappe-socketio:edge   "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_frappe-socketio_1
68975ea6a4c3        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_frappe-schedule_1
32842e628f5f        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_frappe-worker-short_1
76ea2733ef83        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_frappe-worker-long_1
3271d30c4afe        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_frappe-worker-default_1
7c62449264a4        mariadb:10.3                  "docker-entrypoint.s…"   5 hours ago         Up 5 hours          3306/tcp             erp_mariadb_1
d6094a58aeae        redis:latest                  "docker-entrypoint.s…"   5 hours ago         Up 5 hours          6379/tcp             erp_redis-queue_1
54564c755970        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   5 hours ago         Up 5 hours                               erp_erpnext-python_1
ccdf8ddcce16        redis:latest                  "docker-entrypoint.s…"   5 hours ago         Up 5 hours          6379/tcp             erp_redis-cache_1
c745b2233448        redis:latest                  "docker-entrypoint.s…"   5 hours ago         Up 5 hours          6379/tcp             erp_redis-socketio_1
========================================================================
docker logs erpnext-python:
========================== 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
KeyError: 'conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 74, in __getattr__
    raise AttributeError(name)
AttributeError: conf

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 280, in handle
    keepalive = self.handle_request(req, conn)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 329, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 231, in application
    return ClosingIterator(app(environ, start_response), self.cleanup)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/wrappers/base_request.py", line 237, in application
    resp = f(*args[:-2] + (request,))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 96, in application
    frappe.monitor.stop(response)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/monitor.py", line 26, in stop
    if frappe.conf.monitor and hasattr(frappe.local, "monitor"):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/werkzeug/local.py", line 311, in _get_current_object
    raise RuntimeError("no object bound to %s" % self.__name__)
RuntimeError: no object bound to conf
===========================================================================
docker logs erp_erpnext-nginx_1:
==========================
Waiting for frappe-python to be available on erpnext-python port 8000
Frappe-python available on erpnext-python port 8000
Waiting for frappe-socketio to be available on erpnext-python port 8000
Frappe-socketio available on erpnext-python port 8000
10.200.10.1 - - [23/Mar/2020:19:12:36 +0000] "GET /frappe-sever HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.1 - - [23/Mar/2020:19:12:36 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://10.200.10.6/frappe-sever" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.6 - - [23/Mar/2020:19:25:40 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.6 - - [23/Mar/2020:19:25:40 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://10.200.10.6/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
172.19.0.1 - - [23/Mar/2020:19:26:32 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
172.19.0.1 - - [23/Mar/2020:19:26:32 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
172.19.0.1 - - [23/Mar/2020:19:28:19 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
172.19.0.1 - - [23/Mar/2020:19:28:19 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://0.0.0.0/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.1 - - [23/Mar/2020:19:59:35 +0000] "GET / HTTP/1.1" 500 141 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.1 - - [23/Mar/2020:19:59:35 +0000] "GET /favicon.ico HTTP/1.1" 500 141 "http://10.200.10.6/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "-"
10.200.10.6 - - [23/Mar/2020:20:33:20 +0000] "GET /ramesh.local.vikraya.com HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
10.200.10.6 - - [23/Mar/2020:20:33:50 +0000] "GET /frappe-server HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
10.200.10.6 - - [23/Mar/2020:20:35:19 +0000] "GET /frappe-server HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
10.200.10.6 - - [23/Mar/2020:20:35:48 +0000] "GET /ramesh.local.vikraya.com HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
10.200.10.6 - - [23/Mar/2020:20:38:04 +0000] "GET /ramesh.local.vikraya.com:8000 HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
10.200.10.6 - - [23/Mar/2020:20:38:15 +0000] "GET / HTTP/1.1" 500 141 "-" "curl/7.65.3" "-"
=============================================================
Given all this. I am not looking to build a dev. image. I need to just see this working locally and I can then proceed on my own. I followed the instructions on the README. The README (in my opinion) is not clear in terms of the steps needed to get this working.  I am very familiar with docker, docker-compose and containers. Please suggest steps to just get a production image launch and access ERPNext app. Also I am not familar with development env. with VSCode. Getting a dev image is not important as I am not going to test new apps. 

Thanks a bunch for your help.

**Comment by svrfremont** [comment]
Also I had this yesterday. 
Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Updating customizations for Address
*** Scheduler is disabled ***

I have seen this before and I just needed to issue a bench start in the frappe container. 
I did look through the commands directory in frappe-bench. I then found "schedule" command. And I issued:
docker exec -it                                                                                             \
        "$project_name"_erpnext-python_1 docker-entrypoint.sh schedule

Let me know if this is all wrong and I am willing to do what is right to proceed further.

Thanks
Ramesh

**Comment by svrfremont** [comment]
Also here is the env. that is setup:

VERSION=edge
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=123
SITES=ramesh.local.vikraya.com
LETSENCRYPT_EMAIL=
===========================
And the commands issued to get to this point:
1. docker-compose 					\
    	    --project-name $project_name 		\
   	    -f installation/docker-compose-common.yml 	\
    	    -f installation/docker-compose-erpnext.yml 	\
           --project-directory installation up -d

2. docker exec -it 							\
        -e "SITE_NAME=$sites" 						\
	-e "DB_ROOT_USER=root" 						\
	-e "MYSQL_ROOT_PASSWORD=$sql_root_passwd" 			\
	-e "MARIADB_HOST=mariadb"					\
	-e "ADMIN_PASSWORD=admin" 					\
        -e "INSTALL_APPS=erpnext" 					\
        "$project_name"_erpnext-python_1 docker-entrypoint.sh new

3. docker exec -it 							\
        "$project_name"_erpnext-python_1 docker-entrypoint.sh schedule

**Comment by revant** [comment]
ramesh.local.vikraya.com

This won't work locally
You need any URL ending with localhost to try things locally.

Example url `icantformatmarkdown.localhost`

**Comment by revant** [comment]
> Also here is the env. that is setup:
> 
> ```
> VERSION=edge
> MARIADB_HOST=mariadb
> MYSQL_ROOT_PASSWORD=123
> SITES=ramesh.local.vikraya.com
> LETSENCRYPT_EMAIL=
> ```
> 
> And the commands issued to get to this point:
> 
> ```shell
> $ docker-compose \
>     	--project-name $project_name \
>    	    -f installation/docker-compose-common.yml \
>     	-f installation/docker-compose-erpnext.yml \
>         --project-directory installation up -d
> 
> $ docker exec -it \
>     -e "SITE_NAME=$sites" \
> 	-e "DB_ROOT_USER=root" \
> 	-e "MYSQL_ROOT_PASSWORD=$sql_root_passwd" \
> 	-e "MARIADB_HOST=mariadb" \
> 	-e "ADMIN_PASSWORD=admin" \
>     -e "INSTALL_APPS=erpnext" \
>     "$project_name"_erpnext-python_1 docker-entrypoint.sh new
> 
> $ docker exec -it 							\
>         "$project_name"_erpnext-python_1 docker-entrypoint.sh schedule 
> ```

What's the SITE_NAME you set in environment variable? If nothing was set then it creates default site1.localhost try visiting http://site1.localhost

There's a separate container for schedule. If it stops start it. No need to run schedule in python container

**Comment by svrfremont** [comment]
Thanks Revant. The schedule should have been executed in frappe-schedule container. Also I'll try fixing the SITE_NAME variable.

Ramesh

**Comment by svrfremont** [comment]
Also another observation that I have:
The networks is required to start if the environment requires the apps to be launched  *non-local* which means that the apps are available outside of localhost. Now I see that there is a networks block that is appended to the docker-compose file. The script that includes the "docker-compose-networks.yml" file is good.    But ...

None of the containers are attached to that network. It is a network that is started but a "- networks" statement is required ***within the service block*** in the docker-compose to attach to that network. No? 

The way that I look at it, the nginx proxy at least, needs to attach to that network called "webproxy". I don't know if other containers need to connect and I am assuming NO. Let  me know if this is not right. And I am sure you have seen that "depends on" and "links" clauses are going to be deprecated. These are recommended to be replaced by the "networks" clause in docker-compose. 
I am trying out a multi-cloud version of Frappe/ERPNext, across on premises and AWS as a first cut. 

Thanks
Ramesh

**Comment by revant** [comment]
You can modify and extend docker-compose as you wish.

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
the documentation here doesn't specify to add network to any container, it just requires certain ENV variables to be available in the container 

erp.maych.in is using the docker-compose production install

nandadeep.mntechique.com is on docker swarm https://github.com/frappe/frappe_docker/wiki/Docker-Swarm

**Comment by svrfremont** [comment]
Well it also says in "Starting your Web containers section": 

docker run -d -e VIRTUAL_HOST=your.domain.com \
              --network=webproxy \      <=======================
              --name my_app \
              httpd:alpine

This attaches the container to the "webproxy" network. Not the default that is created. Let me know if I still need to look at it more carefully.

**Comment by svrfremont** [comment]
With docker-compose we need to have a "networks" clause inside the service block to do that.

**Comment by revant** [comment]
try it out. If it works?

**Comment by svrfremont** [comment]
Yes. But I have a small home network. I can start this on any machine and access from any machine. I am going to give this a shot. But with the other changes that you have suggested. First local, then take it outside the machine etc. Anyways you'll know if there is further trouble. I'll also make sure to report the result here.

**Comment by revant** [comment]
I'll close this issue. 

If you find things out add to the troubleshoot section under wiki
https://github.com/frappe/frappe_docker/wiki/Troubleshoot
You can open more specific issues or reopen this one when you need.

**Comment by svrfremont** [comment]
So the localhost test was successful. And now how do I build a production version just build v12? Also how will access it from any machine?

Sent from Yahoo Mail for iPhone


On Tuesday, March 24, 2020, 7:25 AM, Revant Nandgaonkar <notifications@github.com> wrote:




I'll close this issue.

If you find things out add to the troubleshoot section under wiki
https://github.com/frappe/frappe_docker/wiki/Troubleshoot
You can open more specific issues or reopen this one when you need.
