### ISSUE TITLE
Mysql connect I get Access denied after restore sql.gz

### ISSUE THREAD

**Issue by AkiM1ta** [frappe/frappe_docker#171]
I run backup,and restore the sql.gz to a new mariadb,then I start a new "docker-compose  --project-name <same> -f .... up -d",
with my old installation file and db volume.
Every thing is Ok,while I got "pymysql.err.OperationalError: (1045, "Access denied for user '_6caefa6809cd585f'@'172.21.0.4' (using password: YES)")"
I can connect the db using the site_config.json.
what happens?

**Comment by ddavidebor** [comment]
Hello, try following the procedure here https://github.com/frappe/frappe_docker/blob/develop/development/README.md#fixing-mariadb-issues-after-rebuilding-the-container

**Comment by AkiM1ta** [comment]
Thanks,I found that I make wrong when set user database. 
GRANT ALL PRIVILEGES ON `db_name`.* TO 'db_name'@'%'; FLUSH PRIVILEGES;
