### ISSUE TITLE
Production image: Installed and up but not reachable 

### ISSUE THREAD

**Issue by svrfremont** [frappe/frappe_docker#172]
I am running my test on a home network. All containers have been installed and up and running including the nginx-proxy-companion.  I am testing a v12 image (which I am assuming is production but I may be wrong).  
-------------------------------------------------------------------------------------------------------------------
The output of docker ps:    docker ps -a
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                              NAMES
6ec1f786d99d        frappe/erpnext-nginx:version-12          "/docker-entrypoint.…"   20 minutes ago      Up 19 minutes       80/tcp                                             erp_erpnext-nginx_1
0433bfab128a        frappe/frappe-socketio:version-12        "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_frappe-socketio_1
ec40cc1687a6        frappe/erpnext-worker:version-12         "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_frappe-worker-long_1
90d30e1e4e59        frappe/erpnext-worker:version-12         "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_frappe-worker-default_1
a4da2e780c35        frappe/erpnext-worker:version-12         "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_frappe-worker-short_1
dbd98be39f74        frappe/erpnext-worker:version-12         "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_frappe-schedule_1
5d0f8b217613        redis:latest                             "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       6379/tcp                                           erp_redis-socketio_1
089204144b14        frappe/erpnext-worker:version-12         "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes                                                          erp_erpnext-python_1
6c29fd65e14d        redis:latest                             "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       6379/tcp                                           erp_redis-queue_1
99a7dd982f39        redis:latest                             "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       6379/tcp                                           erp_redis-cache_1
f38056da2fc8        mariadb:10.3                             "docker-entrypoint.s…"   20 minutes ago      Up 20 minutes       3306/tcp                                           erp_mariadb_1
b49108a7c5e0        jwilder/docker-gen                       "/usr/local/bin/dock…"   22 minutes ago      Up 22 minutes                                                          nginx-gen
7ef18174e1c3        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/entr…"   22 minutes ago      Up 22 minutes                                                          nginx-letsencrypt
5f4263f47dc0        nginx                                    "nginx -g 'daemon of…"   22 minutes ago      Up 22 minutes       10.200.10.6:80->80/tcp, 10.200.10.6:443->443/tcp   nginx-web
-------------------------------------------------------------------------------------------------------------------
All containers are attached to the webproxy network. (Because the default network has been specified as external and created by the nginx-proxy-companion. There is an option to specify the external facing IP address which I have given as 10.200.10.6 and the nginx container reflects that.)
--------------------------------------------------------------------------------------------------------------------
docker network inspect webproxy: (To make sure all app. containers are attached to this network.) 
 docker inspect webproxy
[
    {
        "Name": "webproxy",
        "Id": "e1232ebfe479b6b40b6036133293643d0e42c810ccdfa8a0952e2dee1f834c45",
        "Created": "2020-03-25T14:51:29.147452015-04:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "0433bfab128aeffb5a1bccb5b98436706c4516c4aaee843e620d08b67f8942e8": {
                "Name": "erp_frappe-socketio_1",
                "EndpointID": "2150ed1874ec3a6bf8025a64124293a5c1f967aded300684a2d29c0e40c0a4ad",
                "MacAddress": "02:42:ac:13:00:0a",
                "IPv4Address": "172.19.0.10/16",
                "IPv6Address": ""
            },
            "089204144b14ae9f65a3667c760afe26a1f59a327768dba9eac533bb7cf1c1f7": {
                "Name": "erp_erpnext-python_1",
                "EndpointID": "c39131d83c71b9fd077f4109b881ec89436c1995aa945c8d56c1dd87753f76c3",
                "MacAddress": "02:42:ac:13:00:06",
                "IPv4Address": "172.19.0.6/16",
                "IPv6Address": ""
            },
            "5d0f8b217613a3797fc1a0df0b13e88aaa8718c8791bd9840fdc27202d68ed6b": {
                "Name": "erp_redis-socketio_1",
                "EndpointID": "2dd7778790e576b26766f83ef15275c3bcbe1b52536f4363481ec6d4cb04b8ec",
                "MacAddress": "02:42:ac:13:00:08",
                "IPv4Address": "172.19.0.8/16",
                "IPv6Address": ""
            },
            "5f4263f47dc020ae2d5053e0d0d51e550fe6009ef63792279a58e4d5855065ef": {
                "Name": "nginx-web",
                "EndpointID": "87bd0db223dad63f56e1346beeb3ed808a8c70a863cd1db0dc106fb53de7a17d",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            },
            "6c29fd65e14df4b02fcff90983714012b75d5a67c4c08ee0d6ecacb6919b70b8": {
                "Name": "erp_redis-queue_1",
                "EndpointID": "e00e675cdd0d21ca4ba8f50948bebb2d4cb3b5c3a0c881e500e23e16c1a6d147",
                "MacAddress": "02:42:ac:13:00:05",
                "IPv4Address": "172.19.0.5/16",
                "IPv6Address": ""
            },
            "6ec1f786d99d8e8ad06e8ca3583351bf94ef49d38440362584d14d1e5d18f788": {
                "Name": "erp_erpnext-nginx_1",
                "EndpointID": "cc0773a7ceed3c173161a854ef434d5d0326c57fcb178d19359defdce1996816",
                "MacAddress": "02:42:ac:13:00:0f",
                "IPv4Address": "172.19.0.15/16",
                "IPv6Address": ""
            },
            "7ef18174e1c3adfd72480009158ab00fbd0afad402b5ee7daa86d12cc92e3c6f": {
                "Name": "nginx-letsencrypt",
                "EndpointID": "d46efc5713dd9ca3b79a3f665aa04358af7cf3f3fcc48e52d7ce2f0a97cb6b6a",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "90d30e1e4e59e92ed8595cd4d31aa1999775d93cd3f7258e9abab462abe79929": {
                "Name": "erp_frappe-worker-default_1",
                "EndpointID": "7730e81b952b64491d15d311aac3468034488d9b939cc18adc82b3ecd337d000",
                "MacAddress": "02:42:ac:13:00:0d",
                "IPv4Address": "172.19.0.13/16",
                "IPv6Address": ""
            },
            "99a7dd982f3920f87586b274373d5e3cb6b6e27b240d45f519ce4227d762005d": {
                "Name": "erp_redis-cache_1",
                "EndpointID": "752ae5f254f91464f1609e3c52552120e594b804da8a5fcc3e9602bbea55f6e7",
                "MacAddress": "02:42:ac:13:00:07",
                "IPv4Address": "172.19.0.7/16",
                "IPv6Address": ""
            },
            "a4da2e780c3560c58753a7bf9747bb7c2bd0148031c9c74065a1487f6b4007bf": {
                "Name": "erp_frappe-worker-short_1",
                "EndpointID": "b556ba6936f2262d5166cc4948002d4a9cbca4eb0a5c7446126e7e74c6aae095",
                "MacAddress": "02:42:ac:13:00:0c",
                "IPv4Address": "172.19.0.12/16",
                "IPv6Address": ""
            },
            "b49108a7c5e0471b8a1ef4ec8cf77604b4a786a3322a2ed1317eb58528f4a98d": {
                "Name": "nginx-gen",
                "EndpointID": "4606ae968830561ac6fc613655de4feaa61144b9f92f946fe604e6633a792b68",
                "MacAddress": "02:42:ac:13:00:04",
                "IPv4Address": "172.19.0.4/16",
                "IPv6Address": ""
            },
            "dbd98be39f746d60eb16e820cd7ff6fd39dd625d4f4f4c1c9e6e4774de986566": {
                "Name": "erp_frappe-schedule_1",
                "EndpointID": "9d5d2b40f5c746e61cbcac2cb725ad476d90a4cdad266720ac10dfb5d6369625",
                "MacAddress": "02:42:ac:13:00:0b",
                "IPv4Address": "172.19.0.11/16",
                "IPv6Address": ""
            },
            "ec40cc1687a668abc98192605e974018ca54ea9f3fc4e7625b4a65194d10c12c": {
                "Name": "erp_frappe-worker-long_1",
                "EndpointID": "89c684ffef4f8ef70a8746495b9191d2587f80c5d0dbaa0ddef871bab4c87dd3",
                "MacAddress": "02:42:ac:13:00:0e",
                "IPv4Address": "172.19.0.14/16",
                "IPv6Address": ""
            },
            "f38056da2fc8e8ea5773cecbfa248c24346a9792318fbe1619243226906bf020": {
                "Name": "erp_mariadb_1",
                "EndpointID": "58066c3cc1069b1a85fb9af32e8dde293240e9c361ac2fbc9980c78a6e8b7206",
                "MacAddress": "02:42:ac:13:00:09",
                "IPv4Address": "172.19.0.9/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "encrypted": "true"
        },
        "Labels": {}
    }
]
------------------------------------------------------------------------------------------------------
At this point containers are running but when I access:
https://10.200.10.6:443

I get a "503 ServiceTemporarily Unavailable"  nginx 1.17.9. 
--------------------------------------------------------------------------------------------------------
frappe_docker/installation$ ls
docker-compose-common.yml  docker-compose-erpnext.yml  docker-compose-networks.yml  frappe-mariadb.cnf
docker-compose-custom.yml  docker-compose-frappe.yml   env-example                  sites
ramesh@ramesh-lenovo:/opt/ramesh/mvp/frappe_docker/installation$ ls sites/
apps.txt  app_versions.json  assets  common_site_config.json  ramesh.test
--------------------------------------------------------------------------------------------------------------
docker logs nginx-web
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:07:36 +0000] "GET / HTTP/1.1" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:07:36 +0000] "GET /favicon.ico HTTP/1.1" 503 599 "http://10.200.10.6/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:09:23 +0000] "GET /ramesh.test HTTP/2.0" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:09:23 +0000] "GET /favicon.ico HTTP/2.0" 503 599 "https://10.200.10.6/ramesh.test" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:14:42 +0000] "GET / HTTP/1.1" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:14:42 +0000] "GET /favicon.ico HTTP/1.1" 503 599 "http://10.200.10.6/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:32:01 +0000] "GET / HTTP/2.0" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:32:58 +0000] "GET / HTTP/2.0" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:32:58 +0000] "GET /favicon.ico HTTP/2.0" 503 599 "https://10.200.10.6/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:35:18 +0000] "GET /ramesh.test HTTP/1.1" 503 599 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
10.200.10.6 10.200.10.1 - - [25/Mar/2020:19:35:18 +0000] "GET /favicon.ico HTTP/1.1" 503 599 "http://10.200.10.6/ramesh.test" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36"
-----------------------------------------------------------------------------------------------------------
 docker logs erp_erpnext-nginx_1
Waiting for frappe-python to be available on erpnext-python port 8000
Waiting for frappe-python to be available on erpnext-python port 8000
Frappe-python available on erpnext-python port 8000
Waiting for frappe-socketio to be available on erpnext-python port 8000
Frappe-socketio available on erpnext-python port 8000
-----------------------------------------------------------------------------------------------------------
docker logs erp_frappe-socketio_1
listening on *: 9000
---------------------------------------------------------------------------------------------------------
docker logs erp_frappe-worker-long_1
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 4 to connect to mariadb:3306
Attempt 5 to connect to mariadb:3306
Attempt 6 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
18:54:03 RQ worker 'rq:worker:4788e5d454ee403cbd5071e54b07c059.ec40cc1687a6.11.long' started, version 0.12.0
18:54:03 *** Listening on long...
18:54:03 Cleaning registries for queue: long
--------------------------------------------------------------------
I'd be happy  to provide more logs if necessary.

**Comment by revant** [comment]
Learn Github markdown. It helps in formatting all this dump in readable chunks.

ramesh.test won't work on localhost

You should have ramesh.localhost site to be created

Reason: 

> Why it is so? Both nginx and python serve whatever is caught in $http_host. That is, whatever url typed in browser to request website. If it's not found in sites directory nginx will 404 and python will 500.

https://github.com/frappe/frappe_docker/issues/166#issuecomment-603359989

**Comment by svrfremont** [comment]
I will learn Markdown. 

I do not understand your "ramesh.test wont work on localhost" comment. I will show you a diagram of my test setup:

                172.19.0.0 (Container Addresses Including nginx-web which is 172.19.0.2)
                      ^
                      |
                      |
                     v
                10.200.10.6:80 and 443 (exported)  <---------->  10.200.10.1 (Machine on which I am trying Brower access)

So your recommendation for any site is to have *.localhost whether it is for local testing or production for external access? I can simply rename and try. The site name ramesh.localhost worked for trying out locally from a browser on 10.200.10.6.  And then I renamed ramesh.localhost to ramesh.test and I included the proxy companion which launched the containers nginx-web, nginx-gen and nginx-letsencrypt. Now I was expecting that I would be able to access ramesh.test from other hosts such as 10.200.10.1.  

My assumption is wrong? Always for a site to work I need to name something *.localhost?

**Comment by revant** [comment]
For production site anything will do. Doesn't need localhost.

I'll not answer I guess. May be I'm confusing you more.

Can anyone else understand to explain here?

**Comment by revant** [comment]
DNS resolves means. You've have purchased domain name. You login registrar page. E.g. GoDaddy. Then set the ip of vps I. "A name" entry in DNS

**Comment by revant** [comment]
Did you understand what I meant by following?

Both nginx and python serve whatever is caught in $http_host. That is, whatever url typed in browser to request website. If it's not found in sites directory nginx will 404 and python will 500.

I'll rephrase, explain in depth if necessary

**Comment by svrfremont** [comment]
A site name should be resolved by DNS. Is that the requirement?

**Comment by revant** [comment]
For production Yes.
It should resolve.

You know there's a site directory? Under installation?

In that site directory there are sites that you created?

These sites get resolved as per what you enter in browser url field.

It doesn't work for any name for localhost because. Browser can resolve to localhost and containers internally can resolve to localhost

But if something else is used locally then browser on host machine resolve to different ip that doesnt reach the containers exposed on localhost. Publish ports 80:80 thing.

Sad part is all these issues and information. No one in future will read

**Comment by svrfremont** [comment]
"You know there's a site directory? Under installation?
In that site directory there are sites that you created?
These sites get resolved as per what you enter in browser url field."
From what you express "ramesh.test" should get resolved correctly by DNS. Is this correct?

I do not understand this statement "It doesn't work for any name for localhost because. Browser can resolve to localhost and containers internally can resolve to localhost"

And the statement "But if something else is used locally then browser on host machine resolve to different ip that doesnt reach the containers exposed on localhost. Publish poprts 80:80" thing".

**Comment by svrfremont** [comment]
Sorry I introduced a mistake when I retyped your message "Publish ports 80:80 thing".

**Comment by svrfremont** [comment]
From what you express "ramesh.test" should get resolved correctly by DNS. Is this correct?

**Comment by svrfremont** [comment]
ramesh.test is not a hostname but the name of test site that should be resolved correctly. Am I understanding you correctly?

**Comment by revant** [comment]
> From what you express "ramesh.test" should get resolved correctly by DNS. Is this correct?

No it won't resolve locally


ONLY ramesh.localhost will resolve locally

**Comment by revant** [comment]
There's should be site called ramesh.localhost for it to resolve and serve correctly

**Comment by svrfremont** [comment]
With ramesh.localhost there is a ready made solution I understand. 

With ramesh.test something needs to happen. That is DNS needs to resolve this. Is right?

**Comment by revant** [comment]
You can't use ramesh.test locally.

Why do you want to use ramesh.test locally? 

Add it to /etc/hosts on host machine and resolve it to 127.0.0.1

**Comment by svrfremont** [comment]
I am not ramesh.test locally. I am using ramesh.test on a test network.

**Comment by revant** [comment]
> I am not ramesh.test locally. I am using ramesh.test on a test network.

Then figure it out. Nothing of that sort was documented.

I intended local use. For api development
And production use on line website.

**Comment by svrfremont** [comment]
I am not using ramesh.test locally. I am testing ramesh.test on a test network.

**Comment by revant** [comment]
Your can try adding dns server in local network that acts as local registrar.

**Comment by svrfremont** [comment]
Yeah OK. I am going to figure out why this is failing. All I wanted to understand was the requirement from Frappe/ERPNext.

**Comment by revant** [comment]
> I am not using ramesh.test locally. I am testing ramesh.test on a test network.

I have not ever done this. You're on your own

**Comment by revant** [comment]
Suggestions:

Setup a dns server locally.
Use that dns server instead of isp/any other dns servers.
That'll solve a lot of things. It'll allow resolution across wider network of multiple routers. https://hub.docker.com/r/cytopia/bind

Letsencrypt won't work. So don't configure it.
That'll leave users vulnerable. So you'll have to figure that part.
https://security.stackexchange.com/a/121195

**Comment by revant** [comment]
Reopen if needed
