### ISSUE TITLE
website_script.js 404

### ISSUE THREAD

**Issue by AkiM1ta** [frappe/frappe_docker#173]
I deployed the newest version-12 two days ago,and it run ok.
But today,there are some problems.
![image](https://user-images.githubusercontent.com/18052598/77608992-ae951600-6f59-11ea-980b-b0eb34a4de03.png)
And I can't find the reason.

**Comment by revant** [comment]
Can you share formatted Container logs

**Comment by AkiM1ta** [comment]
Finally,one of my colleague told me he did something...after that it run wrong.
And I remove the site,then add a new same site.Everything is Ok.
