### ISSUE TITLE
Production setup mariadb permission issue

### ISSUE THREAD

**Issue by khadijazaki2** [frappe/frappe_docker#176]
On starting the new site service getting error ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by revant** [comment]
I can't reproduce issue.

Mention steps to reproduce

Also add relevant logs

**Comment by khadijazaki2** [comment]
I am following the procedure of production setup when I ran this command 
`
docker exec -it \
    -e "SITE_NAME=$SITE_NAME" \
    -e "DB_ROOT_USER=$DB_ROOT_USER" \
    -e "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" \
    -e "ADMIN_PASSWORD=$ADMIN_PASSWORD" \
    -e "INSTALL_APPS=erpnext" \
    <project-name>_erpnext-python_1 docker-entrypoint.sh new
`
I got this error if access denied.

**Comment by ddavidebor** [comment]
Did you type the password? it's 123

**Comment by khadijazaki2** [comment]
Oh the password was "admin" not "123" thats what was wrong.
As I just copied the .env file I did not change the password and it was "admin" there otherwise its usually 123 so I entered that.
