### ISSUE TITLE
Write introduction for backup documentation

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#177]
Hello,
Please write some introduction in the readme for the backup commands explaining what is backupped and how the process works.

**Comment by revant** [comment]
are you talking about `push-backup`?

`backup` command existed before this. 

the new `push-backup` command just pushes existing backup to s3 compatible storage.

**Comment by ddavidebor** [comment]
Just an introduction like the following (which is probably wrong):

Frappe_docker includes a backup function, that can be launched with the following commands. The backup function will create a SQL dump of the database, save in in the location XXX.

So that the user knows exactly what the backup command does. Now it's not clear what is backupped and what is not (files, database etc etc)

**Comment by ddavidebor** [comment]
Fixed by #180
