### ISSUE TITLE
Site not available after `bench new-site`

### ISSUE THREAD

**Issue by zborowa** [frappe/frappe_docker#181]
## Description of the issue

According to the development README a new site should be available after the `bench new-site localhost`. The site never becomes available. Also according to the `Local deployment for testing` in the main README it's specified that a site should be available after running two `docker-compose` commands. This also does not work except for displaying a `Internal server error`. Viewing logs from the running containers show that mariadb fails to start.

## Steps to reproduce the issue

1. Follow the development README with or without the help of VSCode.

### Observed result

1. Development README, with VSCode does not produce any public website, port 8000 stays unreachable.
2. Development README, without VSCode produces a Internal Server Error on port 80.

### Expected result

In both cases a default empty setup wizard of ERPNext.

**Comment by revant** [comment]
For development bench,

You'll need to `bench start` then the sites are available on port 8000.

For production deployment, site will be available after 'new' command is executed

**Comment by ddavidebor** [comment]
We should update the documentation before closing this issue

**Comment by revant** [comment]
Please do update what needs to be updated.
