### ISSUE TITLE
ERPNext on the docker development image

### ISSUE THREAD

**Issue by zborowa** [frappe/frappe_docker#186]
Is it possible to set-up ERPNext on the docker development image? When I try to install ERPnext on a generated bench it seems to fail on the final wizard configuration step during the configuration of the default values. Looking at the devcontainer yml and erpnext yml there is a difference between the used images but I would assume that it should also be possible to install ERPnext for app development purposes on the development image, right?

**Comment by revant** [comment]
> Is it possible to set-up ERPNext on the docker development image

Yes it is possible. That's how ERPNext or app development happens.

> When I try to install ERPnext on a generated bench it seems to fail on the final wizard configuration step during the configuration of the default values

Wizard Fails! Retry, Reload, Refresh, Reinstall seems to be the only way.
After few retries I'm able to complete wizard. Check forum and github issues for ERPNext related to wizard fail.

In case of production deployment, try scaling services for default worker, gunicorn if that helps.

> Looking at the devcontainer yml and erpnext yml there is a difference between the used images but I would assume that it should also be possible to install ERPnext for app development purposes on the development image, right?

devcontainer yml is for app development. It starts a container which serves all services required for app development. Viz. SocketIO, Python and services mentioned in `Procfile` in bench directory where `bench start` is executed.

erpnext yml is using multiple images where one container starts one process. That way you can scale needed service containers

**Comment by revant** [comment]
Re-open if needed
