### ISSUE TITLE
Add description to docker hub

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#189]
Docker hub descriptions are missing from images. This is a missed opportunity for cross-linking and exposure of the project.

https://hub.docker.com/u/frappe
https://hub.docker.com/r/frappe/erpnext-nginx
https://hub.docker.com/r/frappe/erpnext-worker
https://hub.docker.com/r/frappe/frappe-nginx
https://hub.docker.com/r/frappe/frappe-worker
https://hub.docker.com/r/frappe/frappe-socketio

I will figure it out how to add them

**Comment by ddavidebor** [comment]
https://github.com/peter-evans/dockerhub-description ? (asking to myself)

**Comment by revant** [comment]
added descriptions to images
