### ISSUE TITLE
How can i connect database from database client?

### ISSUE THREAD

**Issue by hizbul25** [frappe/frappe_docker#209]

**Comment by revant** [comment]
Please elaborate in detail.

Do you wish to connect to mysql?

```sh
docker exec -it project_name_mariadb_1 bash
```

once in container shell, execute:

```sh
mysql -uroot -p$MYSQL_ROOT_PASSWORD
```

Is this what you're looking for?

**Comment by hizbul25** [comment]
I would like to connect db from my [sequel pro](https://www.sequelpro.com/) client. @revant

**Comment by revant** [comment]
publish mariadb ports and then use it.

Google search landed me here: https://stackoverflow.com/a/38918335
