### ISSUE TITLE
Drop nginx for envoy

### ISSUE THREAD

**Issue by blaggacao** [frappe/frappe_docker#214]
Lots of buzz out there, but envoy seems to gain enough traction to win the reverse proxy race in the mid term.

**Describe the solution you'd like**

I'd like to propose giving some thought to using envoyroxy instead and, thereby incorporate myself into this wonderful project.

**Describe alternatives you've considered**
Leave it like it is. But might support efforts at #130 

**Additional context**
Done [similar](https://github.com/xoe-labs/dockery-odoo-scaffold/blob/master/envoy.yaml) before.

¿Worth eventually considering? Please cleanly close, if not.

**Comment by Thunderbottom** [comment]
if i may ask you so, what values does envoy add over the current nginx implementation?

**Comment by blaggacao** [comment]
Depends really on the definition of value, indeed. It's hard to say and a lot depends on one's own preferences. Well, at least it's faster and purposefully designed for vcloud native. That shurely entails some things down the line. I just quote the features from their landing here:

- Out of process architecture
- HTTP/2 & GRPC support
- Advanced load balancing
- APIS for config managment
- Observability

I'm still too litlle involved with ERP Next to be able to triage what is, will, might, will not and might not be useful in this context now and later.

**Comment by revant** [comment]
drop which nginx?

there are 2 nginx involved here.

1. frappe-nginx or erpnext-nginx image. That does the reverse-proxy, static assets and user uploaded file serving. In non-docker production install of Frappe/ERPNext (https://frappe.io/docs/user/en/bench/guides/setup-production).
there's a command `bench setup nginx`. It generates a template for nginx. I've kept is as close to `bench` as possible to keep it in sync with command. Even for future updates to core bench nginx template, we keep docker template in parallel. I think we should not touch this. It will be additional burden on maintainers of this repo to translate nginx config.

2. docker-compose-letsencrypt-nginx-proxy-companion also is based on nginx. Nginx is part of  syllabus already! I was playing around with traefik check this [wiki](https://github.com/frappe/frappe_docker/wiki/Docker-Swarm). both do the docker socket volume magic.

```yaml
volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

If you can fit envoyproxy as an optional section for users to choose, add it. README is growing. Add a `docs` directory and reference it in README.

Also for kubernetes, I think everything will be moved to separate repo where chartpress will host erpnext helm charts. A lot of things open up once the project is on kubernetes. There as well I start with https://github.com/kubernetes/ingress-nginx and https://cert-manager.io. We will add many options after it becomes official.

**Comment by ddavidebor** [comment]
I am willing to bet 10$ it will be surpassed by some other proxy written in Go instead of c++

**Comment by blaggacao** [comment]
@ddavidebor caddy is probably a candidate :wink: - but I don't think so ultimately as the argument goes C shall be still a little more performant.

**Comment by revant** [comment]
Project | Programming Language | Open Core
---------|-----------------------------------|----------------
caddy | golang | no advertised commercial offering
envoyproxy/envoy | c++ | no advertised commercial offering
nginx | c | commercial nginx plus
Traefik | golang | commercial enterprise edition

Anyone can spend time on it and add section to docs to provide alternatives for outer proxy.

Re-open issue if needed
