### ISSUE TITLE
Can not update Website_Theme, Missing Node...

### ISSUE THREAD

**Issue by AlvaroMolano** [frappe/frappe_docker#229]
## Description of the issue
Node.js problems to perform style generation.
Edit, update or create a website theme style is not working.
FileNotFound: [Error2] No such file or directory 'node':'node'
## Context information (for bug reports)
frappe_docker installed version12 
New site install

## Steps to reproduce the issue
1. Use a clean frappe_docker setup
2. Create new site
3. Go to Website module, and edit standard theme. Save changes. Or create new theme and try to save changes.

![image](https://user-images.githubusercontent.com/3089876/81084997-e26b4000-8ef6-11ea-9c5a-31588b95f8c8.png)

### Observed result RIGHT IMAGE
Message error: Node not found.
Some tools running on node might not be working.
### Expected result LEFT IMAGE
Changes are saved as in a bench install without docker.

### Stacktrace / full error message if available
Log from <project>_erpnext-python_1 container
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 893, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1064, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1047, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 788, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 13, in validate
    self.validate_theme()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 43, in validate_theme
    self.generate_bootstrap_theme()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 66, in generate_bootstrap_theme
    process = Popen(command, cwd=frappe.get_app_path('frappe', '..'), stdout=PIPE, stderr=PIPE)
  File "/opt/bitnami/python/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/bitnami/python/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'node': 'node'
```

**Comment by revant** [comment]
That hack I identified here. https://github.com/frappe/frappe_docker/issues/207

We can't do anything until it stabilizes in non-docker environment. I doesn't work in non docker environment as well. production as well as development.

Try the development docker, you'll get an error which is meaningful for core developers. you can post it on frappe issues then

Related post: 
https://discuss.erpnext.com/t/error-theme-file-generation-failed/60793
https://discuss.erpnext.com/t/website-themes-modification/60735

Please open and follow it up in frappe.

My useless opinion: I've given up on styling or customizing frappe/erpnext. frappe/erpnext for me is just ReST API with validations. I use it as it is. I don't write single line of code in frappe/erpnext that is not a PR. All customization I prefer to build as independent microservices (UI as well as backend) connecting to this ReST API.

**Comment by chlarsen** [comment]
Dear All,
This issue should not be closed: The kind hint to use the development branch (with cypress dependencies) or docker is not helpful to the emerging pack of FreeBSD users among the ERPNext community. Hint: Neither cypress nor docker are supported by FreeBSD.) As a workaround, it would be great to get some hints as to where to put a site-specific SCSS file and how to link it to override the default system theming. I am more than happy to edit that site-specific SCSS file manually. This would bring us yet another step forward towards FreeBSD compatibility! Thank you!

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/330

- node is now installed in python worker image using nvm
- node-sass is required 
- other node_modules dependencies are also required to build the scss themes.
- node_modules are installed as part of nginx image
- nginx container rsyncs the required assets to a common volume in docker-entrypoint.sh
- worker container symlinks the node_modules from common volume to apps/frappe/node_modules

This solves it for docker on production systems.

Try in Play with docker https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/frappe/frappe_docker/develop/tests/pwd.yml

**Comment by chlarsen** [comment]
Thanks a lot, indeed, Revant, for your quick reply. Alas, docker is not supported on FreeBSD (if we ignore a rudimentary, by now obsolete attempt to do so).
However, the components you mentioned, are all installed on the system. All I really have to know is where ERPNext/Frappe expects the site-specific SCSS file to live - somewhere belore the "sites/[sitename]/" folder I guess?
Any idea? Thank you so much!
Chris

**Comment by revant** [comment]
> All I really have to know is where ERPNext/Frappe expects the site-specific

https://github.com/frappe/frappe/blob/a6eae56658ee0922086d0c73073354c34205e8fd/frappe/website/doctype/website_theme/website_theme.py#L89

site themes seem to be stored in public/files/website_theme

Check if this helps: https://discuss.erpnext.com/t/steps-to-install-erpnext-without-bench/64757

**Comment by chlarsen** [comment]
Dear Revant,

Thanks a lot, indeed. I will check out the file location, and may even
slim down the ERPNext installation to its pure core :-).

Thank you so much, I will feedback.

Chris


Revant Nandgaonkar:
>> All I really have to know is where ERPNext/Frappe expects the site-specific
> https://github.com/frappe/frappe/blob/a6eae56658ee0922086d0c73073354c34205e8fd/frappe/website/doctype/website_theme/website_theme.py#L89
>
> site themes seem to be stored in public/files/website_theme
>
> Check if this helps: https://discuss.erpnext.com/t/steps-to-install-erpnext-without-bench/64757
>
>
>

**Comment by MarekPikula** [comment]
@revant Was it fixed for erpnext-nginx image or only frappe-nginx?

**Comment by revant** [comment]
@MarekPikula

This was for frappe-nginx.

erpnext-nginx inherits from frappe-nginx.

**Comment by MarekPikula** [comment]
Actually based on Dockerfiles I cannot see in which way erpnext-nginx derives from frappe-nginx. Besides that, when I'm trying to add Website Theme on erpnext-nginx v12.10.1 `node-sass` missing error is risen. Shall I open a new issue, or am I missing something?

**Comment by MarekPikula** [comment]
I cannot see a reference to `frappe-nginx/build.sh`, where `yarn add node-sass` is ran, in `erpnext-nginx`.

**Comment by revant** [comment]
I think you're right.

`yarn add node-sass only happens in frappe-nginx`

I sent a pr to frappe https://github.com/frappe/frappe/pull/11220

Generally in nodejs projects node-sass happens in development and only css assets are packed and served in production.
In frappe theme changes happen with node-sass in production.

snyk shows there are security issues in node-sass to be kept in production.

@MarekPikula send a PR here that adds node-sass even in erpnext-nginx I'll merge.

**Comment by BevanTony1** [comment]
I'm experiencing the same issue for version-13. 

![image](https://user-images.githubusercontent.com/85614308/156211058-9fb289b1-6208-4272-b5a0-a4a6daa59c98.png)

**Comment by ashish-greycube** [comment]
at present (Frappe Framework: v13.27.0 (version-13)) , for non dock user  the workaround is to switch to development mode and create website theme
https://github.com/frappe/bench/wiki/Stopping-Production-and-starting-Development

**Comment by ashish-greycube** [comment]
This happens when node is installed via nvm

**Check**
`$ /usr/bin/node`
Gives output :
` -bash: /usr/bin/node: No such file or directory`
It should give:
```
Welcome to Node.js v14.19.0.
Type ".help" for more information.
> 
```

**Solution**: Make a symbolic link 
`$ sudo ln -s $(which node) /usr/bin/`
