### ISSUE TITLE
Restore-backup from host and not from AWS S3

### ISSUE THREAD

**Issue by AlvaroMolano** [frappe/frappe_docker#230]
Trying to restore a backup with files from host instead of S3 is not defined in the documentation.
Could you explain here how to achieve it, please?

**Comment by revant** [comment]
- mount it as volume at location `/home/frappe/backups`
- directory structure should be as mentioned in README or it will not be able to identify sites and fail.

>  -v ./backups:/home/frappe/backups \

refer https://github.com/frappe/frappe_docker/blob/develop/README.md#restore-backups

re-open issue if necessary
