### ISSUE TITLE
[QUESTION] Subfolder git projects not recognised in VSCode

### ISSUE THREAD

**Issue by ARAGATO** [frappe/frappe_docker#236]
I installed a fresh frappe_docker by cloning https://github.com/frappe/frappe_docker.git as written in https://github.com/frappe/frappe_docker/blob/develop/development/README.md 

Everything works well, except that I cannot get VSCode to recognise my app git repositories. Only the the workspace git project (which comes along when cloning the frappe_docker.git) is recongnized. All my custom apps (which are seperate git projects) are not recognised in VSCode.
![image](https://user-images.githubusercontent.com/25451106/81719627-7add6380-94a7-11ea-9d20-7739f756eebc.png)

I tried to add these folders by excluding them in the .gitignore but that does not change anything. 
![image](https://user-images.githubusercontent.com/25451106/81719686-9183ba80-94a7-11ea-8e2e-8ea4c7843122.png)

Any help appreciated.

**Comment by revant** [comment]
If `development` is removed from .gitignore file it will start showing changes.

Problem I faced was, It started showing there are 5k changes and crashed after sometime.

I am not able to find any solution in settings.

**Comment by GraficheAquilane2021** [comment]
@ARAGATO Same here. How did you solved?

**Comment by revant** [comment]
No solution yet I think
