### ISSUE TITLE
Incorrect PDF View

### ISSUE THREAD

**Issue by khadijazaki2** [frappe/frappe_docker#237]
## Description of the issue
The view as seen in pdf view is different from the view we get in print preview

Print view
![Screenshot from 2020-05-16 22-24-13](https://user-images.githubusercontent.com/55739397/82126705-c5245480-97c7-11ea-9480-594efe40f44c.png)

PDF View
![Screenshot from 2020-05-16 22-26-20](https://user-images.githubusercontent.com/55739397/82126713-d2d9da00-97c7-11ea-9871-cb78baa07459.png)

## Context information (for bug reports)
If I directly print or click on full page, the view is correct the issue is occuring only in the pdf view

## Steps to reproduce the issue

1. I asked this on forum too which suggested to add host name in the config file of site
2. My site name is "mysite.localhost" so I added "host_name":"mysite.localhost:8000" or "host_name":"http://mysite.localhost:8000" but still the issue was not resolved
3. I am developing using my custom app so maybe there was some major update but I checked that also

Let me know if this is a global issue or just in docker installation as I use docker for installation, it worked fine before the latest major changes in docker that was updated recently
What can I do further to resolve it any code change?
Also the version for wkhtmltopdf is "wkhtmltopdf 0.12.5 (with patched qt)"

**Comment by khadijazaki2** [comment]
Update:
I used "host_name":"http://192.168.0.105" that is my local IP so it changed to the following view
![Screenshot from 2020-05-16 23-19-39](https://user-images.githubusercontent.com/55739397/82127276-bcce1880-97cb-11ea-8871-b912b028c1b2.png)

**Comment by revant** [comment]
I'll try development bench.

For production images pdf is working fine.

**Comment by revant** [comment]
Try latest bench image?

It is working on v12.8.0/v12.5.2

**Comment by khadijazaki2** [comment]
are you talking about bench version? like I setup docker and insalled version-12 of frappe and this issue was present

**Comment by khadijazaki2** [comment]
Or can you tell me what files I should look into or what libraries might be not have been installed that maybe created this issue?

**Comment by khadijazaki2** [comment]
I yesterday rebuild and re installed it again, the result is like this still
![Screenshot from 2020-05-18 22-55-44](https://user-images.githubusercontent.com/55739397/82244491-c2a63400-995a-11ea-9603-99eff4561a4d.png)

**Comment by revant** [comment]
> https://user-images.githubusercontent.com/55739397/82126713-d2d9da00-97c7-11ea-9871-cb78baa07459.png

I can confirm, `Student` DocType print looks like this on first install.

On my arch linux native non-docker bench I had no wkhtmltopdf, I installed it from https://aur.archlinux.org/packages/wkhtmltopdf-static and it started working as expected.

It seems something wrong with wkhtmltopdf setup inside docker images

**Comment by revant** [comment]
I think the images are using debian buster base image, and wkhtmltopdf is installed for debian stretch.

Can you send a fix, if it's urgent? Or I'll update in couple of hours.

frappe/frappe-worker (4 Dockerfiles) and frappe/bench (1 Dockerfile) need to change.

**Comment by khadijazaki2** [comment]
No I can't find a fix if its related to docker, its not urgent we are not production ready, but please do resolve this issue.

**Comment by revant** [comment]
I updated the wkhtmltopdf to use buster_amd64.deb

#240 

It doesn't seem to solve the problem.

**Comment by khadijazaki2** [comment]
But I have same result :( 
I tested on easy install script production same issue there too

**Comment by revant** [comment]
https://discuss.erpnext.com/t/pdf-email-problems-thread/11614/2

**Comment by khadijazaki2** [comment]
No success in both docker and easy install have tried all possible solutions as mentioned in above thread

**Comment by revant** [comment]
Report in frappe repo just to keep note of it. 
We'll hope it gets fixed.

Core Priorities may be different.

**Comment by deantheiceman** [comment]
@revant hi is this still relevent in the latest docker versions? I tried setting the config but it doesn't fix the issue. Do we need to use nginx hostname or something else instead?

**Comment by deantheiceman** [comment]
@khadijazaki2 did you end up resolving this?

**Comment by desian78** [comment]
I xperienced this issue as well. We tryed to solve it by using something in "host_name" like  (http://)"my-doman.name".
For the docker version it worked for a while (before erpnext v13.16.x) after updating we had to update all this stuff bin the PDF does notwork anymore.
