### ISSUE TITLE
ERROR: unauthorized: authentication required - Windows 10

### ISSUE THREAD

**Issue by foorman** [frappe/frappe_docker#248]
### Trying to launch on Windows10:

**_During install on step launch container:_**

Launch the command, from Command Palette (Ctrl + Shift + P) Execute Remote Containers : Reopen in Container. You can also click in the bottom left corner to access the remote container menu.

**_got this error:_**

ERROR: unauthorized: authentication required
[2020-05-06T22:49:53.988Z] [PID 14092] [393057 ms] Command failed: docker-compose --project-name frappe_docker_devcontainer -f c:\projects\frappe\frappe_docker\.devcontainer\docker-compose.yml up -d --build

**Comment by revant** [comment]
Have you logged in to docker?

```sh
docker login
```

**Comment by revant** [comment]
Re open the issue if needed
