### ISSUE TITLE
 Error when running docker-compose

### ISSUE THREAD

**Issue by seirian** [frappe/frappe_docker#250]
The following error occurs when running docker-compose. How should I act?
(Please understand that I can't speak English and ask questions with a Google translator.)

ERROR: Network webproxy declared as external, but could not be found. Please create the network manually using `docker network create webproxy` and try again

**Comment by revant** [comment]
If you are on production setup first you need to setup letsencrypt nginx proxy companion.

https://github.com/frappe/frappe_docker#setup-letsencrypt-nginx-proxy-companion

then only the command with networks.yml file work.

```sh
docker-compose \
    --project-name <project-name> \
    -f installation/docker-compose-common.yml \
    -f installation/docker-compose-erpnext.yml \
    -f installation/docker-compose-networks.yml \
    up -d
```

If you don't need to use production or the networks.yml use the *-publish.yml

example

```sh
docker-compose \
    --project-name <project-name> \
    -f installation/docker-compose-common.yml \
    -f installation/docker-compose-erpnext.yml \
    -f installation/erpnext-publish.yml \
    up -d
```

**Comment by seirian** [comment]
Thanks for the help.
But, However, when docker is connected to port 80 after running docker, a screen with the following message is displayed.

Sorry!
We will be back soon.

Don't panic. It's not you, it's us.
Most likely, our engineers are updating the code, and it should take a minute for the new code to load into memory.
Try refreshing after a minute or two.

How do I solve it?

**Comment by revant** [comment]
Did you add a new site?

**Comment by revant** [comment]
Now your can even use single bench setup where you don't have to create site separately.

Re open the issue if needed
