### ISSUE TITLE
Default Username in Documentation

### ISSUE THREAD

**Issue by muniter** [frappe/frappe_docker#251]
In the deployment documentation there's a reference for the Administrator password. Normally a the standard Administrator username is `admin` in the case of erpnext is `administrator` this can lead to confusion and looking up in the internet. Perhaps It would be best practice to reference in the documentation.

**Comment by revant** [comment]
Send PR. 

Add [skip travis] to commit message if you're just editing docs.

**Comment by muniter** [comment]
#262 Adds comments about it.
