### ISSUE TITLE
Docker Run fails  due to non-existent docker network named like this: <project-name>_default.

### ISSUE THREAD

**Issue by Ileriayo** [frappe/frappe_docker#253]
Following the instructions for Production Deployment in [README.md](https://github.com/frappe/frappe_docker/blob/develop/README.md), the [Setup New Site](https://github.com/frappe/frappe_docker#setup-new-sites) section includes a `docker run` command which fails because of an invalid docker network: `--network <project-name>_default`.

This throws an error because no network of the format `<project-name>_default` was ever created in the first place.

I searched the codebase to see if there was any docker compose command that created a network like that but none was found.

Docker Run Command:
```
docker run \
    -e "SITE_NAME=$SITE_NAME" \
    -e "DB_ROOT_USER=$DB_ROOT_USER" \
    -e "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" \
    -e "ADMIN_PASSWORD=$ADMIN_PASSWORD" \
    -e "INSTALL_APPS=erpnext" \
    -v <project-name>_sites-vol:/home/frappe/frappe-bench/sites \
    --network <project-name>_default \
    frappe/erpnext-worker:$VERSION new
```

**Comment by gnunicorn** [comment]
you need to replace the `<project_name>` with whatever you used in the `docker-compose up` after `--project-name` .

**Comment by Ileriayo** [comment]
That's exactly correct @gnunicorn and that's not the issue.
Replace <project-name> with my_project and read the issue again.
The issue is: `Docker Run fails due to **non-existent docker network named like this**: <project-name>_default.`

Following the project name specified above, that will mean that there is no docker network named my_project_default, hence the `docker run` command fails.

**Comment by gnunicorn** [comment]
If you started the regular (not the deployment) docker-compose the network was automatically created by it. If you used the nginx-letsencrypt the network is replaced with the external `webproxy` network and none is created. In that case you probably want to use that instead.

**Comment by Ileriayo** [comment]
Thanks, I did use that eventually.
Part of why I raised this issue is so that the docs can be updated.
