### ISSUE TITLE
Unable to access ERPNext from the browser after production deployment

### ISSUE THREAD

**Issue by Ileriayo** [frappe/frappe_docker#255]
## Description of the issue
Unable to access ERPNext from the browser after production deployment.

## Context information (for bug reports)
Docker production deployment

## Steps to reproduce the issue
1. Follow instructions for production deployment as also specified in this issue [233](https://github.com/frappe/frappe_docker/issues/233)

2. Run `docker compose up` command.

3. Execute `docker-entrypoint.sh new` command in the erpnext_python container.

### Observed result
Cannot access ERP from erp.mycompany.com 

### Expected result
Production deployment is supposed to be complete and ERPNext should be accessible from erp.mycompany.com

**Comment by revant** [comment]
> SITE_NAME=mycompany_erp

SITE_NAME should be the resolvable site name. e.g. `erp.mycompany.com`, exact same as SITES variable.

Also try restarting the `nginx-web`, `nginx-gen` and `nginx-letsencrypt`. On restart the'll

**Comment by Ileriayo** [comment]
The Readme reads `SITE_NAME: name of the new site to create`, which was unclear to me.

But thanks, this fixed it for me.
I'll probably raise a PR to provide more information in the Readme file.

**Comment by revant** [comment]
Do send any PR that makes it clear and easy for new users.

use `[skip travis]` anywhere in your commit message if you are only editing docs.

**Comment by Ileriayo** [comment]
Okay, cool.
