### ISSUE TITLE
bench -c not passing arguments

### ISSUE THREAD

**Issue by africlouds** [frappe/frappe_docker#26]
According to documentation 

> All bench commands can also be directly run from the host machine by using dbench. For instance bench start can be executed by running ./dbench -c start. Just preface the option with ./dbench -c

this should work:
`./dbench -c new-site site_name`

However, the site_name argument is not being passed to the container.
The problem may be here https://github.com/frappe/frappe_docker/blob/master/dbench#L36
I am not familiar with bash but when I hardcode like this
`docker exec -it frappe bash -c "bench $OPTARG site_name"` it works

**Comment by chabad360** [comment]
Please close as this is no longer relevant.
