### ISSUE TITLE
*** Scheduler is disabled ***

### ISSUE THREAD

**Issue by amrhegazy01** [frappe/frappe_docker#265]
hello all
im used single bench not got error in docker-compose command but after execution check logs for creator container im got 

]Updating DocTypes for erpnext       : [======================================= ]Updating DocTypes for erpnext       : [======================================= ]Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***

also when ckeck browser i've got 

404 page not found

**Comment by revant** [comment]
ERPNext is installed correctly. `*** Scheduler is disabled ***` is part of frappe framework code.

Are you using locally?
Are you on windows or mac with vm?

What is the name of site? `mysite.localhost`?

**Comment by amrhegazy01** [comment]
yes locally
on linux ubuntu 18
yes used mysite.localhost for site name

**Comment by revant** [comment]
I just tried on my linux laptop. from fresh start. removed my local images. It worked.

Try restarting traefik container or all containers.

Can you share logs of traefik container, erpnext-nginx and erpnext-python container. make a gist or pastebin.

**Comment by amrhegazy01** [comment]
restarted all container same issue

here log of traefik container

https://pastebin.com/LFZhRkeZ

thanks

**Comment by amrhegazy01** [comment]
resolved it thank you
issue from sitename and traefik

be continue .. perfect project

**Comment by revant** [comment]
I'll close the issue.

Reopen if needed.

**Comment by revant** [comment]
> also im tried with play with docker session
> i've got same error you can test it

run this in an pwd instance:

```sh
git clone https://github.com/frappe/frappe_docker.git && cd frappe_docker
export HYPHEN_IP=$(ip a | grep "scope global eth1" | awk '{print $2}' | sed 's|\(.*\)/.*|\1|' | sed "s/\./-/g")
export SITE_NAME=http://ip$HYPHEN_IP-$SESSION_ID-80.direct.$PWD_HOST_FQDN
cp env-local .env
sed -i -e 's|mysite.localhost|'$SITE_NAME'|g' .env
docker-compose up -d

# Check progress of site creation
docker logs frappe_docker_site-creator_1 -f
echo "visit $SITE_NAME"
```

**Comment by solidet** [comment]
i am facing the same problem. how do you solve this?

**Comment by revant** [comment]
Machine must have at least 2GB Memory (RAM+swap)

**Comment by hovanvydut** [comment]
> solved it thank you issue from sitename and traefik
> 
> be continue .. perfect project

I'm facing the same problem. How do you solve this?
Thank you so much <3
