### ISSUE TITLE
Restore backup in containerized deployment

### ISSUE THREAD

**Issue by angelgavrailov** [frappe/frappe_docker#266]
Hi,

My company is using erpnext and for a current app development we would like to import the current ly exported company backup data, including files, into a containerized erp deployment. Unfortunately, until now we have no idea how to do this.

Any help?

Regrds,
Gavrailov

**Comment by revant** [comment]
If you have a custom app you need custom image

follow documentation here https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md

Once custom app is available it is just another backup restore.

Also if custom app has any fixtures it will apply them during migration.

**Comment by angelgavrailov** [comment]
>There is also wiki for case like this,
>https://github.com/frappe/frappe_docker/wiki/Migrate-from-frappe-bench-to-containerized-cloud

What are the prerequisites of this guide? It doesn't run out of the box.

**Comment by revant** [comment]
- existing frappe-bench on non docker server
- S3 compatible storage credentials

**Comment by angelgavrailov** [comment]
Is it possible to restore erpnext backup in the fresh deployed containerized erpnext instance, on a clean machine?

**Comment by revant** [comment]
Yes it is possible.

Remember the site names that are backed up and restored.

On container environment they should resolve to dns

**Comment by revant** [comment]
Re-open if needed.

**Comment by lekhnath** [comment]
All links are broken

**Comment by bibhashanand** [comment]
@revant please help us to restore backups with files to a containerised erpnext, I copied the backup files in volume _data tired running the bench restore command in both backend and frontend erpnext container but both thorows permission issue error, and when i tired copying backup files inside backend container and run bench restore command it worked but when i tired to login it won't shows something went wrong.

On which container I should run the bench restore command?
Where should I keep the backup files?

**Comment by saru2020** [comment]
> @revant please help us to restore backups with files to a containerised erpnext, I copied the backup files in volume _data tired running the bench restore command in both backend and frontend erpnext container but both thorows permission issue error, and when i tired copying backup files inside backend container and run bench restore command it worked but when i tired to login it won't shows something went wrong.
> 
> On which container I should run the bench restore command? Where should I keep the backup files?

+1
