### ISSUE TITLE
Authentication token manipulation error

### ISSUE THREAD

**Issue by AkiM1ta** [frappe/frappe_docker#281]
When I run a stopped worker container.It told me this.
![image](https://user-images.githubusercontent.com/18052598/85282419-4608f700-b4be-11ea-8faa-3c1b452282e0.png)
 
And I didn't know how to do.

Then,I tried to start a new images and it showed this.
![image](https://user-images.githubusercontent.com/18052598/85282647-adbf4200-b4be-11ea-8592-c7b22a4ec9ec.png)

What should I do with my old customed and stoped container?

**Comment by revant** [comment]
It's related to OS and related settings?

I tried to stop container and It doesn't show me the error.

> What should I do with my old customed and stoped container?

if it was just a run once command like `bash`. You can remove the container. Nothing is stored in it anyway.

**Comment by AkiM1ta** [comment]
> It's related to OS and related settings?
> 
> I tried to stop container and It doesn't show me the error.
> 
> > What should I do with my old customed and stoped container?
> 
> if it was just a run once command like `bash`. You can remove the container. Nothing is stored in it anyway.

I run the image,and exit.Then started the container.And found this.
![image](https://user-images.githubusercontent.com/18052598/85299381-c7b94e80-b4d7-11ea-876c-eb39a3ec7300.png)

I modified code in ../app/erpnext/erpnext.So the old container is important.
Now,I think I have to make the same container run.

**Comment by revant** [comment]
You're on your own if you are changing the state of customer on production. It was designed to be immutable. If possible commit the change to remote repo and build custom image.

If you need to change ERPNext code build your own image with your fork repository.
