### ISSUE TITLE
Patches.txt

### ISSUE THREAD

**Issue by venetanji** [frappe/frappe_docker#296]
Hi! great stuff on the latest development in with frappe_docker.

I am wondering what would be the best way to go about skipping some migrations in patches.txt in this setup. Given the container is recreated everytime would I need to persist patches.txt with a bind mount?

**Comment by revant** [comment]
Anything in frappe-bench is already bind mounted in case you use the `.devcontainer/docker-compose.yml`. 
`./development` directory from repo root is already mounted in container at location `/workspace/development`

all the benches you make inside /workspace/development will persist on host.

check https://github.com/frappe/frappe_docker/tree/develop/development#manually-start-containers if you don't prefer VS Code.

**Comment by venetanji** [comment]
I'm actually just trying to get a new production setup working with an existing database. In the previous version of frappe_docker I was using, the whole bench (including /apps) was bindmounted so I could just edit patches.txt and comment out a few migrations that were failing. Now if the container image is rebuilt patches.txt is fresh off the repo every time. So what would be the proper way to go about this in production?

**Comment by revant** [comment]
Build your custom image with custom app and patches.

If it is non customized ERPNext then, failing patches need to be fixed, rather than skipped.

Bench is not available in production images.

Also check wiki if it helps.

https://github.com/frappe/frappe_docker/wiki

**Comment by revant** [comment]
re-open issue if needed.
