### ISSUE TITLE
am i missing dbench? i don't know what's wrong.. 

### ISSUE THREAD

**Issue by JA500001** [frappe/frappe_docker#298]
Hi,

Hello, I followed steps for installing erpnext docker image from:
https://github.com/frappe/frappe_docker

Working up to step copied below:

First time setup
./dbench init

returns following:

$ pwd
/Users/dd/projects/natural_wraps/frappe_docker

$ /dbench init
-bash: /dbench: No such file or directory

is there something basic i am not grasping here, sorry in advance :-)
installation/docker compose was previously successful

$ docker-compose --project-name natural-wraps-erp-single-bench up -d
Pulling traefik (traefik:v2.2)...
v2.2: Pulling from library/traefik
cbdbe7a5bc2a: Pull complete
f16506d32a25: Pull complete
2be216d464d0: Pull complete
aed51f08b610: Pull complete
Digest: sha256:ad4442a6f88cf35266542588f13ae9984aa058a55a518a87876e48c160d19ee0
Status: Downloaded newer image for traefik:v2.2
Pulling erpnext-nginx (frappe/erpnext-nginx:edge)...
edge: Pulling from frappe/erpnext-nginx
8559a31e96f4: Pull complete
8d69e59170f7: Pull complete
3f9f1ec1d262: Pull complete
d1f5ff4f210d: Pull complete
1e22bfa8652e: Pull complete
849f748c87df: Pull complete
b85d9adf31eb: Pull complete
449896cc30c4: Pull complete
9adf3dbf626b: Pull complete
b387645511fa: Pull complete
a97dd9005a85: Pull complete
af8e29410d6d: Pull complete
6462561e2546: Pull complete
Digest: sha256:a8119f38ab0e92723297d082b3cd5067679b2fdf56e8c62fb1eeeb477ee6518f
Status: Downloaded newer image for frappe/erpnext-nginx:edge
Pulling erpnext-python (frappe/erpnext-worker:edge)...
edge: Pulling from frappe/erpnext-worker
20b41457e783: Pull complete
ce2cbfea1684: Pull complete
31bad6503dd1: Pull complete
32abbe4d7700: Pull complete
635c4e4ec8e8: Pull complete
f122ecbb2921: Pull complete
7e32c96cc4dd: Pull complete
a08dcfabf411: Pull complete
bf49ed438ab0: Pull complete
72a1a2c953be: Pull complete
e966e11b5029: Pull complete
5cc6a4d2de86: Pull complete
aa2482ae16c5: Pull complete
53c7d5a5184c: Pull complete
a9451f9fa2b1: Pull complete
1fbd33abc92f: Pull complete
268f04b28080: Pull complete
30c8bfbf8f4b: Pull complete
0538f17ed489: Pull complete
5ae545bbde57: Pull complete
Digest: sha256:6cfba7f8ce13c0713a8fb201758964323a00327dcaad241834b7ddc911cb977a
Status: Downloaded newer image for frappe/erpnext-worker:edge
Pulling redis-cache (redis:latest)...
latest: Pulling from library/redis
8559a31e96f4: Already exists
85a6a5c53ff0: Pull complete
b69876b7abed: Pull complete
a72d84b9df6a: Pull complete
5ce7b314b19c: Pull complete
04c4bfb0b023: Pull complete
Digest: sha256:800f2587bf3376cb01e6307afe599ddce9439deafbd4fb8562829da96085c9c5
Status: Downloaded newer image for redis:latest
Pulling frappe-socketio (frappe/frappe-socketio:edge)...
edge: Pulling from frappe/frappe-socketio
7d2977b12acb: Pull complete
23e9a36a6e2d: Pull complete
e3a388627cb2: Pull complete
8f0e0c13ebf0: Pull complete
3a8af6752480: Pull complete
44c2ca365c60: Pull complete
25358844f282: Pull complete
b6e2980096d4: Pull complete
573401588d25: Pull complete
9333b811793a: Pull complete
cb20963ca43b: Pull complete
f22375a622ef: Pull complete
Digest: sha256:2d084246262271e5d66cc1681ad2b3ebb568f1bff5b2ce1fe03c41607b5e6a68
Status: Downloaded newer image for frappe/frappe-socketio:edge
Pulling mariadb (mariadb:10.3)...
10.3: Pulling from library/mariadb
a4a2a29f9ba4: Pull complete
127c9761dcba: Pull complete
d13bf203e905: Pull complete
4039240d2e0b: Pull complete
7e2d48f22ade: Pull complete
42ed51adaf49: Pull complete
1e18725209e8: Pull complete
67412c7f89bc: Pull complete
6518a50ecb7c: Pull complete
58175d975ba9: Pull complete
9a152b4639a7: Pull complete
54a0566f14ee: Pull complete
c0fc46e67c23: Pull complete
e5f8ea1411aa: Pull complete
Digest: sha256:7eb3adf906a402351bee26a2959438e206752a8a32bf9eb3decdd13f4d267fa8
Status: Downloaded newer image for mariadb:10.3
Creating natural-wraps-erp-single-bench_redis-cache_1    ... done
Creating natural-wraps-erp-single-bench_erpnext-nginx_1          ... done
Creating natural-wraps-erp-single-bench_redis-socketio_1         ... done
Creating natural-wraps-erp-single-bench_redis-queue_1    ... done
Creating natural-wraps-erp-single-bench_mariadb_1                ... done
Creating natural-wraps-erp-single-bench_traefik_1                ... done
Creating natural-wraps-erp-single-bench_erpnext-python_1         ... done
Creating natural-wraps-erp-single-bench_erpnext-worker-long_1    ... done
Creating natural-wraps-erp-single-bench_erpnext-worker-short_1   ... done
Creating natural-wraps-erp-single-bench_erpnext-worker-default_1 ... done
Creating natural-wraps-erp-single-bench_erpnext-schedule_1       ... done
Creating natural-wraps-erp-single-bench_site-creator_1           ... done
Creating natural-wraps-erp-single-bench_frappe-socketio_1        ... done

$ ls
CONTRIBUTING.md		build			docker-compose.yml	env-local		greetings.yml		travis.py
LICENSE.md		deploy_key.enc		docs			env-production		installation
README.md		development		env-example		frappe-installer	tests

$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                      NAMES
c332b594265b        frappe/frappe-socketio:edge   "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes                                                   natural-wraps-erp-single-bench_frappe-socketio_1
aab06787cb24        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        8000/tcp                                   natural-wraps-erp-single-bench_erpnext-worker-default_1
5149c67dba73        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        8000/tcp                                   natural-wraps-erp-single-bench_erpnext-worker-long_1
1b9a4fa1c18d        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        8000/tcp                                   natural-wraps-erp-single-bench_erpnext-schedule_1
2cb57d2fce10        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        8000/tcp                                   natural-wraps-erp-single-bench_erpnext-worker-short_1
50e8c670790e        traefik:v2.2                  "/entrypoint.sh --lo…"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   natural-wraps-erp-single-bench_traefik_1
50a4d80b122d        redis:latest                  "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        6379/tcp                                   natural-wraps-erp-single-bench_redis-queue_1
f5477c8d234b        redis:latest                  "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        6379/tcp                                   natural-wraps-erp-single-bench_redis-cache_1
7ed50f4c2b56        redis:latest                  "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        6379/tcp                                   natural-wraps-erp-single-bench_redis-socketio_1
cb1d9f2f98bf        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        8000/tcp                                   natural-wraps-erp-single-bench_erpnext-python_1
12fce49adc5c        frappe/erpnext-nginx:edge     "/docker-entrypoint.…"   7 minutes ago       Up 7 minutes        80/tcp                                     natural-wraps-erp-single-bench_erpnext-nginx_1
be5324cf33e7        mariadb:10.3                  "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes        3306/tcp                                   natural-wraps-erp-single-bench_mariadb_1

**Comment by revant** [comment]
There is no more dbench.

For development refer https://github.com/frappe/frappe_docker/blob/develop/development

The docker-compose for single bench is for production deployment.

**Comment by JA500001** [comment]
Thankyou recant for saving my saniry! O can't see the bench utility either , do u know where this is run? Thanks!

**Comment by ddavidebor** [comment]
You can access it from inside the relevant container, you can see example
in the link provided.

**Comment by JA500001** [comment]
thanks ddavidebor, and one last questions, sorry to hijack.. 

which container should i be working in to set up my site?

i have been using this set of instructions , below, from https://blog.karmacomputing.co.uk/erpnext-docker-installation/, but it is presumably out of date as there is not container with name 'frappe' once docker compose has completed ..

docker exec -i -u root frappe bash -c "cd /home/frappe && chown -R frappe:frappe ./*" 
cd ~/
bench init frappe-bench --skip-bench-mkdir --skip-redis-config-generation
cd frappe-bench
mv Procfile_docker Procfile
mv sites/common_site_config_docker.json sites/common_site_config.json
bench set-mariadb-host mariadb

is there an up to date md or equivalent which can be followed to complete the site config?

(when I navigate to http://0.0.0.0:8000 i get a 404 at the moment ..)

**Comment by ddavidebor** [comment]
Yes the link Revant gave you
https://github.com/frappe/frappe_docker/blob/develop/development

All the answers are there. Ignore that blog.

**Comment by JA500001** [comment]
thanks ddavidebor!

yes that .md is much better... when it mentions "Run the following commands in the terminal inside the container. You might need to create a new terminal in VSCode."

which container is it referring to as i have several containers running now after my docker compose

thanks!

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/tree/develop/development#running-the-containers

> docker exec -e "TERM=xterm-256color" -w /workspace/development -it devcontainer_frappe_1 bash

If you're not using vs code then manually exec into frappe container.

If you're using vs code, open the directory with vs code dev containers extension and then open the console from vs code, it'll automatically exec into frappe container

**Comment by JA500001** [comment]
fantastic, thanks so much for your guidance, i really appreciate you taking time out to help me.
