### ISSUE TITLE
How to restore ERPNext Database - should throw errors on fail

### ISSUE THREAD

**Issue by ajs11174** [frappe/frappe_docker#304]
I was able to get the helm chart up and running for ERPNext and I am able to create a backup, however when I restore, only the files are restored. The database is not restored.

Link for reference: https://helm.erpnext.com/kubernetes-resources/create-restore-backups-job

Here are the logs from the restore-backup container 
````
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-database.sql.gz
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-files.tar
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-private-files.tar
Downloading erp.mysite.com/20200707_004431/site_config.json
Overwrite site erp.mysite.com
Extract Database GZip for site erp.mysite.com
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
Restoring MariaDB
sh: 2: _7033aa8d54d18326: not found
Extracting /home/frappe/backups/erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-private-files.tar
Extracting /home/frappe/backups/erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-files.tar
````

I checked Mariadb and database _7033aa8d54d18326 does exist. I'm not sure what is missing.

**Comment by revant** [comment]
> Figured it out. I had a carriage return in my mariadb-root-password so it was not able to log into the db. It might be helpful to check if auth failed during the restore and provide a better error message in the logs. Below is a link where the script sets up the auth and is used in 4 of the lines which correspond to the 4 `sh: 2: -e: not found` errors.
> 
> https://github.com/frappe/frappe_docker/blob/f97c276871a0270d08eda1127959aa32688f7175/build/common/commands/restore_backup.py#L242
> 

https://github.com/frappe/frappe_docker/pull/305

**Comment by dev7495** [comment]
How to restore s3 backup. Installed erpnext via frappe-docker. Please suggest
