### ISSUE TITLE
[bug] Error installing ERPNext v12.10.1 on AWS RDS MariaDB

### ISSUE THREAD

**Issue by ceefour** [frappe/frappe_docker#308]
## Description of the issue

I have enabled `"rds_db": 1` in `common_site_config.json`:

```
(env) root@frappe-bench-0001-erpnext-worker-d-847966697-fwkwc:/home/frappe/frappe-bench/sites# cat common_site_config.json 
{
    "db_host": "xxx.ap-southeast-1.rds.amazonaws.com",
    "db_port": 3306,
    "rds_db": 1,
    "redis_cache": "redis://frappe-bench-0001-erpnext-redis-cache:13000",
    "redis_queue": "redis://frappe-bench-0001-erpnext-redis-queue:12000",
    "redis_socketio": "redis://frappe-bench-0001-erpnext-redis-socketio:11000",
    "socketio_port": 9000
}
```

## Context information (for bug reports)

* Kubernetes 1.18
* frappe/erpnext-worker v12.10.1
* AWS RDS MariaDB 10.4.13

## Steps to reproduce the issue

1. Create AWS RDS MariaDB database
2. Install ERPNext v12.10.1 on Kubernetes using helm chart
3. Error

### Observed result

```
ERROR 1054 (42S22) at line 1: Unknown column 'ERROR (RDS): SUPER PRIVILEGE CANNOT BE GRANTED OR MAINTAINED' in 'field list'
ERROR 1396 (HY000) at line 1: Operation ALTER USER failed for '_9a6f28ddcbb1acb1'@'%'
ERROR 1044 (42000) at line 1: Access denied for user 'root'@'%' to database '_9a6f28ddcbb1acb1'
```

### Expected result

Successful.

### Stacktrace / full error message

```
$ kubectl create -n erpnext -f add-lovia-site-job.yaml 
...

$ kubectl logs -f -n erpnext create-erp-lovia-life-2knwd
Attempt 1 to connect to xxx.ap-southeast-1.rds.amazonaws.com:3306
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-queue:12000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-cache:13000
Attempt 1 to connect to frappe-bench-0001-erpnext-redis-socketio:11000
Connections OK
Created user _9a6f28ddcbb1acb1
Created database _9a6f28ddcbb1acb1
Granted privileges to user _9a6f28ddcbb1acb1 and database _9a6f28ddcbb1acb1
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================]
Updating country info               : [========================================]

Installing erpnext...
Updating DocTypes for erpnext       : [========================================]
Updating customizations for Address
*** Scheduler is disabled ***
ERROR 1054 (42S22) at line 1: Unknown column 'ERROR (RDS): SUPER PRIVILEGE CANNOT BE GRANTED OR MAINTAINED' in 'field list'
ERROR 1396 (HY000) at line 1: Operation ALTER USER failed for '_9a6f28ddcbb1acb1'@'%'
ERROR 1044 (42000) at line 1: Access denied for user 'root'@'%' to database '_9a6f28ddcbb1acb1'
```

## Additional information

OS version / distribution, `ERPNext` install method, etc.

* Kubernetes
* Helm

**Comment by revant** [comment]
Does the site work?

By default it takes `root` as mariadb root username and all examples are showing `root`.

Does AWS allow `root` user to be used? or should is be using different master user account?

**Comment by ceefour** [comment]
@revant AWS RDS MariaDB does allow `root` but it does not allow `GRANT ALL` (specifically, `root` can grant all privileges expect `SUPER`) : https://stackoverflow.com/a/44441811/245552

This is the reason why there is a `"rds_db": 1` option in `common_site_config.json`. However, that option is not always obeyed by some scripts.

The safest option is to use `GRANT` specifics:

```sql
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ...
```

See also https://github.com/tenancy/multi-tenant/issues/660

BTW: I just realized that I'm filing this in `frappe_docker`.. I think this is an `erpnext` issue not a `frappe_docker` one.. But I don't think I have the access to move this issue there. :(

**Comment by revant** [comment]
The issue was moved from ERPNext to here. https://github.com/frappe/frappe_docker/issues/308#event-3544216950

> This is the reason why there is a "rds_db": 1 option in common_site_config.json. However, that option is not always obeyed by some scripts.

I'll check what this does in code and change docker scripts accordingly.

**Comment by ceefour** [comment]
@revant If it helps, I made a pretty intensive writeup about the AWS RDS MariaDB issue (and workaround) here: https://about.lovia.life/docs/infrastructure/erpnext/#2_3_MariaDB_Installation_(and_AWS_RDS_MariaDB_Workaround)

**Comment by revant** [comment]
@ceefour can you test this #312

**Comment by ceefour** [comment]
Thanks @revant , any pointer on how to test this? Can I get the image from docker hub `develop`?

**Comment by revant** [comment]
That's tricky.

you need to build images, push to some registry, update them in your deployment. if things work we'll merge this.
Once stable images are built replace the images again.

**Comment by revant** [comment]
I pushed the new image as revantnandgaonkar/erpnext-worker:edge on docker hub. Try that image in Job which creates new site.

Note: all other workers, nginx and socketio images should be on `:edge` tag

**Comment by revant** [comment]
The PR is merged. You can check the official edge images.

**Comment by ceefour** [comment]
Thank you very much @revant :+1:
