### ISSUE TITLE
ERP Next Docker Image: How to use a different port

### ISSUE THREAD

**Issue by terencejackson8000** [frappe/frappe_docker#316]
I tried to get ERPNext running with the command
`docker-compose --project-name <project-name> up -d`

The problem is that my port 80 is already in use and I am getting the following error:
`ERROR: for nginx  Cannot start service nginx: b'driver failed programming external connectivity on endpoint erpnext-xxx_nginx_1 (dd7aa98d0a9ee89d3c5c8c6a3890e0208d36bccb094882f3602b478a82f22369): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'`

I have already tried to change the ports in the docker-compose.yml. I changed it in the "ports" section as well as in the "command" section but all leading to the same result.

How can I get ERPNext running on e.g. port 81 and 444?

**Comment by revant** [comment]
https://discuss.erpnext.com/t/404-page-not-found-after-docker-installation-on-localhost/63304/4

Not possible in production setup.

**Comment by revant** [comment]
reopen if necessary
