### ISSUE TITLE
Is PostgreSQL service required in .devcontainer/docker-compose.yml ?

### ISSUE THREAD

**Issue by ceefour** [frappe/frappe_docker#317]
https://github.com/frappe/frappe_docker/blob/5a756ce2fa5492bfdcf6ef6c936130118bc85834/.devcontainer/docker-compose.yml#L12

I'm proposing the PostgreSQL is commented by default here. If a developer is specifically using PostgreSQL, they can uncomment that, and optionally comment `mariadb` instead.

**Comment by revant** [comment]
Send PR.

Changes to file and appropriate readme

**Comment by ceefour** [comment]
@revant Ok.

Another question, do you think it's a good idea, **in VSCode Dev Container**, to make mariadb expose port 3306 by default? So it is accessible from the host for debugging purposes.

As it is, again, a Dev Container and not production, I think that it is useful and saves additional initial setup. If you agree with it then I'll make additional PR for it.

**Comment by revant** [comment]
> do you think it's a good idea, in VSCode Dev Container, to make mariadb expose port 3306 by default? So it is accessible from the host for debugging purposes.

https://github.com/frappe/frappe_docker/pull/197#discussion_r410417559

I'd prefer not to. I've native Mariadb already installed and sometimes I use it as well.

**Comment by ceefour** [comment]
@revant Oh that makes sense. In that case, is it desirable to, **in VSCode Dev Container** by default, expose its MariaDB service port to a custom host port, e.g. `13306`?

That way users who accept the default can still access it (like I do), and users who have a host MariaDB can still use it without conflict, and other users can also disable MariaDB if they don't use the container one.

**Comment by revant** [comment]
I that case I'll suggest altogether removing .devcontainer directory and renaming it to devcontainer-example. Also gitignore the .devcontainer

Then ask the user to rename it back to .devcontainer and make needed changes.

Generally projects with example config do that.

Just the problem is, most of the users may get confused.
