### ISSUE TITLE
extra file creating confusion

### ISSUE THREAD

**Issue by premkanish** [frappe/frappe_docker#321]
why there is docker-entrypoint.sh in build/erpnext-nginx folder when it is already in build/frappe-nginx and being used everywhere.

**Comment by revant** [comment]
erpnext-nginx is a layered image.

first layer is frappe-nginx where the file exists.

second layer is based on nginx image where file does not exist.

**Comment by premkanish** [comment]
ok @revant ! I will try to build tomorrow as today was doing detailed analysis of helm and docker codes for. erpnext.

**Comment by revant** [comment]
Continue discussion on PR
