### ISSUE TITLE
How to access erpnext from another host on the same local area network

### ISSUE THREAD

**Issue by mfissehaye** [frappe/frappe_docker#340]
I have the docker container up and running using the instructions under [Single Bench](https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md).

Now my site is accessible as wgga.localhost from the same host. However when I try to access the app from another computer on the same local area network using the ip address of the host machine (192.168.0.107), it doesn't work. I also tried adding the entry into hosts file (pointing wgga.localhost to 192.168.0.107) in the other machine with no luck.

I am guessing there can be some configuration to be done in the traefic docker-compose.yml or somehow determine the IP address of the docker container. How do I do that?

**Comment by revant** [comment]
don't name site localhost. Try different name and then edit etc/hosts for all machines trying to access the site.

Or setup dns server

https://github.com/frappe/frappe_docker/issues/172#issuecomment-604160008

**Comment by bestkid1234** [comment]
Hi @revant I am struggling with same problem. I set up the ERPNext in `docker` in production mode. There is my `.env` :
```
LETSENCRYPT_EMAIL=admin@<mycompany>.ro
ERPNEXT_VERSION=edge
FRAPPE_VERSION=edge
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=admin
SITE_NAME=erp.<mycompany>.ro
SITES=`erp.<mycompany>.ro`
DB_ROOT_USER=root
ADMIN_PASSWORD=<myadminpass>
INSTALL_APPS=erpnext
ENTRYPOINT_LABEL=traefik.http.routers.erpnext-nginx.entrypoints=websecure
CERT_RESOLVER_LABEL=traefik.http.routers.erpnext-nginx.tls.certresolver=myresolver
HTTPS_REDIRECT_RULE_LABEL=traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
HTTPS_REDIRECT_ENTRYPOINT_LABEL=traefik.http.routers.http-catchall.entrypoints=web
HTTPS_REDIRECT_MIDDLEWARE_LABEL=traefik.http.routers.http-catchall.middlewares=redirect-to-https
HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL=traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
```

The container is on a Ubuntu Server v18 VM. How can I access the ERP from LAN? I tried with the local ip of VM or the site name(erp.<mycompany>.ro) but no luck.

**Comment by mfissehaye** [comment]
Removing the localhost in the name fixed the issue. I want to understand why though.
Thank you.

**Comment by bestkid1234** [comment]
> Removing the localhost in the name fixed the issue. I want to understand why though.
> Thank you.

@mfissehaye what name did you gave to your site?

**Comment by revant** [comment]
> I want to understand why though.

May be because of
https://forums.docker.com/t/understanding-the-docker-for-mac-localhost-behavior/41921/4
https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06

**Comment by mfissehaye** [comment]
> > Removing the localhost in the name fixed the issue. I want to understand why though.
> > Thank you.
> 
> @mfissehaye what name did you gave to your site?

All I did was change the name to `wgga.com` instead of `wgga.localhost` and added that entry to /etc/hosts in the remote machines. That's the only change I made.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/wiki/Port-Based-Multi-Tenancy try this

**Comment by ChillarAnand** [comment]
> https://github.com/frappe/frappe_docker/wiki/Port-Based-Multi-Tenancy try this

Updated link: https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md
