### ISSUE TITLE
I clone the erpNext code and commit it to my Git repository

### ISSUE THREAD

**Issue by shuairobin** [frappe/frappe_docker#342]
I clone the erpNext code and commit it to my Git repository. After installing erpNext, how can the name be changed?After I changed the module, the installation will be prompted that the module with my name cannot be found

**Comment by revant** [comment]
### Steps for Frappe and ERPNext forks

Fork frappe_docker and change following files to your respective fork urls:

```
❯ grep -RH "github.com/frappe/" ./build/*
./build/erpnext-nginx/install_app.sh:git clone --depth 1 https://github.com/frappe/frappe ${BRANCH}
./build/erpnext-nginx/Dockerfile:RUN /install_app erpnext https://github.com/frappe/erpnext ${GIT_BRANCH}
./build/erpnext-worker/Dockerfile:RUN install_app erpnext https://github.com/frappe/erpnext ${GIT_BRANCH}
./build/frappe-nginx/Dockerfile:    && git clone --depth 1 https://github.com/frappe/frappe --branch $GIT_BRANCH
./build/frappe-nginx/Dockerfile:RUN git clone --depth 1 https://github.com/frappe/bench /tmp/bench \
./build/frappe-worker/Dockerfile:    && git clone --depth 1 -o upstream https://github.com/frappe/frappe --branch ${GIT_BRANCH} \
```

Create your own pipeline for building and publishing images to image registry. e.g. docker hub

For development setup add `--frappe-path` and `--frappe-branch` to your command:

```
bench init --skip-redis-config-generation --frappe-branch version-12 --frappe-branch <code-branch> --frappe-path https://github.com/user/frappe frappe-bench

```

Note:

- do not use `<` and `>` in your command
- replace `<code-branch>` with branch on your repository where the custom code is
- replace `https://github.com/user/frappe` with your own repository.

**Comment by shuairobin** [comment]
That seems a little complicated. Is there any other way?If I want to customize the ERPNext UI interface translation.For example, can I install ERPNext on an app I created myself?

**Comment by revant** [comment]
Yes you can install multiple apps along with ERPNext

**Comment by shuairobin** [comment]
Can you tell me how to do it?
Q: Will it help to understand Frappe framework if I want to learn Flask?

**Comment by shuairobin** [comment]
Can you tell me how to do it?
Q: Will it help to understand Frappe framework if I want to learn Flask?

**Comment by shuairobin** [comment]
Can you tell me how to do it?
Q: Will it help to understand Frappe framework if I want to learn Flask?

**Comment by revant** [comment]
> Will it help to understand Frappe framework if I want to learn Flask?

It is not related to frappe_docker. Check tutorials and forum.
