### ISSUE TITLE
Setting up erpnext on digital ocean droplet gives 500 Internal Server Error.

### ISSUE THREAD

**Issue by mfissehaye** [frappe/frappe_docker#343]
I am trying to setup erpnext on my digital ocean droplet by following the instructions on the [Multi Bench](https://github.com/frappe/frappe_docker/blob/develop/docs/multi-bench.md) section. Frappe and erpnext installed successfully. I have a couple of domains attached to my droplet and my .env file has `SITE_NAME=mydomain.com` and `SITES=erp.mydomain.com,erp2.mydomain.com`. I am hoping that I should be able to access my site at `erp.mydomain.com`.

However when I access the site I am getting 500 Internal server error. I have checked that there is no separate nginx service running on my droplet. I have also checked the logs for every container and I couldn't find any helpful information. On the `
docker-compose-letsencrypt-nginx-proxy-companion` containers I am only getting access logs which show me that the response is 500 error. However I can't access the error logs.

Is there a way to find out what's going wrong?

Thank you.

**Comment by revant** [comment]
I'd recommend to use docker swarm setup it also gives you portainer gui.

Any log in python container?

Try restarting nginx-letsencrypt containers?

**Comment by mfissehaye** [comment]
> I'd recommend to use docker swarm setup it also gives you portainer gui.
> 
> Any log in python container?
> 
> Try restarting nginx-letsencrypt containers?

Thank you. I am following the docs using Swarm mode and I have setup traefik and portainer. However when I try to create a container after having created a stack, I can't find the volume `frappe-bench-v12_sites_vol`. When I look for it in the dropdown for volume while creating a container, it doesn't exist. Why is the volume not created, I tried recreating the stack but no luck.

**Comment by revant** [comment]
volumes are created as part of this stack

https://github.com/frappe/frappe_docker/blob/develop/docs/docker-swarm.md#deploy-frappeerpnext

anything you missed? 


may not be related, which kernel are you using? Recently I was not able to set it up on Scaleway on ubuntu 20.04 because they provide kvm kernel by default for their ubuntu latest vps(s). DO droplet had generic kernel and it works as expected on DO.

**Comment by mfissehaye** [comment]
I made sure that the configuration is the same as provided [here](https://github.com/frappe/frappe_docker/blob/develop/docs/docker-swarm.md#deploy-frappeerpnext). My droplet has Ubuntu 20.04, but I don't know about kernel and stuff.

**Comment by mfissehaye** [comment]
Also the containers that are using the `frappe-bench-v12_erpnext-worker-default`  `frappe-bench-v12_erpnext-worker-short`  `frappe-bench-v12_erpnext-worker-long` and `frappe-bench-v12_frappe-schedule`  are not created. At least I can't see them in the portainer dashboard.

**Comment by revant** [comment]
I'm currently running 6 production sites using docker swarm, traefik and portainer on DO. I'm not able to reproduce this

![my-volumes](https://user-images.githubusercontent.com/1040161/92352557-fe2c6000-f0fb-11ea-8d04-2168ae3c30b7.png)

**Comment by revant** [comment]
Re open if necessary
