### ISSUE TITLE
For ERPNext custom app image, is it necessary to put RUN /install_app erpnext ?

### ISSUE THREAD

**Issue by ceefour** [frappe/frappe_docker#345]
In https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md , I noticed that:

```
RUN /install_app [custom] https://github.com/[username]/[custom] [branch]
```

However the original Dockerfile is:

```
RUN /install_app erpnext https://github.com/frappe/erpnext ${GIT_BRANCH}
...
RUN echo "erpnext" >> /var/www/html/apps.txt
```

I can understand for Frappe app.

But if this is for building image with ERPNext + custom app, should we `RUN /install_app erpnext ...` before installing our own custom app? (and respectively, `RUN echo "erpnext" >> /var/www/html/apps.txt` before adding our own app to `apps.txt`)

**Comment by revant** [comment]
I don't think it's needed if the base image is ERPNext.
Base image will already have ERPNext installed.

**Comment by ceefour** [comment]
The base image is bitnami/node:

```
FROM bitnami/node:12-prod

COPY build/[custom]-nginx/install_app.sh /install_app

RUN /install_app [custom] https://github.com/[username]/[custom] [branch]

FROM frappe/erpnext-nginx:edge

COPY --from=0 /home/frappe/frappe-bench/sites/ /var/www/html/
COPY --from=0 /rsync /rsync
RUN echo -n "\n[custom]" >> /var/www/html/apps.txt

VOLUME [ "/assets" ]

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
```

I just confirmed that just using that, my image is missing some assets like erpnext.min.js, logo, etc.

After I added installation of erpnext using RUN before, then it works.

But I am not sure what is proper way, e.g. By using the erpnext-nginx as base image instead of bitnami/node.

I suggest that documentation should be updated to add instructions for erpnext app not just frappe.

**Comment by revant** [comment]
I really don't use custom apps. If you find any solution, send PR or update docs. 

I think Frappe is not a microservices friendly framework if you need custom apps in cloud native environment.

**Comment by revant** [comment]
Closing this, send fix of you're sure about it.
