### ISSUE TITLE
ERROR: The Compose file '.\docker-compose.yml' is invalid because: services.traefik.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', '', '', '', ''] services.erpnext-nginx.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', 'traefik.http.routers.erpnext-nginx.rule=Host()', '', '', 'traefik.http.services.erpnext-nginx.loadbalancer.server.port=80']

### ISSUE THREAD

**Issue by michaelfouad** [frappe/frappe_docker#347]
## Description of the issue
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.traefik.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', '', '', '', '']
services.erpnext-nginx.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', 'traefik.http.routers.erpnext-nginx.rule=Host()', '', '', 'traefik.http.services.erpnext-nginx.loadbalancer.server.port=80']
## Steps to reproduce the issue

1. docker-compose up

### Stacktrace / full error message if available
ERROR: The Compose file '.\docker-compose.yml' is invalid because: services.traefik.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', '', '', '', ''] services.erpnext-nginx.labels contains non-unique items, please remove duplicates from ['traefik.enable=true', 'traefik.http.routers.erpnext-nginx.rule=Host()', '', '', 'traefik.http.services.erpnext-nginx.loadbalancer.server.port=80']

**Comment by revant** [comment]
Copy / create the .env file first.

Docs mention that step.

**Comment by Davincible** [comment]
the docs mention to either copy `env-production` or `env-example`, for production and localsetup respectively, but when copying `env-example` it gives this error. So either the documentation is incomplete or `env-example` needs to changed

**Comment by Traace** [comment]
Bug still exists... but its marked as closed...

**Comment by mboy1011** [comment]
@Traace 
Install Frappe
1. Open your Terminal and Clone the repository on the path working directory you're right now.
`git clone https://github.com/frappe/frappe_docker.git`
2. Change the directory on your terminal to frappe_docker.
`cd frappe_docker`
3. Copy the environment you're trying to work on e.g. env-product or env-local as .env file to frappe_docker root directory.
`cp env-local ./.env`
4. Execute the Docker Compose command.
`docker-compose up -d`
5. Open your Browser enter the url: [http://mysite.localhost/](url)

I hope it re-solves your problem.
