### ISSUE TITLE
incorrect version of wkhtmltopdf installed

### ISSUE THREAD

**Issue by sagarvora** [frappe/frappe_docker#35]
need to install wkhtmltopdf manually from this url:
https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz

reasons:
 - patched qt required
 - bug in wkhtmltopdf 0.12.4

**Comment by chabad360** [comment]
Please close, since as of #84 this is no longer relevant.
