### ISSUE TITLE
unable to run erpnext with custom ports / ip

### ISSUE THREAD

**Issue by CristianPi** [frappe/frappe_docker#354]
**Is your feature request related to a problem? Please describe.**
There is no clear way to run erpnext docker compose with custom ip / ports.
I have a server with multiple network Interface (multiple ips) it would be nice to be able to configure the docker compose
imposing the ip (ex: 10.10.xx.xx) instead of the default of 0.0.0.0 (listen to all interface).
This apply to every components (nginx, python server, redis instances).
Also i'm using podman and with a shared network i'm unable to start the redis instance because the python files search for a fixed ip (redis-cache:xxx) instead of being configurable

**Comment by revant** [comment]
> python files search for a fixed ip (redis-cache:xxx)

frappe framework searches for keys mentioned in common_site_config.json

if you need specific IP pass any other ip/hostname as env var to erpnext-python container and it'll generate common_site_config.json on first run.

if common_site_config.json is already created change the keys to hostname/ip needed. https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#edit-configs
