### ISSUE TITLE
erpnext-python returns 404 on clean install

### ISSUE THREAD

**Issue by Killili** [frappe/frappe_docker#355]
## Description of the issue
Can access the app after install.
I traced it back into the erpnext-python container. So erpnext-nginx seems to work

## Context information (for bug reports)

- Subdomain erpnext.[domain].de is Setup and running
- There is already an nginx+lets-encrypt-companion running so i do not need to publish the port just have nginx in the erpnext network. 

## Steps to reproduce the issue

1. setup .env
>ERPNEXT_VERSION=edge
>FRAPPE_VERSION=edge
>MARIADB_HOST=mariadb
>MYSQL_ROOT_PASSWORD=admin
>SITES=erpnext.[domain].de
>LETSENCRYPT_EMAIL=admin@[domain].de
2. 
>docker-compose --project-name erpnext -f installation/docker-compose-common.yml -f installation/docker-compose-erpnext.yml    up -d
3.
>curl erpnext.[domain].de -o -
>.... 404 ... erpnext.[domain].de not found

**Comment by revant** [comment]
> docker-compose --project-name erpnext -f installation/docker-compose-common.yml -f installation/docker-compose-erpnext.yml up -d

also use docker-compose-networks.yml, it is used to set the default network to `webproxy` which is needed for nginx+lets-encrypt-companion to work.

https://github.com/frappe/frappe_docker/blob/develop/installation/docker-compose-networks.yml

**Comment by Killili** [comment]
Thanks for the fast reply. 

I setup nginx+lets_enc externally and then made the default network created by the docker-compose script accessable to it.
And as far as i can see that works already.

I can access the nginx-erpnext proxy from outside without any problems, but if i do a 
>docker exec -it erpnext_erpnext-python_1 /bin/bash
to get into the container and then execute
>curl localhost:8000 
i get the same 404 message.
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>localhost does not exist</p>
```

So the setup look like this
```
nginx+le -(proxypass)-> erpnext-nginx -(proxypass)-> erpnext-python
```
and it works till i ask gunicorn for data inside erpnext-python

Does it expect a special hostname?

**Comment by Killili** [comment]
```nginx
location / {
        rewrite ^(.+)/$ $1 permanent;
        rewrite ^(.+)/index\.html$ $1 permanent;
        rewrite ^(.+)\.html$ $1 permanent;

        location ~ ^/files/.*.(htm|html|svg|xml) {
                add_header Content-disposition "attachment";
                try_files /sites/$http_host/public/$uri @webserver;
        }

        try_files /sites/$http_host/public/$uri @webserver;
    }
```

I checked inside erpnext-python and could not locate anything matching ```/sites/$http_host/public/$uri```
$http_host being erpnext.[my-domain].de

**Comment by revant** [comment]
> curl localhost:8000

it won't work. sites in python container, located at /home/frappe/frappe-bench/sites only resolve.

so `curl site.name.de:8000` with `--header "Host: site.name.de"` or `--resolve` or `--connect-to`

refer this issue https://github.com/frappe/frappe_docker/issues/182#issuecomment-609899924

**Comment by Killili** [comment]
Sure, i figured that much out myself. But there is nothing in there to resolve to ...
```
root@[erpnext-python]:/home/frappe/frappe-bench/sites# ls -la
total 28
drwxr-xr-x 3 frappe frappe 4096 Sep 28 09:20 .
drwxr-xr-x 1 frappe frappe 4096 Sep 27 14:48 ..
-rw-r--r-- 1 root   root      0 Sep 27 14:57 .build
-rw-r--r-- 1 frappe frappe  182 Sep 28 09:20 app_versions.json
-rw-r--r-- 1 root   root     15 Sep 28 09:20 apps.txt
drwxr-xr-x 6 root   root   4096 Sep 28 09:20 assets
-rw-r--r-- 1 frappe frappe  224 Sep 28 09:20 common_site_config.json
```

**Comment by revant** [comment]
try to create a new site.
https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#setup-new-site

**Comment by Killili** [comment]
Ok, that did the trick. Thanks.

I got confused by all the talk about frappe. Maybe it would be a good idea to split this two projects more cleanly. 
As a person who does not know the project it is very confusing to read about both, not knowing what is what.
I expected the ERP System to just get up an running and not to install a web framework and then install the ERP on top.

But thanks again.
