### ISSUE TITLE
docker swarm mail ports

### ISSUE THREAD

**Issue by EjjE101** [frappe/frappe_docker#366]
how do i open ports to enable use of imap and smtp inside docker

**Comment by revant** [comment]
Frappe does not run any mail service.

**Comment by EjjE101** [comment]
i mean for frappe/erpnext to send emails there need to be ports opened in the traefik and docker container.

**Comment by revant** [comment]
No ports need to be open to send email.

Configure 'Email Account' doctype an with any external email service with SMTP/IMAP or POP3 credentials.

**Comment by EjjE101** [comment]
@revant you where right thank you for your help!!
