### ISSUE TITLE
How to change port 9000 to another port ?

### ISSUE THREAD

**Issue by machineska** [frappe/frappe_docker#370]
Hi.. I want to running multiple container to simulate different multiple machine in production. So in my local computer for development I run two docker stack.
I just succeed to run another stack at 8080 port for the web, but i'm confused how to change port 9000 (I guess this port was belong to socketio) to another port.

So.. what should I do to make this happen?

**Comment by revant** [comment]
you can expose only these ports, or you need to change it for your need.

https://github.com/frappe/frappe_docker/blob/develop/devcontainer-example/docker-compose.yml#L36

All the ports config for socketio and gunicorn is in common_site_config.json

**Comment by revant** [comment]
reopen if needed
