### ISSUE TITLE
instatll erpnext on docker 

### ISSUE THREAD

**Issue by zxc916684603** [frappe/frappe_docker#375]
## Steps to reproduce the issue

1.  78b1a54222d9        frappe/erpnext-worker:edge    "docker-entrypoint.s…"   8 seconds ago       Exited (1) 5 seconds ago                                              frappe_docker_site-creator_1

2. docker logs 047f7258863e
3. PermissionError: [Errno 13] Permission denied: './erp.example.com'

### Stacktrace / full error message if available
I'M working on centos7.8   
```
(paste here)
```

**Comment by revant** [comment]
I am not able to reproduce the issue.

Also tests are not showing such error.

I don't know where to start looking for error.

**Comment by revant** [comment]
Re-open if needed
