### ISSUE TITLE
Error when open custom script

### ISSUE THREAD

**Issue by szufisher** [frappe/frappe_docker#377]
## Steps to reproduce the issue

1. successfully installed version-12
2. docker-compose --project-name xx up -d
3. login and complete setup wizard
4. go to custom script

### Observed result

FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/node_modules/ace-builds/src-min-noconflict/ace.js'

![image](https://user-images.githubusercontent.com/12823863/98006134-db34d880-1e2c-11eb-8a4d-ce506423a7ab.png)

the script edit box is not shown.

### Expected result
no error, script edit box is available for maintaining custom script.
### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
check file permissions for mounted volumes and restart the containers. the asset need to be copied from erpnext-nginx container to the sites volume.

**Comment by revant** [comment]
re-open if needed
