### ISSUE TITLE
MariaDB has wrong character encoding

### ISSUE THREAD

**Issue by Mutantpenguin** [frappe/frappe_docker#379]
After exactly following all the previous steps of the README  without any error, the step for creating a site fails.

Command: ``bench new-site site1.local``

Error:
``For key character_set_server. Expected value utf8mb4, found value latin1``
``For key collation_server. Expected value utf8mb4_unicode_ci, found value latin1_swedish_ci``

I think I found the underlying issue and was able to fix it in my environment, I just don't know enough about docker to propose a real solution:
* I opened a console to the mariadb container and started "mysql".
* I was then greeted with the message ``Warning: World-writable config file "/etc/mysql/conf.d/frappe.cnf" is ignored``
* Setting different access restrictions with ``chmod 755 /etc/mysql/conf.d/frappe.cnf`` fixed the problem
* Now I can successfully create a new site.

Would be great if this could be done automatically when setting up the container for mariadb.

**Comment by revant** [comment]
If it's windows based installation, try to make the .cnf file read only

**Comment by revant** [comment]
re-open if necessary
