### ISSUE TITLE
urllib3 1.23 error

### ISSUE THREAD

**Issue by mslake** [frappe/frappe_docker#38]
/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

**Comment by codingCoffee** [comment]
It's just a warning and not an error, and not in any way related to this repo. Closing
