### ISSUE TITLE
How to install custom app on already 3 Month old deployed Erpnext App

### ISSUE THREAD

**Issue by iamkhalidbashir** [frappe/frappe_docker#384]
I have successfully installed my custom app on a completely new install of erpnext using this repo (frappe_docker) but I cannot install on the already 3-month-old erpnext container (which already has a very huge amount of data)

**Comment by Thunderbottom** [comment]
Assuming that you're running your instance using `docker-compose`, one way of doing this would be to:

1. [Back up your sites](https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#backup-sites) from within the container. (Just in case something goes wrong, always good to have backups).
2. Stop your docker-compose setup.
3. Change the ERPNext image name/tag to the newer image with your custom application. Set `AUTO_MIGRATE=1` in your compose file.
4. `docker-compose up -d`
5. [Install the custom application](https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#frappe-internal-commands-using-bench-helper) on your existing site.

If you don't use `docker-compose`, you'll need to take a backup of your sites, stop your instance, spin up a new instance with your custom application's image, and [restore the database](https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#restore-backups) on that instance.

**Comment by iamkhalidbashir** [comment]
Thanks @Thunderbottom for replying quickly.
But I know all steps mentioned above but that dosent work because I am stuck at step 5
"5. [Install the custom application](https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#frappe-internal-commands-using-bench-helper) on your existing site."

What command of the bench should I use to install the application?

The ones mentioned on frappe/bench repo doesn't work as get-app is not an option for the bench_helper.py included in the frappe/frappe-worker container

**Comment by iamkhalidbashir** [comment]
Ok **resolved it!**
this is how I did it:-
Make sure you have your app installed at `/home/frappe/frappe-bench/apps` in the docker container
then use this to install the app
`bench --site erp.os.amoxt.com install-app [custom-app-name]`

Note: **[custom-app-name]** is the directory name of the custom app at `/home/frappe/frappe-bench/apps`
