### ISSUE TITLE
docker production installation internal server error

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#390]
https://discuss.erpnext.com/t/docker-production-installation-internal-server-error/68910

![output](https://user-images.githubusercontent.com/1040161/102179863-e835f480-3ecd-11eb-8034-41bc317b40cf.gif)

Wait for site-creator container to complete or it'll show "Internal Server Error"

**Comment by edmsamuel** [comment]
Hello @revant , i have the same problem, were you able to fix it?
