### ISSUE TITLE
Default install failing...

### ISSUE THREAD

**Issue by mmangione** [frappe/frappe_docker#392]
This should be really quick. On the single bench docker-compose install, the correct user is not inserted into the mysqldb and given permissions.

`pymysql.err.OperationalError: (1045, "Access denied for user '_787d6c84940ca009'@'172.29.0.6' (using password: YES)")`

I have to go into the mariadb docker instance and run:

`GRANT ALL PRIVILEGES ON *.* to '_787d6c84940ca009'@'%';`

Then restart docker-compose. Of course, the username changes every time - so this is a manual process.

**Comment by Lukse** [comment]
Can confirm bug. @mmangione, thank you for temporary solution!

**Comment by Thunderbottom** [comment]
Seems like the commit https://github.com/frappe/frappe_docker/commit/fc36666d272a33266952f42a1ee2e576079fd350 made in #381 may have caused this issue. Could you send a PR to fix it?

**Comment by revant** [comment]
I tried it in pwd

```
$ docker logs frappe_docker_site-creator_1 -f
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 4 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _69928f0f6369849a
Created database _69928f0f6369849a
Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***
```

Site got created successfully. I couldn't reproduce the issue.
Also last cron tests seem to work without this error https://travis-ci.com/github/frappe/frappe_docker/jobs/464800851

If you find any fix do send a PR.

**Comment by nartya** [comment]
Hi, I got a slightly different problem. I followed all the instructions but when I run " docker-compose up -d ", I don't see the frappe_docker_site-creator_1 service running and on the web I got a 500 error code. When I run " docker logs frappe_docker_site-creator_1 -f " I got the following lines in my screenshot. I don't know what I should modify in the docker instance.
![okok](https://user-images.githubusercontent.com/35570611/103159524-cb9d9480-47ca-11eb-9485-a6d88919151e.PNG)

**Comment by revant** [comment]
By looking at the last line I think something to do with docker networking? I don't know exactly. I'm out of ideas.

I am somehow always lucky with manual install, PWD, single bench, multi bench, tests and helm charts when I try them.

**Comment by revant** [comment]
I'm out of ideas. My setup is working, PWD is working, last ci run for daily tests worked.

**Comment by nartya** [comment]
Me too. I got those errors in the screenshot above when I run " docker-compose up -d " for the first time. When I run it again, It only tries to restart site-creator service, It says it's done but the service stops automatically then when I check again the logs I got this. My site already exists but I still got an internal error in my browser.
![Capture](https://user-images.githubusercontent.com/35570611/103217076-006b3200-4918-11eb-9677-9f654962c8d7.PNG)

**Comment by revant** [comment]
> Me too. I got those errors in the screenshot above when I run " docker-compose up -d " for the first time. When I run it again, It only tries to restart site-creator service, It says it's done but the service stops automatically then when I check again the logs I got this. My site already exists but I still got an internal error in my browser.
> ![Capture](https://user-images.githubusercontent.com/35570611/103217076-006b3200-4918-11eb-9677-9f654962c8d7.PNG)

Add `FORCE=1` to site-creator container. it'll force create site even if the directory is found. Remember to remove it after site creation, or it'll re-create/reset fresh site on every docker-compose up/restart and wipe site data.

**Comment by nartya** [comment]
Sorry I'm not used to work with docker containers. I don't know where to find it and how to add "force=1"

**Comment by mmangione** [comment]
> I tried it in pwd
> 
> ```
> $ docker logs frappe_docker_site-creator_1 -f
> Attempt 1 to connect to mariadb:3306
> Attempt 2 to connect to mariadb:3306
> Attempt 3 to connect to mariadb:3306
> Attempt 4 to connect to mariadb:3306
> Attempt 1 to connect to redis-queue:6379
> Attempt 1 to connect to redis-cache:6379
> Attempt 1 to connect to redis-socketio:6379
> Connections OK
> Created user _69928f0f6369849a
> Created database _69928f0f6369849a
> Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
> Starting database import...
> Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql
> 
> Installing frappe...
> Updating DocTypes for frappe        : [========================================] 100%
> Updating country info               : [========================================] 100%
> 
> Installing erpnext...
> Updating DocTypes for erpnext       : [========================================] 100%
> clearing...
> clearing...
> clearing...
> clearing...
> clearing...
> clearing...
> clearing...
> clearing...
> Updating customizations for Address
> Updating customizations for Contact
> *** Scheduler is disabled ***
> ```
> 
> Site got created successfully. I couldn't reproduce the issue.
> Also last cron tests seem to work without this error https://travis-ci.com/github/frappe/frappe_docker/jobs/464800851
> 
> If you find any fix do send a PR.

I will try this right now. Sorry for the delay. It's been a busy holiday season.

**Comment by revant** [comment]
Not clean clone, just used the PWD link, It takes a pwd.yaml for docker stack,

https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/frappe/frappe_docker/develop/tests/pwd.yml

**Comment by revant** [comment]
Someone will re-open soon.

**Comment by dianhenglau** [comment]
I encountered the same problem (500 Internal Error) today while trying to install single bench with local setup.

Steps to reproduce the error: Clone the project, `cd` into it, `cp env-local .env`, then `docker-compose up -d`.

This is what I got for running `docker logs frappe_docker_site-creator_1 -f`:

```
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _69928f0f6369849a
Created database _69928f0f6369849a
Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
For key character_set_server. Expected value utf8mb4, found value latin1
For key collation_server. Expected value utf8mb4_unicode_ci, found value latin1_swedish_ci
================================================================================
Creation of your site - mysite.localhost failed because MariaDB is not properly
configured.  If using version 10.2.x or earlier, make sure you use the
the Barracuda storage engine.

Please verify the settings above in MariaDB's my.cnf.  Restart MariaDB.  And
then run `bench new-site mysite.localhost` again.


================================================================================
Database settings do not match expected values; stopping database setup.
```

So the problem is mariadb's character set and collation.

According to [this comment](https://github.com/frappe/frappe_docker/issues/303#issuecomment-673766430), as a workaround, add `command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']` to `docker-compose.yml` under `mariadb`, like this:

```yaml
  mariadb:
    image: mariadb:10.3
    restart: on-failure
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']
    # ...
```

After that, run `docker-composer down`, `docker volume prune` (**Note that this will remove all volume not used by any container**) and `systemctl restart docker`. Then run `docker-compose up -d` again. Now the result of running `docker logs frappe_docker_site-creator_1 -f` become:

```
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _69928f0f6369849a
Created database _69928f0f6369849a
Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***
```

and opening `mysite.localhost` in browser will show the ERP system running.

However, I'm not sure why mariadb didn't pick up `/etc/mysql/conf.d/frappe.cnf` setting inside the container.

Environment:

- archlinux
- `Docker version 20.10.2, build 2291f610ae`
- `docker-compose version 1.27.4, build unknown`

**Comment by revant** [comment]
I can't figure out why. Just a guess, may be something to do with file permissions?

For Play With Docker, I can't mount files, So I'm using additional containers to create files 

https://raw.githubusercontent.com/frappe/frappe_docker/develop/tests/pwd.yml

**Comment by Davincible** [comment]
@revant Same here, tried it on an Ubuntu 20.04 server and my Manjaro desktop. Both times I get the issue with the specific user "_69928f0f6369849a". I've also seen another user come by that was also denied

**Comment by Luk164** [comment]
Same issue just occurred to me. The `command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']` workaround worked for me.

**Comment by JemCdo** [comment]
Same issue just occurred to me. The command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake'] worked for me too.
