### ISSUE TITLE
v13 beta 7 not uploaded to dockerhub

### ISSUE THREAD

**Issue by deantheiceman** [frappe/frappe_docker#394]
## Description of the issue

With the release of https://github.com/frappe/erpnext/releases/tag/v13.0.0-beta.7

The relevent docker image hasn't been built and pushed to dockerhub

**Comment by revant** [comment]
betas are not automated, only stable releases are automated.

I've triggered the master branch pipeline again. https://travis-ci.com/github/frappe/frappe_docker/builds/210047708

Hope the right tags get generated. I've seen they messed up tags before.

**Comment by revant** [comment]
As I expected!

They messed up with versions again!

https://hub.docker.com/layers/frappe/frappe-socketio/v13.0.1-beta.1/images/sha256-a533fbfd34cbd386bc13851d9635f06e98e3224835b91fdcc77ae717140e07e4?context=repo

now we've 13.0.1-beta.1 as image tag.

I don't know whom and how to teach basics?
