### ISSUE TITLE
http://site_name shows http 404 after installation

### ISSUE THREAD

**Issue by christf** [frappe/frappe_docker#395]
## Description of the issue
After running the steps from single-bench.md the installation succeeds but calling http://hostname yields a http 404 error.

## Context information (for bug reports)

this is erpnext version 12 and frappe version 12

## Steps to reproduce the issue

run steps from single-bench.sh with SITE_NAME=pt-docker-2.localhost

## Logs from site_creator
```
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 4 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _633d806023649803
Created database _633d806023649803
Granted privileges to user _633d806023649803 and database _633d806023649803
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
clearing...
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***

```

## logs of mariadb container

```
Version: '10.3.27-MariaDB-1:10.3.27+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2020-12-29 16:32:26 14 [Warning] Access denied for user 'frappe'@'172.19.0.12' (using password: NO)
2020-12-29 16:32:26 15 [Warning] 'proxies_priv' entry '@% root@8f8d21dca0ec' ignored in --skip-name-resolve mode.
2020-12-29 16:32:29 16 [Warning] Aborted connection 16 to db: '_633d806023649803' user: '_633d806023649803' host: '172.19.0.12' (Got an error reading communication packets)
2020-12-29 16:33:25 19 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:34:25 20 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:35:25 21 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:36:25 22 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:37:25 23 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:38:25 24 [Warning] Access denied for user '_633d806023649803'@'172.19.0.10' (using password: YES)
2020-12-29 16:38:30 25 [Warning] 'proxies_priv' entry '@% root@8f8d21dca0ec' ignored in --skip-name-resolve mode.
2020-12-29 16:38:30 26 [Warning] 'proxies_priv' entry '@% root@8f8d21dca0ec' ignored in --skip-name-resolve mode.
2020-12-29 16:38:31 18 [Warning] Aborted connection 18 to db: '_633d806023649803' user: '_633d806023649803' host: '172.19.0.12' (Got an error reading communication packets)
```

**Comment by christf** [comment]
this *might* be a duplicate to #392

**Comment by revant** [comment]
> calling http://hostname yields a http 404 error.

If trying locally it won't work. Name the site to be sitename.localhost.

Another option is to add hostname in /etc/hosts file pointing to localhost.

Or setup a local dns server and add this set entry in the dns

**Comment by revant** [comment]
Re-open if needed.

Common issue, someone will reopen anyway

**Comment by christf** [comment]
The documentation in the single-bench.md seems to be less than ideal
as the setup actually worked but the error message is difficult to spot.

"The SITE_NAME must be what is entered in the browser and that must be resolvable."

This is a much better way than saying "it must end in .localhost" as the documentation for single-bench setup currently does. "the site names are limited to patterns matching \".localhost by default" so the "Notes" threw me off.


If indeed this is a common issue, maybe it can be avoided in the future.
Raising PR containing what seems to be a doc improvement.

**Comment by christf** [comment]
.. also, what are those access denied errors from? It seems those should not be happening...

**Comment by Thunderbottom** [comment]
> "The SITE_NAME must be what is entered in the browser and that must be resolvable."
>
> There must be a much better way than saying "it must end in .localhost" as the documentation for single-bench setup currently does. "the site names are limited to patterns matching ".localhost by default" so the "Notes" threw me off.

The reason we've made it to be specific is because there's two ways for the site to be resolvable:

1. When the site name ends with `.localhost`.
2. When you add the site to your local DNS registrar or the `/etc/hosts` file.

Now, the only reason to suggest the prior over the latter is to reduce the additional effort required to setup a host and also the clutter in the `/etc/hosts` file. Sometimes people might set up a host mapping and then forget about it, and that might cause some (actual) sites to not work later. Sites ending in `.localhost` prevent all of that since the system knows how to resolve them, and they are only bound to the local domain. From a newcomer's perspective, it is purely to make it easier to set up and access sites.

Although, I do agree that the documentation could have been clearer, thanks for the pull request!

> .. also, what are those access denied errors from? It seems those should not be happening...

Like I said in #392, it could be due to one of the PRs being merged to add MySQL support. You can try reverting that commit locally and then set up the site.
