### ISSUE TITLE
awesomplete.min.js.map 404 (Not Found)

### ISSUE THREAD

**Issue by jonny88** [frappe/frappe_docker#396]
Hey guys, 

I'm very excited to see that there is quite some traction on some official docker image. Good work :) 
I started experimenting with it and after spending quite some time getting familiar with it in a local setup and running into problems with the edge tag, I now switched to v12. Now I was able to complete the setup wizard, but I'm still seeing the following error in the console:

**[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (awesomplete.min.js.map, line 0)**

I tried to find some info about this and it was suggested to call bench build to rebuild assets. What I understood so far is that there is no bench in a production setup and it would also be against the docker philosophy to manually call it inside the container. 

Is there some step missing in the image build? Or what is the recommended way to fix this problem?

Thanks
Jonny

Edit:

I actually tried calling bench build in the python container, but seems, that there are some modules missing:
root@3b023a7d7a53:/home/frappe/frappe-bench# bench build
Please install yarn using below command and try again.
npm install -g yarn

> frappe@ production /home/frappe/frappe-bench/apps/frappe
> FRAPPE_ENV=production node rollup/build.js

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /home/frappe/frappe-bench/apps/frappe/rollup/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/frappe/frappe-bench/apps/frappe/rollup/build.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/frappe/frappe-bench/apps/frappe/rollup/build.js' ]

While experimenting with the running ERPNext instance I again ran into some similar issue (although presented as some frappe error in the browser):
FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/node_modules/ace-builds/src-min-noconflict/ace.js'

**Comment by revant** [comment]
How did you start the services? May be prune the volumes and containers before switching from edge to v12?

Also there is no bench development setup in production images.

There is a separate image for development called frappe/bench

**Comment by jonny88** [comment]
Hey revant, thanks for the quick response. I already pruned everything with docker system prune and docker volumes prune, else I think the old volumes would be reused. 

I started the services in a DigitalOcean droplet with `docker-compose up -d`

with this .env file:

LETSENCRYPT_EMAIL=mail@my-company.com
ERPNEXT_VERSION=v12
FRAPPE_VERSION=v12
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=admin
SITE_NAME=erp.my-company.localhost
SITES=`erp.my-company.localhost`
DB_ROOT_USER=root
ADMIN_PASSWORD=admin
INSTALL_APPS=erpnext
ENTRYPOINT_LABEL=traefik.http.routers.erpnext-nginx.entrypoints=web
CERT_RESOLVER_LABEL=erpnext.local.no-cert-resolver
HTTPS_REDIRECT_RULE_LABEL=erpnext.local.no-redirect-rule
HTTPS_REDIRECT_ENTRYPOINT_LABEL=erpnext.local.no-entrypoint
HTTPS_REDIRECT_MIDDLEWARE_LABEL=erpnext.local.no-middleware
HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL=erpnext.local-no-redirect-middleware


On my local machine I've added a mapping of the site's name to the ip address of the droplet in the /etc/hosts file, else I would get an 404 error by nginx or gunicorn?

I went into the container via:

`docker exec -it frappe_docker_erpnext-python_1 bash`

if I search for awesomplete, I can also not find any 'awesomplete.min.js.map':
root@3b023a7d7a53:/home/frappe/frappe-bench# find . | grep awesomplete
./apps/frappe/frappe/public/less/awesomplete.less
./apps/frappe/frappe/public/js/lib/awesomplete
./apps/frappe/frappe/public/js/lib/awesomplete/awesomplete.min.js
./apps/frappe/frappe/public/js/lib/awesomplete/awesomplete.css

On the other hand, I'm also not sure, if it is expected to be there. I checked in our production version (v8 - I know .. it is about time to move on ;)), which is running also in some self stitched together docker container and I couldn't find it there either. 

I just loaded /desk again and I'm actually seeing two errors, maybe they are related:
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (desk, line 13)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (awesomplete.min.js.map, line 0)

A quick google search tells, that these map files are for debugging and they allow to map to the originating source files, so maybe they should really not be there in production, but the question is why the browser tries to load them?
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

After inspecting it a bit more, I found the comment in `libs.min.js`:
//# sourceMappingURL=awesomplete.min.js.map

Maybe the compiler can be instructed to not generate these comments in a production build? 

Regarding bench, if I'm not mistaken, I'm running the production image and when I jump into the container, I see a bench command - although it has an incomplete command list. Is this unexpected?

`
root@3b023a7d7a53:/home/frappe/frappe-bench# bench
Usage: bench frappe [OPTIONS] COMMAND [ARGS]...

Options:
  --site TEXT
  --profile    Profile
  --verbose    Verbose
  --force      Force
  --help       Show this message and exit.

Commands:
  add-system-manager          Add a new system manager to a site
  add-to-email-queue          Add an email to the Email Queue
  add-to-hosts                Add site to hosts
  backup                      Backup
  browse                      Opens the site on web browser
  build                       Minify + concatenate JS and CSS files, build...
  build-message-files         Build message files for translation
  bulk-rename                 Rename multiple records via CSV file
  clear-cache                 Clear cache, doctype cache and defaults
  clear-website-cache         Clear website cache
  console                     Start ipython console for a site
  data-import                 Import documents in bulk from CSV or XLSX...
  destroy-all-sessions        Clear sessions of all users (logs them out)
  disable-scheduler           Disable scheduler
  disable-user
  doctor                      Get diagnostic info about background workers
  drop-site
  enable-scheduler            Enable scheduler
  execute                     Execute a function
  export-csv                  Export data import template with data for...
  export-doc                  Export a single document to csv
  export-fixtures             Export fixtures
  export-json                 Export doclist as json to the given path, use...
  get-untranslated            Get untranslated strings for language
  import-csv                  Import CSV using data import
  import-doc                  Import (insert/update) doclist.
  import-translations         Update translated strings
  install-app                 Install a new app to site, supports multiple...
  jupyter
  list-apps                   List apps in site
  make-app                    Creates a boilerplate app
  make-demo                   Reinstall site and setup demo
  mariadb                     Enter into mariadb console for a given site.
  migrate                     Run patches, sync schema and rebuild...
  migrate-to                  Migrates site to the specified provider
  mysql                       Deprecated
  new-language                Create lang-code.csv for given app
  new-site                    Create a new site
  postgres                    Enter into postgres console for a given site.
  publish-realtime            Publish realtime event from bench
  purge-jobs                  Purge any pending periodic tasks, if event...
  ready-for-migration
  rebuild-global-search       Setup help table in the current site (called...
  reinstall                   Reinstall site ie.
  reload-doc                  Reload schema for a DocType
  reload-doctype              Reload schema for a DocType
  remove-from-installed-apps  Remove app from site's installed-apps list
  request                     Run a request as an admin
  reset-perms                 Reset permissions for all doctypes
  restore                     Restore site database from an sql file
  run-patch                   Run a particular patch
  run-setup-wizard-ui-test    Run setup wizard UI test
  run-tests                   Run tests
  run-ui-tests                Run UI tests
  schedule
  scheduler
  serve                       Start development web server
  set-admin-password          Set Administrator password for a site
  set-config                  Insert/Update a value in site_config.json
  set-last-active-for-user    Set users last active date to current datetime
  set-maintenance-mode
  setup-global-help           Deprecated: setup help table in a separate...
  setup-help                  Deprecated: Setup help table in the current...
  show-config                 print configuration file
  show-pending-jobs           Get diagnostic info about background jobs
  start-recording
  stop-recording
  trigger-scheduler-event     Trigger a scheduler event
  uninstall-app               Remove app and linked modules from site
  update-translations         Update translated strings
  use                         Set a default site
  version                     Show the versions of all the installed apps
  watch                       Watch and concatenate JS and CSS files as and...
  worker
`

**Comment by revant** [comment]
Bench command in the production image is the bench_helper.py which is part of frappe codebase.
bench_helper has sufficient commands that bench uses to manage sites.

js/css/html assets are part of erpnext-nginx image and are served with reverse proxied gunicorn and socketio.

**Comment by jonny88** [comment]
Ah, ok that makes sense. Thanks for the explanation revant. :)

Do you have some opinion about the map files? Are they expected to be present in the image or is it unexpected that the browser tries to load them? Or would you say the error is fine, I should ignore it? Do you actually also see it on your side?

Thanks
Jonny

**Comment by revant** [comment]
Following from dockerized v13-beta

```
localStorage cleared
desk.js:91 Using this console may allow attackers to impersonate you and steal your information. Do not enter or paste code that you do not understand.
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Delta.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/AttributeMap.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Op.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for webpack://Quill/node_modules/quill-delta/dist/Iterator.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for https://erp.example.com/assets/js/awesomplete.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
frappe-charts.min.esm.js:1 "" is not a valid color.
(anonymous) @ frappe-charts.min.esm.js:1
value @ frappe-charts.min.esm.js:1
e @ frappe-charts.min.esm.js:1
t @ frappe-charts.min.esm.js:1
getChartByType @ frappe-charts.min.esm.js:1
e @ frappe-charts.min.esm.js:1
render @ chart_widget.js:521
(anonymous) @ chart_widget.js:211
Promise.then (async)
fetch_and_update_chart @ chart_widget.js:203
(anonymous) @ chart_widget.js:115
Promise.then (async)
(anonymous) @ dom.js:265
frappe.run_serially @ dom.js:263
(anonymous) @ chart_widget.js:113
Promise.then (async)
make_chart @ chart_widget.js:90
refresh @ chart_widget.js:26
make_widget @ base_widget.js:108
make @ base_widget.js:85
Widget @ base_widget.js:6
ChartWidget @ chart_widget.js:9
frappe.widget.make_widget @ widget_group.js:23
add_widget @ widget_group.js:75
(anonymous) @ widget_group.js:70
make_widgets @ widget_group.js:69
make @ widget_group.js:42
WidgetGroup @ widget_group.js:36
(anonymous) @ desktop.js:340
Promise.then (async)
make_charts @ desktop.js:332
refresh @ desktop.js:244
(anonymous) @ desktop.js:230
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
load (async)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
frappe.request.call @ request.js:220
frappe.call @ request.js:91
get_data @ desktop.js:256
make @ desktop.js:222
reload @ desktop.js:197
DesktopPage @ desktop.js:177
make_page @ desktop.js:160
show_page @ desktop.js:139
route @ desktop.js:26
show @ pageview.js:57
frappe.route @ router.js:70
startup @ desk.js:73
init @ desk.js:29
frappe.start_app @ desk.js:13
(anonymous) @ desk.js:24
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
libs.min.js?ver=1609137764.0:237 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: true, _useUTC: true, _l: undefined, _i: null, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback
```

v12 on non docker, standard bench (from frappe syllabus, errors reportable):

```
localStorage cleared
DevTools failed to load SourceMap: Could not load content for https://erp-v12.example.com/assets/js/awesomplete.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
libs.min.js?ver=1608104743.0:9245 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
libs.min.js?ver=1608104743.0:9254 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

These are production sites, I'm ignoring errors in both cases docker or non docker.

I hope rebrand-ui that is planned in v13 clears the errors and warnings.

**Comment by jonny88** [comment]
Ok thanks for the info. Happy new year :)
