### ISSUE TITLE
TypeError on "Select your Domain"

### ISSUE THREAD

**Issue by MitchellWT** [frappe/frappe_docker#399]
## Description of the issue
After successful installation, during the website setup wizard a TypeError occurs on the 'Select your Domain' page, this error occurs when the 'next' button is selected, halting the setup process.

## Context information (for bug reports)
The installation was done using AWS EC2 running on Ubuntu 20.04.

## Steps to reproduce the issue
1. Perform production installation (single bench).
2. Proceed to complete website setup wizard, until 'Select your Domain' page.
3. Select 'domain' and click 'next' button.

### Observed result
Setup is halted, unable to complete. Webpage does not change or give feedback, aside from the console.

### Expected result
Website setup wizard continues to next step.

### Stacktrace / full error message if available
Image showing web console message:
https://user-images.githubusercontent.com/60099557/103535102-46aa2d80-4ee4-11eb-802c-ea0e10e94fcc.PNG

**Comment by i5o** [comment]
This happens to me too using the develop branch.
The function `strip_html` receives an array instead of a string so it fails to replace.
My solution was to modify the desk.min.js where it says `strip_html = ... e.replace` to `return e` inside the function

**Comment by revant** [comment]
- https://discuss.erpnext.com/t/we-are-not-moving-to-the-next-step-from-select-your-domains/69249
- https://github.com/frappe/erpnext/issues/24190
