### ISSUE TITLE
./dbench init causes 'mariadb' Name or service not known

### ISSUE THREAD

**Issue by yeisonvargasf** [frappe/frappe_docker#40]
When I execute ./dbench init output shows:

`pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on u'mariadb' ([Errno -2] Name or service not known)")`

**Comment by eagleblade** [comment]
You have to change the mariadb image to use in [docker-compose.yml](https://github.com/frappe/frappe_docker/blob/master/docker-compose.yml) from

```
  mariadb:
    image: "mariadb"
```

to

  ```
mariadb:
    image: "mariadb:10.2"
```

This will enable you to set up the containers using the defaults. 

I have tried lots of other stuff, but this seems to be the only valid fix, to install frappe_bench in docker, whit 0 errors.

The reason for this is https://mariadb.com/kb/en/library/xtradbinnodb-file-format/

**Comment by yeisonvargasf** [comment]
Hi @eagleblade, the PR #41 works with mariadb 10.3 :+1:

**Comment by Thunderbottom** [comment]
should be fixed with the latest commits

**Comment by chabad360** [comment]
can this be closed then?

**Comment by khadijazaki** [comment]
getting same error, not solved by specifying the mariadb version

**Comment by chabad360** [comment]
Please make sure you first run `./dbench setup docker` before doing anything else.
