### ISSUE TITLE
Debug mode not work correctly - edit code not update

### ISSUE THREAD

**Issue by GraficheAquilane2021** [frappe/frappe_docker#408]
## Description of the issue
When edit a py file, browser not get the modification if dont restart Bench Web

## Steps to reproduce the issue

1. install docker following this [guide](https://github.com/frappe/frappe_docker/tree/develop/development)
2. enable develop_mode and start Bench Web: _This command starts all processes with the exception of Redis (which is already running in separate container) and the web process. The latter can can finally be started from the debugger tab of VSCode by clicking on the "play" button._
3. edit a py file adding, for example, `frappe.msgprint("hi")`
4. refresh your browser. It doesnt show anything
5. restarting Bench Web 
6. browser show the message

### Observed result
no message showing in the browser

### Expected result
_hi_ message

### Stacktrace / full error message if available
no error appear

**Comment by revant** [comment]
If you use debugger feature auto reload won't work

https://github.com/frappe/erpnext/wiki/VSCode-Debugging-for-Frappe-Python#caveats

**Comment by GraficheAquilane2021** [comment]
@revant, is there a way to get it. Can you link me a guide?

Thanks in advance

**Comment by GraficheAquilane2021** [comment]
@revant i cant enable autoreload. Is there a way to get it? I cant make it works without debugger feature also.

Thanks

**Comment by revant** [comment]
You should have all processes started from procfile.

If you set debugger, documentation says to remove `bench serve`.

To make bench start work again the procfile needs to start  `bench serve`


I'm not able to reproduce this issue on my machine

**Comment by GraficheAquilane2021** [comment]
I solved with this [guide](https://discuss.erpnext.com/t/python-changes-are-not-loaded-local-dev-environment-using-vagrant-osx/42809/30).
