### ISSUE TITLE
frappe/erpnext-worker Dockerfile Source Code

### ISSUE THREAD

**Issue by alihalabyah** [frappe/frappe_docker#411]
Hey guys,

May I know the source code for this `frappe/erpnext-worker` since the `bench` version installed inside of it seems to be very old and as a reference, I'm trying to install Erpnext using helm.

**Comment by revant** [comment]
Bench is not installed in production images.

It is not old bench, it is the restricted part of bench_helper.py, the part of bench which resides in Frappe code.

If bench cli, Frappe and ERPNext is all installed then the image will be more than 3gb.

Why do you need bench in production images?

**Comment by revant** [comment]
Re open if needed

**Comment by alihalabyah** [comment]
@revant Thanks for your answer, I thought it's an old version as it has different commands than the recent bench and moreover you can't see what kind of version if you use `bench version`.

I don't need `bench` in production images, I had a few issues related to creating a new site, I was getting CSS not found issues whenever I try to navigate to the homepage but once I have executed the k8s job again to create the site with force option, the issue was resolved, this might be related to the fact that I have used the `develop` branch, not sure but I saw that you have once published `develop, latest` and some other tags altogether and that indicated all point to the same release, let me know please if that is false.

The Dockerfiles you have mentioned are the ones I was looking at and these don't have actual build instructions, instead, they are like black boxes, see https://github.com/frappe/frappe_docker/blob/develop/build/erpnext-worker/Dockerfile

 Check `FROM ${DOCKER_REGISTRY_PREFIX}/frappe-worker:${GIT_BRANCH}` in this command we still need to rely on something we don't know, How can I built on top or extend ERPNext?
 
 After all, thank you for the exceptional work!
