### ISSUE TITLE
Error: No such command "new-site".

### ISSUE THREAD

**Issue by xmyhhh** [frappe/frappe_docker#413]
### when I type:
frappe@ 9935a0e609ff:/workspace/development$ bench new-site mysite.localhost --mariadb-root-password 123 --admin-password admin --no-mariadb-socket

### I got this error:
Usage: bench [OPTIONS] COMMAND [ARGS]...
Try "bench --help" for help.
Error: No such command "new-site".

### What did I do wrong？？

**Comment by xmyhhh** [comment]
### when I type:
frappe@ 9935a0e609ff:/workspace/development$ bench --help

### I got this below:
Options:
  --version
  --help     Show this message and exit.

Commands:
  backup                   Backup single site
  backup-all-sites         Backup all sites in current bench
  clear-command-cache      Clears Frappe Framework cached commands
  config                   Change bench configuration
  disable-production       Disables production environment for the bench.
  download-translations    Download latest translations
  exclude-app              Exclude app from updating
  find                     Finds benches recursively from location
  generate-command-cache   Caches Frappe Framework commands
  get-app                  Clone an app from the internet or filesystem and...
  include-app              Include app for updating
  init                     Initialize a new bench instance in the specified...
  install                  Install system dependencies for setting up
                           Frappe...
  migrate-env              Migrate Virtual Environment to desired Python...
  new-app                  Create a new Frappe application under apps folder
  pip                      For pip help use `bench pip help [COMMAND]` or...
  prepare-beta-release     Prepare major beta release from develop branch
  release                  Release a Frappe app (internal to the Frappe...
  remote-reset-url         Reset app remote url to frappe official
  remote-set-url           Set app remote url
  remote-urls              Show apps remote url
  remove-app               Completely remove app from bench and re-build...
  renew-lets-encrypt       Sets Up latest cron and Renew Let's Encrypt...
  restart                  Restart supervisor processes or systemd units
  retry-upgrade            Retry a failed upgrade
  set-default-site         Set default site for bench
  set-mariadb-host         Set MariaDB host for bench
  set-nginx-port           Set NGINX port for site
  set-redis-cache-host     Set Redis cache host for bench
  set-redis-queue-host     Set Redis queue host for bench
  set-redis-socketio-host  Set Redis socketio host for bench
  set-ssl-certificate      Set SSL certificate path for site
  set-ssl-key              Set SSL certificate private key path for site
  set-url-root             Set URL root for site
  setup                    Setup command group for enabling setting up a...
  src                      Prints bench source folder path, which can be...
  start                    Start Frappe development processes
  switch-to-branch         Switch all apps to specified branch, or specify...
  switch-to-develop        Switch frappe and erpnext to develop branch
  switch-to-master         [DEPRECATED]: Switch frappe and erpnext to
                           master...
  update                   Performs an update operation on current bench.


### There seems to be no “new-site” command, just "new-app"

**Comment by revant** [comment]
Run the command from `/workspace/development/frappe-bench` directory or any directory you created with `bench init`
