### ISSUE TITLE
Password aging renders maintenance commands unusable

### ISSUE THREAD

**Issue by tbolender** [frappe/frappe_docker#414]
## Description of the issue
We are running ERP Next with docker-compose. It pretty neat usable, thank you for this! However, we have issues when using restore and backup commands. They fail with the request to change the password of the user `frappe`. We encounter this not for the first time.

## Context information (for bug reports)

Our deployments are running for a bit longer (last time ~5 months) before we do an update to the latest version. Shell inspections yielded following output.

```
root@2963d8e8f9e6:/home/frappe/frappe-bench/sites# chage -l frappe
Last password change					: Sep 17, 2020
Password expires					: Dec 16, 2020
Password inactive					: never
Account expires						: never
Minimum number of days between password change		: 0
Maximum number of days between password change		: 90
Number of days of warning before password expires	: 7
```

The commands ran with not the latest version. However since this is not the first time and we can always notice this 2 month after deploy, I suspect the issue is still present.
```
ERPNEXT_VERSION=v12.11.2
FRAPPE_VERSION=v12.9.1
```

## Steps to reproduce the issue

1. Create a deployment
2. Optional: Use backup/restore, commands succeed
3. Operate page for ~2 months
4. Use backup/restore, commands fail with output below

### Observed result

Commands create
```
You are required to change your password immediately (password expired)
Current password: su: Authentication token manipulation error
Changing password for frappe.
```

However, we observe no impact on the web interface.

### Expected result

Successful backup/restore.

### Stacktrace / full error message if available
None

**Comment by tbolender** [comment]
Note: I suspect that the default password expiry rule of the base image causes this, e.g., https://github.com/frappe/frappe_docker/blob/develop/build/frappe-worker/Dockerfile#L4:

```
# Add non root user without password
RUN useradd -ms /bin/bash frappe
```

One could add the `-r` flag to disable password expiry. However, I have no idea about possible side effect this flag has so I did not create a pull request.

**Comment by revant** [comment]
```
useradd --help
...
  -r, --system                  create a system account
```

We need one non root account to run the processes.

**Comment by tbolender** [comment]
Thank you for the quick reply! I am happy to hear that this issue is fixed in the latest release. We will then simply upgrade since we have no other reasons than missing time to stick to an old version.

One note on the `-r` flag: System account seems not be the same as root. It is only used for organizational purposes and prevent shell login. See [[1]](https://unix.stackexchange.com/questions/80277/whats-the-difference-between-a-normal-user-and-a-system-user), [[2]](https://unix.stackexchange.com/questions/213101/implications-creating-system-accounts-useradd-r-linux-fedora-rhel-centos), [[3]](https://www.linuxquestions.org/questions/linux-newbie-8/useradd-r-option-and-system-account-question-892978/). Sorry, should have looked this up earlier.
