### ISSUE TITLE
How can I migrate a site to a new domain without losing data

### ISSUE THREAD

**Issue by kingraphaii** [frappe/frappe_docker#426]
I successfully installed ERPN using frappe_docker and now this site, `site1.mysite.com` is to be migrated to `site2.mysite.com`. How can I make this change without losing data?

**Comment by revant** [comment]
You can just rename the site directory.

Drawback with that is, database name is generated from the former name. If later you create sites1 again you'll face the db already existed.

Second approach, backup site1 and restore it as another.
Check forum

**Comment by kingraphaii** [comment]
I tried renaming the directory but it didn;t work. 

What about the certificate installed by Traefik?

> Check forum

Can you please send links. Been searching everywhere.

**Comment by kingraphaii** [comment]
I've tried the latter, and it seems to be promising. Thanks Revant.

**Comment by revant** [comment]
> What about the certificate installed by Traefik?

for that you need to change the SITES variable. Container labels need the change for traefik to manage letsencrypt. Check Traefik docs.
