### ISSUE TITLE
Unable to run bench commands (setup, config, etc)

### ISSUE THREAD

**Issue by kingraphaii** [frappe/frappe_docker#427]
## Description of the issue
I'm trying to add a certificate to a site using `bench setup lets-encrypt` but I get the following error:

```
Error: No such command "setup"
```
## Steps to reproduce the issue
1. Add new site
2. run bench setup lents-encrypt

### Observed result
No such command

### Expected result
Start lets-encrypt setup for site

### Stacktrace
```
Usage: bench frappe [OPTIONS] COMMAND [ARGS]...
Try "bench frappe --help" for help.

Error: No such command "setup".
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 18, in <module>
    [sys.executable, bench_helper, 'frappe'] + sys.argv[1:],
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/frappe/frappe-bench/env/bin/python', '/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py', 'frappe', 'setup', 'lets-encrypt']' returned non-zero exit status 2.
```

**Comment by revant** [comment]
I'll repeat

- https://discuss.erpnext.com/t/trouble-enabling-autoscheduler-in-single-server-docker-install/65804/2?u=revant_one
- https://discuss.erpnext.com/t/erpnext-12-13-in-an-internal-server-requires-internet-connection-to-the-outside/69373/2?u=revant_one
- https://discuss.erpnext.com/t/docker-installation-how-can-i-access-to-bench-commands/65520/2?u=revant_one
- https://discuss.erpnext.com/t/how-to-add-custom-app-to-frappe-docker-production-installation/65814/2?u=revant_one

Production images do not have bench installed.

For letsencrypt you need to use [traefik](https://traefik.io) or [docker-compose-letsencrypt-nginx-proxy-companion](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) or https://nginxproxymanager.com or any other proxy that can manage it.
