### ISSUE TITLE
Docker env-local

### ISSUE THREAD

**Issue by Mohamedmahrous995** [frappe/frappe_docker#430]
When I run docker compose up -f in my local I can't access the browser with the site I have create , can any one help me with this issue

**Comment by revant** [comment]
Can you provide details, I'll close this.

If you think the details are enough then I'll re-open with help wanted tag.

**Comment by revant** [comment]
![2021-03-26 19-14-05](https://user-images.githubusercontent.com/1040161/112642013-e387c180-8e68-11eb-9073-023413e58c9e.gif)

**Comment by dimanshujatav** [comment]
how to run this on particular port ?
and docker-compose ls is showing none after these commands

docker-compose --project-name erp up -d
docker logs erp_site-creator_1 -f

**Comment by revant** [comment]
check this docs for docker-compose ports https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

**Comment by dimanshujatav** [comment]
i want to run this  locally on Ec2 server without subdomain or domain 
what are the changes that i have to do?

**Comment by revant** [comment]
refer this: https://github.com/frappe/frappe_docker/wiki/Port-Based-Multi-Tenancy to setup port based access to site.

**Comment by dimanshujatav** [comment]
do we have to change nginx in /etc/nginx/ or nginx which is installed in docker container and which container ?
i'm replacing mysite.localhost to my server ip
do we have to replace mysite.localhost with my ip from everywhere or just nginx file ?
can you send us sample nginx file ?

**Comment by dimanshujatav** [comment]
any update @revant ?
