### ISSUE TITLE
docker frappe 

### ISSUE THREAD

**Issue by Mohamedmahrous995** [frappe/frappe_docker#432]
when i create docker-compose --project-name erpnext up -d it works 
then i create 
docker logs erpnext_site-creator_1 -f  it gives me this issue 

Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 5, in <module>
    from frappe.commands.site import _new_site
ImportError: cannot import name '_new_site' from 'frappe.commands.site' (/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py)

i'm using linux ubuntu , how can i solve this issue

**Comment by revant** [comment]
#433

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/431 better and informative title for the same issue.

Confusing title: docker frappe
