### ISSUE TITLE
is it bugs: list.min.css 404 and Port 9000 on /socket.io/?EIO=3

### ISSUE THREAD

**Issue by takyeyu** [frappe/frappe_docker#439]
I installed the v13, while I found that there are two issues,

missing file list.min.css in desk view, no need to build list.min.css in build.json, but the page will include list.min.css, so it caused 404 of this file
every 10 second, I will got an error "GET https://xxxx.com:9000/socket.io/?EIO=3&transport=polling&t=" in google console, I know it is about port of socket.io, how can I make system to run this link without the port 9000, I tried this link, but can't fixed https://discuss.erpnext.com/t/error-in-console-net-err-connection-refused/29046
Could anyone guide me to fixed these two problems, thanks

![WechatIMG64](https://user-images.githubusercontent.com/11435182/111895157-bd6ab780-8a4b-11eb-9a5d-2ffd2caf2056.jpeg)

**Comment by revant** [comment]
Socketio Port 9000 is for development.
In production it's https://erpnext.com/socket.io

**Comment by takyeyu** [comment]
may i know if i can change from development to production directly and easily or i need to re-install based on the production steps, thank.

**Comment by takyeyu** [comment]
Or is it possible to remove port 9000 in development mode? thank.

**Comment by takyeyu** [comment]
I just change the socketio_port to 443 (as i using https for my website), and I found the problem of port 9000 is fixed, may I know if it was a correct method

**Comment by revant** [comment]
In case of vanilla setup with no custom apps.

- choose from the separate production install methods
- `frappe/bench:latest` image is of no use for vanilla setups.

In case of custom apps

- Use `frappe/bench:latest` image for developers to build custom apps.
- Setup a CI pipeline job that builds your own images when you git push changes to your custom app repo
- In case of multiple custom app, create a separate repo for builds like (frappe_docker does)
- Use your own images in the yaml(s)

**Comment by takyeyu** [comment]
ok, thank you very much.
