### ISSUE TITLE
Erpnext Social Login redirect is requested in http, how to switch to https in Docker environment.

### ISSUE THREAD

**Issue by artykbasar** [frappe/frappe_docker#444]
Hello everyone, 

I am facing an issue here with social login redirect.

First of all, this is how am running ERPNext.

Docker
Production Environment.
All https certificates are being handled by Traefik.

Now when you get credentials from google, for social login, you can specify URI Redirect. And if you want to make your application publicly available, your redirects have to be in HTTPS.

<img width="566" alt="Screenshot 2021-03-29 at 09 14 31" src="https://user-images.githubusercontent.com/78363421/112810775-4c428a00-9073-11eb-9fbe-fba55d71aa06.png">

Now when I try to use the social login, looks like ERPNext(frappe) requests the redirect in HTTP rather than HTTPS.
And google throws me 400: redirect_uri_mismatch ERROR shown below:

<img width="487" alt="Screenshot 2021-03-29 at 09 38 05" src="https://user-images.githubusercontent.com/78363421/112812030-8f512d00-9074-11eb-8cad-0bda5b2927df.png">

If I will change redirects to http from https, in google console, social login works but I have to use this feature for only internal purposes. Google will not allow me to use the application publicly, because of the security issue.

I know that there is a way to switch frappe from http to https which involves Nginx handling the certificates. As in docker certificate is being handled by traefik I do not know how to enable https in frappe.

If anyone knows how to enable https in docker environment  in production please help me out.

If I could not explain myself please ask for clarification.

**Comment by revant** [comment]
refer this post

https://discuss.erpnext.com/t/social-key-auth-redirect-issue-google-https/68065/4

add `host_name` and optionally `http_port` to `site_config.json`
