### ISSUE TITLE
Mismatch between frappe and erpnext versions

### ISSUE THREAD

**Issue by cortopy** [frappe/frappe_docker#451]
I've noticed that since last week, frappe versions are ahead of erpnext. Shouldn't https://github.com/frappe/frappe_docker/blob/develop/build/erpnext-worker/Dockerfile be using a different `GIT_BRANCH` for frappe and erpnext? 

For example, right now v3.0.2 for frappe and v3.0.1 for erpnext?

**Comment by revant** [comment]
There won't be mismatch.

`GIT_BRANCH` is not the semver tag. It is just the version branch, currently `version-13`, whenever the version is released it bumped in `frappe.__init__.py`, merged with this version branch and tagged on git with github release.

That means whenever the travis build runs, it will always pull the latest `version-xx` branch and start building. Also the stages ensure frappe is built first and erpnext pull the latest version-xx frappe in the following step after frappe is built.

After my helm release was upgraded :

```
erpnext-v13     erpnext         2               2021-04-07 13:09:34.744332612 +0530 IST deployed        erpnext-3.0.3   v13.0.1
```

`Help > About` from my erpnext-3.0.3 release :

![version-13](https://user-images.githubusercontent.com/1040161/113874540-8a5a4f00-97d3-11eb-9cea-3a577f2c3d54.png)

Limitation with semver in context with frappe and erpnext versioning is: (not related to this question)
Ideally when frappe-v13.0.1 is upgraded by any depending app to v13.0.2, the depending app should also bump its version
e.g. erpnext using frappe v13.0.1 starts using v13.0.2 then erpnext should also bump at least the patch version.

**Comment by cortopy** [comment]
thanks @revant for clarifying this. But then the builds are not predictable right? If someone uses the Dockerfile in frappe-docker a month later and builds the same version of erpnext it will be a very different docker container to the one published since the new build uses a newer version of frappe.

**Comment by revant** [comment]
The builds happen for latest release, assumption is that everything will be archived on the docker registry. 

Idea is, build for today, push to registry with tag for archival.

So if anyone needs to go back in time download older images for frappe or erpnext.

For custom apps, specify exact version from docker registry. https://gitlab.com/castlecraft/excel_erpnext/-/blob/ad8964f682039711e8e20f62314f66c9584d32a9/docker/excel-erpnext-nginx/Dockerfile#L8

In case where docker registry has deleted the stale images, come edit in Dockerfile will be needed if build args are not sufficient.
