### ISSUE TITLE
WARN: bench is installed in editable mode

### ISSUE THREAD

**Issue by guilmori** [frappe/frappe_docker#453]
I followed the developer guide here:
https://github.com/frappe/frappe_docker/tree/develop/development

How to get rid of this warning ?

WARN: bench is installed in editable mode!
This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Thanks !

**Comment by revant** [comment]
Bench is installed in editable mode because bench source is available in ~/.bench directory for development of the bench itself.

**Comment by guilmori** [comment]
@revant Thanks, and is there a way to get rid of this warning ?

**Comment by revant** [comment]
not really, every time you pull latest `frappe/bench:latest` image it will start showing this warning.

try this https://discuss.erpnext.com/t/tutorial-installing-and-upgrading-bench-cli-ver-5-3/73463
