### ISSUE TITLE
Error: Cannot find module 'node-sass' (ERPNEXT_VERSION=v13.0.0 and FRAPPE_VERSION=v13.0.2)

### ISSUE THREAD

**Issue by mtogiz** [frappe/frappe_docker#454]
## Description of the issue
Can't patch and migrate to newest versions
## Context information (for bug reports)
Ugrade to newest version for erpnext
## Steps to reproduce the issue
1. Pull new version
ERPNEXT_VERSION=v13.0.0
FRAPPE_VERSION=v13.0.2
2. Recreate docker
3. Run migrate

### Observed result
Error: Cannot find module 'node-sass'
### Expected result
Patched and no error
### Stacktrace / full error message if available
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/migrate.py", line 51, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 44, in main
    migrate_sites()
  File "/home/frappe/frappe-bench/commands/migrate.py", line 35, in migrate_sites
    migrate()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 89, in migrate
    frappe.get_attr(fn)()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 185, in after_migrate
    doc.generate_bootstrap_theme()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/doctype/website_theme/website_theme.py", line 80, in generate_bootstrap_theme
    frappe.throw('<div style="font-family: monospace;">{stderr}</div>'.format(stderr=stderr))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 424, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 403, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 357, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: <div style="font-family: monospace;">internal/modules/cjs/loader.js:818<br>  throw err;<br>  ^<br><br>Error: Cannot find module 'node-sass'<br>Require stack:<br>- /home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js<br>    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)<br>    at Function.Module._load (internal/modules/cjs/loader.js:667:27)<br>    at Module.require (internal/modules/cjs/loader.js:887:19)<br>    at require (internal/modules/cjs/helpers.js:74:18)<br>    at Object.<anonymous> (/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js:1:14)<br>    at Module._compile (internal/modules/cjs/loader.js:999:30)<br>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)<br>    at Module.load (internal/modules/cjs/loader.js:863:32)<br>    at Function.Module._load (internal/modules/cjs/loader.js:708:14)<br>    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {<br>  code: 'MODULE_NOT_FOUND',<br>  requireStack: [<br>    '/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js'<br>  ]<br>}<br></div>
```

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/develop/build/common/worker/docker-entrypoint.sh#L72-L73

can you check if node-sass exists in node_modules?

If not then try symlink it.

**Comment by revant** [comment]
Upgrade is verified in tests. It's seems to be working as expected.

At start of erpnext-nginx container it populates assets volume, and at start of erpnext-worker container it symlinks node_modules.

**Comment by mtogiz** [comment]
I tried clearing images and pull new one but the same error. node-sass still exists in node_modules (assets-vol).

It's seem like didn't have symlink for _node_modules_ from containers below.
_frappe-worker-default_1
frappe-worker-short_1 
frappe-worker-long_1_ 

But i can find _node_modules_ in cointainer _erpnext-python_1_

So I guest when do migrate symlink was broken
<img width="1021" alt="Screen Shot 2021-04-11 at 10 49 08" src="https://user-images.githubusercontent.com/20220970/114291757-114d4700-9ab4-11eb-80ff-4e97a908eaf0.png">

**Comment by mtogiz** [comment]
I found the problem. We should map assets-vol for _erpnext-worker_ the same with _erpnext-python_

And add -v assets-vol:/home/frappe/frappe-bench/sites/assets when run migrate
```
docker run \
    -e "MAINTENANCE_MODE=1" \
    -v togi-erp/sites-vol:/home/frappe/frappe-bench/sites \
    -v assets-vol:/home/frappe/frappe-bench/sites/assets \
    --network webproxy \
    frappe/erpnext-worker:$ERPNEXT_VERSION migrate
```
you can update on docker compose file

**Comment by revant** [comment]
> you can update on docker compose file

I'll update the site operations README

**Comment by mtogiz** [comment]
> > you can update on docker compose file
> 
> I'll update the site operations README

Ok, thank you bro

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/458
