### ISSUE TITLE
How the get access to Frappe and ERPNext python (Hooks.py) and Js script to configure views and forms?

### ISSUE THREAD

**Issue by ebassmx** [frappe/frappe_docker#457]
I want to edit  hooks.py to add communication_list.js. I edited but I could see the changes.

How to do that?

**Comment by revant** [comment]
I repeat this everywhere
https://discuss.erpnext.com/t/bench-error-no-such-command-setup/71784/6?u=revant_one

You'll have to use build and use custom image.

Refer this https://github.com/castlecraft/custom_frappe_docker

Commercial project? castlecraft.in
