### ISSUE TITLE
How to add a new site to an existing single bench setup?

### ISSUE THREAD

**Issue by esafwan** [frappe/frappe_docker#461]
I have followed the documentation for single-bench setup and I have a site `site1.domain.com`. Now I want to add a new site`site2.domain.com`. 

**As per documentation I have to run the below command:**

```
# Create ERPNext site
docker run \
    -e "SITE_NAME=$SITE_NAME" \
    -e "DB_ROOT_USER=$DB_ROOT_USER" \
    -e "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" \
    -e "ADMIN_PASSWORD=$ADMIN_PASSWORD" \
    -e "INSTALL_APPS=erpnext" \
    -v <project-name>_sites-vol:/home/frappe/frappe-bench/sites \
    --network <project-name>_default \
    frappe/erpnext-worker:$VERSION new
```

However, in the frappe root folder the`.env`file has details of the first site. And from my understanding it will be needed for future changes, backups etc. So for the second site, should we create a new frappe_docker folder first? Or should we add, the new site name to `SITES` variable in `.env` as a comma separated value?

**Comment by revant** [comment]
`SITES` variable need to have as many sites as you need.
`SITE_NAME` variable is used by site-creator container.

Just change the SITE_NAME variable or check this https://discuss.erpnext.com/t/docker-swarm-portainer-frappe-only-need-erpnext/73793/3
