### ISSUE TITLE
Configure Development docker-compose to run multiple sites in different ports

### ISSUE THREAD

**Issue by Ciangi** [frappe/frappe_docker#463]
Hello,

I'm using [dev docker-compose.yml](https://github.com/frappe/frappe_docker/blob/develop/devcontainer-example/docker-compose.yml).

As i see there is smth like:
```
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
```

But `bench start` command runs only with `8000` port with acutal using site.

Is it possible and if it is how can i configure that for example mysite1.localhost will run on 8000 and mysite2.localhost will run on 8001 port?

If i good understand then mysite1.localhost socketio needs to run in 9000 port and mysite2.localhost socketio needs to run in 9001 ?

Greetings

**Comment by revant** [comment]
```
bench init frappe-bench-00
```
will setup bench to serve on 8000 python, 9000 socketio

exec following:

```
bench init frappe-bench-01
```
and it will setup bench to serve on 8001 python, 9001 socketio

you can have multiple benches,

multi site is based on dns and not ports.

e.g. 
site1.localhost:8000, site2.localhost:8000
site3.localhost:8001, site4.localhost:8001
