### ISSUE TITLE
manifest unknown error for version 11.1.20

### ISSUE THREAD

**Issue by xtrmbuster** [frappe/frappe_docker#467]
Hi,

Thanks for your work,

I would like to use docker with the version 11.1.20 but the tag is not created in the docker catalog.

Can you add it please ?

Thanks a lot.

**Comment by revant** [comment]
> Can you add it please ?

Old images cannot be added. Infact docker hub will delete stale images.

Build and use your own images, run following commands.

Worker Images

```shell
docker build --build-arg=GIT_BRANCH=v11.1.69 -t frappe/frappe-worker:v11.1.77 -f build/frappe-worker/Dockerfile .
docker build --build-arg=GIT_BRANCH=v11.1.77 -t frappe/erpnext-worker:v11.1.77 -f build/erpnext-worker/Dockerfile .
```
Nginx Images

```shell
docker build --build-arg=GIT_BRANCH=v11.1.69 -t frappe/frappe-nginx:v11.1.77 -f build/frappe-nginx/Dockerfile .
docker build --build-arg=GIT_BRANCH=v11.1.77 -t frappe/erpnext-nginx:v11.1.77 -f build/erpnext-nginx/Dockerfile .
```
