### ISSUE TITLE
Configurations changes to setup tls certificate without using letsencrypt on docker for frappe/frappe_docker

### ISSUE THREAD

**Issue by karispk** [frappe/frappe_docker#469]
Installation details
Ubuntu server 20.04
Docker engine - Community 20.10.6
frappe/frappe_docker

Installation
Single bench
Production

What configuration changes are required to use a purchased tls certificate (without using letsencrypt) to enable erpnext to run with HTTPS ?

**Comment by revant** [comment]
https://doc.traefik.io/traefik/https/tls/

Check traefik. You'll need to change the docker-compose.yml

**Comment by karispk** [comment]
attempted to change the docker-compose.yml using instruction on the link provided https://doc.traefik.io/traefik/https/tls/ however experienced the below error message. 
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.traefik: 'tls'

**Comment by revant** [comment]
Check traefik and docker-compose docs carefully.
docker-compose syntax is incorrect.
