### ISSUE TITLE
Please tag Docker releases for frappe/bench

### ISSUE THREAD

**Issue by daraul** [frappe/frappe_docker#471]
Every release to docker hub is currently tagged as latest. Would it not be better to tag releases, and development versions of bench?

**Comment by revant** [comment]
Any specific reason you need the tag for? Old and stale tags are deleted from docker hub.

The assumption here was following commands that developers had to run to setup bench will be part of image.

```shell
git clone https://github.com/frappe/bench.git ~/.bench
pip install -e ~/.bench
```

This gets you latest bench always.
To move within in bench source timeline, use git history.

You can even installed pypi version if you need.

If you need old versions:

1. Fork and build your own
2. OR, send PR that pushes multiple versions of bench
