### ISSUE TITLE
Branch names and CI/CD workflows

### ISSUE THREAD

**Issue by b0r1sp** [frappe/frappe_docker#474]
Hi, thanks for making this repo, helps a lot! I wonder why the default branch is "develop"? Which of the branches (develop, master) is the main branch and which should be used for a stable docker-based installation?

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/develop/CONTRIBUTING.md#branches

Develop is periodically merged into master.
If only docs are changed, I merge it less frequently.

**Comment by b0r1sp** [comment]
I’d suggest to make Master the default branch then. If repo gets cloned ‚develop‘ is checked out automatically, that is misleading.

**Comment by revant** [comment]
> If repo gets cloned ‚develop‘ is checked out automatically

Doesn't really matter for user.

If someone is trying to send PR they will have to switch branch. I think keeping it to master will result in many PRs being sent to master.

**Comment by revant** [comment]
Is there any other way?

frappe_docker/develop: 
- all PRs go here.
- people clone this.
- travis job triggers build for frappe/bench image on develop branch
- builds triggered here are tagged edge, develop, latest

frappe_docker/master
- kept in sync with develop, (unless it is just docs), one direction sync, not complex. develop -> master.
- builds triggered on master branch are tagged with semver from frappe or erpnext release.
- master branch triggered by frappe or erpnext release workflow https://github.com/frappe/frappe/blob/develop/.github/workflows/docker-release.yml, https://github.com/frappe/erpnext/blob/develop/.github/workflows/docker-release.yml
- at the end of master pipeline, helm chart pipeline is updated with version tag from frappe/erpnext release and published.

This is the reason there are 2 branches.
