### ISSUE TITLE
Installing Custom Frappe App Using Docker

### ISSUE THREAD

**Issue by harshitshah4** [frappe/frappe_docker#475]
I have followed all the instructions mentioned over at :
 [https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md]()

At the end of this doc, it is written "Install like usual"

After following each and every step in the above doc, Where to go next?

How can I install Custom Frappe App on Docker?

Also, I dont need erp next, but only custom frappe app.
 
Can someone help me with this?

Also it would be better if documentation was more clear.

**Comment by harshitshah4** [comment]
I have made changes in "installation" and  "build" folder as mentioned in the custom app for production doc.

What should I do after this ? What commands to run ? What steps to perform.

**Comment by revant** [comment]
Check this example repo https://github.com/castlecraft/custom_frappe_docker. It has multiple community apps installed over ERPNext. Build your own like that, base it on frappe/frappe-* images, just install your needed apps.

Build? Install?
It means build your own docker image. Push it to docker registry and then use that image in your deployments.
