### ISSUE TITLE
docs: change custome apps in erpnext docs with respect to Dockerfile changes 

### ISSUE THREAD

**Issue by pratikbalar** [frappe/frappe_docker#479]
**Is your feature request related to a problem? Please describe.**

I am running frappe with custom apps installed and I can see dockerfiles for custom apps for production are changed where you now using frappe-worker images as base image and install erpnext etc. so do i/we have to install_app.sh script as per that?

**Quick Question:** frappe release tag and erpnext release tag are concurrent in release, i mean when new frappa tag release there will be erpnext release following that exact tag e.g. frappe `v13.3.0` → erpnext `v13.3.0` is it, just curious ?

**Comment by revant** [comment]
If your app is based on frappe use frappe as base image

If your app is based on erpnext use erpnext as base image

For tagging, bumping of frappe doesn't really into bumping of ERPNext version.
