### ISSUE TITLE
root or non-privileged user

### ISSUE THREAD

**Issue by warwickchapman** [frappe/frappe_docker#480]
The document is not clear about whether the `docker-compose --project-name x up -d` command must be run as root or an unprivileged user.

**Comment by Thunderbottom** [comment]
Running `docker-compose` as a privileged or non-privileged user is left up to the user and completely depends on how you have configured your system's docker daemon. The recommended way of running docker would be to add a non-privileged user to the `docker` group on your system, although that does grant [the same exec permissions](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) as the root user would have.

One thing to keep in mind is that the container runs as the `frappe` user, which is mapped to the `1000:1000` namespace on the host. So the files need to be owned by the same user on the host for the container to function correctly.

Ultimately it's up to the user on how they'd want to run docker and does not really specifically impact this project.
