### ISSUE TITLE
.env with DB on separate host

### ISSUE THREAD

**Issue by warwickchapman** [frappe/frappe_docker#481]
## Description of the issue

If `.env` is populated with a separate host ie. not localhost for the DB, the DB is created on the other host but no tables are created.  The mariadb container is still deployed and no DB is created there.

## Context information (for bug reports)

Internal Server Error is returned.

## Steps to reproduce the issue

1. Example `.env`:

```
LETSENCRYPT_EMAIL=my@email.com
ERPNEXT_VERSION=edge
FRAPPE_VERSION=edge
MARIADB_HOST=a.diffferent.host.com
MYSQL_ROOT_PASSWORD=TheDBpassOnThatHost
SITE_NAME=erp.email.com
SITES=`erp.email.com`
DB_ROOT_USER=root
ADMIN_PASSWORD=erp123
INSTALL_APPS=erpnext
ENTRYPOINT_LABEL=traefik.http.routers.erpnext-nginx.entrypoints=websecure
CERT_RESOLVER_LABEL=traefik.http.routers.erpnext-nginx.tls.certresolver=myresolver
HTTPS_REDIRECT_RULE_LABEL=traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
HTTPS_REDIRECT_ENTRYPOINT_LABEL=traefik.http.routers.http-catchall.entrypoints=web
HTTPS_REDIRECT_MIDDLEWARE_LABEL=traefik.http.routers.http-catchall.middlewares=redirect-to-https
HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL=traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
SKIP_NGINX_TEMPLATE_GENERATION=0
WORKER_CLASS=gthread
```

2. Run `docker-compose --project-name my-erpnext up -d`

3. Try access `erp.email.com` in the browser

### Observed result

Internal Server Error

### Expected result

Working app

**Comment by Thunderbottom** [comment]
could you confirm that the `site-creator` container has exited? if it did, and correctly so, could you also post the logs from that container here?

**Comment by revant** [comment]
Any update on this?

**Comment by revant** [comment]
Re-open if needed
