### ISSUE TITLE
manifest for frappe/erpnext-nginx:12.21.0 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by ji-tusher** [frappe/frappe_docker#482]
#I encountered this error when try to install ERPNext version-12. 
Here is some line of env-production file: 
```
ERPNEXT_VERSION=version-12
FRAPPE_VERSION=version-12
MARIADB_HOST=mariadb
```
on executing command: 
`docker-compose up -d`

I got this error:

`manifest for frappe/erpnext-nginx:12.21.0 not found: manifest unknown: manifest unknown`

**Comment by revant** [comment]
Can you try again? The images were pushed.

https://hub.docker.com/layers/frappe/frappe-socketio/v12.18.0
https://hub.docker.com/layers/frappe/erpnext-worker/v12.21.0
https://hub.docker.com/layers/frappe/erpnext-nginx/v12.21.0
