### ISSUE TITLE
Can I run without Nginx?

### ISSUE THREAD

**Issue by codihaus** [frappe/frappe_docker#485]
Hello,

I have tried ERPNext, it's quite good to use, but I'm not sure If I can use ERPNext Docker-compose without nginx/traefic.

I mean, I already had NginX installed on my server - to run other apps too, so it would be great if I can use ERPNext with its port (I suppose to 8000, 9000)

So that I will do the reserve proxy manually by my end here.

Thank you!

**Comment by revant** [comment]
Yes you can run ERPNext without nginx or traefik reverse proxy.

You can't run ERPNext without the erpnext-nginx. That container serves static web assets and acts as a reverse proxy for gunicorn and socketio service. Think of it as part of app.

Use your reverse proxy above erpnext-nginx

**Comment by codihaus** [comment]
Hi @revant ,

So, can I delete traefic & erpnext-nginx in the docker-compose?

**Comment by revant** [comment]
> You can't run ERPNext without the erpnext-nginx. 

NO. You can't delete the erpnext-nginx container.
You can delete traefik container
