### ISSUE TITLE
CentOS problem with SeLinux

### ISSUE THREAD

**Issue by daffi1238** [frappe/frappe_docker#488]
I wanted to mention here a problem with the docker-compose up -d using CentOS. I know that is not a problem specific from the ERPNext what is a issue that take a lot of time to me. It's neccesary disable SeLinux in your system if you are deploying in CentOS.

The problem consist in de "exited" status of one of the containers.

Greetings and thank you for the work!

**Comment by revant** [comment]
Thanks for posting the info. It might help someone. Re-open the issue if needed.
