### ISSUE TITLE
Why dont you install `jq` ?

### ISSUE THREAD

**Issue by pratikbalar** [frappe/frappe_docker#489]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Why don't you guys install jq for handling stuff like this ?
https://github.com/frappe/frappe_docker/blob/2e6d11aa4dffb93da36f0edaec525446aa121e84/build/common/worker/healthcheck.sh#L6-L7

**Comment by revant** [comment]
Adds 1 more dependency to image just for health check so I didn't add anything.

For other purposes we've python for json.

In fact initially health check was done using python and it started consuming unnecessary resource, then we moved to bash / wait script

We can add, it may be useful for other custom operations as well.

Add it if you really need it urgently

**Comment by pratikbalar** [comment]
Just want to go away with this awk,tr,cut ugliness so but add it based on your need

> Adds 1 more dependency to image just for health check so I didn't add anything.
> We can add, it may be useful for other custom operations as well.
> Add it if you really need it urgently

Ahh, good to know
> In fact initially health check was done using python and it started consuming unnecessary resource, then we moved to bash / wait script
