### ISSUE TITLE
Looks like now arm64 architecture can be built and pushed to the official docker hub repository.

### ISSUE THREAD

**Issue by artykbasar** [frappe/frappe_docker#494]
When building arm64 images it would take more than couple of hours. Main reason, why it was very slow, pandas wheels were being build while docker image was being built.

Looks like that issue is gone. I have managed to build frappe-nginx, frappe-worker, frappe-socketio, erpnext-nginx, erpnext-worker under half an hour, all 5 images combined.

I have built the images from develop branches.

I had to add one line in 2 dockerfiles, for the process to work. Because there are some smaller wheels are still being built while building images, so pip3 was required. I showed the lines that I added/modified below just to explain myself properly.

**Dockerfile of frappe-worker**

```FROM python:3.7-slim-buster

# Add non root user without password
RUN useradd -ms /bin/bash frappe

ARG GIT_REPO=https://github.com/frappe/frappe
ARG GIT_BRANCH=develop
ARG ARCH=amd64
ENV PYTHONUNBUFFERED 1
ENV NVM_DIR=/home/frappe/.nvm
ENV NODE_VERSION=14.17.0
ENV PATH="/home/frappe/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

# Install dependencies
WORKDIR /home/frappe/frappe-bench
RUN apt-get update -y && apt-get install \
    # for frappe framework
    git \
    mariadb-client \
    postgresql-client \
    gettext-base \
    wget \
    wait-for-it \
    #######################
    python3-pip \  ############  This is the line that I added
    ########################
    # for PDF
    libjpeg62-turbo \
    libx11-6 \
    libxcb1 \
    libxext6 \
    libxrender1 \
    libssl-dev \
    fonts-cantarell \
    xfonts-75dpi \
    xfonts-base \
    libxml2 \
    libffi-dev \
    libjpeg-dev \
    zlib1g-dev \
    # For psycopg2
    libpq-dev \
    # For arm64 python wheel builds
    gcc \
    g++ -y \
    # Detect arch, download and install wkhtmltox
    && if [ `uname -m` = 'aarch64' ]; then export ARCH=arm64; fi \
    && if [ `uname -m` = 'x86_64' ]; then export ARCH=amd64; fi \
    && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_${ARCH}.deb \
    && dpkg -i wkhtmltox_0.12.6-1.buster_${ARCH}.deb && rm wkhtmltox_0.12.6-1.buster_${ARCH}.deb \
    && wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh \
    && chown -R frappe:frappe /home/frappe

# Setup docker-entrypoint
COPY build/common/worker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN ln -s /usr/local/bin/docker-entrypoint.sh / # backwards compat

USER frappe
# Install nvm with node
RUN bash install.sh \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install ${NODE_VERSION} \
    && nvm use v${NODE_VERSION} \
    && nvm alias default v${NODE_VERSION}

# Create frappe-bench directories
RUN mkdir -p apps logs commands sites /home/frappe/backups

# Setup python environment
RUN python -m venv env \
    && . env/bin/activate \
    && pip3 install --upgrade pip \
    && pip3 install gevent \
    && cd apps \
    && git clone --depth 1 -o upstream ${GIT_REPO} --branch ${GIT_BRANCH} \
    && pip3 install --no-cache-dir -e /home/frappe/frappe-bench/apps/frappe

# Copy scripts and templates
COPY build/common/commands/* /home/frappe/frappe-bench/commands/
COPY build/common/common_site_config.json.template /opt/frappe/common_site_config.json.template
COPY build/common/worker/install_app.sh /usr/local/bin/install_app
COPY build/common/worker/bench /usr/local/bin/bench
COPY build/common/worker/healthcheck.sh /usr/local/bin/healthcheck.sh

# Use sites volume as working directory
WORKDIR /home/frappe/frappe-bench/sites

VOLUME [ "/home/frappe/frappe-bench/sites", "/home/frappe/backups", "/home/frappe/frappe-bench/logs" ]

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["start"]
```

**Dockerfile of frappe-nginx**

```
# This image uses nvm and same base image as the worker image.
# This is done to ensures that node-sass binary remains common.
# node-sass is required to enable website theme feature used
# by Website Manager role in Frappe Framework
FROM python:3.7-slim-buster

ARG GIT_REPO=https://github.com/frappe/frappe
ARG GIT_BRANCH=develop

ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=14.17.0
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN apt-get update -y \
##################################################################################
    && apt-get install wget python2 git build-essential python3-pip -y \########### This is the line I have modified
##################################################################################
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh \
    && chmod +x install.sh \
    && ./install.sh \
    && . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION} \
    && nvm use v${NODE_VERSION} && npm install -g yarn

WORKDIR /home/frappe/frappe-bench
RUN mkdir -p /home/frappe/frappe-bench/sites \
    && echo "frappe" > /home/frappe/frappe-bench/sites/apps.txt

RUN mkdir -p apps sites/assets/css  \
    && cd apps \
    && git clone --depth 1 ${GIT_REPO} --branch $GIT_BRANCH

RUN cd /home/frappe/frappe-bench/apps/frappe \
    && yarn \
    && yarn run production \
    && yarn install --production=true

RUN node --version \
    && npm --version \
    && yarn --version

RUN git clone --depth 1 https://github.com/frappe/bench /tmp/bench \
    && mkdir -p /var/www/error_pages \
    && cp -r /tmp/bench/bench/config/templates /var/www/error_pages

RUN mkdir -p /home/frappe/frappe-bench/sites/assets/frappe/ \
    && cp -R /home/frappe/frappe-bench/apps/frappe/frappe/public/* /home/frappe/frappe-bench/sites/assets/frappe \
    && cp -R /home/frappe/frappe-bench/apps/frappe/node_modules /home/frappe/frappe-bench/sites/assets/frappe/

FROM nginx:latest
COPY --from=0 /home/frappe/frappe-bench/sites /var/www/html/
COPY --from=0 /var/www/error_pages /var/www/
COPY build/common/nginx-default.conf.template /etc/nginx/conf.d/default.conf.template
COPY build/frappe-nginx/docker-entrypoint.sh /

RUN apt-get update && apt-get install -y rsync && apt-get clean \
    && echo "#!/bin/bash" > /rsync \
    && chmod +x /rsync

VOLUME [ "/assets" ]

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

```

**Comment by revant** [comment]
frappe-worker is built in 19min locally
frappe-nginx, I guess is building node-sass and taking infinite time

**Comment by artykbasar** [comment]
> frappe-worker is built in 19min locally

Locally what machine are you using, to build the images. As I said all 5 images combined took me less than 30 mins. I am using simple Raspberry Pi 4 with 8gb memory.

> frappe-nginx, I guess is building node-sass and taking infinite time (30min)

And what should be the max build time for arm64 images, for it to be considered to be pushed to the official repository?

**Comment by revant** [comment]
I'm using buildx docker plugin. I am using my standard amd64 laptop. I'll set this up for castlecraft/frappe_docker and check how things go on travis. More about build process here https://github.com/frappe/frappe_docker/issues/380#issuecomment-767201476

**Comment by revant** [comment]
Is there a way to test this? I'm not able to use travis on my fork

**Comment by artykbasar** [comment]
> I'm using buildx docker plugin. I am using my standard amd64 laptop. I'll set this up for castlecraft/frappe_docker and check how things go on travis. More about build process here https://github.com/frappe/frappe_docker/issues/380#issuecomment-767201476

Thank you @revant for looking into this. As I know, you have the access to push the docker images to the to official frappe repository, If thats the case, after your tests goes through successfully, I hope it could be pushed to the official frappe images as well. If there are certain limitations that I don't know please let me know.

**Comment by pratikbalar** [comment]
> Is there a way to test this? I'm not able to use travis on my fork

Travis does support arm cpus right!! Or you have to enable it or something ? @revant

**Comment by revant** [comment]
> Travis does support arm cpus right!! @revant

https://www.docker.com/blog/multi-arch-build-what-about-travis

**Comment by revant** [comment]
I've not yet found a way to test on travis.

Should we just test the pipeline here and revert back if it doesn't work?

**Comment by artykbasar** [comment]
Hi Revant, 
I have tried to test (building images only) on Travis with buildx. Error what I was getting is, Dockerfiles has inside detection for arch for installing the correct dependencies. These lines which I am talking about:
```
if [ `uname -m` = 'aarch64' ]; then export ARCH=arm64; fi \
    && if [ `uname -m` = 'x86_64' ]; then export ARCH=amd64; fi \
    && wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_${ARCH}.deb \
    && dpkg -i wkhtmltox_0.12.6-1.buster_${ARCH}.deb && rm wkhtmltox_0.12.6-1.buster_${ARCH}.deb
```
While dockerfile was being built I think buildx was not passing to the dockerfiles correct arch and it was not finishing the build.(Maybe I did something wrong here) I end up building the images old fashion way with Docker manifest. By creating individual images in Different Travis Arches and pushing them to docker(arm64, amd64) then combining them to the one tag with Docker Manifest.
Check out my Docker Hub Repo you will be able to see it there. I know this is the most in efficient way of building it but currently this is what I am dealing with.

Here are my tries in travis: https://travis-ci.com/github/artykbasar/frappe_docker
Docker Hub: https://hub.docker.com/u/artykbasar

changes that I had to make on travis.yml:
https://github.com/artykbasar/frappe_docker/blob/296c389ff64e1da217592b5e891e1e87f73884a3/.travis.yml

changes that I had to make on travis.py:
https://github.com/artykbasar/frappe_docker/blob/296c389ff64e1da217592b5e891e1e87f73884a3/travis.py

I am open for any suggestions that I could have done differently. Please do not judge me as I am very new in this field 😂😂😂

**Comment by revant** [comment]
How did you setup buildx?

Did you run the following commands?

```
before_install:
  # Install latest docker (https://www.docker.com/blog/multi-arch-build-what-about-travis)
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx create --use
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx inspect --bootstrap
```

**Comment by artykbasar** [comment]
Ok that might be the reason then, I have used these lines below to update the docker, I will try building and testing it today. with what you have provided. Let's see how it goes.
```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker buildx create --name mybuilder --platform linux/arm64,linux/amd64
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
```

**Comment by artykbasar** [comment]
> How did you setup buildx?
> 
> Did you run the following commands?
> 
> ```
> before_install:
>   # Install latest docker (https://www.docker.com/blog/multi-arch-build-what-about-travis)
>   - sudo rm -rf /var/lib/apt/lists/*
>   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
>   - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
>   - sudo apt-get update
>   - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
>   - mkdir -vp ~/.docker/cli-plugins/
>   - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
>   - chmod a+x ~/.docker/cli-plugins/docker-buildx
>   - docker buildx create --use
>   - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
>   - docker buildx inspect --bootstrap
> ```
> 
> latest docker can detect i think, the one which comes with travis runner is not working.

I have just seen your travis.yml commit. Leave some work for me too mate.😂😂😂 You have done all of it))) Looks like it passed the test as well, so finally we will start to see the arm64 support on official frappe registry. Thank you Revant for this. This is going to open the door to the quite a lot of people actually.

**Comment by revant** [comment]
Can you test it on your Travis account? Things from my PR.

**Comment by artykbasar** [comment]
OK I will try it today

**Comment by artykbasar** [comment]
Hello @revant,

I have tried your travis config file. Buildx working fine but it is slow when it comes to arm64 build, as expected, but and on top there are dependency builds happening in arm64 and travis keep aborting the build by giving this message:
 
```
#31 116.7 warning "esbuild-vue > @vue/component-compiler@4.2.3" has unmet peer dependency "postcss@>=6.0".
3684#31 117.0 warning Workspaces can only be enabled in private projects.
3685#31 155.9 [5/5] Building fresh packages...
3686
3687
3688No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
3689Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
3690
3691The build has been terminated
```
I am not sure if there is a way to extend travis's time-out limit, maybe 15-20 mins, what I am guessing that will give us, at least, see if there is actual possibility to build it or not

**Comment by revant** [comment]
> I am not sure if there is a way to extend travis's time-out limit, maybe 15-20 mins, what I am guessing that will give us, at least, see if there is actual possibility to build it or not

Following can be done for jobs that need to wait, check the comment here https://github.com/frappe/frappe_docker/issues/380#issuecomment-767201476

```yaml
      script:
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:latest \
            -f build/frappe-nginx/Dockerfile .
```
Check how much time it takes. ~30 min should be okay I think. Ideally <20 is what we get for only amd64

**Comment by artykbasar** [comment]
I have tried the build with buildx whole thing took 2 hours with buildx.
I think if we want it to run quick currently, best way is, using travis's own arm64 platform for arm images and and amd64 platform for amd64 images then we can link them with Docker manifest. That took me less than hour

**Comment by artykbasar** [comment]
Does travis have 10000 credit limits on frapp's account?

**Comment by revant** [comment]
> I have tried the build with buildx whole thing took 2 hours with buildx.
I think if we want it to run quick currently, best way is, using travis's own arm64 platform for arm images and and amd64 platform for amd64 images then we can link them with Docker manifest.

Can how to do that? link them with Docker manifest?

> That took me less than hour

How long it took?

On the edge of hour is also too long. May be we should just run them on master branch instead of develop branch that runs daily.



> Does travis have 10000 credit limits on frappe's account?

I don't know, I think frappe has paid account. I have maintainer access to this repo, that gives me restricted access to control travis jobs related to this repo.

**Comment by artykbasar** [comment]
> 
> Can how to do that? link them with Docker manifest?
> 
1) created the images in different arches. In travis you can specify each stage's arch
2) then created another stage which merges those created arches

Here is how I did with docker manifest:
```
- stage: "Build Frappe bench development environment (latest)"
      if: branch = develop AND type != pull_request
      arch:
        - amd64
      script:
        - docker build -t ${REG}/bench:${ARCH}_latest -f build/bench/Dockerfile .
        - docker push ${REG}/bench:${ARCH}_latest
    - stage: "Build Frappe bench development environment (latest)"
      if: branch = develop AND type != pull_request
      arch:
        - arm64
      script:
        - docker build -t ${REG}/bench:${ARCH}_latest -f build/bench/Dockerfile .
        - docker push ${REG}/bench:${ARCH}_latest

    - stage: "Frappe Bench merge"
      arch:
        - amd64
      if: branch = develop AND type != pull_request
      script:
        - docker manifest create ${REG}/bench:latest ${REG}/bench:arm64_latest ${REG}/bench:amd64_latest
        - docker manifest push ${REG}/bench:latest
```

>
> > That took me less than hour
> 
> How long it took?
> 
> On the edge of hour is also too long. May be we should just run them on master branch instead of develop branch that runs daily.

Travis ran everything in 34 mins. Combined duration was 1hr 18 mins. I am not sure what number is most important. Here is the screenshot:
![Screenshot 2021-06-30 at 17 15 36](https://user-images.githubusercontent.com/78363421/123997976-e1ce1c80-d9c8-11eb-8bfe-451486f9d3d8.png)
In case if you want to check the travis built in detail here is the link
https://travis-ci.com/github/artykbasar/frappe_docker/builds/231395874


> I don't know, I think frappe has paid account. I have maintainer access to this repo, that gives me restricted access to control travis jobs related to this repo.

Cool I didn't know that. 

Do you thinks it is still possible to include arm64 in the official builds or we will have to wait till builds get faster?

**Comment by revant** [comment]
What if we just build v13 latest stable for arm64.

I'm keen on keeping runs short because I don't know if we might move to some other CI.

Frappe framework repo moved to GitHub actions I think.

**Comment by artykbasar** [comment]
> What if we just build v13 latest stable for arm64.
> 
> I'm keen on keeping runs short because I don't know if we might move to some other CI.
> 
> Frappe framework repo moved to GitHub actions I think.

You are right I was thinking of moving my app builds to the Github actions as well.
Then I am thinking when everything will transition to the Github actions at that time we can think about arm64 then.

**Comment by japatel5213** [comment]
I want to install ERPNext on ARM-Based architecture. How to? Have Any Script?

**Comment by JomoliTech** [comment]
> 

You should be able to do it by cloning the repo, stepping into the frappe-docker directory and then using buildx in three steps:
frappe-bench, frappe-development, erpnext-development and then using docker-compose to start and run them

**Comment by carstenblt** [comment]
I built all of frappe-worker, erpnext-worker, frappe-nginx, erpnext-nginx and frappe-socketio successfully. For redis you have to use the official image and change the CMD instead of supplying the variable to change the port. Everything else just works.

**Comment by rajat-tomar** [comment]
> I built all of frappe-worker, erpnext-worker, frappe-nginx, erpnext-nginx and frappe-socketio successfully. For redis you have to use the official image and change the CMD instead of supplying the variable to change the port. Everything else just works.

Hey @carstenblt , can you please elaborate more on this. I mean what did you update in CMD part of redis and how were you able to build the arm64 images for frappe? Thanks!

**Comment by carstenblt** [comment]
> Hey @carstenblt , can you please elaborate more on this. I mean what did you update in CMD part of redis and how were you able to build the arm64 images for frappe? Thanks!

Building is as simple as

`REGISTRY_USER=XXX FRAPPE_VERSION=v14.19.1 ERPNEXT_VERSION=v14.10.1 docker buildx bake -f docker-bake.hcl --progress auto --set "*.platform=linux/arm64" erpnext-worker erpnext-nginx frappe-socketio`

As for redis, you just have to change CMD to `redis-server --port XXXX`. I'm running on AWS ECS, this definition should give you the gist:

```
"containerDefinitions": [
        {
            "name": "cache",
            "image": "redis:6.2-alpine",
            "portMappings": [
                {
                    "containerPort": 13000,
                    "hostPort": 13000,
                    "protocol": "tcp"
                }
            ],
            "essential": true,
            "command": [
                "redis-server",
                "--port",
                "13000"
            ]
      },
      ...
],
```

**Comment by MohammedNoureldin** [comment]
Can't ARM64 images be built as part of the pipeline on every release? It will be much easier for people rely on ARM64 architecture.

**Comment by revant** [comment]
Every few months we add arm64 builds and then remove it because it is very slow to build.

https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-build-arm64-images

**Comment by MohammedNoureldin** [comment]
Thank you for your reply.

OK I understand now. The latest one (and actually the only one) I found in Docker Hub for frappe/erpnext is v13.49.4.

How slow is it? In my opinion, getting it (too) slowly built. is better than not having it at all. Is there any suggested alternatives or solutions? Maybe I can contribute to them.

**Comment by MohammedNoureldin** [comment]
@revant, another idea that came to my mind. Would you consider setting a monthly- or bimonthly scheduled build to build ARM64 of the latest version? By this ARM64 build will be frequently available and ARM users can stay up to date, while keeping the pipeline not busy. What do you think?

**Comment by carstenblt** [comment]
github will probably offer arm builders at some point. Until then hosting your own runner is the only viable option...

**Comment by MohammedNoureldin** [comment]
@carstenblt, I took 10 very known Docker images as an example, all of them have ARM64 in their pipeline using QEMU, of course. So waiting for GitHub to provide ARM64 runner is not the only viable way for many other Docker images. I do not see it as a problem if it takes long to build, as it can be just scheduled instead of being built every time.

**Comment by MohammedNoureldin** [comment]
I am sorry but could anyone give me a short guide or link how to build the whole ERPNext and Frappe stack? I have been for the last couple of days with no success. Though my target is to build for ARM64, I assume there should be no difference if I read a guide for x86 build.

**Comment by MohammedNoureldin** [comment]
Finally I got it working. Here are some notes for anyone who might come later willing to build it for ARM64:

- To build for ARM64, just spin up an ARM64 VPS and install `buildah`. The full Docker is not needed.
- It is as simple as following the *building with custom apps* [documentation](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md).
- make sure that the apps have a version compatible with the image you are building (for example make sure to not have apps for version 14 when building version 15)
- For my case I was interested in building an image that will be later used in K8s cluster. I I noticed that some older versions of mariadb charts were built for AMD but not ARM64. However, the new ERPNext Helm charts seem to use MariaDB charts that were also built for ARM64. At the moment I tested [ERPNext Helm Chart 7.0.14](https://artifacthub.io/packages/helm/erpnext/erpnext/7.0.14). So in practice nothing should be done when.

**Comment by MohammedNoureldin** [comment]
Does anyone have an issue lately while building for ARM64?

```
...
I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md
verbose 23.752022999 
verbose 23.76898318 
verbose 26.893875919 /home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp-build/node-gyp-build.js:60
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.20.2
    loaded from: /home/frappe/frappe-bench/apps/frappe/node_modules/bufferutil

    at load.resolve.load.path (/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp-build/node-gyp-build.js:60:9)
    at load (/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp-build/node-gyp-build.js:22:30)
    at Object.<anonymous> (/home/frappe/frappe-bench/apps/frappe/node_modules/node-gyp-build/build-test.js:19:19)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.20.2

gyp info it worked if it ends with ok
...
```

**Comment by MohammedNoureldin** [comment]
The issue was a trailing comma `,` in the last element of Apps JSON array.

```
  export APPS_JSON='[
    {
      "url": "https://github.com/frappe/erpnext",
      "branch": "v15.25.0"
    },
    {
      "url": "https://github.com/frappe/helpdesk",
      "branch": "0.10.0"
    }, <<<<<------ !!! HERE IS THE ISSUE !!!
  ]'
```

Basically this is known to be not very correct according to JSON, though I would expect a cleaner error message.
