### ISSUE TITLE
What’s  the password for user su root in erpnext-python_1 docker?

### ISSUE THREAD

**Issue by jackwiy** [frappe/frappe_docker#497]
docker exec -it xx_erpnext-python_1 bash

$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/

$ su root
Password:
su: Authentication failure

**Comment by jackwiy** [comment]
it is ok now

docker exec -it -u root xx_erpnext-python_1  bash

apt-get update

**Comment by revant** [comment]
Just for note:

Docker containers are not supposed to be used like VM.

When you need to update, get the latest container Image and restart the container with new image.
