### ISSUE TITLE
Readme improvement

### ISSUE THREAD

**Issue by tjscomics** [frappe/frappe_docker#5]
The following command does not work actually (inside docker container):
```bash
cd ..
bench init --skip-bench-mkdir --skip-redis-config-generation frappe-bench && cd frappe-bench
```
It seems that access to some directories requires `root` permissions ...

**Comment by tjscomics** [comment]
It works if I do the following beforehand:
```bash
docker exec -it --user root frappe bash
cd ..
chown -R frappe:frappe frappe-bench
exit
```

**Comment by vishalseshagiri** [comment]
Which system are you on?

**Comment by vishalseshagiri** [comment]
Changes made to readme
