### ISSUE TITLE
Docker swarm and links

### ISSUE THREAD

**Issue by chabad360** [frappe/frappe_docker#50]
As of right now, the current compose file doesn't work too well with docker swarm for a few reasons, mainly because it uses Compose File Version 2, not Version 3, and because it uses links. I have tried removing the links, but then frappe keeps crashing during setup. Does someone know what we need links for?

**Comment by Thunderbottom** [comment]
so we have multiple different containers for database and frappe itself. we use links to resolve inter container dependencies. I am unsure if it works without linking though. Have you tried (not in the swarm) that it works without links?

**Comment by chabad360** [comment]
Frappe refuses to finish the GUI setup, without links.

**Comment by chabad360** [comment]
That i figured, but what are the actual dependencies? Maybe there are work-arounds, something?

**Comment by Thunderbottom** [comment]
I am unsure, best is to let it be I guess? I will figure something out over the weekend.

**Comment by chabad360** [comment]
Cool. If I get a chance too, I'll look into it too.

**Comment by chabad360** [comment]
I think it's only needed for configuring what the ip for redis and MySQL is on. 

Which can be replaced by a defined network.

**Comment by pipech** [comment]
Hi, you should check out this yml file, I using my own erpnext image but with a little tweak it should works with official docker image too.
This works with docker stack and should be work using docker swarm too.

https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/prd.yml

**Comment by chabad360** [comment]
@pipech thanks for that, I see quite a few things that I'll take from your yml and add to mine.
