### ISSUE TITLE
404 Not Found Docker Swarm

### ISSUE THREAD

**Issue by lapillaga** [frappe/frappe_docker#501]
Hi! I ran my stack with docker swarm configuration but when I access to my `erp.domain.com` in my web browser it shows erp.domain.com does not exist. These are my python and nginx logs:
- nginx
```
"GET / HTTP/1.1" 404 149 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" "10.0.0.2"
```
- python
```
[2021-07-12 21:25:09 +0000] [17] [INFO] Starting gunicorn 20.1.0
[2021-07-12 21:25:09 +0000] [17] [INFO] Listening at: http://0.0.0.0:8000 (17)
[2021-07-12 21:25:09 +0000] [17] [INFO] Using worker: gthread
```
I run my stack with these files:
- traefik.yml
https://gist.github.com/lapillaga/0448985c924f5a763a73c5767bd085ec
- frappe-mariadb.yml
https://gist.github.com/lapillaga/f1dbcb7e66f3d1a416fb1bb6130970e0
- frappe-bench-v13.yml
https://gist.github.com/lapillaga/103aea7b3372b2c6569173d74ffd11eb

I run all this files with `docker stack deploy ` command. In my research I found that it cloud be a problem related with traefik config.

**Comment by revant** [comment]
can you check the traefik ui and is it serving proper service for http(s)?

**Comment by lapillaga** [comment]
Sure. I have changed my custom domain to `erp.domain.com`
- Routers
![image](https://user-images.githubusercontent.com/42658241/125501576-7fe4025c-43ea-43e6-8f82-b59351d687c4.png)

- Services
![image](https://user-images.githubusercontent.com/42658241/125501744-80712d3c-437a-4017-b543-6933e93bfeef.png)

- erpnext-nginx@docker
![image](https://user-images.githubusercontent.com/42658241/125501969-e3bcd093-9f05-4658-9578-dba5e4000260.png)

**Comment by revant** [comment]
I don't know what's wrong.

Are all containers running without restarts? Must be running.

Recently, I've been asking ssh access to people's servers to debug any docker issues. That saves a lot of time. I install 2-3 such swarms weekly.

my keys: https://github.com/revant.keys
Contact me on telegram, you'll find me in ERPNext group. https://t.me/erpnexthelp

**Comment by revant** [comment]
After logging into your machine I found out you were not following the documentation.

your stack had erpnext-worker-create instead of erpnext-worker-default. It was doing the job of site-creator from simple setup.
