### ISSUE TITLE
404 page not found && Access denied for user 'frappe'@'172.19.0.12'

### ISSUE THREAD

**Issue by satyajitghana** [frappe/frappe_docker#502]
## Description of the issue

I've tried a lot to setup frappe docker-compose locally, but failed.

## Context information (for bug reports)

I haven't been able to use port 80, and traefik complains about port 80 already being used, so i've mapped it to 9080 instead in compose. But still there are other problems that pop up

erpnext nginx dies: `frappe_docker_erpnext-nginx_1 exited with code 124`

db access denied

```
mariadb_1                 | 2021-07-23 11:21:34 146 [Warning] Access denied for user 'frappe'@'172.19.0.12' (using password: NO)
mariadb_1                 | 2021-07-23 11:26:34 183 [Warning] Access denied for user '_69928f0f6369849a'@'172.19.0.12' (using password: YES)
```

although the user `_69928f0f6369849a` is created

```
site-creator_1            | Created user _69928f0f6369849a
site-creator_1            | Created database _69928f0f6369849a
mariadb_1                 | 2021-07-23 11:21:33 108 [Warning] 'proxies_priv' entry '@% root@70594c8ec6f2' ignored in --skip-name-resolve mode.
site-creator_1            | Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
site-creator_1            | Starting database import...
```

site-creator, erpnext workers also report as connections ok

```
site-creator_1            | Attempt 3 to connect to mariadb:3306
site-creator_1            | Attempt 1 to connect to redis-queue:6379
site-creator_1            | Attempt 1 to connect to redis-cache:6379
site-creator_1            | Attempt 1 to connect to redis-socketio:6379
site-creator_1            | Connections OK
erpnext-worker-default_1  | Attempt 2 to connect to mariadb:3306
erpnext-worker-default_1  | Attempt 1 to connect to redis-queue:6379
erpnext-worker-default_1  | Attempt 1 to connect to redis-cache:6379
erpnext-worker-default_1  | Attempt 1 to connect to redis-socketio:6379
erpnext-worker-default_1  | Connections OK
erpnext-worker-long_1     | Attempt 2 to connect to mariadb:3306
erpnext-worker-long_1     | Attempt 1 to connect to redis-queue:6379
erpnext-worker-long_1     | Attempt 1 to connect to redis-cache:6379
erpnext-worker-long_1     | Attempt 1 to connect to redis-socketio:6379
erpnext-worker-long_1     | Connections OK
```

site-creator exits !

```
site-creator_1            | Updating customizations for Address
site-creator_1            | Updating customizations for Contact
site-creator_1            | *** Scheduler is disabled ***
mariadb_1                 | 2021-07-23 11:32:24 189 [Warning] 'proxies_priv' entry '@% root@70594c8ec6f2' ignored in --skip-name-resolve mode.
mariadb_1                 | 2021-07-23 11:32:24 190 [Warning] 'proxies_priv' entry '@% root@70594c8ec6f2' ignored in --skip-name-resolve mode.
mariadb_1                 | 2021-07-23 11:32:25 178 [Warning] Aborted connection 178 to db: '_69928f0f6369849a' user: '_69928f0f6369849a' host: '172.19.0.10' (Got an error reading communication packets)
frappe_docker_site-creator_1 exited with code 0
```

I have no clue what's wrong !

I've tried PWD and it works fine ! (there was once a out of space error, but ran it a second time and it worked)

I'm not able to run it locally though, i've tried out on 3 different systems now.

Also i thought this could be because i'm accessing it through ip (192.168.0.x) instead of mysite.localhost, so i did try to open `mysite.localhost:9080` ON the host system itself. but same thing, 404

I've tried both `edge` and `v13`, the db issue is there on both

## Steps to reproduce the issue

1. set the .env file to v13

```
ERPNEXT_VERSION=v13
FRAPPE_VERSION=v13
```

2. set traefik port mapping in docker-compose

```
    ports:
      - "9080:80"
      - "9443:443"
```

Here's my docker-compose https://pastebin.com/RLVMVymX
and .env file: https://pastebin.com/5xDkjpKU

3. Open `<ip>:9080`

### Observed result

404 page not found

### Expected result

Login Page?

### Stacktrace / full error message if available

here's the dump with `v13`: https://pastebin.com/aHuassxP
here's the dump with `edge` : https://pastebin.com/QJpewVPN

**Comment by satyajitghana** [comment]
UPDATE:

I tried it on another machine

Now i'm getting Internal Server Error

dump with `edge`: https://pastebin.com/K3mLggRM

```
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py", line 64, in connect
erpnext-python_1          |     self._conn = self.get_connection()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 80, in get_connection
erpnext-python_1          |     local_infile=frappe.conf.local_infile
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
erpnext-python_1          |     self.connect()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 633, in connect
erpnext-python_1          |     self._request_authentication()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 907, in _request_authentication
erpnext-python_1          |     auth_packet = self._read_packet()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
erpnext-python_1          |     packet.raise_for_error()
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
erpnext-python_1          |     err.raise_mysql_exception(self._data)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
erpnext-python_1          |     raise errorclass(errno, errval)
erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_69928f0f6369849a'@'172.19.0.6' (using password: YES)")
```

**Comment by satyajitghana** [comment]
Don't ask me why

changed to `test.localhost` in `.env`

`docker-compose up -d`
`docker logs frappe_docker_site-creator_1 -f`

wait for it to finish

open http://test.localhost/ on chrome

it works :smile: 

if someone knows why please tell me why this worked

**Comment by revant** [comment]
> ite name must be resolvable by users machines and the ERPNext components. e.g. erp.example.com or mysite.localhost.

https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md#setup-environment-variables search for `.localhost`

If you're trying things locally, not for development, just to test before actually deploying on VM with IP and DNS then try it with *.localhost as site names.

Also it needs at least 2 GB Memory. If you're running VM with 1GB RAM add 1GB swap.

**Comment by satyajitghana** [comment]
Yes thanks !

I'm going to try few more things, I was able to get it working on local machine, with test.localhost but not with an ip.

I have a very vague understanding of how traefik and DNS work.

what changes do I need to do to acces it using an ip 192.168.0.3 ? like a different machine but on the same local network

I'm guessing I have to modify hosts file to point to that ip ?
