### ISSUE TITLE
Broken frappe-socketio:edge after update

### ISSUE THREAD

**Issue by lpadula** [frappe/frappe_docker#514]
Hi, i have two different instance of erpnext dockerized and afther the last update, both are broken.

## Steps to reproduce the issue

1. cd frappe_docker
2. docker-compose pull
3. docker-compose --project-name <project_name> up -d

The problem seems to be:

frappe/frappe-socketio:edge 

When I run: docker ps

![image](https://user-images.githubusercontent.com/1341504/132109415-fdcfb84b-5490-4873-9ca9-e75387a8d1b0.png)

When I run: docker logs erp.broobe.com_site-creator_1 -f

docker logs erp.broobe.com_site-creator_1 -f

![image](https://user-images.githubusercontent.com/1341504/132109435-e8c9f801-a964-4085-8cc8-f5e0a4a5b905.png)

**Comment by revant** [comment]
Start redis and Mariadb containers
