### ISSUE TITLE
Images for various Python versions

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#518]
**Is your feature request related to a problem? Please describe.**
Currently, Frappe provides Docker images only for Python 3.7. 3.7 is kinda old. I work on Frappe app that work on Python 3.9 only and I have to rebuild images myself just changing image `python:3.7-slim-buster` to `python:3.9-slim-buster`.

**Describe the solution you'd like**
I propose we add new environment variable PYTHON_VERSION and leave 3.7 as default version. Also, image tags would change, for example, instead of `frappe/erpnext-worker:v13.11.0` we will have `frappe/erpnext-worker:v13.11.0` (default Python 3.7), `frappe/erpnext-worker:v13.11.0-3.7`, `frappe/erpnext-worker:v13.11.0-3.8` and `frappe/erpnext-worker:v13.11.0-3.9`.

@revant Do you think this should be worked on?

**Comment by revant** [comment]
For now build custom images for what you need. OR send a PR that can take --build-args for what you intend to do and defaults to 3.7.

3.7 is selected because it is what is used to test the framework https://github.com/frappe/frappe/blob/develop/.github/workflows/server-mariadb-tests.yml

**Comment by vrslev** [comment]
I see. Frappe seems to be working great on Python 3.9 in my day-to-day.
`--build-arg` (`docker build`) and `.env` (`docker-compose build`) is practically the same thing if I understand correctly. Or you mean something else?

**Comment by vrslev** [comment]
I will work on it after some time but I don't think I can make Travis CI work. What to do with it?

**Comment by vrslev** [comment]
@revant Forgot to tag you

**Comment by revant** [comment]
Option 1: fork repo, change the image tags where it is used in Dockerfile(s)

Option 2: add `ARG PY_IMAGE_TAG=3.7-slim-buster` to Dockerfile(s) and use it instead of tag; `FROM python:${PY_IMAGE_TAG}` and send a PR. Then when you fork you don't need to hard code anything, just use build arg during docker build command and pass the PY_IMAGE_TAG, e.g.  `docker --build-arg=PY_IMAGE_TAG=3.9-slim-buster build ...`

Don't tag me.
Mostly I'll only reply on this repo.

**Comment by revant** [comment]
re-open if needed.

**Comment by vrslev** [comment]
Since we you Buildx Bake and GitHub Actions it is quite easy to build for different Python versions. Need to change some code in `docker-bake.hcl` and add python-version to workflow matrix

**Comment by vrslev** [comment]
Can't actually re-open the issue

**Comment by vrslev** [comment]
@revant Do you support the idea to add builds for different Pythons?

**Comment by revant** [comment]
I kept it consistent with tests to minimize the overheads for maintaining the repo (issues, pulls and major upgrades)

**Comment by vrslev** [comment]
@revant Month ago workflow for tests has been changed: now they are ran on Python 3.9. That was your argument for 3.7. Should we just change it to Python 3.9?

**Comment by revant** [comment]
Yes!! 3.9 should be base then!

**Comment by vrslev** [comment]
I’ll send PR

**Comment by vrslev** [comment]
#540

**Comment by revant** [comment]
Can you re-open now?

**Comment by vrslev** [comment]
Yep
