### ISSUE TITLE
Missing packages required for WeasyPrint in frappe-worker 

### ISSUE THREAD

**Issue by dtwm** [frappe/frappe_docker#526]
## Description of the issue
Image for `frappe-worker` doesn't have some packages required by `weasyprint` package. Due to that when trying to start ERP-next `site-creator` fails.

## Context information
While using `develop` branch `site-creator` failed on importing `weasyprint` with message of missing `libcairo-2` package

## Steps to reproduce the issue
0. Checkout develop branch
1. Copy `env-local` to `.env`
2. Start project with docker-compose
3. Logs of `site-creator` shows critical error on importing `weasyprint`
4. Project isn't configured and doesn't work.

## Solution
Add more packages in frappe-worker Dockerfile. 
I had to add `libcairo2 python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0 libpangocairo-1.0-0` but I'm not really familiar with weasyptint so that might be excessive. 
Weasyprint documentation state https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#debian-11 that for debian only `python3-cffi python3-brotli libpango-1.0-0 libpangoft2-1.0-0` are needed but I was not able to run without explicit installation of `libpangocairo`.

**Comment by vrslev** [comment]
@dtwm Will you send PR to fix this?

**Comment by dtwm** [comment]
sorry, was away for a while.

**Comment by todfox** [comment]
Same issue. Anything I can do to help?

**Comment by revant** [comment]
merged #537
