### ISSUE TITLE
Watch for CI Jobs

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#529]
- [x] Watch for the daily builds https://github.com/frappe/frappe_docker/actions/runs/1401133843,
- [x] PR builds, https://github.com/frappe/frappe_docker/actions/runs/1402283292
- [x] stable builds https://github.com/frappe/frappe_docker/actions/runs/1403988132
- [x] helm release https://github.com/frappe/frappe_docker/actions/runs/1403988132

@vrslev please help as needed!

**Comment by vrslev** [comment]
> why docker login fails on PR?

Begin in #533

**Comment by revant** [comment]
helm release step failed.

cannot use `uses` with `run`.

**Comment by revant** [comment]
everything seems to be working as expected!

Thanks gavin and lev!

Now we need to replace

1. https://github.com/frappe/frappe/blob/version-13/.github/workflows/docker-release.yml
2. https://github.com/frappe/erpnext/blob/version-13/.github/workflows/docker-release.yml
3. https://github.com/frappe/frappe/blob/develop/.github/workflows/docker-release.yml
4. https://github.com/frappe/erpnext/blob/develop/.github/workflows/docker-release.yml
