### ISSUE TITLE
Update the automated trigger on Frappe and ERPNext Release to build docker images 

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#535]
Previously the ReST API request was made to Travis, Now it needs to change to GitHub Actions.

- [x] https://github.com/frappe/frappe/blob/version-13/.github/workflows/docker-release.yml
- [x] https://github.com/frappe/erpnext/blob/version-13/.github/workflows/docker-release.yml
- [x] https://github.com/frappe/frappe/blob/develop/.github/workflows/docker-release.yml
- [x] https://github.com/frappe/erpnext/blob/develop/.github/workflows/docker-release.yml

**Comment by revant** [comment]
Following fommand triggers workflow stable release workflow

```shell
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: Bearer $TOKEN" \
  https://api.github.com/repos/frappe/frappe_docker/actions/workflows/build_stable.yml/dispatches \
  -d '{"ref":"main"}'
```

@vrslev do we need to setup https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency

**Comment by revant** [comment]
- https://github.com/frappe/frappe/pull/14865
- https://github.com/frappe/erpnext/pull/28191
- https://github.com/frappe/frappe/pull/14868
- https://github.com/frappe/erpnext/pull/28192

**Comment by vrslev** [comment]
Is it working locally? I guess it is fine then. Also, maybe use https://github.com/actions/github-script for readability or https://cli.github.com (it is included to environment)

**Comment by vrslev** [comment]
There definitely should be some kind of concurrency lock.
We can setup GHA concurrency and check if there were recent runs with ‘repository_dispatch’ trigger.

I see another issue. Usually major releases are published in the same day. What if ERPNext repo triggers a build and it build upon old frappe image?
