### ISSUE TITLE
Pack worker command in Python package

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#547]
Now we have chaotic and purely tested Python scripts for that. I suggest to package it all in one centralised thing.
I have interest in doing it myself. @revant What do you think?

**Comment by revant** [comment]
Initially I added few scripts because installing bench increased size of the image.
After some time I made a wrapper shell script for bench_helper from frappe.
It exposes all bench commands from framework and installed apps.

worker, schedule, new, migrate, drop, console, doctor, backup, console are available as `bench <command>` using bench_helper

`start` selects worker type
`push-backup` and `restore-backup` push and restore from given S3 bucket with specified structure.

**Comment by vrslev** [comment]
Frappe has S3 integration in itself. Why not use it?

**Comment by revant** [comment]
> Frappe has S3 integration in itself. Why not use it?

It is used by site user anyway.

These scripts are for devops/infra user.

**Comment by vrslev** [comment]
> worker, schedule, new, migrate, drop, console, doctor, backup, console are available as bench <command> using bench_helper

Why do you keep these scripts instead of redirecting to bench helper?

**Comment by revant** [comment]
:sweat_smile: Didn't change it after adding `bench` script. You can do that.

In case of new site, the new script does what `bench new-site --no-mariadb-socket ...` does. If --no-mariadb-socket is not used then the database user is created as `db_name@localhost` instead of `db_name@%`

**Comment by vrslev** [comment]
What about environment variables? They're used hardly in the scripts

**Comment by revant** [comment]
they are used as params/options to the command, like bench new-site $SITE_NAME etc.

I don't think we need to change this here.

We need to change the docs everywhere else.

helm.erpnext.com, frappe_docker/docs and frappe_docker/wiki

Let this remain for backward compatibility or people using existing scripts in their setup. May be remove it after sufficient time the new doc / migration doc is available.

**Comment by vrslev** [comment]
We can remove Python scripts and redirect to bench command for now.
For example:
```diff
  worker)
    checkConfigExists
    checkConnection
    # default WORKER_TYPE=default

-    /home/frappe/frappe-bench/env/bin/python /home/frappe/frappe-bench/commands/worker.py
+  if [[ -z "$WORKER_TYPE" ]]; then
+    $WORKER_TYPE=default
+  fi
+  bench worker --queue $WORKER_TYPE
    ;;
```

**Comment by vrslev** [comment]
> Let this remain for backward compatibility or people using existing scripts in their setup.

If we are talking about scripts like `worker.py`—that's internal thing. It's okay to refactor internals if frontend keeps the same.

**Comment by vrslev** [comment]
Why is there https://github.com/frappe/frappe_docker/blob/main/build/frappe-worker/healthcheck.sh when we have https://github.com/frappe/frappe_docker/blob/main/build/frappe-worker/commands/check_connection.py?

**Comment by revant** [comment]
> Why is there https://github.com/frappe/frappe_docker/blob/main/build/frappe-worker/healthcheck.sh when we have https://github.com/frappe/frappe_docker/blob/main/build/frappe-worker/commands/check_connection.py?

python health check was slower than using shell script health check.

https://github.com/frappe/frappe_docker/issues/346

**Comment by vrslev** [comment]
Should we replace Python script with bash script completely?

**Comment by revant** [comment]
> Should we replace Python script with bash script completely?

yes!

**Comment by vrslev** [comment]
It is irrelevant, closing the issue.
