### ISSUE TITLE
Helm chart release fails

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#560]
Frappe Docker stable build runs fail because helm release is unsuccessful:
https://github.com/frappe/frappe_docker/runs/4162821011?check_suite_focus=true

**Comment by revant** [comment]
error with git credentials

https://github.com/frappe/frappe_docker/runs/4165528872?check_suite_focus=true

planning to use https://github.com/marketplace/actions/configure-git-credentials

**Comment by revant** [comment]
#561
