### ISSUE TITLE
[Deployment help] Installing ERPNext with frappe_docker

### ISSUE THREAD

**Issue by TheBlapse** [frappe/frappe_docker#568]
Hello everyone,

I am trying to install ERPNext with Frappe Docker and I have litespeed webserver running at port `443` and port `80` and `8000` are reserved too, I have changed `443` to `123`, `80` to `1234` and `8000` to `1231`, but I am not able to see the site working at neither `<ip>:123` nor at `<ip>:1234` nor at `<ip>:1231`. I am a newbie, could anyone help me where I am wrong? 

Here's my `docker-compose.yml` file which I am using.

https://github.com/TheBlapse/frappe_docker/blob/main/docker-compose.yml

**Comment by revant** [comment]
check this if it helps https://discuss.erpnext.com/t/erpnext-behind-nginx-reverse-proxy/70885/2?u=revant_one

**Comment by TheBlapse** [comment]
@revant no not working.

**Comment by revant** [comment]
> I am a newbie

Share ssh access, add my github public keys.

I'll have to explore your system, how litespeed is configured, if I can publish erpnext ports on host machine and litespeed can proxy it? Lot of variables to explore.

I can't help without that because you may reply things like "no not working" for which I'll have to write few replies to extract out error or anything abnormal? (being a newbie you may not know what is normal and what is abnormal)

SSH access will be easier.

**Comment by TheBlapse** [comment]
Hey there, I have got everything running here without any errors. 
![image](https://user-images.githubusercontent.com/76247922/142379479-9459ccc8-9f97-4e22-8886-c3678612250a.png)

I am sure that my reverse proxy setup works as I have tried running a docker image, I have set up port number 8080 in erpnext-nginx container and reverse proxy. Also used env-local and instead of mysite.localhost I have added my site's name, but when I visit it it says 
`Not Found localhost does not exist`

**Comment by TheBlapse** [comment]
Also @revant
 
```shell
$docker logs erp_site-creator_1 -f

Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _d9c7efd6acaad7b6
Created database _d9c7efd6acaad7b6
Granted privileges to user _d9c7efd6acaad7b6 and database _d9c7efd6acaad7b6
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***
```

site_creator logs say this, so It should work, but it's saying localhost does not exist

**Comment by TheBlapse** [comment]
Now It's giving Error 502: Bad gateway

**Comment by revant** [comment]
i just created the site called "localhost".

then your Apache reverse proxy to "localhost", resolves the site and serves it.
