### ISSUE TITLE
404 Page not found after selinux profile applied to docker daemon

### ISSUE THREAD

**Issue by Tus1688** [frappe/frappe_docker#573]
## Description of the issue
Coming from #567 
Everything is working if I change to `"selinux-enabled": false`
## Context information (for bug reports)
Every container run as it supposed to be 
## Steps to reproduce the issue

1. `docker exec -it <hash of erpnext python> bash
2. `ls -lah`
3. I found my site
4. `curl -v http://mysitename.com.localhost:8000`
5. Got Connection refused
6. `curl mysitename.com:8000`
7. Got `curl: (7) Failed to connect to mysitename.com.localhost port 8000: Connection refused`

### Observed result
```
* Rebuilt URL to: http://mysitename.com.localhost:8000/
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8000 failed: Connection refused
* Failed to connect to mysitename.com.localhost port 8000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to mysitename.com.localhost port 8000: Connection refused
```
### Expected result
Can access my site using browser and curl
### Stacktrace / full error message if available
There is no error

**Comment by revant** [comment]
what is the SITE_NAME and SITES variable in .env file?

**Comment by Tus1688** [comment]
```
SITE_NAME=mysitename.com
SITES=`mysitename.com`
```

**Comment by revant** [comment]
so you can only visit that site domain to resolve site

try

```
curl -H "Host: mysitename.com" http://localhost/api/method/ping
```

**Comment by Tus1688** [comment]
Got `404 page not found`

> when you create sites make sure you name them so they resolve.
>use actual configured domain names in case of production use

I am using real domain here, but I am not sure if I can disclose my domain name so.. I reproduce it with `mysitename.com`

**Comment by revant** [comment]
why are you trying to connect to port 8000?
if you've not changed anything `curl https://mysitename.com` should work

**Comment by Tus1688** [comment]
>if you've not changed anything curl https://mysitename.com should work

I have never changed anything and still got `404 page not found`
Everything is working if selinux profile which is disabled by default is not applied to docker daemon.

**Comment by revant** [comment]
Okay. I can't help much for now. I'll have to manage to setup selinux. I'm on arch linux and it only supports selinux unofficially so I'm not going to mess with it right now.

I'll try virtualbox+rocky linux+selinux if it works. No ETA. I'll need to setup these things first. Anyone else can help.

**Comment by Tus1688** [comment]
Don't worry about me, take your time :)

**Comment by todfox** [comment]
I am having the same issue. 

Generating default template
Waiting for frappe-python to be available on erpnext-python port 8000
Frappe-python available on erpnext-python port 8000
Waiting for frappe-socketio to be available on frappe-socketio port 9000
Frappe-socketio available on frappe-socketio port 9000
2021/11/23 14:32:18 [notice] 1#1: using the "epoll" event method
2021/11/23 14:32:18 [notice] 1#1: nginx/1.21.4
2021/11/23 14:32:18 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2021/11/23 14:32:18 [notice] 1#1: OS: Linux 5.14.18-300.fc35.x86_64
2021/11/23 14:32:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/11/23 14:32:18 [notice] 1#1: start worker processes
2021/11/23 14:32:18 [notice] 1#1: start worker process 21
2021/11/23 14:32:18 [notice] 1#1: start worker process 22
2021/11/23 14:32:18 [notice] 1#1: start worker process 23
2021/11/23 14:32:18 [notice] 1#1: start worker process 24
2021/11/23 14:32:18 [notice] 1#1: start worker process 25
2021/11/23 14:32:18 [notice] 1#1: start worker process 26
2021/11/23 14:32:18 [notice] 1#1: start worker process 27
2021/11/23 14:32:18 [notice] 1#1: start worker process 28
2021/11/23 14:32:18 [notice] 1#1: start worker process 29
2021/11/23 14:32:18 [notice] 1#1: start worker process 30
2021/11/23 14:32:18 [notice] 1#1: start worker process 31
2021/11/23 14:32:18 [notice] 1#1: start worker process 32
2021/11/23 14:32:18 [notice] 1#1: start worker process 33
2021/11/23 14:32:18 [notice] 1#1: start worker process 34
2021/11/23 14:32:18 [notice] 1#1: start worker process 35
2021/11/23 14:32:18 [notice] 1#1: start worker process 36
2021/11/23 14:32:18 [notice] 1#1: start worker process 37
2021/11/23 14:32:18 [notice] 1#1: start worker process 38
2021/11/23 14:32:18 [notice] 1#1: start worker process 39
2021/11/23 14:32:18 [notice] 1#1: start worker process 40

**Comment by revant** [comment]
@todfox same issue means you've enabled selinux?

Your nginx container seems to have started correctly.

make sure the setup/config/labels uses port 8080 instead of port 80 for nginx container(s).

**Comment by Tus1688** [comment]
By the way, my nginx container log has similarity with what he has
```
Generating default template
Waiting for frappe-python to be available on erpnext-python port 8000
Generating default template
Waiting for frappe-python to be available on erpnext-python port 8000
Generating default template
Waiting for frappe-python to be available on erpnext-python port 8000
Frappe-python available on erpnext-python port 8000
Waiting for frappe-socketio to be available on frappe-socketio port 9000
Frappe-socketio available on frappe-socketio port 9000
2021/11/22 23:23:48 [notice] 1#1: using the "epoll" event method
2021/11/22 23:23:48 [notice] 1#1: nginx/1.21.4
2021/11/22 23:23:48 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
2021/11/22 23:23:48 [notice] 1#1: OS: Linux 4.18.0-305.19.1.el8_4.x86_64
2021/11/22 23:23:48 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/11/22 23:23:48 [notice] 1#1: start worker processes
2021/11/22 23:23:48 [notice] 1#1: start worker process 25
2021/11/22 23:23:48 [notice] 1#1: start worker process 26
```

**Comment by revant** [comment]
that means the nginx container is running correctly.

**Comment by tonicanada** [comment]
I'm having the same Issue, ¿which are the steps to follow to disable selinux? 
I've created the file /etc/docker/daemon.json with the following content:
{
        "selinux-enabled": false
}
I have also changed the line 47 in docker-compose.yml file, changing the port 80 to 8080.
  - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=80" to
  - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080"
And still having the same result "Bad Gateway", "404 not found".

**Comment by Tus1688** [comment]
@todfox , personally I have never set my selinux to permissive, if you have same issue like me, all I do is
1. `edit /etc/docker/daemon.json` and set it to false
2. `sudo systemctl restart docker`
3. Removing all container that created after applying selinux profile to docker daemon, I think it should do the trick

@tonicanada , /etc/docker/daemon.json is enabled optionally, so if you have never set it to true, you don't need to set it to false. if you used to enable it, make sure to do `systemctl restart docker` and verified that selinux profile isn't applied to docker daemon by typing `docker info`
```
...
Security Options:
  seccomp
   Profile: default
...
```

ps. I didn't change any port configuration

**Comment by revant** [comment]
> I didn't change any port configuration

https://github.com/frappe/frappe_docker/blob/5aae67117c92bb144c1a5a7496e6d929d2f862cc/docker-compose.yml#L47

in the latest code the port is 8080, before it was 80 when nginx container was running as root.

**Comment by tonicanada** [comment]
I still can't update to 13.5 version and I don't have enabled selinux. It show "bad gateway" when I try to access the app in the browser. Does anyone know how to update from 13.14.1 to 13.5.0 with docker?

**Comment by revant** [comment]
> Does anyone know how to update from 13.14.1 to 13.5.0 with docker?

make sure the traefik label for loadbalancer port is 8080: `traefik.http.services.erpnext-nginx.loadbalancer.server.port=8080`

**Comment by tonicanada** [comment]
> 
Yes, I've made "docker-compose --project-name erpnext down", changed that line in "docker-compose.yml", to port 8080, but still fails. Did I miss some step? Thanks.

**Comment by revant** [comment]
> 13.14.1 to 13.5.0

sure this is not a typo? 13.14.1 to 13.**15**.0
13.5.0 if it exists is using port 80

**Comment by tonicanada** [comment]
It's a typo, I'm trying to update from 13.14.1 to 13.15.0.

**Comment by revant** [comment]
@tonicanada you should start another issue or forum post if it's not really related to selinux.

Also just changing the version updates the code, you still have to somehow execute `bench --site site.name.com migrate` or https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#migrate-site to run the patches and schema migration.

**Comment by tonicanada** [comment]
Hi! Any update or progress with this issue? Thanks in advance.
