### ISSUE TITLE
Custom apps documentation results in DB access denied

### ISSUE THREAD

**Issue by JPaulMora** [frappe/frappe_docker#578]
## Description of the issue
Hi i followed the instructions shown [here](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps-for-production.md) to add my custom app to the repo.

App is simple with 4 DocTypes created

## Steps to reproduce the issue

1. Create custom app in local dev environment
2. Create production setup in remote/staging environment
3. Add custom app following instructions linked above

### Observed result
Main site fails with status 500 and logs show worker returning access denied from database.

I am trying to debug the issue but I cant find where or how is docker reading my file on `docker-compose-custom.yml`

### Expected result
Fresh install with new app listed as installed.

### Stacktrace / full error message if available

```
erpnext-python_1          |     err.raise_mysql_exception(self._data)
erpnext-python_1          |   File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
erpnext-python_1          |     raise errorclass(errno, errval)
erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_3b1cec08e3d9b4e6'@'172.21.0.8' (using password: YES)")

# Also found this error 
site-creator_1            | Could not find app "kecustom_crm"
```

**Comment by revant** [comment]
We need some different way to make the example files/templates.

Check this repo for now how it builds images. It is currently hosted app.

Source: https://github.com/revant/erpnext_feature_board
Production: https://board.castlecraft.co.in

**Comment by revant** [comment]
> erpnext-python_1          | pymysql.err.OperationalError: (1045, "Access denied for user '_3b1cec08e3d9b4e6'@'172.21.0.8' (using password: YES)")

try to execute these lines in mariadb shell, https://github.com/frappe/frappe_docker/blob/main/development/README.md#fixing-mariadb-issues-after-rebuilding-the-container

> site-creator_1            | Could not find app "kecustom_crm"

sites/apps.txt needs to have list of apps installed in py environment.

**Comment by JPaulMora** [comment]
@revant I understand it must be installed, however I followed the instructions which are supposed to achieve just that. Would appreciate some updated instructions if they're available.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#edit-configs

add your apps in apps.txt using following command.

```
docker run \
    -it \
    -v frappe_docker_sites-vol:/sites \
    alpine vi /sites/apps.txt
```

Note:

- `frappe_docker_sites-vol` is the name of volume where sites directory exists.
- `vi` will be used to edit the `apps.txt`

**Comment by vrslev** [comment]
> Edit: DB access denied is a mystery that I can't solve!

@revant My guess, it is ping by health check.

**Comment by revant** [comment]
> @revant My guess, it is ping by health check.

it's just check host:port can you try to ping manually and check if the logs show the message?

**Comment by vrslev** [comment]
@revant Will do tomorrow

**Comment by vrslev** [comment]
`python3 ~/frappe-bench/commands/doctor.py ` and `python3 ~/frappe-bench/commands/check_connection.py`  get this logs generated:
```console
docker-mariadb-1         | 2021-12-02 21:18:01 139 [Warning] Aborted connection 139 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.15' (This connection closed normally without authentication)
docker-mariadb-1         | 2021-12-02 21:18:17 155 [Warning] Aborted connection 155 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.15' (This connection closed normally without authentication)
```

**Comment by vrslev** [comment]
Tried to initialise new bench with `bench init` and it still has this messages!
```console
2021-12-03  0:40:13 3 [Warning] Access denied for user '_8e62d73f722067cc'@'localhost' (using password: YES)
2021-12-03  0:40:17 5 [Warning] Aborted connection 5 to db: '_8e62d73f722067cc' user: '_8e62d73f722067cc' host: 'localhost' (Got an error reading communication packets)
2021-12-03  0:42:23 7 [Warning] Aborted connection 7 to db: '_8e62d73f722067cc' user: '_8e62d73f722067cc' host: 'localhost' (Got an error reading communication packets)
```

So, the problem is with Frappe framework itself.

**Comment by JPaulMora** [comment]
Hey @revant sorry for late reply 
>add your apps in apps.txt using following command.

I'll test this and report back, thanks everyone else for your help.

**Comment by workpush** [comment]
I have the same issue. What has actually changed? 2-3 weeks ago everything worked fine for me?

**Comment by vrslev** [comment]
@workpush I think, [new bench release](https://github.com/frappe/bench/releases/tag/v5.7.0) causes this. Can you leave an issue to [frappe/bench](https://github.com/frappe/bench/issues) repo?

**Comment by workpush** [comment]
> @workpush I think, [new bench release](https://github.com/frappe/bench/releases/tag/v5.7.0) causes this. Can you leave an issue to [frappe/bench](https://github.com/frappe/bench/issues) repo?

Is there a way where I can define which bench version is used in the docker-image(s)?
".env" file is just giving me the possibility to select:
```
ERPNEXT_VERSION=v13
FRAPPE_VERSION=v13
```

**Comment by vrslev** [comment]
@workpush Oh, I was wrong. I though this issue is relevant to frappe/bench image. frappe/frappe-worker image doesn’t have bench installed. 

When you build image with custom app you have to append name of app to /home/frappe/frappe-bench/sites/apps.txt. It is the way for frappe to check if app is “installed”
