### ISSUE TITLE
Script report boilerplates not being generated

### ISSUE THREAD

**Issue by Meradoch** [frappe/frappe_docker#583]
I created a named-volume on erpnext-worker-default that I linked to /home/frappe/frappe-bench/apps. My intention was that I be able to create script reports easily and sync them on my github. I have enabled developer mode but I still can't see the new report folder. I'm creating the script report as an administrator but the py, json and js files are not being generated in my erpnext folder. What could I be doing wrong? I'm on v13.15.0 for both erpnext and frappe and using docker.

**Comment by revant** [comment]
Production images are immutable. You'll have you build your apps into image and then deploy it.

Check how the images are made, the install py packages into the py env.

use the frappe/bench:latest image for development

**Comment by Meradoch** [comment]
Thank you, thank you, you are far too kind.
