### ISSUE TITLE
docker compose installation error, site create can't start *** Scheduler is disabled ***

### ISSUE THREAD

**Issue by weilingwei** [frappe/frappe_docker#584]
Updating DocTypes for erpnext       : [======================================= ] 99%
Updating DocTypes for erpnext       : [======================================= ] 99%
Updating DocTypes for erpnext       : [======================================= ] 99%
Updating DocTypes for erpnext       : [======================================= ] 99%
Updating DocTypes for erpnext       : [========================================] 100%,
Updating customizations for Address,
Updating customizations for Contact,
*** Scheduler is disabled ***

above logs

**Comment by weilingwei** [comment]
site-creator 
After starting, the log is executed as
Updating DocTypes for erpnext : [======================================= ] 99%
Updating DocTypes for erpnext : [======================================== ] 100%,
Updating customizations for Address,
Updating customizations for Address, Updating customizations for Contact,
*** Scheduler is disabled ***
The container is stopped directly
Please help me

**Comment by zwessels** [comment]
it is supposed to stop :)

**Comment by revant** [comment]
closing this. site-creator exiting with exit code 0 is expected behaviour.
