### ISSUE TITLE
Wrong python interpreter in latest vscode.

### ISSUE THREAD

**Issue by cwooldridge** [frappe/frappe_docker#591]
Issue:   frappe module not found   ./bench-helper.py on launch of debugger in vscode.

Expected Result:  Debugger would launch successfully.

Steps To Reproduce:

      1.  Use Visual Studio Code Version: 1.62.3 or greater.
      2.  Install Development environment as described in documentation
      3.  Launch Bench Web task in Debugger

Observed result:
  The debugger launched but the python.pythonPath setting in .vscode/settings.json is ignored.
  The wrong python interpreter is being used and the frappe module cannot be found.

Expected result:
  The correct interpreter would be used.

### Workaround:

This is the result of a deprecated setting in vscode as described here.

https://github.com/microsoft/vscode-python/wiki/AB-Experiments

There are options for moving forward.

1. Set pythonPath in launch.json

      ```json
      {
                  "name": "Bench Web",
                  "type": "python",
                  "request": "launch",
                  "program": "${workspaceFolder}/frappe-bench/apps/frappe/frappe/utils/bench_helper.py",
                  "args": [
                      "frappe", "serve", "--port", "8000", "--noreload", "--nothreading"
                  ],
                  "pythonPath": "${workspaceFolder}/frappe-bench/env/bin/python",
                  "cwd": "${workspaceFolder}/frappe-bench/sites",
                  "env": {
                      "DEV_SERVER": "1"
                  }
              }
      ```

2. OR use vscode command Python: Select Interpreter to set the  interpreter to ./frappe-bench/env/bin/python
3. OR set python.defaultInterpreterPath in .vscode/settings.json

**Comment by revant** [comment]
The issue needs to be fixed, I'll make changes soon.

`.vscode` should also be `.gitignore` and there should be `vscode-example` for users to copy to `.vscode`. That will also allow custom advance configuration for vscode devcontainer.
