### ISSUE TITLE
Edge Latest Update: ImportError: Module import failed for IMAP Folder

### ISSUE THREAD

**Issue by yabdali** [frappe/frappe_docker#596]
Hi,
I am getting an error (ImportError: Module import failed for IMAP Folder) when starting the docker container after pulling the latest (Edge) image. Can you please provide guidance on what could be the issule?  I have an IMAP domain with an email account already in place.  Thanks for your support...

```
erpnext-worker-default_1  | Attempt 1 to connect to 192.168.50.81:3306
erpnext-worker-default_1  | Attempt 1 to connect to redis-queue:6379
erpnext-worker-default_1  | Attempt 1 to connect to redis-cache:6379
erpnext-worker-default_1  | Attempt 1 to connect to redis-socketio:6379
erpnext-worker-default_1  | Connections OK
erpnext-worker-default_1  | 17:54:51 Worker rq:worker:b59aa482c64a438e8eafe276f517e8a4.57f9eddc6159.12.home-frappe-frappe-bench:default: started, version 1.8.1
erpnext-worker-default_1  | 17:54:51 Subscribing to channel rq:pubsub:b59aa482c64a438e8eafe276f517e8a4.57f9eddc6159.12.home-frappe-frappe-bench:default
erpnext-worker-default_1  | 17:54:51 *** Listening on home-frappe-frappe-bench:default...
erpnext-python_1          | Attempt 1 to connect to 192.168.50.81:3306
erpnext-python_1          | Attempt 1 to connect to redis-queue:6379
erpnext-python_1          | Attempt 1 to connect to redis-cache:6379
erpnext-python_1          | Attempt 1 to connect to redis-socketio:6379
erpnext-python_1          | Connections OK
erpnext-python_1          | Migrating erp.mydomain.com
erpnext-python_1          | Executing frappe.patches.v14_0.copy_mail_data #08.03.21 in erp.mydomain.com (_e5a6ed7928bff629)
erpnext-python_1          | Traceback (most recent call last):
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 202, in load_doctype_module
erpnext-python_1          |     doctype_python_modules[key] = frappe.get_module(module_name)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 987, in get_module
erpnext-python_1          |     return importlib.import_module(modulename)
erpnext-python_1          |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
erpnext-python_1          |     return _bootstrap._gcd_import(name[level:], package, level)
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
erpnext-python_1          | ModuleNotFoundError: No module named 'frappe.core.doctype.imap_folder'
erpnext-python_1          | 
erpnext-python_1          | During handling of the above exception, another exception occurred:
erpnext-python_1          | 
erpnext-python_1          | Traceback (most recent call last):
erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 64, in <module>
erpnext-python_1          |     main()
erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 58, in main
erpnext-python_1          |     migrate_sites(maintenance_mode=True)
erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/migrate.py", line 35, in migrate_sites
erpnext-python_1          |     migrate()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 68, in migrate
erpnext-python_1          |     frappe.modules.patch_handler.run_all(skip_failing)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
erpnext-python_1          |     run_patch(patch)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
erpnext-python_1          |     if not run_single(patchmodule = patch):
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
erpnext-python_1          |     return execute_patch(patchmodule, method, methodargs)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
erpnext-python_1          |     frappe.get_attr(patchmodule.split()[0] + ".execute")()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v14_0/copy_mail_data.py", line 15, in execute
erpnext-python_1          |     doc.append("imap_folder", {
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 183, in append
erpnext-python_1          |     value = self._init_child(value, key)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 222, in _init_child
erpnext-python_1          |     value = get_controller(value["doctype"])(value)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
erpnext-python_1          |     site_controllers[doctype] = _get_controller()
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 52, in _get_controller
erpnext-python_1          |     module = load_doctype_module(doctype, module_name)
erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
erpnext-python_1          |     raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
erpnext-python_1          | ImportError: Module import failed for IMAP Folder (frappe.core.doctype.imap_folder.imap_folder Error: No module named 'frappe.core.doctype.imap_folder')
erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Starting gunicorn 20.1.0
erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Listening at: http://0.0.0.0:8000 (19)
erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Using worker: gthread
erpnext-python_1          | [2021-12-04 17:54:47 +0000] [20] [INFO] Booting worker with pid: 20
erpnext-python_1          | [2021-12-04 17:54:47 +0000] [21] [INFO] Booting worker with pid: 21
erpnext-worker-long_1     | Attempt 1 to connect to 192.168.50.81:3306
erpnext-worker-long_1     | Attempt 1 to connect to redis-queue:6379
erpnext-worker-long_1     | Attempt 1 to connect to redis-cache:6379
erpnext-worker-long_1     | Attempt 1 to connect to redis-socketio:6379
erpnext-worker-long_1     | Connections OK
erpnext-worker-long_1     | 17:54:41 Worker rq:worker:eb100763311c44db93ace15950637041.fd64d512504c.12.home-frappe-frappe-bench:long: started, version 1.8.1
erpnext-worker-long_1     | 17:54:41 Subscribing to channel rq:pubsub:eb100763311c44db93ace15950637041.fd64d512504c.12.home-frappe-frappe-bench:long
erpnext-worker-long_1     | 17:54:41 *** Listening on home-frappe-frappe-bench:long...
erpnext-worker-long_1     | 17:54:41 Cleaning registries for queue: home-frappe-frappe-bench:long
erpnext-worker-short_1    | Attempt 1 to connect to 192.168.50.81:3306
erpnext-worker-short_1    | Attempt 1 to connect to redis-queue:6379
erpnext-worker-short_1    | Attempt 1 to connect to redis-cache:6379
erpnext-worker-short_1    | Attempt 1 to connect to redis-socketio:6379
erpnext-worker-short_1    | Connections OK
erpnext-worker-short_1    | 17:54:47 Worker rq:worker:ba86eafd26114f05a14daeba3b89cb49.fe03e51358a2.13.home-frappe-frappe-bench:short: started, version 1.8.1
erpnext-worker-short_1    | 17:54:47 Subscribing to channel rq:pubsub:ba86eafd26114f05a14daeba3b89cb49.fe03e51358a2.13.home-frappe-frappe-bench:short
erpnext-worker-short_1    | 17:54:47 *** Listening on home-frappe-frappe-bench:short...
frappe-socketio_1         | listening on *: 9999
frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.006 * monotonic clock: POSIX clock_gettime
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 * Running mode=standalone, port=6379.
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # Server initialized
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * Loading RDB produced by version 6.2.6
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * RDB age 339 seconds
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * RDB memory usage when created 0.77 Mb
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 # Done loading RDB, keys loaded: 0, keys expired: 0.
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * DB loaded from disk: 0.000 seconds
redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * Ready to accept connections
redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.454 * monotonic clock: POSIX clock_gettime
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 * Running mode=standalone, port=6379.
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # Server initialized
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * Loading RDB produced by version 6.2.6
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * RDB age 336 seconds
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * RDB memory usage when created 3.25 Mb
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.640 # Done loading RDB, keys loaded: 62, keys expired: 0.
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.641 * DB loaded from disk: 0.182 seconds
redis-cache_1             | 1:M 04 Dec 2021 17:54:09.641 * Ready to accept connections
site-creator_1            | Attempt 1 to connect to 192.168.50.81:3306
site-creator_1            | Attempt 1 to connect to redis-queue:6379
site-creator_1            | Attempt 1 to connect to redis-cache:6379
site-creator_1            | Attempt 1 to connect to redis-socketio:6379
site-creator_1            | Connections OK
```

**Comment by yabdali** [comment]
> Hi, I am getting an error (ImportError: Module import failed for IMAP Folder) when starting the docker container after pulling the latest (Edge) image. Can you please provide guidance on what could be the issule? I have an IMAP domain with an email account already in place. Thanks for your support...
> 
> ```
> erpnext-worker-default_1  | Attempt 1 to connect to 192.168.50.81:3306
> erpnext-worker-default_1  | Attempt 1 to connect to redis-queue:6379
> erpnext-worker-default_1  | Attempt 1 to connect to redis-cache:6379
> erpnext-worker-default_1  | Attempt 1 to connect to redis-socketio:6379
> erpnext-worker-default_1  | Connections OK
> erpnext-worker-default_1  | 17:54:51 Worker rq:worker:b59aa482c64a438e8eafe276f517e8a4.57f9eddc6159.12.home-frappe-frappe-bench:default: started, version 1.8.1
> erpnext-worker-default_1  | 17:54:51 Subscribing to channel rq:pubsub:b59aa482c64a438e8eafe276f517e8a4.57f9eddc6159.12.home-frappe-frappe-bench:default
> erpnext-worker-default_1  | 17:54:51 *** Listening on home-frappe-frappe-bench:default...
> erpnext-python_1          | Attempt 1 to connect to 192.168.50.81:3306
> erpnext-python_1          | Attempt 1 to connect to redis-queue:6379
> erpnext-python_1          | Attempt 1 to connect to redis-cache:6379
> erpnext-python_1          | Attempt 1 to connect to redis-socketio:6379
> erpnext-python_1          | Connections OK
> erpnext-python_1          | Migrating erp.mydomain.com
> erpnext-python_1          | Executing frappe.patches.v14_0.copy_mail_data #08.03.21 in erp.mydomain.com (_e5a6ed7928bff629)
> erpnext-python_1          | Traceback (most recent call last):
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 202, in load_doctype_module
> erpnext-python_1          |     doctype_python_modules[key] = frappe.get_module(module_name)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 987, in get_module
> erpnext-python_1          |     return importlib.import_module(modulename)
> erpnext-python_1          |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
> erpnext-python_1          |     return _bootstrap._gcd_import(name[level:], package, level)
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> erpnext-python_1          |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
> erpnext-python_1          | ModuleNotFoundError: No module named 'frappe.core.doctype.imap_folder'
> erpnext-python_1          | 
> erpnext-python_1          | During handling of the above exception, another exception occurred:
> erpnext-python_1          | 
> erpnext-python_1          | Traceback (most recent call last):
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 64, in <module>
> erpnext-python_1          |     main()
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 58, in main
> erpnext-python_1          |     migrate_sites(maintenance_mode=True)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/migrate.py", line 35, in migrate_sites
> erpnext-python_1          |     migrate()
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 68, in migrate
> erpnext-python_1          |     frappe.modules.patch_handler.run_all(skip_failing)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 36, in run_all
> erpnext-python_1          |     run_patch(patch)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 25, in run_patch
> erpnext-python_1          |     if not run_single(patchmodule = patch):
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 66, in run_single
> erpnext-python_1          |     return execute_patch(patchmodule, method, methodargs)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 86, in execute_patch
> erpnext-python_1          |     frappe.get_attr(patchmodule.split()[0] + ".execute")()
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/patches/v14_0/copy_mail_data.py", line 15, in execute
> erpnext-python_1          |     doc.append("imap_folder", {
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 183, in append
> erpnext-python_1          |     value = self._init_child(value, key)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 222, in _init_child
> erpnext-python_1          |     value = get_controller(value["doctype"])(value)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 70, in get_controller
> erpnext-python_1          |     site_controllers[doctype] = _get_controller()
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/base_document.py", line 52, in _get_controller
> erpnext-python_1          |     module = load_doctype_module(doctype, module_name)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 204, in load_doctype_module
> erpnext-python_1          |     raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
> erpnext-python_1          | ImportError: Module import failed for IMAP Folder (frappe.core.doctype.imap_folder.imap_folder Error: No module named 'frappe.core.doctype.imap_folder')
> erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Starting gunicorn 20.1.0
> erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Listening at: http://0.0.0.0:8000 (19)
> erpnext-python_1          | [2021-12-04 17:54:47 +0000] [19] [INFO] Using worker: gthread
> erpnext-python_1          | [2021-12-04 17:54:47 +0000] [20] [INFO] Booting worker with pid: 20
> erpnext-python_1          | [2021-12-04 17:54:47 +0000] [21] [INFO] Booting worker with pid: 21
> erpnext-worker-long_1     | Attempt 1 to connect to 192.168.50.81:3306
> erpnext-worker-long_1     | Attempt 1 to connect to redis-queue:6379
> erpnext-worker-long_1     | Attempt 1 to connect to redis-cache:6379
> erpnext-worker-long_1     | Attempt 1 to connect to redis-socketio:6379
> erpnext-worker-long_1     | Connections OK
> erpnext-worker-long_1     | 17:54:41 Worker rq:worker:eb100763311c44db93ace15950637041.fd64d512504c.12.home-frappe-frappe-bench:long: started, version 1.8.1
> erpnext-worker-long_1     | 17:54:41 Subscribing to channel rq:pubsub:eb100763311c44db93ace15950637041.fd64d512504c.12.home-frappe-frappe-bench:long
> erpnext-worker-long_1     | 17:54:41 *** Listening on home-frappe-frappe-bench:long...
> erpnext-worker-long_1     | 17:54:41 Cleaning registries for queue: home-frappe-frappe-bench:long
> erpnext-worker-short_1    | Attempt 1 to connect to 192.168.50.81:3306
> erpnext-worker-short_1    | Attempt 1 to connect to redis-queue:6379
> erpnext-worker-short_1    | Attempt 1 to connect to redis-cache:6379
> erpnext-worker-short_1    | Attempt 1 to connect to redis-socketio:6379
> erpnext-worker-short_1    | Connections OK
> erpnext-worker-short_1    | 17:54:47 Worker rq:worker:ba86eafd26114f05a14daeba3b89cb49.fe03e51358a2.13.home-frappe-frappe-bench:short: started, version 1.8.1
> erpnext-worker-short_1    | 17:54:47 Subscribing to channel rq:pubsub:ba86eafd26114f05a14daeba3b89cb49.fe03e51358a2.13.home-frappe-frappe-bench:short
> erpnext-worker-short_1    | 17:54:47 *** Listening on home-frappe-frappe-bench:short...
> frappe-socketio_1         | listening on *: 9999
> frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
> frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
> frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
> frappe-socketio_1         | Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')
> redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
> redis-socketio_1          | 1:C 04 Dec 2021 17:54:09.005 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.006 * monotonic clock: POSIX clock_gettime
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 * Running mode=standalone, port=6379.
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # Server initialized
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.007 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * Loading RDB produced by version 6.2.6
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * RDB age 339 seconds
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * RDB memory usage when created 0.77 Mb
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 # Done loading RDB, keys loaded: 0, keys expired: 0.
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * DB loaded from disk: 0.000 seconds
> redis-socketio_1          | 1:M 04 Dec 2021 17:54:09.008 * Ready to accept connections
> redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
> redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
> redis-cache_1             | 1:C 04 Dec 2021 17:54:09.453 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.454 * monotonic clock: POSIX clock_gettime
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 * Running mode=standalone, port=6379.
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # Server initialized
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.455 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * Loading RDB produced by version 6.2.6
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * RDB age 336 seconds
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.464 * RDB memory usage when created 3.25 Mb
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.640 # Done loading RDB, keys loaded: 62, keys expired: 0.
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.641 * DB loaded from disk: 0.182 seconds
> redis-cache_1             | 1:M 04 Dec 2021 17:54:09.641 * Ready to accept connections
> site-creator_1            | Attempt 1 to connect to 192.168.50.81:3306
> site-creator_1            | Attempt 1 to connect to redis-queue:6379
> site-creator_1            | Attempt 1 to connect to redis-cache:6379
> site-creator_1            | Attempt 1 to connect to redis-socketio:6379
> site-creator_1            | Connections OK
> ```

I am also noticing some issues looking at the logs of frappe_frappe-socketio_1  service!  Please advise, thanks...

listening on *: 9999,
Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user'),
Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user'),
Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user'),
Unable to join chat room. TypeError: Cannot read properties of undefined (reading 'user')

**Comment by vrslev** [comment]
There's too much issues! 😃 And it works for me. Edge image is for development, so it should be okay to erase all the data and dead containers. To do this run `docker-compose down -v --remove-orphans`. After that try again.

**Comment by yabdali** [comment]
> docker-compose down -v --remove-orphans

@vrslev Thanks, I tried your suggest using `docker-compose down -v --remove-orphans`  but I still I keep getting `The system is being updated. Please refresh again after a few moments.`  even after two hours from starting the container.  I don't see any errors raised in the logs except `Cleaning registries for queue: home-frappe-frappe-bench:long` every one hour!

**Comment by revant** [comment]
In `common_site_config.json` set `maintenance_mode` and `pause_scheduler` to `0`

**Comment by yabdali** [comment]
> In `common_site_config.json` set `maintenance_mode` and `pause_scheduler` to `0`

@revant I had to switch the version to v13.16.0 as per @vrslev advice.  I did try to change the maintenance mode value to 0 prior to seeing your reply but it didn't work so I expect its due to missing pause scheduler parameter.  
Another note, I had an issue with Mariadb due to the compression feature in the latest version, just in case someone may need a workaround, I added  the option to disable compression in the docker-compose.yml as per the comments below.

```
command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--innodb-read-only-compressed=OFF"
```

**Comment by vrslev** [comment]
> Another note, I had an issue with Mariadb due to the compression feature in the latest version, just in case someone may need a workaround, I added the option to disable compression in the docker-compose.yml as per the comments below.

I recently sent PR and changed it in here too.
