### ISSUE TITLE
Use Pre-commit for code quality

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#602]
[Pre-commit](https://pre-commit.com) is `A framework for managing and maintaining multi-language pre-commit hooks.` We could use it to improve code quality. Frappe started using it in multiple repos why don't we? I use it in all my projects and it really helps to keep style consistent. I can provide pre-commit config. 

@revant Thoughts?

**Comment by revant** [comment]
pre commit hooks are okay. I think of it like client side validation. CI is the server side validation.

git hooks can be skipped with `-n` or `--no-verify`

I generally do lint, check format, test, e2e as part of ci which can't be skipped without reviewers noticing it.

**Comment by vrslev** [comment]
`pre-commit` is not just raw shell-script-like git hooks. Poorly named, probably 😃 I suggest you check how cool it is: https://pre-commit.com/

The pre-commit framework can be easily configured as GitHub Actions check. See example here: https://github.com/vrslev/ikea-api-client/runs/4422541657?check_suite_focus=true. 
Doesn't matter if they can be skipped as long as pre-commit is in our CI.

**Comment by revant** [comment]
oh! okay we can implement.

**Comment by vrslev** [comment]
Alright! I'll send the PR soon.

**Comment by vrslev** [comment]
@revant One question. Should we reformat whole repository in one PR or do it gradually?
In the first case we could include `.git-blame-ignore-revs` like @ankush did here: https://github.com/frappe/ecommerce_integrations/blob/develop/.git-blame-ignore-revs,
In second one we would have more or less truthful diffs but there may occur situations when whole files would be reformatted.

**Comment by revant** [comment]
you or me are to blame! 😬

how many files are to be changed any idea?

**Comment by vrslev** [comment]
@revant Let’s begin in the PR. See comment: https://github.com/frappe/frappe_docker/pull/604#issuecomment-986256668
