### ISSUE TITLE
CI: Frappe image rebuilds after ERPNext is released

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#616]
Currently our continuous integration is quite messed up (partially I caused it myself 😃). I suggest to adjust the way that would trigger ERPNext builds only when they're required and would run only for required version (12, 13 or develop). Adding this issue to discuss it before doing it. @revant What do you think?

**Comment by revant** [comment]
> wouldn't trigger ERPNext builds when they're required and build would run only for required version (12, 13 or develop).

I didn't get you.

**Comment by vrslev** [comment]
@revant Yep, what I wrote was misleading, sorry. I meant that we shouldn’t trigger ERPNext build if there was a Frappe release.

**Comment by revant** [comment]
Travis had an option where only one pipeline runs at a time. There must be something equivalent on GHA?

**Comment by vrslev** [comment]
There is. But I don't think that is a good solution. `repository_dispatch` trigger has inputs. We could send git tag and repo, parse it and set build targets. Here's a start: https://github.com/vrslev/frappe_docker/blob/89236d8ed6b7e04bf62e2d4a2e507f2c0125f694/.github/scripts/get_latest_tags.py

**Comment by vrslev** [comment]
@revant Do you have any thoughts on the issue after some time?

**Comment by vrslev** [comment]
@revant ping

**Comment by revant** [comment]
what's the plan? you're sending PR?

I'm not very experienced with GHA, I'll read through what you share/send

**Comment by vrslev** [comment]
For now, I can't get an algorithm right. The idea is to prevent redundant rebuilds on simultaneous Frappe and ERPNext releases. ERPNext shouldn't trigger Frappe build, but what if it got released before Frappe did and there's no Frappe image yet?

**Comment by revant** [comment]
for this to work should the application (ERPNext) bump up its version when it updates dependency (Frappe) version it uses?

because that is not the case with ERPNext. even if frappe is updated ERPNext can remain on same version and still use updated dependency.

that's why we just run both Frappe and ERPNext builds on any release.

may be we keep running both jobs just with concurrency https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

**Comment by vrslev** [comment]
`concurrency` feature would not be helpful. If Frappe release triggered first, it probably will never get to new ERPNext version 😬

**Comment by vrslev** [comment]
After time (3 month) I don't see a solid solution.
