### ISSUE TITLE
missing Bench command 'set-mariadb-host'

### ISSUE THREAD

**Issue by Robproject** [frappe/frappe_docker#626]
## Description of the issue
command 'bench set-mariadb-host mariadb' acts like that command doesn't exist:
```
$ bench set-mariadb-host mariadb
Usage: bench frappe [OPTIONS] COMMAND [ARGS]...
Try 'bench frappe --help' for help.

Error: No such command 'set-mariadb-host'.
```

## Steps to reproduce the issue
Following the procedure for [setting up a new dev environment](https://github.com/frappe/frappe_docker/tree/main/development)

I've been following this procedure without error until yesterday. This is my first issue submission so apologies for not having more info.

### Observed result
![Screenshot 2022-01-03 181253](https://user-images.githubusercontent.com/74115869/148092239-0b5c136c-049e-4b18-9907-54afdd6fd8fc.png)

### Expected result

No error / mariadb is set as db_host

### Stacktrace / full error message if available

total error listed above

**Comment by Robproject** [comment]
Manually adding ` "db_host": "mariadb", ` to `frappe-bench/sites/common_site_config.json` allowed me to continue regularly. Seems like `mariadb` is also a command and it gets confused. Using `bench set-mariadb-host anyotherstring` works.

**Comment by CleoMenezes** [comment]
> Manually adding `"db_host": "mariadb",` to `frappe-bench/sites/common_site_config.json` allowed me to continue regularly. Seems like `mariadb` is also a command and it gets confused. Using `bench set-mariadb-host anyotherstring` works.

Unfortunately it didn't work for me.

**Comment by Robproject** [comment]
> > Manually adding `"db_host": "mariadb",` to `frappe-bench/sites/common_site_config.json` allowed me to continue regularly. Seems like `mariadb` is also a command and it gets confused. Using `bench set-mariadb-host anyotherstring` works.
> 
> Unfortunately it didn't work for me.

Could try it in this order, what I did:
1. adding it to the json file
2. running the next commands 'bench set redis-%' etc. This will sort the json file and tell you if the formatting was correct (since it will fail if format is wrong)
3. Then bench set-mariadb-host

**Comment by CleoMenezes** [comment]
Deleted my comment that said it didn't work. The workaround works perfectly, I was doing it wrong,

**Comment by shamsi2u** [comment]
> Manually adding `"db_host": "mariadb",` to `frappe-bench/sites/common_site_config.json` allowed me to continue regularly. Seems like `mariadb` is also a command and it gets confused. Using `bench set-mariadb-host anyotherstring` works.

adding  "db_host": "mariadb", this worked for me but now having trobule with redis server those 3 commands to change port also seems not working

**Comment by lucasvazq** [comment]
Related issue in bench: https://github.com/frappe/bench/issues/1254

**Comment by lucasvazq** [comment]
I list three alternatives in this issue https://github.com/frappe/bench/issues/1254
After the changes, I recommend clearing your cache, migrate, and restar. I don't know if all of these things are required and in which order they must be executed, but do it anyway.

**Comment by revant** [comment]
I'll close this issue as there's an issue open in frappe/bench.

alternatives:

- manually edit common_site_config.json and set db_host key to mariadb
- use `bench set-config -g db_host mariadb`
