### ISSUE TITLE
Use bench get-app in docker?

### ISSUE THREAD

**Issue by mehrdd** [frappe/frappe_docker#632]
Hi,
How can i use `bench get-app ...` in Docker with local config - dev mode?
when i do it in the Worker container i get this error:

```
Error: No such command 'get-app'.
```

I couldn't find the right answer...

**Comment by revant** [comment]
You really didn't find any answer related to bench in production images is limited to bench_helper from frappe framework?

Development related bench commands are not available in production containers.

@vrslev can `pretend_bench` catch unknown commands with a bold colorful message with url to docs. I've answered this question countless times and still it comes up.

I tried to count the instances where I've answered this in a post here https://discuss.erpnext.com/t/bench-error-no-such-command-setup/71784/6 I gave up counting after a point.

**Comment by vrslev** [comment]
@revant I will check what can be done.

**Comment by mehrdd** [comment]
Sorry about that @revant and i know what you are talking about! Really!
But i think naming and/or the process is little misleading.. We can use docker image with non-production environment. So at first i thought using `local-env` will give me `bench` access.
I think messages can be little more clear, if lots of people are coming to you with such questions..
Thanks BTW.
