### ISSUE TITLE
Agriculture isn't available

### ISSUE THREAD

**Issue by steff107** [frappe/frappe_docker#634]
I installed ERPNext locally via docker-compose. After site-creator ended up, I set up my ERP.
But in this steps, I can't see agriculture. Also in `Home/Settings/Domain Settings` there is no agriculture.
I'm using versions:
```
ERPNext: v13.x.x-develop () (develop)
Frappe Framework: v14.x.x-develop () (develop)
```
Did I forgot something?
Isn't it available any more?

Thanks in advance!

**Comment by Alchez** [comment]
@steff107, the agri module has been shifted to its own app in v14. The new one is over at https://github.com/frappe/agriculture.

**Comment by steff107** [comment]
ahh, thanks.
But I don't understand how to use bench cli at the moment. Can I install agriculture directly in the container?

**Comment by vrslev** [comment]
Check out this guide: https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps-for-production.md

**Comment by steff107** [comment]
Thanks for the hint. I set up all, but the 2nd last step isn't clear:
`sed -i "s#\[app\]#[custom]#" ./installation/docker-compose-custom.yml`
How do I need to replace `app` and `custom` in the `sed`-command?

**Comment by revant** [comment]
> Open up ./installation/docker-compose-custom.yml and replace all instances of [app] with the name of your app.
> ```shell
> sed -i "s#\[app\]#[custom]#" ./installation/docker-compose-custom.yml
> ```

replace all the instances of `[app]` with `custom_app_name`.

e.g. replace following :

- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L4
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L5
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L7
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L18
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L24
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L33
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L34
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L36
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L61
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L75
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L91
- https://github.com/frappe/frappe_docker/blob/42bfd485f881e70918707a5ffa99778873baca13/installation/docker-compose-custom.yml#L107

> Install like usual, except that when you set the INSTALL_APPS variable to erpnext,[custom].

You've to set the `INSTALL_APPS` variable to include list of apps to be installed. https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#setup-new-site

**Comment by steff107** [comment]
Ok, I replaced all `[app]`with `agriculture` and ran `docker-compose up -d`, but there's no agriculture.
Then I edited my `.env` like following:
```
LETSENCRYPT_EMAIL=<some@mail.com>
ERPNEXT_VERSION=edge
FRAPPE_VERSION=edge
MARIADB_HOST=mariadb
MYSQL_ROOT_PASSWORD=admin
SITE_NAME=erp-test.localhost
SITES=`erp-test.localhost`,`agrar-test.localhost`
DB_ROOT_USER=root
ADMIN_PASSWORD=admin
INSTALL_APPS=erpnext,agriculture
ENTRYPOINT_LABEL=traefik.http.routers.erpnext-nginx.entrypoints=web
CERT_RESOLVER_LABEL=erpnext.local.no-cert-resolver
HTTPS_REDIRECT_RULE_LABEL=erpnext.local.no-redirect-rule
HTTPS_REDIRECT_ENTRYPOINT_LABEL=erpnext.local.no-entrypoint
HTTPS_REDIRECT_MIDDLEWARE_LABEL=erpnext.local.no-middleware
HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL=erpnext.local-no-redirect-middleware
SKIP_NGINX_TEMPLATE_GENERATION=0
WORKER_CLASS=gthread
```

But it doesn't work, so I did something wrong or forgot something...
Do I need to add `agriculture` to `docker-compose.yml` too?


Maybe you can help me out there?

**Comment by revant** [comment]
check this diff, I tested it, it is working. It builds the image, creates the site and installs erpnext and agriculture for **develop** branch.

https://github.com/castlecraft/custom_frappe_docker/compare/agriculture?expand=1

**Comment by sbergmair** [comment]
It doesn't work for me, I think I forgot something. 
Do I need to build the single Dockerfiles? 
Or does docker-compose up -d Build and install Ali components?

**Comment by revant** [comment]
> check this diff, I tested it, it is working. It builds the image, creates the site and installs erpnext and agriculture for **develop** branch.
> 
> https://github.com/castlecraft/custom_frappe_docker/compare/agriculture?expand=1

**Comment by revant** [comment]
there is new way to add apps now.

ask @vrslev about details if needed.
