### ISSUE TITLE
Public Attachements are not found (404) when using custom external port

### ISSUE THREAD

**Issue by 0FiRE0** [frappe/frappe_docker#637]
## Description of the issue
I have encountered an issue of receiving an HTTP 404 Error Not Found when loading static assets and attachments (like images ...etc.).

Please refer to the below issue raised for all the details, and the solution is provided too:
https://github.com/frappe/erpnext/issues/28971#issue-1085277206

## Steps to reproduce the issue

1. Map custom external port to the "Taerfik" container (E.g. port 800 instead of 80, or 4430 instead of 443)
2. Run all the containers through "docker-compose"
3. Upload a file attachment (E.g. Image, PDF ...etc.), any static file.
4. Try loading or accessing the file attachment

### Observed result
The 404 error shows up

### Expected result
The file should be accessed and loaded successfully

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
i think it is related to this https://github.com/frappe/frappe_docker/issues/629

we'll keep that open.
