### ISSUE TITLE
Access Traefik dashboard

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/frappe_docker#640]
How to access Traefik dashboard using frappe and erpnext installation with docker?

https://traefik.example.com/dashboard/ for Traefik dashboard

**Comment by revant** [comment]
Check Traefik documentation to enable it, https://doc.traefik.io/traefik/operations/dashboard/#secure-mode

you also need to setup a domain name and ssl, basic auth for it. Check traefik docs for that as well.

**Comment by mohsinalimat** [comment]
Try but not get result

**Comment by revant** [comment]
traefik training out is scope.

try #715 some people got success.
