### ISSUE TITLE
"setup-wizard" is blank and "next" button doesn't work.

### ISSUE THREAD

**Issue by mooseen** [frappe/frappe_docker#642]
OS: MacOS  Big Sur 11.5.2
Docker Version: v20.10.7
I have successfully installed the frappe.
![image](https://user-images.githubusercontent.com/3996051/150643679-2ad90501-4f36-4c29-ad96-594af3aab6ee.png)
After I log in,the "setup-wizard" page does not show any content and the "next" button doesn't work either.
![image](https://user-images.githubusercontent.com/3996051/150643550-7e9f5759-9aa5-4ee1-8dcf-c5779c0ce3ee.png)
If I click the next button, The Browser "Develop Console" will show this error:
![image](https://user-images.githubusercontent.com/3996051/150643805-fc016bd1-81b0-45b8-8df0-006643d5c53a.png)

Does anyone know what the cause is?

**Comment by revant** [comment]
which images are you using? are you using edge or develop tags?

**Comment by mooseen** [comment]
> which images are you using? are you using edge or develop tags?
I'm using edge tag images.
<img width="1018" alt="图片" src="https://user-images.githubusercontent.com/3996051/151150699-38c4ec71-1308-4b50-a985-bf3bd26b1e8e.png">

**Comment by revant** [comment]
edge images are not meant for production they will have bugs.

you can try updating edge images daily to test the latest development.

or in case of production, use v13.19.0 or the latest semver tag available.
