### ISSUE TITLE
Changing the UID/GID from 1000 to something different without rebuilding the images

### ISSUE THREAD

**Issue by mwllgr** [frappe/frappe_docker#645]
## Description of the issue
The 1000 user is used for another purpose on my system (ISPconfig), when setting the volume directory to 1000, I essentially allow unwanted guests in these folders.

### Observed result
Web clients (they are somehow connected with my user 1000) might be able to access my ERP system.

### Expected result
One should be able to change the used UID/GID.  Is this possible somehow?

**Comment by revant** [comment]
right now only way is to build image. 
even during build it runs chown.
