### ISSUE TITLE
How to make imports work

### ISSUE THREAD

**Issue by sudo-vaibhav** [frappe/frappe_docker#649]
Guys I have defined a utils module in my custom app. But pylance is complaining about it, although the actual app runs fine, even the imported functions work fine. Any idea how to make these yellow lines go away and actually get autocomplete. It's making developing very hard without any autocomplete.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/53619134/152149618-0b10e842-dcc6-43a5-bd1b-d38e46dc43ad.png">

As you can see the utils directory is present. The logic in it runs fine but no autocomplete.
<img width="430" alt="image" src="https://user-images.githubusercontent.com/53619134/152150319-4782c514-4812-43d8-90a1-cd7c59cea04f.png">

**Comment by revant** [comment]
try absolute path? `your_app.path.to.utils`

**Comment by sudo-vaibhav** [comment]
well that also did not work out of the box. But after playing around a little more. I found that I also have to add my own app to vs code config for pylance
Had to change the .vscode/settings.json file and add the following lines:
```
"python.analysis.extraPaths": [
    "./frappe-bench/apps/frappe",
    "./frappe-bench/apps/myappname"
],
```
Finally the code should look like this.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/53619134/152209364-2b1d29b9-23ab-49aa-80e9-ade6c2f8c4ed.png">

I feel this could be better documented in the READMEs.
