### ISSUE TITLE
Could not find app "custom_app"

### ISSUE THREAD

**Issue by saru2020** [frappe/frappe_docker#653]
I'm trying to install a custom app and I'm seeing this issue:
"Could not find app "myapp""

## Description of the issue
Not able to install custom app in frappe_docker

## Steps to reproduce the issue

1. Follow the custom app documentation: https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps-for-production.md, to setup/configure your custom app
2. Follow the single bench setup tutorial: https://github.com/frappe/frappe_docker/blob/main/docs/single-bench.md
As mentioned in the docs, when I run this command: "docker logs <project-name>_site-creator_1 -f", I don't see images/containers for the custom app being created

**Question:** Should we install custom app separately/manually?

### Observed result
Custom app is not getting installed and the console shows this issue: "Could not find app "myapp""

### Expected result
App should get installed w/o any issues

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/634#issuecomment-1017250021

fork this repo and build your images, check this diff

https://github.com/castlecraft/custom_frappe_docker/compare/agriculture?expand=1

**Comment by saru2020** [comment]
thank you for the response @revant , I see that you're the main contributor replying to all the queries/issues raised in this repo, you're doing a fabulous job of acting as a bridge for noobs like to get onto the frappe world.

with custom_frappe_docker, I was able to build the images successfully but again a noob question:
how should I create the containers? any references/docs for me to follow, please! [note: I tried following the single bench installation doc but still facing the same issue]

**Comment by revant** [comment]
the repo has a docker-compose.yml file with diff of images. use that docker compose file and try

**Comment by saru2020** [comment]
i tried using that but it is trying to pull the image from the hub and failing with this error:
```
CHMB115932:custom_frappe_docker saravanan_vij$ docker-compose --project-name frappe_custom_sample up -d
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating network "frappe_custom_sample_default" with the default driver
Creating volume "frappe_custom_sample_mariadb-vol" with default driver
Creating volume "frappe_custom_sample_redis-cache-vol" with default driver
Creating volume "frappe_custom_sample_redis-queue-vol" with default driver
Creating volume "frappe_custom_sample_redis-socketio-vol" with default driver
Creating volume "frappe_custom_sample_assets-vol" with default driver
Creating volume "frappe_custom_sample_sites-vol" with default driver
Creating volume "frappe_custom_sample_cert-vol" with default driver
Pulling custom-erpnext-nginx (custom-erpnext-nginx:edge)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling custom-erpnext-nginx (custom-erpnext-nginx:edge)...
ERROR: pull access denied for custom-erpnext-nginx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

am I doing anything wrong here?

**Comment by saru2020** [comment]
I ran this command 
```
docker compose up
```
and the containers were created as expected 

but when I see the logs inside 'custom_frappe_docker_site-creator_1' container, it stopped with this log:
```
*** Scheduler is disabled ***
```

also, the 'custom_frappe_docker_frappe-socketio_1' container status is always: 'RESTARTING' with this log:
```
#

# Fatal process OOM in Failed to reserve virtual memory for CodeRange

#


qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

/usr/local/bin/docker-entrypoint.sh: line 24: 8 Trace/breakpoint trap node /home/frappe/frappe-bench/apps/frappe/socketio.js
```

**Comment by revant** [comment]
> *** Scheduler is disabled ***

this means site was created successfully, that's expected.

> OOM

how much RAM is available?

**Comment by saru2020** [comment]
I dont know how but all the containers are up & working now, somehow the 'custom_frappe_docker_frappe-socketio_1' started working after a restart.

but now, I'm seeing this issue:

```
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1023, in get_module_list

    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))

  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 981, in get_module

    return importlib.import_module(modulename)

  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'posawesome'
```

note: I've removed the 'posawesome' from the apps list but the site is still expecting it. 
I've gone through the diff and even a global search inside the repo as well and I don't seem to get where else to make the change, any inputs on this please?

**Comment by saru2020** [comment]
finally got all the containers working by keeping all the apps mentioned in the repo but if i delete any one of them, it always fails with this error:
```
ModuleNotFoundError: No module named '<removed module name>'
```

Also, i'm seeing this error:
```
pymysql.err.OperationalError: (1045, "Access denied for user '_f3c1320bb2d43983'@'172.18.0.4' (using password: YES)")
```


**One more unrealted question: (is this related to the above error?)**
when i do bench setup manually, i'd get the wizard to setup the administrator account for the first time, but running via docker, i'm not seeing that instead the login/signup page is only displayed. where

**Comment by saru2020** [comment]
I was able to login with the default username: administrator / pwd: admin('ADMIN_PASSWORD' value from .env)
but i'm still not able to remove other apps like mentioned in this [diff](https://github.com/castlecraft/custom_frappe_docker/compare/agriculture?diff=unified).
i'm always getting this issue:
```
ModuleNotFoundError: No module named 'posawesome'
```

how do i solve it?

@revant

**Comment by revant** [comment]
sites/apps.txt should only have list of apps available in apps directory

**Comment by saru2020** [comment]
the issue was that the existing volumes were being used.
i ran this command: 
```
docker volume prune
```
which cleared up all the existing volumes

and then re-did everything, re-creating images & containers and now everything works as expected

thank you @revant for your kind support, w/o it, it might've taken me possibly another week or more.
