### ISSUE TITLE
Installation of version13 failed

### ISSUE THREAD

**Issue by pumpkin-nbc** [frappe/frappe_docker#659]
An error occurs when using docker to install

[root@centos frappe_docker]# docker logs erpnext_site-creator_1
/usr/local/bin/docker-entrypoint.sh: line 67: /home/frappe/frappe-bench/sites/apps.txt: Permission denied
config file not created, retry 1
config file not created, retry 2
config file not created, retry 3
config file not created, retry 4
config file not created, retry 5
config file not created, retry 6
config file not created, retry 7
config file not created, retry 8
config file not created, retry 9
config file not created, retry 10
config file not created, retry 11
config file not created, retry 12
config file not created, retry 13
config file not created, retry 14
config file not created, retry 15
config file not created, retry 16
config file not created, retry 17
config file not created, retry 18
config file not created, retry 19
config file not created, retry 20
config file not created, retry 21
config file not created, retry 22
config file not created, retry 23
config file not created, retry 24
config file not created, retry 25
config file not created, retry 26
config file not created, retry 27
config file not created, retry 28
config file not created, retry 29
config file not created, retry 30
config file not created, retry 31
timeout: config file not created

**Comment by revant** [comment]
make sure all volumes and files within are owned by uid:gid 1000:1000

**Comment by pumpkin-nbc** [comment]
@revant 
I use the following command

git clone https://github.com/frappe/frappe_docker.git
cd frappe_docker
cp env-production .env

then
I changed the version to bit 13

docker-compose --project-name erpnext up -d

Then he reported a mistake

**Comment by revant** [comment]
latest tag is develop branch

**Comment by revant** [comment]
reopen if needed.

repo has changed after refactor.
