### ISSUE TITLE
wkhtmltopdf cannot access a CSS file of frappe on a live site

### ISSUE THREAD

**Issue by a157147899** [frappe/frappe_docker#661]
Hi guys,
I'm encountering an issue where 'wkhtmltopdf' threw a timeout error during the process of converting HTML to PDF. 

I've located the root cause is that wkhtmltopdf cannot access a CSS file of frappe in the docker container. However, this is a live site and I can access the CSS file from the browser but not in the container, using CURL is also not able to access.

Using wkhtmltopdf command line to test in the container, found that accessing the CSS file was time out.
``/assets/frappe/dist/css/print.bundle.XUXXDMUU.css``
![image](https://user-images.githubusercontent.com/1812136/153691632-211b2fc1-f8dd-47af-864b-3a43fcbf5782.png)

Can access the CSS file from the browser but not in the container with CURL.
![image](https://user-images.githubusercontent.com/1812136/153691738-4cff50d9-9501-44b9-941f-aaaf82bc0dbe.png)

![image](https://user-images.githubusercontent.com/1812136/153692067-2f10c804-afca-44ab-9e2b-3799a5065f6a.png)

Error log:
```
ERROR frappe Could not take error snapshot: characters_written
Form Dict: {'name': '090122-00003', 'cmd': 'frappe.email.doctype.email_queue.email_queue.send_now', 'doctype': 'Sales Order', 'format': 'Standard', 'style': None, 'doc': None, 'no_letterhead': False}
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1220, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 330, in send_now
    record.send()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 123, in send
    message = ctx.build_message(recipient.recipient)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 244, in build_message
    message = self.include_attachments(message)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 310, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1595, in attach_print
    content = get_print(doctype, name, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1561, in get_print
    return get_pdf(html, options=pdf_options, output=output)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, False, options=options or {})
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/api.py", line 72, in from_string
    return r.to_pdf(output_path)
  File "/home/frappe/frappe-bench/env/lib/python3.9/site-packages/pdfkit/pdfkit.py", line 156, in to_pdf
    raise IOError("wkhtmltopdf reported an error:{0}\n{1}".format(stderr, input))
OSError: wkhtmltopdf reported an error:Exit with code 1 due to network error: TimeoutError
```

Any help would be appreciated.

**Comment by a157147899** [comment]
I also tried to point the domain to the default docker host's IP 172.17.0.1 inside the container but it doesn't give me any difference. Not sure if 172.17.0.1 is the correct one?
<img width="517" alt="image" src="https://user-images.githubusercontent.com/1812136/153698374-c46e1b15-3756-4edb-8da8-3c2b54446d76.png">

Ip address and gateway of the container:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/1812136/153698491-44ebede6-b607-47ce-a553-86ac5fe35c51.png">

**Comment by revant** [comment]
@vrslev this is one of the case where nginx assets are needed in certain path by python container.

@a157147899 can you make sure the failing path exists in container?
it needs to be populated

**Comment by a157147899** [comment]
Hey guys, any hints to solve this issue? Or this is something I'm the only one encountered.

**Comment by revant** [comment]
you must have done this already? try restarting? that may setup the assets again.

or try copying the files manually.
files are in nginx container (/var/www/html/), they need to be copied to sites-vol/assets. or some how made available there for worker, scheduler and python container

**Comment by a157147899** [comment]
> you must have done this already? try restarting? that may setup the assets again.
> 
> or try copying the files manually. files are in nginx container (/var/www/html/), they need to be copied to sites-vol/assets. or some how made available there for worker, scheduler and python container

@revant  Hi, sorry for taking so long to come back to this as I've been busy with other things recently.

I can confirm that the failing file is existing in the path for both python, worker and scheduler containers. 

![image](https://user-images.githubusercontent.com/1812136/156879133-28651351-a4b2-43e6-98c4-802c2766a59a.png)

However, it still failed to convert HTML to PDF as I manually tested it via `wkhtmltopdf` command lines in the python container.

![image](https://user-images.githubusercontent.com/1812136/156878906-b1bfaa78-6ea3-462e-bf56-85b30b915c71.png)

I feel like it's probably related to some network settings as it's a socket timeout error.

**Comment by a157147899** [comment]
Hi Guys, I just wanted to confirm whether this is a bug or just related to my settings?

**Comment by vrslev** [comment]
@revant?

**Comment by revant** [comment]
This seems to be happening on Generating PDF from documents as well.

Add a Letter Head with HTML called `Example` :

```html
<div style="text-align: center;">
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Erpnext_logo.svg/240px-Erpnext_logo.svg.png" width="10%">
  <div style="font-size: 30px;">Example Limited</div>
</div>
```

Create a new Note: "Hello Letterhead from containers"

Set letterhead: `Example`

print pdf

**Comment by revant** [comment]
"Socket operation timed out" may be something else. I created new issue for missing Letter head

**Comment by a157147899** [comment]
@vrslev @revant 
Just wanted to mention that I can't even access that CSS file by using `CURL ` command in the python container.
![image](https://user-images.githubusercontent.com/1812136/159109798-46b19756-6e61-40d6-a35c-0b24c9efa1ad.png)

I strongly feel like it's probably something like a **circular reference** issue?  Because the domain is being pointed to the host and the `traefik` container will route the request to the python container, so it's actually accessing itself.

**Comment by vrslev** [comment]
Frontend assets are managed by Nginx service — it is placed before backend service. It works as expected

**Comment by vrslev** [comment]
@a157147899 You can try to access assets by `frontend` host. Link would look like this: `https://frontend/assets/...`. I assume that you use setup after refactor #617

**Comment by a157147899** [comment]
> 

@vrslev  I actually set up the site before refactor. I checked the latest docs and am feeling a little bit lost. 
My question now is - how do I reuse the previous containerized Mysql db? I don't mind setting up a brand new site but I definitely want to keep my data.

**Comment by a157147899** [comment]
I probably need to point the `DB_HOST` to the IP address of the previous mysql container but I have no idea how to specify the database name as it seemed a random name.
![image](https://user-images.githubusercontent.com/1812136/161364951-8d1dff16-4de2-4000-8339-7c9a00b25f2d.png)

![image](https://user-images.githubusercontent.com/1812136/161365102-e62f4af2-4bb8-4666-9356-f8511d008db1.png)

**Comment by vrslev** [comment]
> how do I reuse the previous containerized Mysql db?

I suggest to backup previous site and restore it in new setup.

**Comment by a157147899** [comment]
> 

@vrslev  thanks, are you suggesting using frappe commands `Site Backups` and `Site Restores` to do this?

**Comment by a157147899** [comment]
But I remember `bench` was not available for production as its image size is too big, wasn't it?

**Comment by vrslev** [comment]
> thanks, are you suggesting using frappe commands Site Backups and Site Restores to do this?

Yes. 

> But I remember bench was not available for production as its image size is too big, wasn't it?

That’s correct. In backend image we have pretend bench that exposes Frappe’s bench commands.

**Comment by a157147899** [comment]
> That’s correct. In backend image we have pretend bench that exposes Frappe’s bench commands.
@vrslev  I'm a bit confused now. The existing site is running on a production Ubuntu server, if `bench  CLI` is not available for production so how am I supposed to use bench commands to backup/restore the site.

There is no `backend` container before, it only has `python` container. Should I just manually install `bench CLI` in the python container and then backup the site?

**Comment by vrslev** [comment]
> There is no backend container before, it only has python container. Should I just manually install bench CLI in the python container and then backup the site?

Nope. I meant a container that runs http server (Python app). In your case, I guess, it is container named `python`
