### ISSUE TITLE
site restore error - 'docker: invalid reference format'

### ISSUE THREAD

**Issue by saru2020** [frappe/frappe_docker#662]
## Description of the issue
I'm trying to restore a site by running the below command as mentioned [in the docs](https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#restore-backups):
```
docker run -e "MYSQL_ROOT_PASSWORD=admin" -e "BUCKET_NAME=backups" -e "BUCKET_DIR=frappe-bench" -v custom_frappe_docker_sites-vol:/home/frappe/frappe-bench/sites -v ./backups:/home/frappe/backups --network custom_frappe_docker_default frappe/frappe-worker:$FRAPPE_VERSION restore-backup
```
but I'm getting this error:
```
docker: invalid reference format
```

## Steps to reproduce the issue

1. Copy the backup files in the mounted volume
2. Run the command to restore the site from the backups folder
3. Observe the issue

### Observed result
docker: invalid reference format

### Expected result
Should be able to restore the site from the backup files

### Stacktrace / full error message if available

```
bash$ docker run -e "MYSQL_ROOT_PASSWORD=admin" -e "BUCKET_NAME=backups" -e "BUCKET_DIR=frappe-bench" -v custom_frappe_docker_sites-vol:/home/frappe/frappe-bench/sites -v custom_frappe_docker_sites-vol:/home/frappe/backups --network custom_frappe_docker_default frappe/frappe-worker:${FRAPPE_VERSION} restore-backup
docker: invalid reference format.
See 'docker run --help'.
```

note:
I didn't built the containers using the `--project-name`, instead I built the containers by running this: `docker compose up`

Should I be doing something else?

CC: @revant

**Comment by revant** [comment]
> frappe/frappe-worker:$FRAPPE_VERSION

$FRAPPE_VERSION should not be empty

**Comment by saru2020** [comment]
i do have that var in env but for some reason, it is not being picked up, so I just hardcoded it and ran this command:

```
docker run -e "MYSQL_ROOT_PASSWORD=admin" -e "BUCKET_NAME=backups" -e "BUCKET_DIR=frappe-bench" -v custom_frappe_docker_sites-vol:/home/frappe/frappe-bench/sites -v custom_frappe_docker_sites-vol:/home/frappe/backups --network custom_frappe_docker_default custom-app-erpnext-worker:v13 restore-backup
```

and now I'm seeing this error:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 313, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 271, in main
    backups = [
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 272, in <listcomp>
    datetime.datetime.strptime(backup, DATE_FORMAT)
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'logs' does not match format '%Y%m%d_%H%M%S'
```

I think the volume I'm using is wrong. 
[note: I don't know how to mount a new 'backups' volume onto a container, should it be a new one? any reference on how to do this with step-by-step instructions would be helpful for noobs like me]

**here's what I did:**
I bash'ed into the running container(custom-app-erpnext-nginx:v13) and created a folder named: "backups" and added the backup files in the same structure as described [here](https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#restore-backups), then, I committed the changes into a new image by following this [instruction](https://stackoverflow.com/a/33956387/1374730), then deleted the old image and renamed the newly created image & also deleted all the existing containers and again ran `docker compose up` (which recreated the containers from the newly created image)

**Comment by revant** [comment]
i had written those scripts, those scripts are going to be removed.

neon
nginx container doesn't have anything to restore backups.

manually restoring is the only option.

**Comment by saru2020** [comment]
> i had written those scripts, those scripts are going to be removed.

ok, you mean the scripts aren't working?

> manually restoring is the only option.

may I know, what do you mean by manual restore? any reference with the instructions on this topic, please

**Comment by revant** [comment]
scripts are working. there is no accurate "how to"

manual option:

use `docker cp` to copy backups into container, or mount volume.

once files are available to python container use bench restore or simply copy files and restore db dump

**Comment by saru2020** [comment]
manual backup works but now i'm seeing this issue thrown in a popup after the restore:
```
Session Start Failed
(1054, "Unknown column 'category' in 'field list'")
```
the `bench restore` command didn't throw any error and it simply replied with this message (in green): `Site mynewsite1.localhost has been restored with files`

now, i don't know where to even look to fix this issue, any inputs?

**Comment by saru2020** [comment]
@revant thank you for the guidance, manual restore works though not an ideal process, 
isn't there a way to simplify this? is this WIP or something?
also, any inputs on how this could be automated?

**Comment by saru2020** [comment]
@revant thank you for the guidance, manual restore works though not an ideal process,
isn't there a way to simplify this? is this WIP or something?
also, any inputs on how this could be automated?

another unrelated question: how should i configure 'site_config.json' ?

**Comment by revant** [comment]
i don't use docker or docker swarm, you can write scripts using docker command to automate.

for Kubernetes I mount pvc with backups into Job resources and run them.

also I'm not automating restore as it's part of installation i have to do only once. Once the compressed gz of the db reaches 2gb even backup and restore become topic out of syllabus. Volume snapshot and restore can be useful in that case.

it's not WIP. in fact in the next refactor we'll be removing all commands scripts and directly use patched bench command instead. so "[bench restore](https://discuss.erpnext.com/t/backup-restore/5675/4?u=revant_one)" will work directly

**Comment by saru2020** [comment]
thank you @revant for these insights. 

> another unrelated question: how should i configure 'site_config.json' ?

should I update site config also manually?

**Comment by revant** [comment]
> should I update site config also manually?

yes. you can do that manually or use `bench set-config` command
