### ISSUE TITLE
[BUG]No module named traceback, when I finish the ERPNexts setting

### ISSUE THREAD

**Issue by JoeyGaojingxing** [frappe/frappe_docker#67]
03:35:27 web.1            | 123.124.147.122 - - [02/Jul/2019 03:35:27] "POST /api/method/erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.validate_bank_account HTTP/1.1" 200 -
03:35:27 web.1            | INFO:werkzeug:123.124.147.122 - - [02/Jul/2019 03:35:27] "POST /api/method/erpnext.accounts.doctype.account.chart_of_accounts.chart_of_accounts.validate_bank_account HTTP/1.1" 200 -
03:35:31 worker_default.1 | 03:35:31 default: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name=u'frappe.core.doctype.user.user.update_gravatar', kwargs={'name': u'mojerro@163.com'}, method=u'frappe.core.doctype.user.user.update_gravatar', site='site1.local', user=u'Administrator') (1bef8aa7-fbde-4a5e-9f97-65036d8e1476)
03:35:49 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.pyc', reloading
03:35:49 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.pyc', reloading
03:35:49 web.1            |  * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.pyc', reloading
03:35:49 web.1            | INFO:werkzeug: * Detected change in '/home/frappe/frappe-bench/apps/erpnext/erpnext/setup/setup_wizard/operations/taxes_setup.pyc', reloading
03:35:50 web.1            | ----------------------------------------
03:35:50 web.1            | Exception happened during processing of request from ('123.124.147.122', 56481)
03:35:50 web.1            | Exception in thread Thread-18 (most likely raised during interpreter shutdown):
03:35:50 web.1            | Traceback (most recent call last):
03:35:50 web.1            |   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
03:35:50 web.1            |   File "/usr/lib/python2.7/threading.py", line 754, in run
03:35:50 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
03:35:50 web.1            |   File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/werkzeug/serving.py", line 747, in handle_error
03:35:50 web.1            |   File "/usr/lib/python2.7/SocketServer.py", line 350, in handle_error
03:35:50 web.1            | <type 'exceptions.ImportError'>: No module named traceback
03:35:50 web.1            |  * Restarting with inotify reloader
03:35:50 worker_default.1 | 03:35:50 default: Job OK (1bef8aa7-fbde-4a5e-9f97-65036d8e1476)
03:35:50 worker_default.1 | 03:35:50 Result is kept for 500 seconds
03:35:51 worker_default.1 | 03:35:51 default: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name=u'frappe.core.doctype.user.user.update_gravatar', kwargs={'name': u'mojerro@163.com'}, method=u'frappe.core.doctype.user.user.update_gravatar', site='site1.local', user=u'Administrator') (c55e7949-05d2-4260-946a-a7eacfe68ad4)
03:35:51 worker_default.1 | 03:35:51 default: Job OK (c55e7949-05d2-4260-946a-a7eacfe68ad4)
03:35:51 worker_default.1 | 03:35:51 Result is kept for 500 seconds

![image](https://user-images.githubusercontent.com/15071824/60480964-203b7e80-9cbe-11e9-8ea0-35795706c520.png)

**Comment by chabad360** [comment]
For now, my only workaround is to try again. It happened to me numerous times, and you just have to hit "go back", and then just try again

**Comment by JoeyGaojingxing** [comment]
I have tried many times, I think I should try for more

**Comment by chabad360** [comment]
The other possibility is that the `develop` branch (which is pulled by default) has a bug... If not that, idk what the issue is, try running a plain `debian:9.6` container and run the official install instructions from the bench wiki and see what happens.

**Comment by JoeyGaojingxing** [comment]
I think this error is in code
`07:36:16 web.1            | <type 'exceptions.ImportError'>: No module named traceback`
it import a model which is unknown, I will try for the master branch to checkout if there is the same error

**Comment by chabad360** [comment]
Honestly, I don't think that's an issue on our side, but if it is, I've got no idea why.
