### ISSUE TITLE
docker-compose --project-name erpnext up -d not working with docker-compose v 2.2.3

### ISSUE THREAD

**Issue by ThiloteE** [frappe/frappe_docker#670]
## Description of the issue

See error message:
```
[Thilo@server frappe_docker]$ sudo docker compose --project-name exampleprojectname up --detach
unknown flag: --project-name
See 'docker --help'.
```

## Context information (for bug reports)

I think it might be because the script is using the old syntax `docker-compose`
Starting from 2.0, docker-compose got more integrated into docker and changed the main command to `docker compose`. They don't want to break scripts for 1.x versions, but apparently there are still issues. When i installed version1.29 (via [this guide](https://docs.docker.com/compose/install/)) the command worked flawlessly.

## Steps to reproduce the issue

1. Install docker compose v2.2.3 on fedora server 35 following [this guide](https://docs.docker.com/compose/cli-command/#install-on-linux)
2. Try to install frappe_docker following [this guide](https://github.com/frappe/frappe_docker/wiki/Easiest-Install)

**Comment by ThiloteE** [comment]
- I tried using [Compose-Switch](https://docs.docker.com/compose/cli-command/#compose-switch), but it was not working either. I suspect, because it is not available for my hardware (x86-64)

- After i was done, i stumbled upon this sentence:

   "If the command `docker-compose` fails after installation, check your path. You can also create a symbolic link to `/usr/bin` or any other directory in your path."
   
   For example:

    `sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose`
    
    Have not tried this yet though.

**Comment by vrslev** [comment]
`compose` is a Docker plugin now. As I can see, you haven’t installed it right. Also the issue is not relevant to frappe_docker. Follow this guide, please: https://github.com/docker/compose#where-to-get-docker-compose 😉

**Comment by ThiloteE** [comment]
Thanks. Maybe i misconfigured it. The guide you posted had some new info I was not aware of.
Anyway, since 1.29 worked for me, I will refrain from pursuing this any further.
