### ISSUE TITLE
Error: no such option: --skip-bench-mkdir

### ISSUE THREAD

**Issue by JoeyGaojingxing** [frappe/frappe_docker#68]
![image](https://user-images.githubusercontent.com/15071824/60481268-385fcd80-9cbf-11e9-8a96-52e3aee6325a.png)
in wiki, bench do not have a --skip-bench-mkdir attribute

**Comment by JoeyGaojingxing** [comment]
I guess it should be --ignore-exist

**Comment by chabad360** [comment]
Yes exactly

**Comment by JoeyGaojingxing** [comment]
I just wanna to help correct the wiki

**Comment by chabad360** [comment]
You should be able to do that from the wiki page
