### ISSUE TITLE
how to build custom apps

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#681]
- single Frappe app
- single Frappe app depending on ERPNext
- multiple official apps, v14 onwards users will need multiple apps along with ERPNext (twilio_integration, agriculture, etc)
- multiple community apps (posawesome, s3 attachments, etc)
- multiple private apps from private repositories

**Comment by vrslev** [comment]
Probably blocked until #697.

**Comment by vrslev** [comment]
@revant We have custom app guide and install-app script. Maybe close the issue?

**Comment by vrslev** [comment]
Custom app guide covers all cases. If there’s still will be need to change something, open another issue. https://github.com/frappe/frappe_docker/tree/main/custom_app
