### ISSUE TITLE
exec './dbench init' shows 'Procfile_docker': No such file or directory

### ISSUE THREAD

**Issue by JoeyGaojingxing** [frappe/frappe_docker#69]
![image](https://user-images.githubusercontent.com/15071824/60482736-516b7d00-9cc5-11e9-963d-1b855d7d1876.png)

when execute `./dbench init`, it always shows this error. It's originally because the directory 'frappe' already exist, I want to fix this warnnings.

**Comment by chabad360** [comment]
This can only be run once...

**Comment by JoeyGaojingxing** [comment]
I re-clone the repository and solve the problem. But I think this is not the convinent way, and I will try use these command later

**Comment by JoeyGaojingxing** [comment]
anyway, thank you very much

**Comment by chabad360** [comment]
Recloning is effectively what I told you to do (unfortunately), but if you research what it is that our wrapper script is doing you'll realise there's not really a way around it...

**Comment by chabad360** [comment]
As this is a non-issue, can this be closed?
