### ISSUE TITLE
build v14-beta images

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#699]

**Comment by revant** [comment]
@vrslev can we enable it without costly builds?

**Comment by vrslev** [comment]
Why not

**Comment by revant** [comment]
can you send PR whenever you find time?

**Comment by vrslev** [comment]
Sorry, I don't think so. I'm moving on from Frappe related work to new exciting things. I will still keep helping with maintenance, but not new features. Counting on your understanding ✌️

**Comment by revant** [comment]
docker buildx bake is new for me, let me try it out. I'll send PR.
