### ISSUE TITLE
On Mac, irdmi will occupy port 8000

### ISSUE THREAD

**Issue by tom10271** [frappe/frappe_docker#70]
```
	 Open TCP Port: 	8000   		irdmi
```

https://support.apple.com/en-us/HT202944

**Comment by tom10271** [comment]
To bypass this issue, you need to set port mapping from local to docker for Web server to

`docker-compose.yml`

```
      - "8080:8000" # Webserver Port
```

**Comment by chabad360** [comment]
Honestly I would suggest simply changing the port to a different one. You will need to change three files, `docker-compose.yml`, `frappe-bench/Procfile-docker`, and `frappe-bench/sites/common_site_config_docker.json`.

**Comment by tom10271** [comment]
You mean `frappe-bench/Procfile`?

**Comment by chabad360** [comment]
Yes-ish, if you haven't run `./dbench init` yet, it's `Procfile_docker`. However, once you do it's renamed to `Procfile`.

**Comment by chabad360** [comment]
Please close, since as of #84 this is no longer relevant.
