### ISSUE TITLE
How to enable remote access to mariadb container?

### ISSUE THREAD

**Issue by firmlab** [frappe/frappe_docker#706]
Hello, i'm wondering how we can connect database tools such as Heidisql to the mariadb container from frappe_docker installation

i tried to add 'ports' config in the docker-compose.yml, but it seems not working

` 
mariadb:
    image: mariadb:10.6
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # Sometimes db initialization takes longer than 10 seconds and site-creator goes away.
      # Frappe doesn't use CONVERT_TZ() function that requires time zone info, so we can just skip it.
      - MYSQL_INITDB_SKIP_TZINFO=1
    ports:
      - "3306:3306"
     `
![image](https://user-images.githubusercontent.com/48182512/158732973-0789f763-47d3-422b-9a31-b73013478eaa.png)

**Comment by revant** [comment]
> i tried to add 'ports' config in the docker-compose.yml, but it seems not working

As soon as I add ports it works. I am not able to reproduce it. https://discuss.erpnext.com/t/connecting-mariadb-docker-instance-from-mysql-workbench/71541

**Comment by firmlab** [comment]
![image](https://user-images.githubusercontent.com/48182512/158741447-cba92789-1868-4530-94d5-7cba0e692190.png)

thanks @revant 

it's my bad, found the issue, i think if on dev mode, the docker-compose file is in the .devcontainer folder, so you have to add "ports" in there instead right, just added it in there and it works!
