### ISSUE TITLE
Dead link in docker swarm deployment guide.

### ISSUE THREAD

**Issue by RashiqAzhan** [frappe/frappe_docker#707]
Dead link in docker swarm deployment guide.

[Here](https://github.com/frappe/frappe_docker/blob/main/docs/docker-swarm.md) is the link to the guide. This is the dead link: https://github.com/frappe/frappe_docker/blob/main/docs/site-operations

**Comment by vrslev** [comment]
Hey there! Can you send a PR with fix?

**Comment by RashiqAzhan** [comment]
Thank you for entrusting me with the work. I did as advised. #710 https://github.com/frappe/frappe_docker/pull/710

**Comment by vrslev** [comment]
Thanks!
