### ISSUE TITLE
Can't deploy using docker swarm. ERROR: The Compose file './compose.yaml' is invalid because:

### ISSUE THREAD

**Issue by RashiqAzhan** [frappe/frappe_docker#709]
## Description of the issue
Can't deploy using docker-swarm using the [guide](https://github.com/frappe/frappe_docker/blob/main/docs/docker-swarm.md).

## Context information (for bug reports)
OS: Almalinux 8 (CentOS 8 alternative)
Docker version 20.10.13, build a224086
docker-compose version 1.27.4, build 40524192
yq (https://github.com/mikefarah/yq/) version 4.22.1

## Steps to reproduce the issue

1. Clone project and cd to the directory.
```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
```
2. Copy example.env to .env.
```
cp example.env .env
```
3. Follow the swarm guide.
```
docker-compose -f compose.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.swarm.yaml \
  -f overrides/compose.https.yaml \
  config \
  | yq eval 'del(.services.*.depends_on) | del(.services.frontend.labels)' - \
  | yq eval '.services.proxy.command += "--providers.docker.swarmmode"' - > \
  ~/gitops/compose.yaml
```

### Observed result
The Docker swarm doesn't start.

### Expected result
The swarm should just start.

### Stacktrace / full error message if available

```
no such file or directory: /home/user/gitops/compose.yaml
ERROR: The Compose file './compose.yaml' is invalid because:
services.backend.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.queue-default.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.queue-long.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.queue-short.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.scheduler.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
services.websocket.depends_on.configurator.condition contains "service_completed_successfully", which is an invalid type, it should be a service_started, or a service_healthy
```

**Comment by revant** [comment]
which `yq` are you using?

I'm using the one written in golang https://github.com/mikefarah/yq

**Comment by RashiqAzhan** [comment]
> which `yq` are you using?
> 
> I'm using the one written in golang https://github.com/mikefarah/yq

That's the one I'm using.

**Comment by revant** [comment]
can you share the output generated? the gitops/compose.yaml

**Comment by RashiqAzhan** [comment]
I would but there isn't any, if it exists, I can't find it. There isn't any gitops folder in my home folder or inside the cloned project.

**Comment by RashiqAzhan** [comment]
I ran the command again but I manually created the `gitops` folder in my `home` folder and this is what is inside the `compose.yaml`.
```
{services: {proxy: {command: --providers.docker.swarmmode}}}
```

**Comment by revant** [comment]
clearly the compose is invalid. it needs to have more than 7 services.

try docker compose V2?

**Comment by revant** [comment]
I'll try to setup and improve docs. I've not run through docs in live environment anywhere.

**Comment by RashiqAzhan** [comment]
> I'll try to setup and improve docs. I've not run through swarm docs in live environment anywhere.

Would really appreciate the update. ERPNext works fine on local machines but getting it deployed on a VPS has been quite a challenge.

**Comment by revant** [comment]
move discussion to #717
