### ISSUE TITLE
Nginx container is not startiing

### ISSUE THREAD

**Issue by pptyasar** [frappe/frappe_docker#716]
## Description of the issue
All container is started but nginx container alone not started

## Context information 
OS: Ubuntu 18 / Ubuntu 21
Cloud Provider: Digital Ocean
RAM: 2GB
Hard Disk: 25GB

## Steps to reproduce the issue

1. git clone https://github.com/frappe/frappe_docker
2. cd frappe_docker
3. cp example.env .env
4. docker-compose -f compose.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  -f overrides/compose.https.yaml \
  config > ~/gitops/docker-compose.yml
5. docker-compose --project-name <project-name> -f ~/gitops/docker-compose.yml up -d

### Observed result

68d43325ca22   frappe/erpnext-nginx:v13.22.1     "/docker-entrypoint.…"   33 seconds ago   Exited (1) 29 seconds ago                                                                              ms_frontend_1

### Expected result

frappe/erpnext container should run

### Stacktrace / full error message if available

```

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/frappe-entrypoint.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/03/19 15:24:42 [emerg] 1#1: invalid variable name in /etc/nginx/nginx.conf:37
nginx: [emerg] invalid variable name in /etc/nginx/nginx.conf:37

```

**Comment by pptyasar** [comment]
Solution is here 
https://github.com/frappe/frappe_docker/pull/712/commits/aa1719a3a25f6a857c8566d175c77aa4f2be0c2a

Also same issue is here so closing this one
https://github.com/frappe/frappe_docker/issues/711

**Comment by 1ubuntuuser** [comment]
@pptyasar Did you mean #701?
