### ISSUE TITLE
Do we need a docker swarm setup?

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#717]
@1ubuntuuser do you really need a swarm setup?

Does the community really need the swarm setup?

- docker is being replaced by more free and open source alternatives in many places.
- Docker has built-in `docker swarm`. The alternatives don't. e.g. `podman` doesn't have swarm mode.
- When things need to be distributed Kubernetes is where everyone is focusing on.
- Storage is also a challenge: docker volumes by default are mounted on the hosts where the containers run.
- For shared volumes across nodes, NFS is needed and any other alternative is also a challenge.
- There is no dedicated loadbalancer, we choose one of our manager node as loadbalancer and tie the stacks to that node only using labels. In case of kubernetes there variety of ingress-controller/loadbalancer alternatives available which are dedicated loadbalancers

**Comment by 1ubuntuuser** [comment]
I hope to use this system up to a point where swarm mode is required.  For quick setups, I use docker-compose but I have migrated a few services to swarm for the following reasons:

- Better reliability. Docker swarm keeps containers running more reliably in my experience and handles things like power outages etc very well out of the box. I haven't experience with compose v2 but v1 isn't production-grade in my opinion.
- Cost-effective compute. AWS etc offer instances tailored to different kinds of loads. Being able to split the services up between instances reduces the need to run one massive instance

You are right about the pain of file storage. I have used AWS EFS with NFS between nodes. Rock solid for years.

I suggest focusing on making the docker compose experience very quick and easy, and removing complications related to swarm. If anyone wants to use swarm mode, they'ed better know what they are doing.

**Comment by vrslev** [comment]
I agree with @1ubuntuuser. We should remove Docker Swarm related content and focus on Docker Compose setup.

**Comment by revant** [comment]
Okay.

For any container orhestrator setup, understand the volume mounts, environment variables and set of container/image combinations.

Refer:

- [Image and compose files](https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md)
- [Site operations](https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md)
- [compose.yml for volume locations](https://github.com/frappe/frappe_docker/blob/main/compose.yaml)

**Comment by 1ubuntuuser** [comment]
@vrslev That's fair. I wouldn't want it removed completely, as for some it could be very useful but I understand.

**Comment by 1ubuntuuser** [comment]
If someone want's to get a start on swarm, they can review the removed and obsolete files here.
https://github.com/frappe/frappe_docker/commit/b83938c0b89617fb8eb618fe42bd8a0019e89a09
