### ISSUE TITLE
error on compile 

### ISSUE THREAD

**Issue by Ramr93** [frappe/frappe_docker#724]
on exciting the following i got some error 

command : docker-compose -f compose.yaml -f overrides/compose.noproxy.yaml config > ~/gitops/docker-compose.yml
error : bash: /root/gitops/docker-compose.yml: No such file or directory

need help

**Comment by revant** [comment]
try:

`mkdir -p ~/gitops`

**Comment by revant** [comment]
you need to know at least bash errors.

directory should exist before using it to output file.
