### ISSUE TITLE
not found install-app script on erpnext-worker:v12.23.1

### ISSUE THREAD

**Issue by angga30** [frappe/frappe_docker#726]
=> CACHED [backend 1/2] FROM docker.io/frappe/erpnext-worker:v13.23.1@sha256:416c537142d16ff04dc995cf04162c5fd044944a23065378dc7180c3a35a55e0                                0.0s
 => ERROR [backend 2/2] RUN install-app bench_manager version-13  https://github.com/frappe/bench_manager   

this my dockerfile backend

ARG ERPNEXT_VERSION
FROM frappe/erpnext-worker:${ERPNEXT_VERSION}

USER root

RUN install-app bench_manager version-13  https://github.com/frappe/bench_manager

USER frappe

**Comment by revant** [comment]
try with `--no-cache` just?

**Comment by revant** [comment]
@vrslev can help? I've not used the install app scripts.

**Comment by vrslev** [comment]
@angga30 Sorry for inconvenience. Pull latest images, it works now.
