### ISSUE TITLE
install-app from worker image requires git

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#735]
if install-app with git url is used it doesn't work. It needs git command installed.

should we keep the git clone out of image building and just use COPY to get the code into image?

**Comment by vrslev** [comment]
Maybe add Git in final image? It will not be significantly bigger.

**Comment by revant** [comment]
I was able to build images without git in image, I used `COPY` instead.

refer this https://github.com/castlecraft/custom_frappe_docker/tree/beautify

It clones the repos with a script: https://github.com/castlecraft/custom_frappe_docker/blob/beautify/ci/clone-apps.sh

copy repos in backend: https://github.com/castlecraft/custom_frappe_docker/blob/558bcb1b362699ed92954e81cfff9be822d06dec/images/backend.Dockerfile#L6

copy repos in frontend: https://github.com/castlecraft/custom_frappe_docker/blob/558bcb1b362699ed92954e81cfff9be822d06dec/images/frontend.Dockerfile#L8

I had to create `/frappe-bench/sites/assets` directory before executing `install-app bench_manager` or it failed with following:

```
#0 17.14 Done in 10.63s.
#0 17.15 + cp -r sites/assets /out
#0 17.15 + rm -rf apps/posawesome
#0 17.28 + rm -rf sites/assets
#0 17.29 + APP=bench_manager
#0 17.29 + BRANCH=
#0 17.29 + GIT_URL=
#0 17.29 + cd /frappe-bench
#0 17.29 + test ''
#0 17.29 + cp -r apps/bench_manager/bench_manager/public /out/assets/bench_manager
#0 17.29 + yarn --cwd apps/bench_manager --prod
#0 17.45 yarn install v1.22.17
#0 17.47 info No lockfile found.
#0 17.48 [1/4] Resolving packages...
#0 17.48 [2/4] Fetching packages...
#0 17.48 [3/4] Linking dependencies...
#0 17.49 [4/4] Building fresh packages...
#0 17.50 success Saved lockfile.
#0 17.50 Done in 0.05s.
#0 17.51 + cp -r apps/bench_manager/node_modules /out/assets/bench_manager/node_modules
#0 17.51 + yarn --cwd apps/bench_manager
#0 17.66 yarn install v1.22.17
#0 17.69 [1/4] Resolving packages...
#0 17.69 success Nothing to install.
#0 17.69 success Saved lockfile.
#0 17.70 Done in 0.04s.
#0 17.71 + echo bench_manager
#0 17.71 + yarn --cwd apps/frappe run production --app bench_manager
#0 17.86 yarn run v1.22.17
#0 17.92 $ FRAPPE_ENV=production node rollup/build.js --app bench_manager
#0 18.62 Production mode
#0 18.63 internal/fs/utils.js:332
#0 18.63     throw err;
#0 18.63     ^
#0 18.63 
#0 18.63 Error: ENOENT: no such file or directory, mkdir '/frappe-bench/sites/assets/js'
#0 18.63     at Object.mkdirSync (fs.js:1013:3)
#0 18.63     at /frappe-bench/apps/frappe/rollup/build.js:171:7
#0 18.63     at Array.forEach (<anonymous>)
#0 18.63     at ensure_js_css_dirs (/frappe-bench/apps/frappe/rollup/build.js:169:8)
#0 18.63     at Object.<anonymous> (/frappe-bench/apps/frappe/rollup/build.js:39:1)
#0 18.63     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#0 18.63     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#0 18.63     at Module.load (internal/modules/cjs/loader.js:950:32)
#0 18.63     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
#0 18.63     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
#0 18.63     at internal/main/run_main_module.js:17:47 {
#0 18.63   errno: -2,
#0 18.63   syscall: 'mkdir',
#0 18.63   code: 'ENOENT',
#0 18.63   path: '/frappe-bench/sites/assets/js'
#0 18.63 }
#0 18.64 error Command failed with exit code 1.
#0 18.64 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
frontend.Dockerfile:12
--------------------
  11 |     # Installing apps with public directory and build.json only
  12 | >>> RUN install-app posawesome && \
  13 | >>>     install-app bench_manager
  14 |     
--------------------
error: failed to solve: process "/bin/sh -c install-app posawesome &&     install-app bench_manager" did not complete successfully: exit code: 1
```

ref: https://github.com/castlecraft/custom_frappe_docker/blob/558bcb1b362699ed92954e81cfff9be822d06dec/images/frontend.Dockerfile#L14

**Comment by vrslev** [comment]
Should we make required changes to avoid this errors and make it the standard way to install apps from remote git repo? Or just add git?

**Comment by revant** [comment]
I'll prefer to keep the git out of image we can always use `COPY`.

We do need to make the changes to make `install-app` from assets-builder work. 

It is failing for:

- any frappe apps which do not have public directory and
- bench_manager because it can't find `/frappe-bench/sites/assets/js`.

**Comment by vrslev** [comment]
I will send a PR soon.

**Comment by zwessels** [comment]
> I'll prefer to keep the git out of image we can always use COPY.

another benefit is that people don't have to worry about secrets cleanup when cloning private repos

**Comment by vrslev** [comment]
> It is failing for:
> any frappe apps which do not have public directory and

@revant Users shouldn't even try to install apps without frontend code, or I am wrong here? If so, should we update custom app guide?

**Comment by revant** [comment]
> Users shouldn't even try to install apps without frontend code, or I am wrong here?

Some apps may not have frontend code. If you create new app it won't have frontend code. If you do `bench get-app`, it'll run through the script and build no assets. Yet it goes through the `yarn` commands.
