### ISSUE TITLE
cannot get app from other git repo such as gitlab  with bench version v5.0.0

### ISSUE THREAD

**Issue by mojerro** [frappe/frappe_docker#736]
refer to this issue [https://github.com/frappe/bench/issues/1282](url) 

hope to update the frappe/bench image version

**Comment by revant** [comment]
bench image always has latest bench code.

if you don't wish to pull new image and rebuild containers then execute this in devcontainer 

`cd ~/.bench && git pull origin develop && pip3 install --user -e ~/.bench`

**Comment by mojerro** [comment]
actually, I delete all my old image and run a new bench image, it shows that the bench version is always 5.0.0-dev, I don't know what's wrong with it

```
C:\Users\gaojx>docker run --rm -it frappe/bench bash
Unable to find image 'frappe/bench:latest' locally
latest: Pulling from frappe/bench
ae13dd578326: Pull complete
e711733b94df: Pull complete
4a4750314276: Pull complete
411c9b14f613: Pull complete
35bca1ebf3ea: Pull complete
4f4fb700ef54: Pull complete
7277b0fd243a: Pull complete
b017ab505f24: Pull complete
7f67deef8990: Pull complete
Digest: sha256:d28373deb2b3a74123944af22b4ead50b20d9dcb8dfd9a553fbbff15d17500ad
Status: Downloaded newer image for frappe/bench:latest
frappe@50d6016581ee:~$ bench --version
5.0.0-dev
frappe@50d6016581ee:~$
```

and I need to update the bench by reinstalling it in docker.

**Comment by mojerro** [comment]
I used another computer and pulled this image, it has the same problem.


And this problem has been fixed in the newest bench version.

**Comment by revant** [comment]
bench in the image won't show any version 

it is installed using repository code. the code is available in ~/.bench. you can confirm the latest code using `git log`

**Comment by mojerro** [comment]
> bench in the image won't show any version
> 
> it is installed using repository code. the code is available in ~/.bench. you can confirm the latest code using `git log`

I have a try with the latest image, and it's all well done. Thanks for your explanation

**Comment by mojerro** [comment]
after I re-pull the latest image, I only check the bench version instead of trying to run the command again, so I didn't notice that the problem has already been solved.
