### ISSUE TITLE
Can't start frappe

### ISSUE THREAD

**Issue by hizbul25** [frappe/frappe_docker#74]
While I `./dbench start` run it showing end of the installation.

07:29:51 watch.1          | Rebuilding list.min.css
07:29:51 watch.1          | Rebuilding list.min.js
07:29:53 watch.1          | Rebuilding report.min.css
07:29:53 watch.1          | Rebuilding report.min.js
07:29:55 watch.1          | Rebuilding web_form.min.js
07:29:56 watch.1          | Rebuilding web_form.css
07:29:56 watch.1          | Rebuilding email.css
07:29:56 watch.1          | Rebuilding social.min.js
07:29:58 watch.1          | Rebuilding modules.min.js
07:29:58 watch.1          | Rebuilding barcode_scanner.min.js
07:30:00 watch.1          | Killed
07:30:00 watch.1          | error Command failed with exit code 137.
07:30:00 watch.1          | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
07:30:01 system           | watch.1 stopped (rc=0)
07:30:01 system           | sending SIGTERM to worker_long.1 (pid 952)
07:30:01 system           | sending SIGTERM to web.1 (pid 954)
07:30:01 system           | sending SIGTERM to schedule.1 (pid 955)
07:30:01 system           | sending SIGTERM to worker_default.1 (pid 956)
07:30:01 system           | sending SIGTERM to socketio.1 (pid 957)
07:30:01 system           | sending SIGTERM to worker_short.1 (pid 958)
07:30:01 system           | socketio.1 stopped (rc=-15)
07:30:01 system           | schedule.1 stopped (rc=-15)
07:30:01 worker_long.1    | 07:30:01 Warm shut down requested
07:30:01 worker_short.1   | 07:30:01 Warm shut down requested
07:30:01 worker_default.1 | 07:30:01 Warm shut down requested
07:30:03 system           | worker_short.1 stopped (rc=-15)
07:30:03 system           | worker_default.1 stopped (rc=-15)
07:30:03 system           | worker_long.1 stopped (rc=-15)
07:30:03 system           | web.1 stopped (rc=-15)

**Comment by chabad360** [comment]
that seems to be an issue with frappe...
But I will try to have a look at it some time this week.

**Comment by chabad360** [comment]
Have you tried again?

**Comment by micksatana** [comment]
@chabad360 I tried just now. It can start normally.

**Comment by hizbul25** [comment]
Today I've installed once again and getting the same issue. @chabad360
