### ISSUE TITLE
Can't create a new site

### ISSUE THREAD

**Issue by a157147899** [frappe/frappe_docker#749]
Hi,

I followed the latest instructions to set up a new ERPNext site on a Ubuntu server (`20.04 (LTS) x64`), and all the containers have been started up successfully, but I failed to create a new site by running the command below, it didn't give any responses/errors.
`docker-compose exec backend bench new-site rockerp.co.nz --mariadb-root-password 123 --admin-password admin`

![image](https://user-images.githubusercontent.com/1812136/161377823-7ef1ee6a-463c-42f1-b14d-40b0b8f75d9a.png)

One thing I've noticed is that SSL certificate generation was failed, I have no idea why it was trying to register for the domain `frontend-rockerpconz` as it's not a configuration I specified.
![image](https://user-images.githubusercontent.com/1812136/161378060-1bdd8d39-8f73-4720-a71e-81bc28806fc3.png)

I checked the sites inside the `backend` container, no sites were created.
![image](https://user-images.githubusercontent.com/1812136/161378222-7bbc58f4-e920-4c69-9b3f-9f1d6002ae7a.png)

.env
```
# Reference: https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md

FRAPPE_VERSION=v13.24.0

# Only with ERPNext override
ERPNEXT_VERSION=v13.24.0

DB_PASSWORD=123

# Only if you use external database
DB_HOST=
DB_PORT=

# Only if you use external Redis
REDIS_CACHE=
REDIS_QUEUE=
REDIS_SOCKETIO=

# Only with HTTPS override
LETSENCRYPT_EMAIL=rockleeyu@gmail.com

# These environment variables are not required.

# Default value is `$$host` which resolves site by host. For example, if your host is `example.com`,
# site's name should be `example.com`, or if host is `127.0.0.1` (local debugging), it should be `127.0.0.1`.
# This variable allows to override described behavior. Let's say you create site named `mysite`
# and do want to access it by `127.0.0.1` host. Than you would set this variable to `mysite`.
FRAPPE_SITE_NAME_HEADER=

# Default value is `127.0.0.1`. Set IP address as our trusted upstream address.
UPSTREAM_REAL_IP_ADDRESS=

# Default value is `X-Forwarded-For`. Set request header field whose value will be used to replace the client address
UPSTREAM_REAL_IP_HEADER=

# Allowed values are on|off. Default value is `off`. If recursive search is disabled,
# the original client address that matches one of the trusted addresses
# is replaced by the last address sent in the request header field defined by the real_ip_header directive.
# If recursive search is enabled, the original client address that matches one of the trusted addresses is replaced by the last non-trusted address sent in the request header field.
UPSTREAM_REAL_IP_RECURSIVE=
```

**It would be helpful if you guys could try a fresh installation to make sure the whole refactor is actually working.**

**Comment by revant** [comment]
#715 was merged recently, check the updated docs for more details about setup.

**Comment by a157147899** [comment]
@revant Is this a typo?
![image](https://user-images.githubusercontent.com/1812136/161461104-0e7c990b-fe43-4acc-bed4-834b85a485d0.png)

**Comment by a157147899** [comment]
@revant I‘m also wondering why there is no notes mentioned to replace those dummy domains? We should replace it with our actual domain right?

![image](https://user-images.githubusercontent.com/1812136/161465580-2a70c135-a463-4779-9052-5522144c6ff7.png)

**Comment by revant** [comment]
@a157147899 you didn't comment anything about this when it was a PR? if you wish to fix send a PR?

everyone who tested the PR commented, i made changes as per their comments. Now you can update the base docs if you feel there need improvement.

**Comment by a157147899** [comment]
> 

@revant  

First, I didn't even realise there was such a refactor PR until @vrslev mentioned it in this issue #661 so how I am supposed to mention it when it was PR? Actually, I wouldn't have followed the latest docs and tried a fresh installation if my previous issue could get resolved.

Second, I understand this is an open-source project and I really appreciate that you guys using your spare time to share this project with everyone, but just remember that most of the people who came here are not intended to make code changes, or they are just simply not able to do it as they may not be familiar enough with docker. 

Last, even though I found the docs may have some issues doesn't mean I have the capability to improve it, and most important thing is that I have no idea what the refactor plan is, you guys probably already have a solid plan in mind, so I would think the best thing I can do is to raise an issue as I am not sure what changes I should make if I am gonna submit a PR.
