### ISSUE TITLE
Need to set "host_name" in "site_config.json"?

### ISSUE THREAD

**Issue by workpush** [frappe/frappe_docker#756]
I am facing several differences between "printing" and directly creating a "PDF", e.g. for a sales invoice.
The "printed" version is correct, where the direct "PDF" generated one is broken.

I found this thread: https://discuss.erpnext.com/t/pdf-print-format-difference-using-the-printer-icon-and-pdf-icon/39394/2
where the solutions should be to set "host_name" in the "site_config.json" file.
Executing:
```
podman exec -it frappe_docker_erpnext-python_1 cat erpnext.mysite.lan/site_config.json
```
does not show any "host_name" key.

I am using the current "v13.24.0" docker images, but I'm not sure to which service I need to set as value for "host_name".

If I should guess I would use for the new `compose.yml`:
https://github.com/frappe/frappe_docker/blob/main/compose.yaml
```
"host_name": "backend",
```
and for the `legacy`one:
https://github.com/frappe/frappe_docker/blob/compat/docker-compose.yml
```
"host_name": "erpnext-python",
```

Can you help me with that? Is it still needed nowadays in the site_config.json?

**Comment by revant** [comment]
host_name should be the site name/FQDN that resolves to your site. It is not the container hostname.

to set it, enter any container that runs the worker image and mounts the sites volume and run the `bench --site site.name set-config host_name https://erp.example.com`

you can even create a new container with nano or vi image and mount sites volume to access the config files with editor.
