### ISSUE TITLE
Access admin panel of ERPNext

### ISSUE THREAD

**Issue by a157147899** [frappe/frappe_docker#757]
Hi,

I followed the latest docs [Single Server](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md) to set up ERPNext on a production Ubuntu server and now I can access the Traefik dashboard via my domain.

![image](https://user-images.githubusercontent.com/1812136/161735820-e5a3dd27-f64c-48f5-9c9b-6429d3a14e9e.png)

However, I couldn't figure out what URL I should access for the admin panel of ERPNext. During the setup process, I changed the dummy domains below ``"SITES=\`one.example.com\`,\`two.example.com\`"`` to my actual domain, which I am not sure if it is supposed to be changed, but the point is that I have only one domain, and since it is being used by Traefik dashboard, so how can I access the real admin panel of ERPNext?

![image](https://user-images.githubusercontent.com/1812136/161735578-2d38a2b5-6c39-4530-802f-c1c615d1a16e.png)

Any help would be much appreciated.

**Comment by darkacorn** [comment]
did you point your domain to your ip too ? the a record needs to point torwards it / clear dns cache 
and try again
say its erp.mydomain.tdl 
and you will need an a record for erp pointing to the server ip 

you can fake/mock that if you alter the /etc/host file and fill it in for now

**Comment by a157147899** [comment]
> 

@darkacorn  yes, DNS records have been pointed to the server IP and I can access the Traefik dashboard via my domain.

**Comment by revant** [comment]
traefik subdomain and erp subdomain are 2 different domains

the list of site that need to generate letsencrypt certificate are metioned in `SITES` environment variable. Each site is quote in backtick (`) if you just have 1 site create it with

```
SITES=`erp1.example.com`
```

You can access traefik on the subdomain configured for traefik.

You can access erpnext on subdomain configured for erpnext.

Same domain can't be used to serve both traefik and erpnext.

e.g. `traefik.mydomain.com` will server the traefik and `www.mydomain.com` will serve erpnext

**Comment by a157147899** [comment]
> traefik subdomain and erp subdomain are 2 different domains
> 
> the list of site that need to generate letsencrypt certificate are metioned in `SITES` environment variable. Each site is quoted in backtick (`) if you just have 1 site create it with
> 
> ```
> SITES=`erp1.example.com`
> ```
> 
> You can access traefik on the subdomain configured for traefik.
> 
> You can access erpnext on subdomain configured for erpnext.
> 
> Same domain can't be used to serve both traefik and erpnext.
> 
> e.g. `traefik.mydomain.com` will server the traefik and `www.mydomain.com` will serve erpnext

@revant ah, I didn't realize it's subdomain, thanks a lot.

**Comment by tejasgowdaki** [comment]
@a157147899 i'm stuck in the same place. Did you replace `SITES=`one.example.com`,`two.example.com`` with `SITES=`erp1.yourdomian.com``
