### ISSUE TITLE
One of bench command seems not working?

### ISSUE THREAD

**Issue by firmlab** [frappe/frappe_docker#761]
Hi,

I installed a fresh frappe_docker installation, when setting up the host seems the command `bench set-mariadb-host mariadb` is not working with message: *No such command set-mariadb-host*

in the end I resolved this issue by editing `common_site_config.json` to set the host, but this will confuse a newcomer to this framework

any suggestion?

**Comment by revant** [comment]
That command won't work, use:

```shell
bench set-config -g db_host mariadb
```

**Comment by firmlab** [comment]
@revant would you mind to update the readme file in here?
https://github.com/frappe/frappe_docker/tree/main/development

I believe many people will refer to this guide when they use frappe with docker

thanks a lot!
