### ISSUE TITLE
documentation issue single-server example.md

### ISSUE THREAD

**Issue by laptopmutia** [frappe/frappe_docker#768]
https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

the command is `docker-compose` instead `docker compose`

also I confused I have follow the guide and steps from that example 

until the last command

how to access the website? how to run the server/docker ?

**Comment by africlouds** [comment]
you need to use docker compose v2

**Comment by revant** [comment]
If you follow this step of the guide https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md#install-compose-v2 It installs the docker compose v2. After that is installed `docker compose` should work.

If you wish to make `docker-compose` as well as `docker compose` to work and use v2, download compose-switch as docker-compose: https://docs.docker.com/compose/cli-command/#compose-switch

```
sudo curl -fL https://github.com/docker/compose-switch/releases/download/v1.0.4/docker-compose-linux-amd64 -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
