### ISSUE TITLE
Multiple Custom Apps

### ISSUE THREAD

**Issue by africlouds** [frappe/frappe_docker#769]
I am testing to use 2 custom apps following the documentation. Here is my Dockerfile:
I am following this:
`Both backend and frontend builds contain install-app script that places app where it should be. Each call to script installs given app. Usage: install-app [APP_NAME].`

```
ARG FRAPPE_VERSION

FROM frappe/assets-builder:${FRAPPE_VERSION} as assets

COPY ./apps apps
RUN install-app frappe_plus
RUN install-app administrative_locations


FROM frappe/frappe-nginx:${FRAPPE_VERSION}

COPY --from=assets /out /usr/share/nginx/html

```
It looks like in sites/apps.txt only the first app is present. I have reversed the order and always the first app is added in the file.

_Note that I have chosen to put my apps under apps folder so I can run one COPY command on the whole folder_

**Comment by revant** [comment]
I have an example repo with custom apps https://github.com/castlecraft/custom_frappe_docker. Check if that helps.
