### ISSUE TITLE
Copy env-production to .env (setting up)

### ISSUE THREAD

**Issue by sebadamus** [frappe/frappe_docker#780]
Hi, very sorry to ask, dont know if here would be ok... but where can I get the env-production file to be copied to .env? because here https://github.com/frappe/frappe_docker/wiki/Easiest-Install says so but cant be found...```

Thanks,

$ **cp env-production .env**
$ sed -i -e "s/FRAPPE_VERSION=edge/FRAPPE_VERSION=v12.9.4/g" .env
$ sed -i -e "s/ERPNEXT_VERSION=edge/ERPNEXT_VERSION=v12.6.2/g" .env
$ sed -i -e "s/email@example.com/hello@myweb.com/g" .env
$ sed -i -e "s/erp.example.com/erp.myweb.com/g" .env
$ sed -i -e "s/ADMIN_PASSWORD=admin/ADMIN_PASSWORD=supersecret/g" .env
$ sed -i -e "s/MYSQL_ROOT_PASSWORD=admin/MYSQL_ROOT_PASSWORD=longsecretpassword/g" .env
```

**Comment by vrslev** [comment]
@revant We forgot to remove wikis

**Comment by revant** [comment]
I added a message https://github.com/frappe/frappe_docker/wiki#is-not-maintained

closing this.

**Comment by sebadamus** [comment]
Thanks @revant sorry to ask here... but do you know if ERPNext is updating its docs/web or something because I could not find a good installation guide and I really spent lot of hours searching within ERPNext places (discuss, forum, github, like here) I got a burnt, will try again another time.  So if you can point me to a good working official guide would really apreciate it! Thanks.

**Comment by revant** [comment]
Docker Swarm related post https://discuss.erpnext.com/t/erpnext-updating-from-13-22-1-to-13-25-1/88287/12
