### ISSUE TITLE
CI fails

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#781]
CI fails after #777: https://github.com/frappe/frappe_docker/actions/runs/2158948806

**Comment by revant** [comment]
Any idea what is wrong?

I'll try to figure out today.

**Comment by vrslev** [comment]
Look at annotations down below failed run page.

**Comment by revant** [comment]
Okay got it.

```
The workflow is not valid. .github/workflows/build_develop.yml (Line: 31, Col: 18): Invalid input, platforms is not defined in the referenced workflow.
```
