### ISSUE TITLE
builds failing

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#792]
https://github.com/frappe/frappe_docker/runs/6243175361?check_suite_focus=true

Any idea? @vrslev 

anything to report to upstream?

**Comment by revant** [comment]
tried locally, fails with this.

```
subprocess.CalledProcessError: Command '('docker', 'compose', '-p', 'test', '--env-file', '/tmp/pytest-of-revant/pytest-0/frappe-docker0/.env', 'down', '-v', '--remove-orphans')' returned non-zero exit status 1
```

anything to do with latest docker compose v2.5.0?

**Comment by revant** [comment]
@vrslev if we don't solve this the release will not happen. I may have to do things manually for the upcoming release(s) untill the builds are fixed.

The reason I allowed tests to fail but without non 0 exit before.

**Comment by vrslev** [comment]
Hi there!

> anything to do with latest docker compose v2.5.0?

Yes, I guess so. In `frappe_setup` test fixture we stop containers in compose project named `test`. Previously it exited with code `0`, now it does not.

I sent PR where I suppress the exception that caused CI to fail.

**Comment by revant** [comment]
Follow 793, closing this.
