### ISSUE TITLE
frappe docker with postgres

### ISSUE THREAD

**Issue by cleett** [frappe/frappe_docker#80]
Has anyone configured frappe docker(-compose) with postgres?

**Comment by chabad360** [comment]
I haven't tried this yet, but now that you mention it, I'll have a look into in.

**Comment by ddavidebor** [comment]
That would be frigging amazing

**Comment by revant** [comment]
it is possible in frappe-worker image only. I think ERPNext needs some changes to run on postgres.

Challenges:

- new.py is common for v11, v12, develop, frappe and erpnext workers.
- _new_site() function in v12+ has parameter for db_type which defaults to mariadb.
- detect version > if v12+ and DB_TYPE env variable is set > create db on postgres.
- docker-compose-common becomes docker-compose-mariadb, docker-compose-postgres, docker-compose-redis and user can choose to load any

**Comment by ddavidebor** [comment]
Did anybody take a look into it?

**Comment by up_the_irons** [comment]
This would be awesome :100:

**Comment by revant** [comment]
continue discussion here https://github.com/frappe/frappe_docker/pull/288
