### ISSUE TITLE
background tasks doesn't work

### ISSUE THREAD

**Issue by lekhnath** [frappe/frappe_docker#807]
Upon submitting the `Sales Invoice` I am trying to add a task in background assuming it will auto run after some time but it is not happening. 

```python
import frappe
from erpnext.accounts.doctype.sales_invoice.sales_invoice import SalesInvoice as BaseSalesInvoice
import logging
_logger = logging.getLogger(__name__)

class SalesInvoice(BaseSalesInvoice):
    def on_submit(self):
        super(SalesInvoice, self).on_submit()

        _logger.info('Invoice - %s queued in background task...')

        frappe.enqueue('my_app.tasks.my_background_task',
            queue = 'short' ,
            invoice = self.name,
        )
```

I can see the log in console from `_logger` but the task is never run.

I've enabled the scheduler for the current site also. `bench --site=$(sitename) scheduler enable`. What should I do to run the tasks in the background??

**Comment by revant** [comment]
frapp.enqueue() not working in frappe and ERPNext as well?

**Comment by lekhnath** [comment]
In production, by viewing the worker container's log it seems the job has been executed but there will be no effect. For instance, I've created a new file and added some content to that file from the background task. Even if the logs are there the file is not being created. However, if I ran the same command from bench CLI (ie, `$ bench --site <mysite.com> execute 'my_app.tasks.bg'`) the file is being created instantly.

**Short worker container's log***
```
04:42:03 Cleaning registries for queue: short
05:09:03 Cleaning registries for queue: short
05:36:03 Cleaning registries for queue: short
06:03:03 Cleaning registries for queue: short
06:30:04 Cleaning registries for queue: short
06:57:04 Cleaning registries for queue: short
06:59:12 short: frappe.utils.background_jobs.execute_job(event=None, is_async=True, job_name='ird_nepal.tasks.sync_invoice_realtime', kwargs={'invoice': 'ACC-SINV-2022-00002'}, method='ird_nepal.tasks.sync_invoice_realtime', site='demo.thapaaccounting.com.np', user='info@thapaaccounting.com.np') (f698511d-b8f0-4e4c-90ad-1463a34782b9)
06:59:12 short: Job OK (f698511d-b8f0-4e4c-90ad-1463a34782b9)
INFO:rq.worker:short: Job OK (f698511d-b8f0-4e4c-90ad-1463a34782b9)
06:59:12 Result is kept for 500 seconds
INFO:rq.worker:Result is kept for 500 seconds
```

**Comment by lekhnath** [comment]
I was searching for the created file in wrong location as I thought the file will be created on the same directory where the python script was present but instead it was being created at the sites directory. 

Closing the issue.
