### ISSUE TITLE
Cron job not working

### ISSUE THREAD

**Issue by lekhnath** [frappe/frappe_docker#808]
I've added following cron job in my app's `hooks.py` but it is not working.

```python
scheduler_events = {
    'cron': {
        '15 14 * * *': [
            'my_app.tasks.my_cron_job'
        ]
    }
}
```
Is not this task supposed to run at `02:15 PM UTC` daily? What should I do further to make it work?

NOTE: I've enabled the background scheduler for related site. `bench --site=$(sitename) scheduler enable`

**Comment by kurtrottmann** [comment]
Hi, did you run a `bench --site {site} migrate` after changes?

**Comment by revant** [comment]
are ERPNext or frappe `scheduler_events` working?

**Comment by lekhnath** [comment]
> Hi, did you run a `bench --site {site} migrate` after changes?

Yes, @kurtrottmann. I ran migrate several times.

**Comment by lekhnath** [comment]
> are ERPNext or frappe `scheduler_events` working?

Hi @revant . I am not sure how to verify that but I ran the bench command to enable scheduler on that particular site.

**Comment by lekhnath** [comment]
I am still not able to run cron jobs specified in `hooks.py`.

**Comment by revant** [comment]
I think you need to restart bench after hooks are changed.

If it is development setup, quit bench and start it again. Do Ctrl+C in the terminal window where `bench start` is running and run `bench start` again

If it is production setup, redeploying the container does the restart.

Also try `bench --site <sitename> clear-cache`.

> I am not sure how to verify that

check `hooks.py` from erpnext and check if one of those jobs work?

**Comment by lekhnath** [comment]
@revant Thanks. I will give that a try. My another source of confusion is regarding timezone. In which timezone should I set the time value? Is is UTC? or the timezone of the system ? or the timezone of `Administrator` user? 

When I set cron job as below:

```
'cron': {
        '15 14 * * *': [
            'my_app.tasks.my_cron_job'
        ]
    }
```

Is is 02:15 PM UTC?

**Comment by revant** [comment]
> Is is UTC? or the timezone of the OS ? or the timezone of `Administrator` user?

I think it is timezone configured on the server.

**Comment by revant** [comment]
re-open if needed

**Comment by Topiya** [comment]
I am using CRON like this only, but the issue is if the _job is new_ and I do _bench migrate_ .. this job is also enqueued once regardless of given time.

Can anyone please suggest a solution to this?

**Comment by johnrald1** [comment]
e

**Comment by pgandert1963** [comment]
I have the same problem:
In the development environment the scheduler sucks.
When deploying it on production it works.
No errormessage for diagnosis.
The best thing was, that there was a time, when it worked.
If anyone has a solution it is very appreciated. So development of scheduled tasks is nearly impossible.

**Comment by revant** [comment]
try reducing the `scheduler_tick_interval` in `common_site_config.json`.

https://frappeframework.com/docs/user/en/basics/site_config#common-site-config

Another alternative during development is to manually trigger the function with `bench --site .. execute app.path.to.function`.
