### ISSUE TITLE
Need Help to get ERPNext Docker-Compose working on windows 10 

### ISSUE THREAD

**Issue by ashrafZolkopli** [frappe/frappe_docker#809]
Hi all,

I am currently trying to get ERPNext to work on my Windows 10 Laptop using Docker Compose.

I followed the instruction given in this [post](https://discuss.erpnext.com/t/docker-installation-changed-mar-1x-2022/87249/7)

specifically this one

![ERPNext Steps docker compose](https://user-images.githubusercontent.com/59853680/169586262-f468ebf5-f172-45bd-b971-be17a396d8ee.png)

my .env file are as follows

```
# Reference: https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md

FRAPPE_VERSION=v13.29.2

# Only with ERPNext override
ERPNEXT_VERSION=v13.30.0

DB_PASSWORD=123

# Default value is `$$host` which resolves site by host. For example, if your host is `example.com`,
# site's name should be `example.com`, or if host is `127.0.0.1` (local debugging), it should be `127.0.0.1`.
# This variable allows to override described behavior. Let's say you create site named `mysite`
# and do want to access it by `127.0.0.1` host. Than you would set this variable to `mysite`.
FRAPPE_SITE_NAME_HEADER=127.0.0.1
```

to start my docker-compose I'm using this command on my powershell

```Powershell
docker-compose -f compose.yaml -f .\overrides\compose.mariadb.yaml -f .\overrides\compose.redis.yaml -f .\overrides\compose.noproxy.yaml -f .\overrides\compose.erpnext.yaml up -d
```

however when I try to open the browser 

![Localhost error](https://user-images.githubusercontent.com/59853680/169587129-95080683-be94-4283-93e4-cee433e3f8e0.png)

Any pointer would be great

Thanks
Ash

**Comment by revant** [comment]
have you created the first site?

check site operations docs to create new site

**Comment by Namekkural** [comment]
Yes you need to manually create the site the first time you start your instance. Also important: the URL you enter will be used to match the site. So if you enter 127.0.0.1 it will not work.

you need to map e.g. testsite.local (or anything else) to 127.0.0.1 and then create the site testsite.local in frappe.

you can then access it via testsite.local:PORT (the port you specified the yaml files you use to start the server)

hope this helps
