### ISSUE TITLE
Honcho not installed in frappe python env and gives error on debug

### ISSUE THREAD

**Issue by jalajc** [frappe/frappe_docker#816]
## Description of the issue
1. Debug config "Honcho SocketIO Watch Schedule Worker" gives error that honcho.command not present at the location.
 `import main Exception has occurred: ModuleNotFoundError No module named 'honcho'`
2. However, running honcho command directly on bash works well.

## Context information (for bug reports)
1. Upon diagnosis I found, honch is installed on a different location of pip which is default.
2. instead the python referred to location in `launch.json` ->       `"python": "${workspaceFolder}/frappe-bench/env/bin/python",` where have not found the honcho module.
4. `${workspaceFolder}/frappe-bench/env/bin/pip install honcho` resolved the error.

Therefore request: 
1. to configure the docker image such that honcho is available at right location 
2. to update the documents, if need be.

**Comment by revant** [comment]
I don't use this. I comment `web:` line in `Procfile` and do `bench start`.

If you use it, add a fix and send a PR. or mention it in docs.
