### ISSUE TITLE
Specific Scenario Implementation (Docker, Frappe, ERPNext)

### ISSUE THREAD

**Issue by AdelAlMajed** [frappe/frappe_docker#820]
Dears,

Thank you for the hard work, appreciate your efforts.
I'm struggling a lot in implementing a specific scenario as shown in the following link:

[Scenario Link](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Business%20Case.drawio#R7Vtbc%2BI6Ev41qZ2zVbjkK%2FDIJRdPxSYTmMkwLylfhBHYFmvLgPn12%2FIFbOycyewh2ZmqkEqQ222pu79Wd0uRr%2BRRsL%2BNrM3SoC72ryTk7q%2Fk8ZUkiVpXhi9OSXNKX1ZyghcRNyehE2FKDrh4sqQmxMVxQctJjFKfkU2d6NAwxA6r0awoors624L6bo2wsTzcIEwdy29Sn4jLljm1p6IT%2FQ4Tb1mOLKLiTmCVzAUhXlou3VVI8vWVPIooZXkr2I%2Bwz41Xt8vNC3ePgkU4ZK95wPns9jzpsFFvNv7zyhk4w7tFR8p72Vp%2BUihcCMvS0gIg94Y3SZCZarhkgQ%2BXIjS3OGIEbDXwiRcCjdFNhXpv2dh%2FoDFhhPK7NmWMBsDg8xtDy1l7EU1Cd0R9GmVjyYvsAyzZYIN4k0OKgGKVFwuyx27JAtdLxrgvDLjm0o3jhopAwBsWJHRxJDgwonTjWsyCL06P4VvpdezEtn2cX8AfqS8YltMRpZ6wCb3CKKAH3r9obfGIITg%2FpgFmUQos%2B6Mj5I%2FsTl6jSb2ctqx4zJFoFZ7qHfs6gQmNAs9fwFZUG1hm9ubWy0xKI7akHg0BKsqRyzBdYcbSYh5aCaN1xEH7KP3OLwQk9kvCHAgdJCDtyDLeF2PkV2n16gFHBDTEUUHMpcRuYyKe2Ro0oUnk4L9TuYgQVuRh9jd8Wjt2EfYtRrZ1OS6Pi9bAhSs%2FLS5DGvJpdjmoODKico6VIv8hWKn%2FV6xeER%2FXmDnLl6JUBZANJSHLBFSHV%2BqYcxdx0wHjcROXMW24oCErgBWlSqwjAcSmG5%2FYXJnYsTB8j6mzhkAXb70jPv8ocsl9VegVT5VJu9%2BIZV1FkPst0eytgJB%2FDgR2CbMgqI%2Fi%2BDHxs6JB%2BDfY5DyBXSI%2FtWe%2B9hxVS2MlkllGkgf5pXTD0ZOGe%2FAVafRwZ0o%2F0qFiP%2B0T54CIdfeInDHd3suu7KaqbKTq1gmcrbEa7IxR%2F%2BAGDtHvlsy%2BVQ%2BTcN7XgyVy74aHCelt3eDbyr29Tqyn3tYObhI71T1X8tfurdfXV9fonvcx1tXJ7ItoHJyDOTNEg%2Biedftt80NaooepvjenCtzXVWOly5OxrkxmjmpOoZ%2FA9130eYvHiNzPBokxhr5mX1RzNVBMaENfh8lsIBsz3Svvm%2BP53jzoqTH2DpPxV9Ec6zvj8NWD5%2FLnV2vVHH89mAeQ4%2FA11cfX4j3QgJ4aK0cxVp5qHtaivlICXV4uJ7t1z5EfVfv2q%2Bfe%2BbsfM3Cj22%2BKO%2BqvHNkgD2S%2BwrfX3dFUPbjjYfdH4Mf2mK5gXMV8mqOJjI793Msmwk97%2F%2FjMbL%2Bbf3%2Bk%2Bq0Zz7%2Bbh4fpZ%2BhjQPTbL319jfZGqkhmOjjcr8Bu6518vzIksKdqBtcJ6Mh%2FPWM02OnjAQMe0GVoAM9BHxtwz5DmUwUk5L8ZD%2FCixDjAvdVn6FdJJ7eNfrx8jHlqj%2BcJ2MLLZGjly8aLTaIcjCkCGeeoOd6Aj8d4fy5BIL%2BuvCBTxoMDBN%2BerI%2BdxAh2DPjS%2B9k1yOFK9zMD%2BB7j7HsFeE4VxZTnMO4yBj6V85krx%2BPPAKbA4zDwK2ROuf2uizaX81rUx3piELQHeWTenkwHe64PyMj7M0BnpHP9D7rkrspx%2BTOD7BngAxvpqj3%2BmoAvMeDfm3fz9H71RbVHCL7XXD7ZAMy4LubMk%2BxxJjfjck9yHpbxfJ9zPdHkaQd%2B%2BEXk2BmzR00nULUNPxNTmc9i7jnSj4PCY8RFQrCqoFr8lcSuICqNGKyogqQ2Y7AqCt23CsNqIww%2FRNRNnCyESpoPIgztCFoeb12HWxLRMOBqn0drsA6r58cIx%2BTAA3iZS6GkiYsk2JYsz2NwQFyXP9ySaBfE9yth3FVxz%2BUVUcwiusaVOz3JljWtUX5dAlO1jqnYay4QSlIVTRm9EZRaA8ox3mKfbnK4%2FhQsIR9LjtOGpavZmvomWMJHUOSfwtl%2FTzh7v1ipHrcj%2BIVrxcujgSow1m1arEz8s7qpAeKLhVV71UQT5pMQRil3cFCbh5RVXLD3%2BE6TQBcL4mCB11G2FeP42HoOSEie5aanSKgrDXuX8QBNPI%2FQiqA2HEBui87dN3KAfsMBrh8fQj4zG3MZTM0sMHn0%2B8zkwrdaHe7ysVjqClp9%2FkpdrbnGec%2F5WzpUNR4XHv0BYAPAvlROt98Gv1dsFXysUD9WqB8r1I8V6p%2B%2FQpVESZC7ZyVQX%2Bh2%2B6dP93dYsIqv%2BQ%2FXR118qbpY6rX4RevmxbvWxmJz%2B%2FijOH4JQnS2tOn2BK2J3%2FsWV8pHcfx6ADVF6HV%2FPwy7r4jEf9pZA%2BmnZw1wHANuxPI7O2zz%2FdMbvhF4k%2FlLx8cL1smOqXScJNrijg2SHk8hgA%2F5ZPOtdFXKrEI7RS1lOmlW8bJqOruAP8naWUCQmpldbDvaIL7d0YbX7HZ9%2BFLNl2puwR3r7gXHuoTL9Bqb3W3x5729prlFNvL5nJEQWCzTDZSs%2FD%2Fjp%2Bnj9fnhPNG0HAaop56Xt7Nf2gDPDg0U0oqXAFGtb5HJcnOLW9RaUoj0VilEau6RPSTxEigh3p1hx08EvroMeE8cNaeH7UUTR9fCvcWb4Cj3zidjE8e2%2F1W8HY6vOVbzp4Xvnx87JNy5Qsw68Luj0ZqEXscK3Q4wB0kIsnOJO56fbpYdSeGnEvmfQXaK9bnG9Mx7fmaRtcX%2BMw%2F8z1ngf444eHn7pch%2FkQITHdfxZU0ga0JParpVT5C1lhB%2FIl%2Fet16z4P%2Fwrd%2FVt9TeaaVy9C35d%2FGt5jbCFFKGFRGaofXqPMPN%2BoZZplgItKxA67klv76xAuJzW49oEhGeL5EJ6bR2ClHSLlQY9mvQquVBwyquatuqVH0rSJs7C3pWT8CE5K8a8EIiwhbjRaJUrSpg0qFPg83mimdJzQqy%2F65kf4EyHv7FhQ15H4G15g%2BzJQ6uju8p8N7P9y1iUGlJdwJwzZYkzqySKWDz54P0vMDB1RMZaEE5cMWullDtveKS2n8S%2FrpBhmwnd58BVwxt9png5f1SpEGmgbVgmVe4eOPTNB8PrI30k4hOUUeDludifiLh8UZsBS0bNoHlLMGkfzUMbvFHMJjMbaj7qXJY5WTrNcablv6pSxYp4ef6Cz62w9Y6J%2BSCWRmQCSyu%2FEKxBc7eZIkhJsYLknnDjrBl%2BUTrGEUEjXPzAF9Yt1IEBrScF%2ByUi1CpWi%2BCYFVmALBywKc61OjMgsilVevksGX606Rly5TRhCPotStWbkBfyilnzSHqvhGDlL5bThzLcWDdTHgwBVQjnjwRaBETtwXGT2Ue%2FetS0pbdcP7M6GVlcGKUEdI0WMI1njUpK7rnTmRxyZO48GMeIGkGSylyFcaqV1ejyJLGWexBbcf1shDzwDv59ASlBn93SkIiOk2vMhDwwXdLwi06ase8Bsj5OLWwRrenSJt3BLEkcQtZc2Wh6y3AVThqMXJtwPMh6g5xnH6BdRaMjihD8sgRqqN26vFlyt8h2%2B8jxPfTz5F98HG2d41CyvJ4YPE%2B9H8FOa0wcjFhS80rmSkLjSybq3Z6bP%2BiLv%2BL5Fkd6iVRGekK14gx42AVoY%2BEjp%2B4OXifEhviapKNEwTAXfBE2CV58x2kNtLpl%2Ft83JC6hd%2BG2yBvpFYUFiSPhPu86WbvVeRtcKe8YePQ4fFUEASoe%2BtB4mdyNxT8p%2BVivja5wI5E9mnZWVL5zz%2BpGlFxXek0%2F7xJNamJLWeAui1bjIr26zsbcHl6VzO7V3njVb7%2BLw%3D%3D)

The main issue I beleive is that everyone is talking to developers, no one has explain or expected to write the instuction for a business user. Before 3 weeks, I never heared about Frappe nor ERPnext, and before 2 days I don't know what Docker is.

This scenario is suggested by a developer close to me, but he never touched or worked with python before.
So please, if you have any other suggestion, detailed the steps.

Thanks in advance

**Comment by revant** [comment]
> I need to create 2 containers (App & DB) and make them connected
somehow. This will be my production environment for ERPnext.
And after deployment, I will clone the production (in the same
machine) to create a second environment (Development) and keep
modifying and tweaking the app until I feel satisfied with the
modifications, then I will replace the production app container
with the development container, and keep doing the same without
touching the production database.
The production environment should be accessible from outside
(internet).
Note: I am using a home internet, and the app will be hosted on
my PC (Windows 10) and after a while, the production environment
will be moved to the cloud hosting provider, while production
environment will remain the same.

> Please note that I'm not a developer, I need a step by step
configurations and settings, including (ubuntu commands, redis,
MySQL, node, nvm, yarn, nginx, docker, env, bench ...etc).

You should spend more time understanding both frappe/erpnext and containers. It will answer your questions.

To understand architecture read through https://github.com/frappe/frappe/wiki/The-Hitchhiker%27s-Guide-to-Installing-Frappe-on-Linux

General workflow I came up (2021) with for continuous development is mentioned here https://github.com/frappe/frappe_docker/issues/858#issuecomment-1192501048

Search the forum and existing issues for more information.
