### ISSUE TITLE
Images and attachments still not working when site isn't the same as domain

### ISSUE THREAD

**Issue by treasuryesc** [frappe/frappe_docker#826]
## Description of the issue
I've create a site named "soma.com.br", but for the moment my domain isn't available yet, so I use the IP address to access my ERPnext instance using docker and behind a nginx proxy.

The problem is that the images and attachments can't be shown.

I saw that issue #629 tried to solved this, but I still have the same problem because I access my site with IP address. I set FRAPPE_SITE_NAME_HEADER=soma.com.br , which is the domain to be used when available.

## Context information (for bug reports)
I saw in /etc/nginx/templates/default.conf.template that the variable being used is $http_host, which in my case will be the IP address and not soma.com.br, so it causes an error reading the path /files. 

If we could change the variable from http_host to {FRAPPE_SITE_NAME_HEADER} in default.conf.template, this would solve this situation:

        location / {
               ...
                location ~ ^/files/.*.(htm|html|svg|xml) {
                        add_header Content-disposition "attachment";
                        try_files /sites/${FRAPPE_SITE_NAME_HEADER}/public/$uri @webserver;
                }

                try_files /sites/${FRAPPE_SITE_NAME_HEADER}/public/$uri @webserver;
        }

**Comment by revant** [comment]
Can you send a PR if you can confirm it works?
