### ISSUE TITLE
[Proposal] Docker based deployment for production

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#83]
Goals

- Immutable image(s) with locked dependencies for version
- Quick pull and deploy production
- One deployment is one `frappe-bench`
- Deployment supports multi-tenancy like frappe-bench

Proposal

- build images in docker image repo
   - python image has python venv that runs the bench serve process
     - mounts `sites` from host in docker container of this image at `/home/frappe/frappe-bench/sites`
     - mounts `asset-vol` in container at `/home/frappe/frappe-bench/sites/assets`
   - static assets image
     - mounts `sites` from host in docker container at `/var/www/html/sites`
     - mounts `assets-vol` from host to `/assets` in container.
     - Static asset container `rsync` asset to python container on boot
- Images for
  - frappe-socketio (common for other distributions)
  - frappe-python
  - erpnext-python
  - erpnext-com-python
  - ...-python (other official python apps and dependencies)
  - frappe-assets
  - erpnext-assets
  - erpnext-com-assets
  - ...-python (other official html/css/js assets)
- Travis job that runs every day to check, build and push docker images to docker hub
- Update documentation for Docker based production
- click app for use in docker and on docker hosts (optional)
  - in docker container: call frappe functions
  - on docker host: wrapper for `docker exec`, `docker-compose`

I'll move / improve things from here:
- https://gitlab.com/castlecraft/erpnext_kubernetes

**Comment by chabad360** [comment]
First of all, this is amazing (although I am a bit annoyed as it makes all of my hard work obsolete). I really hope that this can become a officially supported/recommended way to run frappe.

Immutability is something that frappe desperately needs, and this could provide the ice-pack for that sore.


> - Images for  
> - frappe-socketio (common for other distributions) 
> - frappe-python  
> - erpnext-python  
> - erpnext-com-python 
> - ...-python (other official python apps and dependencies)
> - frappe-assets
> - epnext-assets
> - erpnext-com-assets
> - ...-python (other official html/css/js assets)


I don't know about you, but a lot of this feels like a bit much. Two containers for a single app feels a bit over the top, especially when you consider that there are a lot of different apps out there, and almost every frappe setup requires at least a bit of individual customization. So this seems a bit daunting for most people to just start to use.


Regarding tags, frappe versions, package versions, etc.: I would think tags should be done similar to distro images, where there is `stretch`, `9`, `9-20190416`, etc. version updates should be as easy as change a tag in the `docker-compose.yml` and running `migrate` (although I think that should be something that is auto-detected). Between major frappe versions (i.e. `11` to `12`) there can be package updates and even distro version updates (i.e. `stretch` to `buster`). But between minor versions, the only thing that should be changing is the python code (unless it's necessary for security reasons).

**Comment by chabad360** [comment]
To say the least, I have a lot to say about this issue, so I'll try to help where I can.

**Comment by revant** [comment]
It is 3 images per deployment.

Python and assets+nginx images are equivalent of bench with apps installed, 

ERPNext, Official apps, forks or whoever wants to add custom app to bench needs to tweak and maintain these images, python image and assets+nginx image.

It is 11 containers per deployment!
Going with idea of one process per container we've

- redis-cache
- redis-queue
- redis-socketio
- mariadb
- web
- frappe socketio
- nginx serves assets and reverse proxy to socketio and python
- schedule
- worker default
- worker short
- worker long

Anyone knows why 3 redis?

I tried only one redis in config and it seems to work

**Comment by chabad360** [comment]
> It's 11 containers per deployment!

But that's a bit misleading, it's only 3 images (and that matters quite a bit). If you could make it rather easy to maintain your own image, or provide a little wrapper that will make it easy to install your own apps, that would be best (maybe I'll try my hand at that).

Regarding Redis, I think the easiest way to test if one is enough, is to run the frappe unit tests (if they work) and see what happens.

Also, do you know anything about running frappe with Postgres? Considering that this is a Docker setup, being a bit modular wouldn't be a bad thing.

**Comment by revant** [comment]
> it's only 3 images (and that matters quite a bit)

If best practices are to be followed, at least 3 images and 7 containers are required, redis and mariadb can be connected to managed service.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#decouple-applications

We already have a multi port, multi process, closely coupled development image/container. Do send PRs to that for ease of development

I've added everything under directory `build` for production images

> If you could make it rather easy to maintain your own image, or provide a little wrapper that will make it easy to install your own apps, that would be best (maybe I'll try my hand at that).

like i said before,
> ERPNext, Official apps, forks or whoever wants to add custom app to bench needs to tweak and maintain these images, python image and assets+nginx image.

Refer how images are made and add your apps or forks in Dockerfile(s). You can even treat these images as base images if you just need to install custom app.
For forks, check how images are built and replace `https://github.com/frappe/erpnext` with your fork

In production images, I'll not recommend to install apps and builds in live containers.
If you still need to modify live containers, exec into container shell and execute commands.

> Regarding Redis, I think the easiest way to test if one is enough, is to run the frappe unit tests (if they work) and see what happens.

Confirmed with adityahase, 3 redis services are required for the use case.

> Also, do you know anything about running frappe with Postgres? Considering that this is a Docker setup, being a bit modular wouldn't be a bad thing.

Frappe framework and apps you build with it can run on Postgres,
ERPNext does not run on postgres today.

Eventually I'll add postgres and other dbs that frappe plans to connect to, it's very modular.

I'll update Howto/Docs/Readme when things are green. I'll add a section for maintaining custom images.

**Comment by revant** [comment]
Can anyone help me with this?
