### ISSUE TITLE
Not available for arm64 arquitecture

### ISSUE THREAD

**Issue by joepa37** [frappe/frappe_docker#838]
Make  `frappe/erpnext-nginx` image compatible with arm64 arquitecture

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues?q=is%3Aissue+arm64

We don't build arm64 images yet.

**Comment by revant** [comment]
if you have arm machine available you can build it locally

```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
# Set environment variables, refer docker-bake.hcl
docker buildx bake --load
```
