### ISSUE TITLE
Support RediSearch

### ISSUE THREAD

**Issue by 1ubuntuuser** [frappe/frappe_docker#841]
**Is your feature request related to a problem? Please describe.**
When trying to save e-commerce settings I get the following `Invalid field name: is_redisearch_enabled`
I'm assuming it's related to this?
![image](https://user-images.githubusercontent.com/17303371/177258162-a1d78f6a-f4a1-475f-a4cf-67d1d1affd0c.png)

I would follow the instructions here but I think it needs to be done at the container level as they are static.
https://docs.erpnext.com/docs/v13/user/manual/en/e_commerce/articles/installing_redisearch_to_enable_super_fast_e_commerce_search

**Comment by 1ubuntuuser** [comment]
I also get the `Invalid field name: is_redisearch_enabled` when I try publish an item to the website.

**Comment by revant** [comment]
can you try this image instead of standard redis image https://hub.docker.com/r/redislabs/redisearch/ for redis-cache container?

**Comment by revant** [comment]
If you wish you can send PR and document it. Closing it.
