### ISSUE TITLE
Mount assets on workers

### ISSUE THREAD

**Issue by toontoet** [frappe/frappe_docker#844]
## Description of the issue

Sending PDF mails didn't work using the default compose.yml configuration. See: https://github.com/frappe/frappe/issues/14177

That was caused by the fact that the assets volume was not shared with the worker services.

## Steps to reproduce the issue

1. Start a Frappe config using the default `compose.yml`
2. Set-up e-mail domain and default e-mail account configuration
3. Send a DocType using e-mail

### Observed result

Errors appear in frappe error logs about missing asset (`website.bundle.css`).
Checked inside the conainer and the sites/assets folder was empty
Mail was not sent

### Expected result

No errors,
Mail sent

### Solution

Mount the assets on the workers
```
x-backend-defaults: &backend_defaults
  <<: *depends_on_configurator
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - assets:/home/frappe/frappe-bench/sites/assets
```

**Comment by revant** [comment]
please send a PR.

**Comment by revant** [comment]
note: It also needs to be changed for helm chart.

I'll change it some time, no ETA.
