### ISSUE TITLE
Non-existent link

### ISSUE THREAD

**Issue by CringeDeveloper** [frappe/frappe_docker#849]
At page https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md
We have string "Note: To know more about environment variable [read here](https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files#configuration). Set the necessary variables in the .env file." which [read here](https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files#configuration) but this link is invalid end return 404 page

**Comment by revant** [comment]
working link: https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md

no eta for me to fix this, if you wish you can send a fix.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/850
