### ISSUE TITLE
Building docker images with sudo git clone for preserving files permission 

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [frappe/frappe_docker#851]
Hey so now I am successfully able to build image for arm64 and only erpnext stack build is taking only less then 6 minutes
And now with trial and error I took conclusion that there were no any error in Dockerfile
It was git who is not preserving files permission when cloning repository without root
So i had to clone repository with sudo and then build it successfully.

I have 2 suggestions 
1. Add image build instructions and mention to clone frappe repository with sudo 
2. Add files permission externally in Dockerfile COPY command so they get exact permission if user didn't cloned with sudo

And also you find it appropriate than you can revert my PR.
Thanx

**Comment by revant** [comment]
can you send a PR as per your suggestion @Morakhiyasaiyam?

@vrslev any comments?

**Comment by revant** [comment]
> Add files permission externally in Dockerfile COPY command so they get exact permission if user didn't cloned with sudo

can you share the line you used here? If it's minor I'll send the PR.

**Comment by Morakhiyasaiyam** [comment]
> > Add files permission externally in Dockerfile COPY command so they get exact permission if user didn't cloned with sudo
> 
> can you share the line you used here? If it's minor I'll send the PR.

Hey 
As I mentioned I just cloned repository with root user to preserve permission of file 
But it also achieved but COPY command in Dockerfile but when I was investigated some files needed different permission in some COPY command so i will look further and update it in some time and will notify you !

**Comment by revant** [comment]
For v14 building images has changed. Create new issue if needed.
