### ISSUE TITLE
Not Found page

### ISSUE THREAD

**Issue by Pazdo** [frappe/frappe_docker#852]
## Description of the issue
Installed erpnext/frappe with this tutorial with docker https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md, Installed on debian 10, debian 11, ubuntu 20.04 server, everytime starting both benches containing one site results in random Not Found, site does not exist. Stopping one of the two backend services results in oposing page working without random Not Found drops. Running two benches continuosly results in Not Found drops every second refresh or more. In every volume containing sites, I created currentsite.txt with belonging site, did't helped.  Is there new version of tutorial or Am I Missing something? Thank you. 
## Steps to reproduce the issue

1. Install two benches via single-server-example
2. Start both projects 
3. Try refreshing both pages 

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
try renaming the services?

if there is `frontend` service in one stack make it frontend-two in other stack. Then try again?

**Comment by Pazdo** [comment]
Thank you, Renaming all services helped. In my opinion, there was problem with same name in `backend `service, as both `frontend `services were reffering to `backend:8000`. Please, consider updating documentation.

**Comment by revant** [comment]
> Please, consider updating documentation.

can you add a note in docs?

or if there a way to keep the services same and manage availability using networks. Add soon as we share networks and containers names start conflicting.

**Comment by Pazdo** [comment]
@revant  Made pull request, only thing needed was to repair default config.


https://github.com/frappe/frappe_docker/pull/857

**Comment by Pazdo** [comment]
Problem was, there was mariadb network for every backend service and frontend service. Frontend service then sees every backend service. Now you don't need to rename services as frontend service is not connected to mariadb-network, mariadb-network is needed only in backend service.
