### ISSUE TITLE
[Custom Apps] Assest doesn't transfered

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#853]
## Description of the issue
I edit the frontend docker file to add my 8 custom apps, but I face a problem that when I migrate apps to the site, some js files and images are not appear
I check the front-end container, I find a folder for 1 custom app only.

## Context information (for bug reports)

my Dockerfile:

```

ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION

FROM frappe/assets-builder:${FRAPPE_VERSION} as assets

ARG APP_NAME

COPY MY_APP1/ apps/MY_APP1
RUN install-app MY_APP1

COPY MY_APP2/ apps/MY_APP2
RUN install-app MY_APP2


FROM frappe/erpnext-nginx:${ERPNEXT_VERSION}

COPY --from=assets /out /usr/share/nginx/html
```
### Logs

```
+ APP=MY_APP2
+ cd /frappe-bench
+ test -d apps/MY_APP2/MY_APP2/public
+ cleanup
+ rm -rf apps/MY_APP2
+ rm -rf 'sites/assets/*'
+ exit 0
```

### Expected result
images and files shown in /usr/share/nginx/html/assests

**Comment by sdfateh** [comment]
### Investigations:

I found that the problem is in "volumes". When I first tried the front-end Dockerfile, I only added one app, and it worked perfectly.
But when I add many other apps, their assets are not showing up in the Nginx counter.

### Solution:

**Delete** the `frappe_docker_assets` volume when adding a new app **if you have run the container before**.

**Comment by revant** [comment]
https://gist.github.com/revant/6a67f775aa8198f9b306f32d6872799f#file-erpnext-v13-yaml-L177

```yaml
  # populate-assets:
  #   image: frappe/erpnext-nginx:${VERSION}
  #   deploy:
  #     restart_policy:
  #       condition: none
  #   entrypoint: ["sh", "-c"]
  #   command:
  #     - >
  #       cp -fR /usr/share/nginx/html/assets /data;
  #       touch /data/sites/.build;
  #   volumes:
  #     - assets-vol:/data/assets:rw
  #     - sites-vol:/data/sites:rw
```

can something like this work for you?
