### ISSUE TITLE
Accessing ERPNext's API is blocked by CORS

### ISSUE THREAD

**Issue by jrGabrillo** [frappe/frappe_docker#860]
I just installed the ERPNext in my Digital Ocean's  Centos 7 Droplet.
Installation went well and I was able to restore the ERPNext from a different server. 

Then when I integrate the ERPNext's API to my react jr webpage, it is blocked by CORS

## Steps to reproduce the issue
1. Install ERPNext
2. Run React Js page that is integrated into the newly deployed ERPNext
3. API call in the React Js page is blocked by CORS

### Observed result
API calls from React Js page are blocked by CORS. 
I think Traefik is blocking the CORS. I have tried adding the following labels below in compose.traefik.yml but it doesn't work. 
      - traefik.http.middlewares.testheader.headers.accesscontrolalloworigin=*
      - traefik.http.routers.service.middlewares=serviceheaders

### Expected result
Integration should work well. 

CORS result
<img width="1417" alt="Screen Shot 2022-07-26 at 5 34 01 PM" src="https://user-images.githubusercontent.com/19164950/180975925-7a344835-e56c-4222-a0b1-3846b3813480.png">

**Comment by revant** [comment]
https://frappeframework.com/docs/v13/user/en/basics/site_config#optional-settings-2

user allow_cors in site_config.json

**Comment by jrGabrillo** [comment]
I have tried that as well. and it doesn't work.

**Comment by jrGabrillo** [comment]
I finally solved this issue. 
To those who will experience the same issue, here is how I fixed it. 
Make sure everything is running well to ensure success. 

This command is found here:  https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#edit-configs
$ docker run --rm -it  -v <project-name>_sites:/sites alpine vi /sites/common_site_config.json
This will open the common_site_config.json file in Vim.
Add this config:
