### ISSUE TITLE
Docker For developer frappe/bench:latest bench --version => 5.0.0-dev

### ISSUE THREAD

**Issue by FHenry** [frappe/frappe_docker#863]
Hello,

As I was setting up new dev environement I was surprise to see that 
$bench --version
5.0.0-dev

Instead of 5.12.0 for "normal" bench install.

Is that the bench version put into docker image is dated and don't have the same feature than the production ones ?
Or is it just that in frappe/bench project the version number is not really updated on develop branch (like in version-XX-hotfix branch for erpnext) ?

**Comment by revant** [comment]
we use the cloned repository instead of pip package frappe-bench

it is assumed that the default branch of frappe/bench repo has the latest code even the unreleased one.

**Comment by FHenry** [comment]
I undestand and it more for bench dev team to change it or not, any way thanks for the answer
