### ISSUE TITLE
pip3 version provide with docker  frappe/bench:latest is outdated

### ISSUE THREAD

**Issue by FHenry** [frappe/frappe_docker#864]
when playing with pip3 inside frappe container
WARNING: You are using pip version 22.0.4; however, version 22.2.1 is available.
You should consider upgrading via the '/home/frappe/.pyenv/versions/3.10.5/bin/python3.10 -m pip install --upgrade pip' command.

**Comment by revant** [comment]
We're not using python distributed by debian. We're using pyenv python. We've setup for 3.10 and 3.7 for v12
pip is not installed using apt-get.

Upgrade whenever you setup the `env`

What else do you wish to do?

**Comment by FHenry** [comment]
Thank's for reply, I'll do a documentation PR. 
There is no real impact, it's just a warning message when I try to upgrade bench with pip but with bad call. That's all right
