### ISSUE TITLE
broken PDF export

### ISSUE THREAD

**Issue by smmitc** [frappe/frappe_docker#865]
## Description of the issue

PDF files for quotations and invoices are rendered incorrectly in ERPNext v13.30.0 and above. There is a [related issue](https://github.com/frappe/erpnext/issues/31488) but I think this is related to docker so I've opened this issue.

## Context information (for bug reports)

I observed this issue in ERPNext using docker and Kubernetes.

Used versions for docker compose on my development machine:
```
Ubuntu 20.04.4 LTS
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
Docker Compose version v2.2.3
```

Used versions on my server with k3s:
```
Ubuntu 22.04 LTS
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

## Steps to reproduce the issue

Install ERPNext using docker compose:
```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
mkdir ~/gitops
docker compose -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  config > ~/gitops/docker-compose.yml

docker compose --project-name example -f ~/gitops/docker-compose.yml up -d
docker exec example-backend-1 bench new-site localhost --mariadb-root-password 123 --admin-password secret --install-app erpnext
```

In the setup, I've used the following values:
```
Language: english
Country: United states
Timezone: CT America/Chicago
Currency: US Dollar

Full Username: Administrator
Login: admin@example.org
Password: secret

Domains: [Services]

Organization: Example Org
short: EO

What does the company do: Build tools for builders
Name of the bank: Bank of America
Chart of Accounts: Standard
```

Generate customer, item and quotation:
```
curl --cookie-jar erpcookie --request POST "http://localhost:8080/api/method/login" -H 'Content-Type: application/json' -H 'Accept: application/json' --data-raw "{ \"usr\" : \"admin@example.org\", \"pwd\": \"secret\" }"
curl --cookie erpcookie "http://localhost:8080/api/resource/Item" -H 'Accept: application/json' -d '{"item_code": "my Service","item_group": "Services","stock_uom": "hour","is_stock_item": "0","standard_rate": "1000"}'
curl --cookie erpcookie "http://localhost:8080/api/resource/Customer" -H 'Accept: application/json' -d '{"customer_name": "Customer 1","customer_type": "Company","customer_group": "Commercial","territory": "All Territories"}'
curl --cookie erpcookie "http://localhost:8080/api/resource/Address" -H 'Accept: application/json' -d '{"address_title": "Customer 1","address_type": "Billing","address_line1": "Mall Street 1","city": "NYC","country": "United States","links": [{"link_doctype": "Customer","link_name": "Customer 1","__unsaved":0}]}'
curl --cookie erpcookie "http://localhost:8080/api/resource/Quotation" -H 'Accept: application/json' -d '{"naming_series": "SAL-QTN-.YYYY.-","quotation_to": "Customer","party_name":"Customer 1","company": "Example Org","order_type": "Sales","transaction_date": "2022-07-28","currency": "USD", "conversion rate": "1","plc_conversion_rate":"1","selling_price_list": "Standard Selling", "items": [{"item_code":"my Service","qty":"1"}]}'
```

### Observed result

Generated PDF file contains the text "Print Get PDF" with additional whitespace.
![v13 32 0](https://user-images.githubusercontent.com/110170775/181819446-58d54eec-da8b-49db-b165-2cc60cbc242d.png)

### Expected result

PDF is generated without errors like in ERPNext v13.29.2 and below.
![v13 31 1](https://user-images.githubusercontent.com/110170775/181819492-57b4052a-104d-4c05-aaa4-e30ea6035b14.png)

### Additional information

When I switch the version of the worker image to v13.29.2 or below the PDF is generated correctly, with v13.30.0 and above not. Deleting the docker volume `frappe_docker_assets` doesn't help.

**Comment by polycurve** [comment]
As a temporary workaround, you can add this to the CSS.

`.action-banner { visibility: hidden; }`

**Comment by smmitc** [comment]
> `.action-banner { visibility: hidden; }`

That solves the issue for me. Thank you very much!

**Comment by casesolved-co-uk** [comment]
> As a temporary workaround, you can add this to the CSS.
> 
> `.action-banner { visibility: hidden; }`

Which css specifically?
Presumably a print template somewhere.
Has this been raised and fixed in frappe itself?

**Comment by casesolved-co-uk** [comment]
Fixed here, just needs a bench build apparently...
https://github.com/frappe/frappe/issues/17171
