### ISSUE TITLE
/api/method/erpnext.templates.pages.product_search.get_product_list not working on develop and version-14

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#866]
### Information about bug

Automated tests for frappe_docker for develop and version-14-beta branches tries to test erpnext by requesting `/api/method/erpnext.templates.pages.product_search.get_product_list` endpoint

https://github.com/frappe/frappe_docker/blob/5c74ff9407620741448b14b8c00f546d1c19bd83/tests/test_frappe_docker.py#L138

The tests are failing for develop and v14 since 2 days.

Logging the issue for reference

### Module

ecommerce

### Version

frappe version : develop / version-14-beta
erpnext version : develop / version-14-beta

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

v14: https://github.com/frappe/frappe_docker/runs/7563145625?check_suite_focus=true#step:10:1628
develop: https://github.com/frappe/frappe_docker/runs/7570733828?check_suite_focus=true#step:10:1627

**Comment by dj12djdjs** [comment]
@revant  Yes, you can watch for required apps from the required_apps hook

https://github.com/frappe/erpnext/blob/590e91bb80d919cd7743e0368d710c4ed4663eaf/erpnext/hooks.py#L13

**Comment by revant** [comment]
> required_apps hook

@dj12djdjs It is a python list `required_apps=["payments"]`. Nothing that helps for automation. Where to clone from? frappe/payments? which version? develop? Too many assumptions for script to be written.

I'll depend on daily container builds and tests for now. It helped me detect and fix this change anyway.

**Comment by ankush** [comment]
@revant there's `--resolve-deps` flag in bench CLI that auto-installs dependencies. 


https://github.com/frappe/bench/pull/1257

**Comment by revant** [comment]
no bench in production images
