### ISSUE TITLE
Request building ARM Docker Image

### ISSUE THREAD

**Issue by JingerTea** [frappe/frappe_docker#870]
Can you please provide a guide of how to build ARM Docker Image locally? Or a EST time for this to be available?

**Comment by revant** [comment]
After the release of v14 we can re-check how much time it takes to build arm64 images for v14. I think v14 is lighter than v13.

Edit the docker-bake.hcl file and add platforms for targets, check docs https://docs.docker.com/engine/reference/commandline/buildx_bake/

then execute `docker buildx bake --load`.

If you don't wish to edit the hcl file you can set the platforms via cli. Refer docker buildx bake docs.

**Comment by kirtan403** [comment]
@revant I'm a newbie and trying to build for arm64. From where should I run this `docker buildx bake` command?
From the images folder or somewhere else?

**Comment by kirtan403** [comment]
I ran the command `docker buildx bake --set *.platform=linux/arm64` from the root folder. It took ~20 mins to complete. After that I am running the docker compose file generated from the steps mentioned in the https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

But I'm still getting the same error:

```
ktx-erpnext-configurator-1   | exec /usr/local/bin/configure.py: exec format error
```

What am I missing?

**Comment by revant** [comment]
try with `--no-cache`.

so it'll pull latest base images instead of using from available.

all the Frappe base images need to be built with arm64,

**Comment by siddhpant** [comment]
> After the release of v14 we can re-check how much time it takes to build arm64 images for v14. I think v14 is lighter than v13.

So what is the verdict? Are arm64 images built now? I get the following on an arm64 vm:

```
Pulling configurator (frappe/erpnext:v14.16.0)...
v14.16.0: Pulling from frappe/erpnext
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by mykeysr** [comment]
+1
