### ISSUE TITLE
Python Version Frappe 14

### ISSUE THREAD

**Issue by Tom-Finke** [frappe/frappe_docker#873]
Since Frappe V14, Initializing the App doesn't work because frappe v14 need python 3.10 but the container still has 3.9
Replicate: https://github.com/frappe/frappe_docker/tree/main/development

**Comment by revant** [comment]
`docker pull frappe/bench:latest`

Rebuild and reopen in devcontainer. Make sure your `env` is also updated. you can remove the `env` directory and `bench setup env` again.

https://github.com/frappe/frappe_docker/blob/a20dd916d22492e770d3cd67dccd82af7211ac2e/images/bench/Dockerfile#L81-L83

There are 3 python versions available to develop v12, v13, v14/develop

**Comment by Tom-Finke** [comment]
That did it, thanks 👍
