### ISSUE TITLE
version 14 - Install officials custom apps

### ISSUE THREAD

**Issue by guilmori** [frappe/frappe_docker#876]
It has been a while since I’ve been here, I see the documentation has greatly improved, good job 👍 

Now that version 14 is out, and many modules have been extracted to custom apps, I’d like to see how to install a couple of custom apps, following this [great tutorial ](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md) 

I saw this [custom app doc](https://github.com/frappe/frappe_docker/tree/main/custom_app), but it seems targeting how to build our own custom app images.

**Comment by revant** [comment]
Right now there is no official image with all apps.
You need to build your own image with required official as well as custom apps.

Using the official docs, I have example repo here https://github.com/castlecraft/custom_frappe_docker

Any suggestions you have to make it even easier?

**Comment by guilmori** [comment]
Ah I see. 

As per installation instructions of most/all custom apps, I thought the usual get-app / install-app was to be executed somehow on startup of container, but this isn’t probably the docker way.

**Comment by sdfateh** [comment]
@revant @guilmori 

I suggest that we make an image for each app, and an image that collects all the applications, in this way, whoever needs one application can get it, and whoever needs more than one application takes the general image and install the required application directly on the site.

**Comment by guilmori** [comment]
Your comment really puzzle me… how can Frappe recommend docker as de facto method of installation when they don’t maintain proper images ?

**Comment by revant** [comment]
They recommend frappecloud or some plan that'll support your self hosted environment. I've not checked the latest offer. And if you go for self-host plan (if it exists) most probably it'll be manual setup on VM.

I prefer containers with all its best practices, so I shared my setup with community. Container using community helped in improving it and getting this repo where it is. My update fails, I fix and contribute. Others do the same. Rest there are open issues that no one has answers yet.

Most of the veterans don't use containers. For newcomers who have already used containers, this repo will make sense. Newcomers who have not used containers but get lost in 50 step rituals turn to 4-5 step container setup rituals and may have more probability of success. 

Recommending docker for ritual following newcomer is better than recommending manual setup.

Why you'll get free support from me? 1) I use it. 2) Customers of [company that I own](https://www.castlecraft.in) use it.

**Comment by revant** [comment]
`frontend.Dockerfile` that works with `version-14`

```dockerfile
# syntax=docker/dockerfile:1.3

ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION

FROM frappe/bench:latest as assets

ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION

USER root

WORKDIR /builds

RUN chown -R frappe:frappe /builds

USER frappe

RUN bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /builds/bench

WORKDIR /builds/bench

# Comment following if ERPNext not required
RUN bench get-app --branch=${ERPNEXT_VERSION} --skip-assets --resolve-deps erpnext

COPY --chown=frappe:frappe repos apps

RUN bench setup requirements

RUN bench build --production --verbose --hard-link

FROM frappe/frappe-nginx:${FRAPPE_VERSION}

USER root

RUN rm -fr /usr/share/nginx/html/assets

COPY --from=assets /builds/bench/sites/assets /usr/share/nginx/html/assets

USER 1000
```

**Comment by DrZoidberg09** [comment]
@revant Thank you so much for the updated Docker files. So far, it now correctly populaltes assets for erpnext, frappe and payments (basically the official apps).

However, the assets of my custom apps still dont work. Nothing gets copied to the assets folder, even tough the apps get otherwise installed correctly. 

This is my dockerfile:

```
ARG FRAPPE_VERSION=version-14

# Prepare builder image
FROM frappe/bench:latest as assets

ARG FRAPPE_VERSION=version-14
ARG ERPNEXT_VERSION=version-14
ARG APP_NAME1
ARG APP_NAME2
ARG APP_NAME3
ARG APP_NAME4
ARG APP_NAME5
ARG APP_NAME6
ARG APP_NAME7

# Setup frappe-bench using FRAPPE_VERSION
RUN bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /home/frappe/frappe-bench
WORKDIR /home/frappe/frappe-bench

# Comment following if ERPNext is not required
RUN bench get-app --branch=${ERPNEXT_VERSION} --skip-assets --resolve-deps erpnext

# Copy custom app(s)
COPY --chown=frappe:frappe . apps/${APP_NAME1}
COPY --chown=frappe:frappe . apps/${APP_NAME2}
COPY --chown=frappe:frappe . apps/${APP_NAME3}
COPY --chown=frappe:frappe . apps/${APP_NAME4}
COPY --chown=frappe:frappe . apps/${APP_NAME5}
COPY --chown=frappe:frappe . apps/${APP_NAME6}
COPY --chown=frappe:frappe . apps/${APP_NAME7}

# Setup dependencies
RUN bench setup requirements

# Build static assets, copy files instead of symlink
RUN bench build --production --verbose --hard-link


# Use frappe-nginx image with nginx template and env vars
FROM frappe/frappe-nginx:${FRAPPE_VERSION}

# Remove existing assets
USER root
RUN rm -fr /usr/share/nginx/html/assets

# Copy built assets
COPY --from=assets /home/frappe/frappe-bench/sites/assets /usr/share/nginx/html/assets
COPY . apps/cn_theme/cn_theme/public/* /usr/share/nginx/html/assets/cn_theme
COPY . apps/cn_app/cn_app/public/* /usr/share/nginx/html/assets/cn_app
COPY . apps/erpnext_germany/erpnext_germany/public/* /usr/share/nginx/html/assets/erpnext_germany

# Use non-root user
USER 1000
```

**Comment by revant** [comment]
If you have multiple apps to be built into an image use a builder repo.

```
COPY --chown=frappe:frappe . apps/${APP_NAME1}
```

The above statement copies same directory (`.`) to `apps/${APP_NAME1}`, `apps/${APP_NAME2}`, etc.

Instead it should copy multiple apps.

```
COPY --chown=frappe:frappe repos apps
```

`repos` is local directory where you clone all your apps first using a script. e.g. https://github.com/castlecraft/custom_frappe_docker/blob/main/ci/clone-apps.sh

**Comment by DrZoidberg09** [comment]
Yes, that worked! Thank you

**Comment by kirtan403** [comment]
I was trying to add HRMS with the following command:

```
docker compose --project-name erpnext exec backend bench get-app hrms
```

But it throws the error:

```
Usage: bench frappe [OPTIONS] COMMAND [ARGS]...
Try 'bench frappe --help' for help.

Error: Only Frappe framework bench commands are available in container setup.
https://frappeframework.com/docs/v13/user/en/bench/frappe-commands

No such command 'get-app'.
```

I guess this is not going to work and that is why we need to update the frontend dockerfile to include those apps and build the image ourself than using the official image.

**Comment by fecoderchinh** [comment]
If you want to build frappe docker with producion mode, you have to use `install-app` instead.
But you must build your own image for your custom_app for first.
Just follow Dockerfile in @revant repo [https://github.com/castlecraft/custom_frappe_docker](https://github.com/castlecraft/custom_frappe_docker)
You can also check the `pwd.yml` for more details

**Comment by kirtan403** [comment]
@fecoderchinh Thanks for providing details. So, I'm just trying to understand the whole ecosystem here. What is happening here is, we need to build the custom image (that is understood as we need to include those apps manually into our image as everyone does not want everything), and then use [this guide](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md) for deploying using docker compose. Am I correct or missing something? 

With the docker compose, I might need to update the worker image name and nginx image name (backend and frontend) when building custom apps image.

**Comment by kirtan403** [comment]
@fecoderchinh I've just checked `pwd.yml` . What is the main purpose of this? This looks similar to my generated docker compose file from the [guide here](https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md)

**Comment by revant** [comment]
> Am I correct or missing something?

you are correct.

> I might need to update the worker image name and nginx image name (backend and frontend) when building custom apps image.

you'll need to replace it in all processes except websocket/socketio. workers, scheduler, frontend, backend.

> What is the main purpose of this?

Play with docker. You can use it to understand all components that are needed.

only thing that production setup add over this is TLS certificates. If you understand the PWD, you can even make the setup HA on k8s, mesos, nomad or wherever you can translate from pwd.yml

**Comment by kirtan403** [comment]
Thanks @revant That was quick and detailed!

**Comment by 1ubuntuuser** [comment]
@kirtan403 How'd you go? Get it going?

This has been discussed here: https://github.com/frappe/frappe_docker/issues/858 We need to put our heads together to figure something out. I'll be circling back to this soon.

**Comment by 1ubuntuuser** [comment]
I've started working on a "Quick Deploy" version. see https://github.com/MarqUnity/frappe_docker/tree

If you want to try it out just replace the `git clone https://github.com/frappe/frappe_docker.git` with git clone `https://github.com/marqunity/frappe_docker.git`

**Comment by revant** [comment]
Re-opened 858, continue related discussion there.

**Comment by 0FiRE0** [comment]
> `frontend.Dockerfile` that works with `version-14`
> 
> ```dockerfile
> # syntax=docker/dockerfile:1.3
> 
> ARG FRAPPE_VERSION
> ARG ERPNEXT_VERSION
> 
> FROM frappe/bench:latest as assets
> 
> ARG FRAPPE_VERSION
> ARG ERPNEXT_VERSION
> 
> USER root
> 
> WORKDIR /builds
> 
> RUN chown -R frappe:frappe /builds
> 
> USER frappe
> 
> RUN bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /builds/bench
> 
> WORKDIR /builds/bench
> 
> # Comment following if ERPNext not required
> RUN bench get-app --branch=${ERPNEXT_VERSION} --skip-assets --resolve-deps erpnext
> 
> COPY --chown=frappe:frappe repos apps
> 
> RUN bench setup requirements
> 
> RUN bench build --production --verbose --hard-link
> 
> FROM frappe/frappe-nginx:${FRAPPE_VERSION}
> 
> USER root
> 
> RUN rm -fr /usr/share/nginx/html/assets
> 
> COPY --from=assets /builds/bench/sites/assets /usr/share/nginx/html/assets
> 
> USER 1000
> ```

Hi @revant ,
I have been stuck for the past couple of days trying to install custom app in docker, and tried everything mentioned in the documentation of the `custom_app` https://github.com/frappe/frappe_docker/tree/main/custom_app, and also tried the file in the previous comment https://github.com/frappe/frappe_docker/issues/876#issuecomment-1239306339 for building the image.
But unfortunately, both have failed in the `frontend.Dockerfile` after executing the Build command `docker buildx bake -f docker-bake.hcl --load`.

It is facing an issue with Python version where the loaded version is 3.9.9 and it is expecting >=3.10 thus it is not able to proceed with building the image.

Partial log below:
```
#0 178.5   Downloading num2words-0.5.12-py3-none-any.whl (125 kB)
#0 178.6      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 kB 4.7 MB/s eta 0:00:00
#0 178.7 Collecting openpyxl~=3.0.7
#0 178.8   Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
#0 178.8      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 12.6 MB/s eta 0:00:00
#0 178.9 Collecting pyasn1~=0.4.8
#0 179.0   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
#0 179.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 295.9 kB/s eta 0:00:00
#0 179.4 Collecting google-api-python-client~=2.2.0
#0 179.5   Downloading google_api_python_client-2.2.0-py2.py3-none-any.whl (7.0 MB)
#0 180.4      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 7.5 MB/s eta 0:00:00
#0 180.7 Collecting psycopg2-binary~=2.9.1
#0 180.8   Downloading psycopg2_binary-2.9.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
#0 181.2      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 7.7 MB/s eta 0:00:00
#0 181.2 ERROR: Package 'frappe' requires a different Python: 3.9.9 not in '>=3.10'
#0 182.7 Traceback (most recent call last):
#0 182.7   File "/home/frappe/.bench/bench/commands/make.py", line 70, in init
#0 182.7     init(
#0 182.7   File "/home/frappe/.bench/bench/utils/render.py", line 95, in wrapper_fn
#0 182.7     return fn(*args, **kwargs)
#0 182.7   File "/home/frappe/.bench/bench/utils/system.py", line 78, in init
#0 182.7     get_app(
#0 182.7   File "/home/frappe/.bench/bench/app.py", line 354, in get_app
#0 182.7     app.install(verbose=verbose, skip_assets=skip_assets)
#0 182.7   File "/home/frappe/.bench/bench/utils/render.py", line 110, in wrapper_fn
#0 182.7     return fn(*args, **kwargs)
#0 182.7   File "/home/frappe/.bench/bench/app.py", line 185, in install
#0 182.7     install_app(
#0 182.7   File "/home/frappe/.bench/bench/app.py", line 405, in install_app
#0 182.7     bench.run(f"{bench.python} -m pip install {quiet_flag} --upgrade -e {app_path} {cache_flag}")
#0 182.7   File "/home/frappe/.bench/bench/bench.py", line 43, in run
#0 182.7     return exec_cmd(cmd, cwd=cwd or self.cwd)
#0 182.7   File "/home/frappe/.bench/bench/utils/__init__.py", line 126, in exec_cmd
#0 182.7     raise CommandFailedError
#0 182.7 bench.exceptions.CommandFailedError
#0 182.7
#0 182.7 ERROR: There was a problem while creating /builds/bench
#0 182.7 Do you want to rollback these changes? [y/N]: Aborted!
------
ERROR: failed to solve: executor failed running [/bin/sh -c bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /builds/bench]: exit code: 1
```

Appreciate your support on this.
Thank you.

**Comment by 0FiRE0** [comment]
After longer investigation sessions, I found the root cause of the issue and solved it.
The issue was in the `frappe/bench` package, as it was old and out-dated, for that reason it had an older version of python.
Although it was using the `latest` tag, but it was fetching it from the local repository instead of the one available in "Docker Hub".
The solution was just to delete the local image and pull the new image from "Docker Hub".

Remove the image by executing `docker rm frappe/bench:latest` then execute `docker pull frappe/bench`.

**Comment by revant** [comment]
Check the new guide for custom apps.

**Comment by saru2020** [comment]
on my Mac, i'm following the steps laid out [here](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) for custom apps and I'm facing the below error:

```
436.1 Found existing apps updating states...
436.1 WARN: restart failed: Couldn't find supervisorctl in PATH
436.1 A directory for the application 'frappe' already exists. Do you want to continue and overwrite it? [y/N]: Traceback (most recent call last):
436.1   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 75, in init
436.1     init(
436.1   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
436.1     return fn(*args, **kwargs)
436.1            ^^^^^^^^^^^^^^^^^^^
436.1   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", line 98, in init
436.1     install_apps_from_path(apps_path, bench_path=path)
436.1   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 1030, in install_apps_from_path
436.1     get_app(
436.1   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 761, in get_app
436.1     or click.confirm(
436.1        ^^^^^^^^^^^^^^
436.1   File "/usr/local/lib/python3.11/site-packages/click/termui.py", line 235, in confirm
436.1     raise Abort() from None
436.1 click.exceptions.Abort
436.1 
436.1 ERROR: There was a problem while creating /home/frappe/frappe-bench
436.1 Do you want to rollback these changes? [y/N]: 
------
Containerfile:117
--------------------
 116 |     ARG FRAPPE_PATH=https://github.com/frappe/frappe
 117 | >>> RUN export APP_INSTALL_ARGS="" && \
 118 | >>>   if [ -n "${APPS_JSON_BASE64}" ]; then \
 119 | >>>     export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
 120 | >>>   fi && \
 121 | >>>   bench init ${APP_INSTALL_ARGS}\
 122 | >>>     --frappe-branch=${FRAPPE_BRANCH} \
 123 | >>>     --frappe-path=${FRAPPE_PATH} \
 124 | >>>     --no-procfile \
 125 | >>>     --no-backups \
 126 | >>>     --skip-redis-config-generation \
 127 | >>>     --verbose \
 128 | >>>     /home/frappe/frappe-bench && \
 129 | >>>   cd /home/frappe/frappe-bench && \
 130 | >>>   echo "{}" > sites/common_site_config.json && \
 131 | >>>   find apps -mindepth 1 -path "*/.git" | xargs rm -fr
 132 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c export APP_INSTALL_ARGS=\"\" &&   if [ -n \"${APPS_JSON_BASE64}\" ]; then     export APP_INSTALL_ARGS=\"--apps_path=/opt/frappe/apps.json\";   fi &&   bench init ${APP_INSTALL_ARGS}    --frappe-branch=${FRAPPE_BRANCH}     --frappe-path=${FRAPPE_PATH}     --no-procfile     --no-backups     --skip-redis-config-generation     --verbose     /home/frappe/frappe-bench &&   cd /home/frappe/frappe-bench &&   echo \"{}\" > sites/common_site_config.json &&   find apps -mindepth 1 -path \"*/.git\" | xargs rm -fr" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/mz889b2h7j20hbrnfpqkouxn5

```

how do I solve it?

note: I got the same error for development setup but I've gotten rid of it by writing a custom sh script to give a reply when the command expects an input but I feel that's not the right way to do it either
