### ISSUE TITLE
Web bundles not loading- URGENT

### ISSUE THREAD

**Issue by varunblaze** [frappe/frappe_docker#881]
I have create a containerized custom app and using it as the worker image during new site creation. below is the snippet of appe-bench-erpnext-new-site-.... CRD:

```
      containers:
      - name: create-site
        image: "ghcr.io/xxx/xxxx:latest"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - >
            bench new-site $(SITE_NAME)
            --db-type=$(DB_TYPE)
            --db-host=$(DB_HOST)
            --db-port=$(DB_PORT)
            --db-name=dbname
            --admin-password=$(ADMIN_PASSWORD)
            --mariadb-root-username=$(DB_ROOT_USER)
            --mariadb-root-password=$(DB_ROOT_PASSWORD)
            --install-app=erpnext
            ;rm -f currentsite.txt
```

**backend.Dockerfile** of the app:

```
ARG ERPNEXT_VERSION=v14
FROM frappe/erpnext-worker:${ERPNEXT_VERSION}
USER root
ARG APP_NAME=myapp
COPY . ../apps/${APP_NAME}
RUN --mount=type=cache,target=/root/.cache/pip \
    install-app ${APP_NAME}
USER frappe
```
The deployment is successful and I am getting the login screen too. But after the authentication, pages are not getting loaded and I see the below error in the browser console :

`Loading failed for the <script> with source “http://domain.../erpnext-web.bundle.js?ver=1656397231.0”.

Loading failed for the <script> with source “http://domain../libs.bundle.js?ver=1656397231.0”. app:763:1
    Loading failed for the <script> with source “http://domain../desk.bundle.js?ver=1656397231.0”. app:765:1
    Loading failed for the <script> with source “http://domain../list.bundle.js?ver=1656397231.0”. app:767:1
    Loading failed for the <script> with source “http://domain../form.bundle.js?ver=1656397231.0”. app:769:1
    Loading failed for the <script> with source “http://domain../controls.bundle.js?ver=1656397231.0”. app:771:1
    Loading failed for the <script> with source “http://domain../report.bundle.js?ver=1656397231.0”. app:773:1
    Loading failed for the <script> with source “http://domain../erpnext.bundle.js?ver=1656397231.0”.
`

Screen looks like this:
![Screenshot 2022-07-25 at 11 11 58 am](https://user-images.githubusercontent.com/3373829/180675059-ef1ef95f-7fcf-47ca-826f-40a1c5366449.png)

How can I solve this issue? For testing purposes, I am still installing only the erpnext app instead of my custom app to be sure that the issue is not because of the custom app.

**Comment by varunblaze** [comment]
Hi Revant, I am still finding it hard to stabilize the container based deployments. Is there way to reach out to you directly? 

Now when I use to create job template and install my custom app I get the below error: 

 pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxxx-mariadb' ([Errno 111] Connection refused)")

The service is available and working

**Comment by revant** [comment]
> pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'xxxx-mariadb' ([Errno 111] Connection refused)")

can you confirm credentials
are all IP allowed to connect to db.
which db is this? one installed along with helm chart?

**Comment by revant** [comment]
I used `frappe/bench:latest` to build assets

```Dockerfile
# syntax=docker/dockerfile:1.3

ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION

FROM frappe/bench:latest as assets

ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION

USER root

WORKDIR /builds

RUN chown -R frappe:frappe /builds

USER frappe

RUN bench init --version=${FRAPPE_VERSION} --skip-redis-config-generation --verbose --skip-assets /builds/bench

WORKDIR /builds/bench

# Comment following if ERPNext not required
RUN bench get-app --branch=${ERPNEXT_VERSION} --skip-assets --resolve-deps erpnext

COPY --chown=frappe:frappe repos apps

RUN bench setup requirements

RUN bench build --production --verbose --hard-link

FROM frappe/frappe-nginx:${FRAPPE_VERSION}

USER root

RUN rm -fr /usr/share/nginx/html/assets

COPY --from=assets /builds/bench/sites/assets /usr/share/nginx/html/assets

USER nginx
```

**Comment by revant** [comment]
follow https://github.com/frappe/frappe_docker/issues/919
