### ISSUE TITLE
wkhtmltopdf reported an error

### ISSUE THREAD

**Issue by Altizo** [frappe/frappe_docker#884]
There is a problem with generating PDF files in v13 and v14
The solution is described in issue [https://github.com/frappe/erpnext/issues/31611](https://github.com/frappe/erpnext/issues/31611)

**Comment by revant** [comment]
we need to install patched wkhtmltopdf and not the one available on default debian repos

**Comment by revant** [comment]
create new issue. I'm closing due to no solution available.
