### ISSUE TITLE
Run erpnext on localhost

### ISSUE THREAD

**Issue by C-monC** [frappe/frappe_docker#890]
Hi,

I have no idea how to run the containers in this repo. I want to run the most basic erpnext production setup. Preferably with postgres. No reverse-proxy (Already have one).

I'll document my steps here.
```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
```
> We provide simple and intuitive production setup with prebuilt Frappe and ERPNext images and compose files. To learn more about those, [read the docs](https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md).

From the docs in **Compose files** 
> After building the images we have to run the containers.

So I assume the Dockerfiles need to be built before proceeding.
/bench successfully builds.
/nginx fails with `fatal: repository 'apps/frappe' does not exist` but that's okay. Not critical for my setup.
/socketio and /worker fail similarly.

Maybe it's not necessary to prebuild, we continue.

Considering the naming of overrides, I'll run compose.yml as is. 
Fails with  `RuntimeError: Required environment variable "REDIS_CACHE" not set`. Okay cool .env not set but it is mentioned lower down.

**Selecting overrides and env vars:**
- compose.noproxy.yaml to expose ports to host
- compose.erpnext.yaml I don't want other apps
- compose.postgres.yaml Override db service to use postgres

Final compose builder script:
```
  docker compose \
  -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.postgres.yaml \
  -f overrides/compose.erpnext.yaml \
   config > ./test-compose.yaml
```

The .env (comments removed for a smaller post):
```
FRAPPE_VERSION=v14.3.0
ERPNEXT_VERSION=v14.0.1
DB_PASSWORD=changeit
LETSENCRYPT_EMAIL=mail@example.com
FRAPPE_SITE_NAME_HEADER=
UPSTREAM_REAL_IP_ADDRESS=
UPSTREAM_REAL_IP_HEADER=
UPSTREAM_REAL_IP_RECURSIVE=
ROUTER=erpnext-one
SITES=localhost
BENCH_NETWORK=erpnext-one
```
First error:
`RuntimeError: Required environment variable "REDIS_CACHE" not set`

Docs on this page don't show manual loading of .env is required. 
`docker-compose --env-file ./.env -f comp ......`

Variables with a description are not actually optional:
> Set only if external service for database is used.

So looks like I need to include override redis no matter what.
New .env:
```
FRAPPE_VERSION=v14.3.0
ERPNEXT_VERSION=v14.0.1
DB_PASSWORD=changeit
DB_HOST=db
DB_PORT=5432
REDIS_CACHE=
REDIS_QUEUE=
REDIS_SOCKETIO=
LETSENCRYPT_EMAIL=mail@example.com
FRAPPE_SITE_NAME_HEADER=
UPSTREAM_REAL_IP_ADDRESS=
UPSTREAM_REAL_IP_HEADER=
UPSTREAM_REAL_IP_RECURSIVE=
ROUTER=erpnext-one
SITES=localhost
BENCH_NETWORK=erpnext-one
```
New docker config:
```
  docker compose --env-file ./.env \
  -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.postgres.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.redis.yaml \
   config > ./test-compose.yaml
```
The compose now starts successfully:
frontend access shows localhost/0.0.0.0 does not exist
After adding FRAPPE_SITE_NAME_HEADER = localhost doesn't change the error
Setting sites to one.example.com and adding that to my host's hosts gives the same error.

I've tried many things not documented here but I feel like this was pretty much following the docs. 
I would appreciate some help getting erpnext running.

This process is a clean pull of master. 

Thanks.

**Comment by revant** [comment]
download pwd.yml from root of this two
repo and use it to deploy single site locally.
read through the file to change admin password, image, install apps.

```
docker compose -p erpnext -f pwd.yml up -d
```

**Comment by C-monC** [comment]
Thanks, the pwd.yml did the trick.
I changed db to postgres and it worked.

**Comment by C-monC** [comment]
I've modified pwd.yml to include 

```
  db:
    image: postgres:14
    deploy:
      restart_policy:
        condition: on-failure
    command: []
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql
```
I can login and I can do most things.
but on certain requests there are errors like 

> ["Syntax error in query:\nSELECT \"name\",\"year_start_date\",\"year_end_date\" FROM \"tabFiscal Year\" WHERE \"disabled\"= '0' AND (NOT EXISTS (SELECT \"tabFiscal Year Company\".\"name\" FROM \"tabFiscal Year Company\" WHERE \"tabFiscal Year Company\".\"parent\"=\"tabFiscal Year\".\"name\") OR EXISTS (SELECT \"tabFiscal Year Company\".\"company\" FROM \"tabFiscal Year Company\" WHERE \"tabFiscal Year Company\".\"parent\"=\"tabFiscal Year\".\"name\" AND \"tabFiscal Year Company\".\"company\"=%(param1)s)) ORDER BY \"year_start_date\",'DESC' {'param1': 'mycompany'}", "Traceback (most recent call last):\n  File \"apps/frappe/frappe/app.py\", line 69, in application\n    response = frappe.api.handle()\n  File \"apps/frappe/frappe/api.py\", line 54, in handle\n    return frappe.handler.handle()\n  File \"apps/frappe/frappe/handler.py\", line 45, in handle\n    data = execute_cmd(cmd)\n  File \"apps/frappe/frappe/handler.py\", line 83, in execute_cmd\n    return frappe.call(method, **frappe.form_dict)\n  File \"apps/frappe/frappe/__init__.py\", line 1599, in call\n    return fn(*args, **newargs)\n  File \"apps/frappe/frappe/__init__.py\", line 783, in wrapper_fn\n    retval = fn(*args, **get_newargs(fn, kwargs))\n  File \"apps/frappe/frappe/desk/query_report.py\", line 253, in run\n    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)\n  File \"apps/frappe/frappe/__init__.py\", line 783, in wrapper_fn\n    retval = fn(*args, **get_newargs(fn, kwargs))\n  File \"apps/frappe/frappe/desk/query_report.py\", line 87, in generate_report_result\n    res = get_report_result(report, filters) or []\n  File \"apps/frappe/frappe/desk/query_report.py\", line 68, in get_report_result\n    res = report.execute_script_report(filters)\n  File \"apps/frappe/frappe/core/doctype/report/report.py\", line 142, in execute_script_report\n    res = self.execute_module(filters)\n  File \"apps/frappe/frappe/core/doctype/report/report.py\", line 159, in execute_module\n    return frappe.get_attr(method_name)(frappe._dict(filters))\n  File \"apps/erpnext/erpnext/accounts/report/profit_and_loss_statement/profit_and_loss_statement.py\", line 18, in execute\n    period_list = get_period_list(\n  File \"apps/erpnext/erpnext/accounts/report/financial_statements.py\", line 74, in get_period_list\n    period.to_date_fiscal_year = get_fiscal_year(period.to_date, company=company)[0]\n  File \"apps/erpnext/erpnext/accounts/utils.py\", line 56, in get_fiscal_year\n    return get_fiscal_years(date, fiscal_year, label, verbose, company, as_dict=as_dict)[0]\n  File \"apps/erpnext/erpnext/accounts/utils.py\", line 90, in get_fiscal_years\n    fiscal_years = query.run(as_dict=True)\n  File \"apps/frappe/frappe/query_builder/utils.py\", line 76, in execute_query\n    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep\n  File \"apps/frappe/frappe/database/postgres/database.py\", line 187, in sql\n    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)\n  File \"apps/frappe/frappe/database/database.py\", line 209, in sql\n    self._cursor.execute(query, values)\npsycopg2.errors.SyntaxError: non-integer constant in ORDER BY\nLINE 1: ...any\".\"company\"='mycompany')) ORDER BY \"year_start_date\",'DESC'\n                                                                 ^\n\n"]

and 

> ["Syntax error in query:\nSELECT \"name\",\"year_start_date\",\"year_end_date\" FROM \"tabFiscal Year\" WHERE \"disabled\"= '0' AND (NOT EXISTS (SELECT \"tabFiscal Year Company\".\"name\" FROM \"tabFiscal Year Company\" WHERE \"tabFiscal Year Company\".\"parent\"=\"tabFiscal Year\".\"name\") OR EXISTS (SELECT \"tabFiscal Year Company\".\"company\" FROM \"tabFiscal Year Company\" WHERE \"tabFiscal Year Company\".\"parent\"=\"tabFiscal Year\".\"name\" AND \"tabFiscal Year Company\".\"company\"=%(param1)s)) ORDER BY \"year_start_date\",'DESC' {'param1': 'mycompany'}", "Traceback (most recent call last):\n  File \"apps/frappe/frappe/app.py\", line 69, in application\n    response = frappe.api.handle()\n  File \"apps/frappe/frappe/api.py\", line 54, in handle\n    return frappe.handler.handle()\n  File \"apps/frappe/frappe/handler.py\", line 45, in handle\n    data = execute_cmd(cmd)\n  File \"apps/frappe/frappe/handler.py\", line 83, in execute_cmd\n    return frappe.call(method, **frappe.form_dict)\n  File \"apps/frappe/frappe/__init__.py\", line 1599, in call\n    return fn(*args, **newargs)\n  File \"apps/frappe/frappe/__init__.py\", line 783, in wrapper_fn\n    retval = fn(*args, **get_newargs(fn, kwargs))\n  File \"apps/frappe/frappe/desk/query_report.py\", line 253, in run\n    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)\n  File \"apps/frappe/frappe/__init__.py\", line 783, in wrapper_fn\n    retval = fn(*args, **get_newargs(fn, kwargs))\n  File \"apps/frappe/frappe/desk/query_report.py\", line 87, in generate_report_result\n    res = get_report_result(report, filters) or []\n  File \"apps/frappe/frappe/desk/query_report.py\", line 68, in get_report_result\n    res = report.execute_script_report(filters)\n  File \"apps/frappe/frappe/core/doctype/report/report.py\", line 142, in execute_script_report\n    res = self.execute_module(filters)\n  File \"apps/frappe/frappe/core/doctype/report/report.py\", line 159, in execute_module\n    return frappe.get_attr(method_name)(frappe._dict(filters))\n  File \"apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py\", line 21, in execute\n    prepare_chart_data(data, filters)\n  File \"apps/erpnext/erpnext/assets/report/fixed_asset_register/fixed_asset_register.py\", line 132, in prepare_chart_data\n    period_list = get_period_list(\n  File \"apps/erpnext/erpnext/accounts/report/financial_statements.py\", line 74, in get_period_list\n    period.to_date_fiscal_year = get_fiscal_year(period.to_date, company=company)[0]\n  File \"apps/erpnext/erpnext/accounts/utils.py\", line 56, in get_fiscal_year\n    return get_fiscal_years(date, fiscal_year, label, verbose, company, as_dict=as_dict)[0]\n  File \"apps/erpnext/erpnext/accounts/utils.py\", line 90, in get_fiscal_years\n    fiscal_years = query.run(as_dict=True)\n  File \"apps/frappe/frappe/query_builder/utils.py\", line 76, in execute_query\n    return frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep\n  File \"apps/frappe/frappe/database/postgres/database.py\", line 187, in sql\n    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)\n  File \"apps/frappe/frappe/database/database.py\", line 209, in sql\n    self._cursor.execute(query, values)\npsycopg2.errors.SyntaxError: non-integer constant in ORDER BY\nLINE 1: ...any\".\"company\"='mycompany')) ORDER BY \"year_start_date\",'DESC'\n                                                                 ^\n\n"]

Is there an init script for postgres that I am missing?

**Comment by revant** [comment]
ERPNext doesn't work with postgres yet.
Only frappe will work

**Comment by C-monC** [comment]
Okay thank you. Then it works correctly.

**Comment by fecoderchinh** [comment]
> read through the file to change admin password, image, install apps.

Hello @revant 
I changed some code at `create-site` as below
```
bench get-app myapp git_url;
bench get-app hrms;
```
but it said
```
No such command 'get-app'.
Usage: bench frappe [OPTIONS] COMMAND [ARGS]...
Try 'bench frappe --help' for help.
```
Could you please help me to check and solve this?
