### ISSUE TITLE
PDF's fail to get generated on v14

### ISSUE THREAD

**Issue by moroslantia** [frappe/frappe_docker#894]
## Description of the issue

PDF's failed to get generated on frappe/erpnext v14

## Context information (for bug reports)
Docker based v14 (fresh installation)

## Steps to reproduce the issue

1. On any doctype item, click printer icon
2. Click PDF icon

### Observed result
Server error 

### Expected result
downloadable PDF (a latest v13 fresh installation works well)

### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.10/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: UnknownContentError


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1598, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 129, in download_pdf
    frappe.local.response.filecontent = get_pdf(html)
  File "apps/frappe/frappe/utils/pdf.py", line 46, in get_pdf
    frappe.throw(_("PDF generation failed because of broken image links"))
  File "apps/frappe/frappe/__init__.py", line 523, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 491, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: PDF-Generierung ist aufgrund fehlerhafter Verknüpfungen für Bilddateien fehlgeschlagen

```

**Comment by polycurve** [comment]
Do you have a `host_name` key set in your site_config.json?

**Comment by moroslantia** [comment]
Yes, host_name is set. 
I tried different ways to ensure and verify the setting. 
Ex. if i put a wrong host_name for testing, the error message results in HostNotFound error

**Comment by polycurve** [comment]
Few things to check:

1. Are you able to connect to the host from within the backend container?
2. Is there an entry in your /etc/hosts on your host OS for the hostname you're using? If so, comment it out and test.
3. What happens if you delete the `host_name` key from site_config.json?

**Comment by moroslantia** [comment]
Finally it works. I'm not sure what it solved at the end. 
`host_name` is set to FQDN + port like: https://erp.mydomain.tld:1234 

A image file was missing, which was used on one of the stock items. I don't know if this can be the root cause, since this image is not involved in the PDF's i wanted to print.

For the record:
> * Are you able to connect to the host from within the backend container?
Yes
> * Is there an entry in your /etc/hosts on your host OS for the hostname you're using? If so, comment it out and test.
No
> * What happens if you delete the `host_name` key from site_config.json?
The error as reported above occurs

**Comment by dawoodjee** [comment]
Hey @moroslantia which port are you using if encrypted?

I tried this and it didn't work

```
{
 "db_name": "xxx",
 "db_password": "xxx",
 "host_name": "xxx.app:443",
 "db_type": "mariadb",
 "domains": [
  "www.xxx.app"
 ],
 "encryption_key": "xxx="
}

```
