### ISSUE TITLE
Edge image not built

### ISSUE THREAD

**Issue by MarekPikula** [frappe/frappe_docker#92]
There is no `develop` branch here, so `edge` images are not being built by Travis.

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/tree/develop

https://travis-ci.org/frappe/frappe_docker/builds/657414944

https://hub.docker.com/layers/frappe/erpnext-assets/edge/images/sha256-a49e9d992d0c05e73ed8a48137a521b8cf096d57bad7d16623fa360fe4f8fdc9?context=explore
