### ISSUE TITLE
Feasibility of creating  worker image with a default site and app installed

### ISSUE THREAD

**Issue by pythonpen** [frappe/frappe_docker#923]
I am exploring the option of cluster deployment where - we don't have to run the job to create the site - but the image to have site files already pre-created in it.

And after deployment just run a db script to create the database and run any migration command.

The main objective is to avoid PVC for the worker image - the only stuff I see we need the PVC is for site folder and logs - logs we will take it out to stdio and not write to the log folder.

This way we can have a stateless images and deployment option after which just a few db patch or script can setup the site. 

Appreciate any pointers to this end. Thanks!

**Comment by revant** [comment]
> You can create a custom image from scratch that serves your purpose and override it in values. Use entrypoint.sh to create the first site if it doesn’t exist.

https://discuss.erpnext.com/t/custom-apps-on-erpnext-kubernetes/87932/9?u=revant_one
