### ISSUE TITLE
service "backend" is not running container 1 @shubham-samant 

### ISSUE THREAD

**Issue by pv4n** [frappe/frappe_docker#927]
@shubham-samant 

You have to add `-p` or `--project-name` to your operations commands

like this :
```
docker compose -p ai-team-erp exec backend bench new-site sitename.com --mariadb-root-password admin@123 --admin-pssword admin@123 
```
It will work like this.

@pv4n check if that helps you!

_Originally posted by @sdfateh in https://github.com/frappe/frappe_docker/issues/924#issuecomment-1247921795_

I did the following:
```
docker compose -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  config > ~/gitops/docker-compose.yml
  
docker compose --project-name erp -f ~/gitops/docker-compose.yml up -d

docker compose exec backend bench new-site erpsite --mariadb-root-password <same as .env password> --admin-password <password> --install-app chat --project-name erp
```

docker ps:
IMAGE                            COMMAND                  CREATED        STATUS                  PORTS                                       NAMES
frappe/erpnext-nginx:v14.1.0     "/docker-entrypoint.…"   20 hours ago   Up 20 hours             0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   erp-frontend-1
frappe/erpnext-worker:v14.1.0    "bench worker --queu…"   20 hours ago   Up 20 hours                                                         erp-queue-default-1
frappe/erpnext-worker:v14.1.0    "/home/frappe/frappe…"   20 hours ago   Up 20 hours                                                         erp-backend-1
frappe/erpnext-worker:v14.1.0    "bench worker --queu…"   20 hours ago   Up 20 hours                                                         erp-queue-long-1
frappe/erpnext-worker:v14.1.0    "bench schedule"         20 hours ago   Up 20 hours                                                         erp-scheduler-1
frappe/frappe-socketio:v14.6.0   "docker-entrypoint.s…"   20 hours ago   Up 20 hours                                                         erp-websocket-1
frappe/erpnext-worker:v14.1.0    "bench worker --queu…"   20 hours ago   Up 20 hours                                                         erp-queue-short-1
mariadb:10.6                     "docker-entrypoint.s…"   20 hours ago   Up 20 hours (healthy)   3306/tcp                                    erp-db-1
redis:6.2-alpine                 "docker-entrypoint.s…"   20 hours ago   Up 20 hours             6379/tcp                                    erp-redis-1

Still getting:
```service "backend" is not running container #1```

**Comment by shubham-samant** [comment]
@pv4n 
You have to pass -p <project_name> for the docker compose exec command as well.
Eg:

docker compose -p <project_name>  \
exec backend bench new-site <site_name>.localhost \ # use .localhost not .com etc if running on localhost of your system
--mariadb-root-password <DB_PASSWORD from .env> \
--admin-password <set_new_password> 


Hope that helps!

**Comment by revant** [comment]
Restart backend container and check if it keeps running.

Try to figure out why backend container stopped. use `docker logs`

If backend container is not available same commands can be used through any worker/queue containers. Image used is same.

If restart doesn't work. I think you have `common_site_config.json` not properly configured. You can verify by checking it. Exec into container or start container with sites volume and check (`cat common_site_config.json`).

**Comment by revant** [comment]
> FRAPPE_SITE_NAME_HEADER should be that same <site_name> that is used in "...new-site <site_name>.localhost" right?

if it is set to `$host` it'll auto pick from host header

https://nginx.org/en/docs/http/ngx_http_core_module.html#var_host
