### ISSUE TITLE
frontend exit 1 with `invalid variable name in /etc/nginx/conf.d/default.conf:63`

### ISSUE THREAD

**Issue by jeffery9** [frappe/frappe_docker#928]
## Description of the issue

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/frappe-entrypoint.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/09/16 02:01:37 [emerg] 1#1: invalid variable name in /etc/nginx/conf.d/default.conf:63
nginx: [emerg] invalid variable name in /etc/nginx/conf.d/default.conf:63
```
## Steps to reproduce the issue

1.  update repo.
2.  run command `docker-compose  --env-file  example.env -f compose.yaml -f overrides/compose.mariadb.yaml -f overrides/compose.redis.yaml -f overrides/compose.noproxy.yaml  -f overrides/compose.erpnext.yaml  up
`

### Observed result

1. `frontend_1` started and then exit.
2. 

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
can you check which variable name is invalid?

**Comment by jeffery9** [comment]
found the cause,  should define variable  `FRAPPE_SITE_NAME_HEADER`  as  `frontend`  in  `example.env `, or fix  variable ``FRAPPE_SITE_NAME_HEADER` in  `compose.yaml', change it to `FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-frontend}`

**Comment by revant** [comment]
`$$host` is needed for DNS multi tenancy. if `$$host` doesn't work for you, try `$$$$host`. Site called `frontend` needs to exist. That is not the case.

Create a site that can be resolved in your browser and it should work. e.g. for local setup erp.localhost, for live setup erp.example.com.
