### ISSUE TITLE
Missing node_modules for worker

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/frappe_docker#930]
Hi there,

I want to import Website Themes into my custom app. However, this requires a couple of node_modules (e.g. sass, quill, bootstrap).

For whatever reason they are not existent in the worker image / the persistent storage, but in nginx. This is somehow clear as they are defined dependencies according to the package.json.

After manually installing these node_modules it works well. However, this is not really the way it should be.

Do you have any clue why the node_modules between nginx and worker differ and how I can fix this?

Thank you so much!

**Comment by revant** [comment]
1) Build and copy the node_modules to nginx image. (debian-slim is used to build the node_modules)
2) populate assets on init with non-restarting container, it will copy node_modules from nginx image to assets volume for access from worker container. https://github.com/frappe/frappe_docker/issues/872#issuecomment-1203708755 (worker image is based on debian-slim, binary for node-sass, etc will work)

**Comment by DrZoidberg09** [comment]
Hi revant,

Thank you very much for your responsiveness and your help. Very much appreciated!

I think this is fully my mistake. I misunderstood the populate-assets job that is already incorporated in the Helm Chart.

I ran the migrate command in a rondom worker container rather than using the migrate job. And if so, I would need to run it in the Gunicorn container that is a worker container where the populate-assets job is run.

Now it seems to work flawlessly. 

Thanks again!
