### ISSUE TITLE
Error: No such option: --production

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/frappe_docker#932]
I've followed the README directions. Everything is fairly stock. Here's the build command I used: 

FRAPPE_VERSION=v13.39.0 ERPNEXT_VERSION=v13.39.0 docker buildx bake

It results in the following: 

writing image sha256:1510401c26b7ee1193aab9017b10ead149121bb235280fb833d1d5ad98de326f                                                                                   
0.0s

naming to docker.io/custom_app/worker:latest                                                                                                                              0.0s

  [frontend assets 7/7] RUN bench build --production --verbose --hard-link:
#21 1.922 Usage: bench  build [OPTIONS]
#21 1.922 Try 'bench  build --help' for help.
#21 1.922 
#21 1.922 Error: no such option: --production

error: failed to solve: executor failed running [/bin/sh -c bench build --production --verbose --hard-link]: exit code: 2

**Comment by revant** [comment]
in v13 there is no --production, use environment variable `FRAPPE_ENV=production`

it's only available under v14
