### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#94]
<strike>- Move Documentation to frappe website. Unnecessary to trigger builds on documentation changes</strike>
- [x] Describe each image separately in documentation
- [X] Section for single host docker-compose
- [ ] Section for multi node Docker swarm 
- [ ] Add and document Helm Charts for kubernetes based installation
- [x] Section to build production images based on frappe or erpnext images

**Comment by ddavidebor** [comment]
Consider kubernetes instead of docker swarm, nobody is supporting docker swarm anymore

**Comment by ddavidebor** [comment]
Also, please don't separate code documentation from the code, once you do it's impossible to enforce documentation improvements on pull request.

**Comment by revant** [comment]
> Please consider Kubernetes instead of docker swarm, nobody is supporting docker swarm anymore

Kubernetes is expensive!

DO the easiest and cheapest I found. Right now it will need 3 nodes, 1 load balancer, 1 object storage and block storages for installed stateful apps. Can anyone fund me a cluster for 15 days?

I think most of the users are looking for "free" / "affordable" single-host installation with least complications and costs. 

From docker-compose it is easy to move to docker swarm. May be someone can take a step to make a single machine docker swarm cluster.

For Self hosting users with no intention to build SaaS Docker swarm may be sufficient.

Of course! everything in my plan is going on for Kubernetes!

Here is an existing Helm-Chart and "Job" Resources that help in creating/backing up and migrating sites. https://gitlab.com/castlecraft/erpnext_kubernetes/-/tree/master/kubernetes

**Comment by ddavidebor** [comment]
For a simple and affordable single-host installation docker-compose is more than sufficient. if you don't have multiple nodes, there is no reason to use docker-swarm.

You can test kubernetes cluster on any single machine using minikube, you don't need a production grade cluster.

**Comment by revant** [comment]
I make helm chart using Minikube.

I need to test it in production

**Comment by ddavidebor** [comment]
If you can estimate the expenses for DO I'll see what I can do

**Comment by revant** [comment]
> If you can estimate the expenses for DO I'll see what I can do

for reference
https://github.com/frappe/frappe_docker/issues/106

I've shared this with DO support and ERPNext Foundation.

**Comment by ddavidebor** [comment]
#103 addresses point 2 " Describe each image separately in documentation" @revant

**Comment by revant** [comment]
Closing this issue
For helm chart #106 
For docker swarm #118
