### ISSUE TITLE
Nginx reverse proxy not working with ERPNext

### ISSUE THREAD

**Issue by solancer** [frappe/frappe_docker#941]
I'm trying to self-host ERPNext on my home server 

**Hardware Stack:**
AMD Ryzen 5th Gen 6 cores with 12 threads CPU
256 m.2 SSD (for boot)
1TB HDD LVM storage mounted on /home
16 GB DDR4 Ram with heat sink
GigaByte motherboard board
Cool master heat sink for CPU
Cool Master SMPS real 450 watts

**Server Tech Stack:**
Ubuntu 22.04 LTS Server
Docker
Nginx reverse proxy manager for reverse proxy
Static ipv6 address managed by cloudfront with a 300 MBPS internet connection

Since I'm using nginx reverse proxy I don't need Trafeik so I ran the below commands to get ERP Next running without Trafeik

```
sudo docker compose -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  config > /home/kiatronic/docker_apps/erpnext_gitops/docker-compose.yml
```
  
` sudo docker compose --project-name erpnext -f ~/docker_apps/erpnext_gitops/docker-compose.yml up -d`
  
` sudo docker compose --project-name erpnext exec backend bench new-site erpnext.sozeno.com`

![Screenshot 2022-09-29 at 1 34 01 AM](https://user-images.githubusercontent.com/800668/192886047-4204eaa1-365b-4eae-8793-26178d7466d8.png)

I made an entry on Nginx reverse proxy to point to my static server IP address

After this, I created a DNS entry on my Cloudflare dashboard

But when I access the site I get a 504 error

Upon trying to access the site directly through its local LAN IP address with 8080 I get a 

Not Found
192.168.*.* does not exist

**Comment by revant** [comment]
you need to access site by site name that you created it with. e.g. if you created `site1.local` access it using `http://site1.local:8080`. This will work only if you have `site1.local` pointing to `127.0.0.1` in `/etc/hosts`. OR create `site1.localhost` and access on `http://site1.localhost:8080`

`182.168.. does not exist` means it is trying to find site under the bench. If you wish to use only 1 site per bench then override [FRAPPE_SITE_NAME_HEADER](https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md#frappe_site_name_header) env variable.

**Comment by solancer** [comment]
@revant I'm still not able access the domain but now I was able to see a login page but it's just a frappe app not erp next 

![Screenshot 2022-10-01 at 2 28 41 AM](https://user-images.githubusercontent.com/800668/193355385-41194d22-39a0-48f3-93bd-dbd3ad0c8e4b.png)

**Comment by revant** [comment]
> I was able to see a login page from the IP LAN IP address but it's just a frappe app not erp next

when you created `bench new-site` add `--install-app=erpnext` or before you complete the wizard run `bench --site ... install-app erpnext`

No idea why your traefik, domain, ssl doesn't work. Mine works on traefik, istio/virtualservice, kubernetes/ingress-nginx.

**Comment by solancer** [comment]
@revant Ok let me try with the above --install-app=erpnext

Also what's the best way I can get rid of the old volume attached to my machine? I'd like to do a fresh install

**Comment by revant** [comment]
> what's the best way I can get rid of the old volume attached to my machine?

stop the container(s) using the volume and then delete the volume. check help for `docker stop` and `docker volume rm`

**Comment by solancer** [comment]
@revant Thank you, I actually wanted to know the path the volume `docker volume inspect`

Let me know if I could add your github public key for ssh access to access my bare metal server

**Comment by revant** [comment]
> Let me know if I could add your github public key for ssh access to access my bare metal server

Yes. Add my GitHub public key.

**Comment by solancer** [comment]
@revant I've added your public key to the login 

you can log in to masterchief@galactic.sozeno.com

It would be to wipe out the old frappe erpnext install and try again fresh

**Comment by revant** [comment]
Check single compose file

```
$HOME/docker_apps/erpnext_pwd/compose.yml
```

I used it to start the containers

```
cd ~/docker_apps/erpnext_pwd
docker compose -p erp-pwd up -d
```

I entered the backend container and created first site and set it as default

```sh
docker exec -it erp-pwd-backend-1 bash
# Following command executed in container
frappe@8346321b647a:~/frappe-bench/sites$ bench new-site frontend --admin-password=admin --db-root-password=admin --install-app payments --install-app erpnext --set-default;
```

Site is available at `http://galactic.sozeno.com:8080`

I don't have access to your Nginx Proxy Manager, you can block port 8080 on your VM with a firewall (ufw) and use Nginx Proxy Manager to proxy to internal port 8080.

once you understand the setup, clean it up and set it up again with secure passwords.

**Comment by solancer** [comment]
@revant this version of docker-compose works now thankyou.
Is there anything another config I need to take care of in case I need to swipe out the old docker images and volumes and recreate them?

```
$HOME/docker_apps/erpnext_pwd/compose.yml
cd ~/docker_apps/erpnext_pwd

docker compose -p erp-pwd up -d

docker exec -it erp-pwd-backend-1 bash
# Following command executed in the container
frappe@8346321b647a:~/frappe-bench/sites$ bench new-site frontend --admin-password=admin --db-root-
password=admin --install-app payments --install-app erpnext --set-default;
```

**Comment by revant** [comment]
> Is there anything another config I need to take care of in case I need to swipe out the old docker images and volumes and recreate them?

just the passwords need to be set to more secure ones for db as well as site admin

**Comment by solancer** [comment]
@revant Thanks you for all the help, really appreciate it
