### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: hr/doctype/job_opening/templates/job_opening_row.html

### ISSUE THREAD

**Issue by fecoderchinh** [frappe/frappe_docker#942]
## Description of the issue
I have built frappe docker in production mode and i have also installed hrms.
I can go to `localhost/jobs`
![image](https://user-images.githubusercontent.com/13318452/192938077-fa4d1f9a-cb97-4d09-9a6b-cea0cbda9671.png)

But when i added new job_opening, i got `error code 500` as the below image

## Context information (for bug reports)
![image](https://user-images.githubusercontent.com/13318452/192938251-ba1f27e7-256c-43c5-80ef-1dfd6cb9678e.png)

## Steps to reproduce the issue

1. Add Job Opening
2. Go to `localhost/jobs`
3. Error

### Observed result
![image](https://user-images.githubusercontent.com/13318452/192938251-ba1f27e7-256c-43c5-80ef-1dfd6cb9678e.png)
### Expected result
List of jobs
### Stacktrace / full error message if available

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/list_page.py", line 12, in render
    return super().render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
  File "apps/frappe/frappe/www/list.py", line 25, in get_context
    context.update(get(**frappe.local.form_dict))
  File "apps/frappe/frappe/www/list.py", line 63, in get
    rendered_row = frappe.render_template(row_template, new_context, is_path=True)
  File "apps/frappe/frappe/utils/jinja.py", line 80, in render_template
    return get_jenv().get_template(template).render(context)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "env/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "env/lib/python3.10/site-packages/jinja2/loaders.py", line 575, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: hr/doctype/job_opening/templates/job_opening_row.html
```

**Comment by revant** [comment]
if it is related to hrms app then you'll need to build your own custom image with hrms app

**Comment by fecoderchinh** [comment]
I have built my own image that included hrms and install properly (hrms was listed in the project).
![image](https://user-images.githubusercontent.com/13318452/192960911-44ae716c-10b2-4743-a77a-aaa53f9c4eda.png)
I think the problem occured on installing app by frappe_docker, i have tried uninstall and re-install hrms but it is not working. 
Any idea?

**Comment by fecoderchinh** [comment]
Hi @revant 
I think the problem happened when we change the language, in this case i selected Vietnamese.
And the installation progress may be changed based on the language.
Any idea to fix it?

**Comment by revant** [comment]
you can ask this on hrms repo? i don't know how the app code works.

**Comment by fecoderchinh** [comment]
I believe this issue come from the main progress as i said when i select language which is not English on the first Setup stage then i got the problem.
One more problem i think it related with this is that when i change language in the Settings page, my custom brand on frontend have been  replaced by E too.
Could you please try to check and reproduce for this? Try select another language and see if it work or not.

**Comment by ankush** [comment]
@ruchamahabal can you have a look at this?

**Comment by fecoderchinh** [comment]
Hey guys,
i tried increase docker memory and the problem seem gone.
i guess when i run app with low docker memory and then something went wrong.
i cannot make sure if i was right or not.

**Comment by fecoderchinh** [comment]
https://user-images.githubusercontent.com/13318452/193386735-762bda65-4ee4-45a1-9079-788d8de793fd.mp4

Here is the problem, but now it was gone after i changed docker memory.
Maybe something went wrong when we run the setup with slow bandwidth or low memory.

**Comment by revant** [comment]
Please create new issue it persists.
