### ISSUE TITLE
Question for Staffing Plan & Job Opening

### ISSUE THREAD

**Issue by fecoderchinh** [frappe/frappe_docker#943]
I have a question for creating job opening, there are 2 red lines as the below picture.
![image](https://user-images.githubusercontent.com/13318452/192939740-896369c5-aa6c-44c3-9e13-7347008e9de3.png)
I cannot ignore Designation as it is required and when i select a designation then the staffing plan is missing and i cannot see any relationship with these doctypes.
![image](https://user-images.githubusercontent.com/13318452/192940193-8e33a2a1-dd63-4229-a80a-e168516c57bf.png)

The question is How can i keep linking staffing plan with job opening in this case?

**Comment by revant** [comment]
if it is related to hrms app then you'll need to build your own custom image with hrms app

**Comment by fecoderchinh** [comment]
I found it.
For future user who has the same problem.
Check your `schedule_on` or `From Date` of `Staffing Plan`
