### ISSUE TITLE
Instructions do not install "payments" app.  Needs --resolve-deps flag.

### ISSUE THREAD

**Issue by geverit4** [frappe/frappe_docker#947]
## Description of the issue

Since Payments is now split out from ERPNext, the installation instructions on the Developer page cause an error when adding the ERPNext application. 

Perhaps add a new set of instructions to add the version 14 build of ERPNext:

```
bench get-app --branch version-14 --resolve-deps erpnext
bench --site mysite.localhost install-app erpnext
```

**Comment by revant** [comment]
You can't run command `bench get-app` in production containers.

You can only run `bench get-app` in `frappe/bench:latest` development container. The instructions you've shared will only work in development container.

Read this to build custom production images https://github.com/frappe/frappe_docker/blob/main/custom_app/README.md

example repo that builds custom images: https://github.com/castlecraft/custom_frappe_docker

**Comment by geverit4** [comment]
@revant that's a good point.  I was referring to the instructions for setting up a development container, not a production container.  
That is found  https://github.com/frappe/frappe_docker/tree/main/development#install-an-app
