### ISSUE TITLE
docker startup problem

### ISSUE THREAD

**Issue by louishot** [frappe/frappe_docker#949]
Hello,

compose.traefik.yaml and single-server-example.md did not add startup for production? for example restart: always inside yaml
I see only docs/compose/compose.mariadb-shared.yaml have restart: unless-stopped option

Thanks

**Comment by revant** [comment]
you can add what you want and send PR.

**Comment by louishot** [comment]
> I see only docs/compose/compose.mariadb-shared.yaml have restart: unless-stopped option

Ok I just want to know if I'm not turning a certain knob so did not apply startup option to the compose yaml file or still no knob at all

**Comment by revant** [comment]
if it works then it works!

Send PR if it works.

more about restart: https://docs.docker.com/compose/compose-file/compose-file-v3/#restart
