### ISSUE TITLE
Workers Call

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#954]
Greetings,

My question is how does the backend call the workers? where is the definition?
I can't find where they called

**Comment by revant** [comment]
check the code for `enqueue()`

https://frappeframework.com/docs/v14/user/en/guides/app-development/running-background-jobs

**Comment by sdfateh** [comment]
to clarify my question:

I'm asking about the docker container call, as an example: if I change the Redis service name in my docker-compose I have to edit the configuration, 

but what if I change the service name for any worker? where it reflect or where the name of the service defined

**Comment by revant** [comment]
> but what if I change the service name for any worker? where it reflect or where the name of the service defined

worker service name doesn't matter. you can scale them or name them as you wish.

that decides their type is their command

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/issues/912#issuecomment-1272252290
