### ISSUE TITLE
sites/apps.txt not updating with new custom apps

### ISSUE THREAD

**Issue by shivangag** [frappe/frappe_docker#958]
I've multiple custom apps cloned in repos folder inside custom_app, I've changed the backend.Dockerfile and frontend.Dockerfile to install these apps. When I build the custom image and run docker compose it correctly populates the sites/apps.txt with all the custom apps.
But after I clone more custom app in the repos directory, update the backend.Dockerfile, build image and run docker compose up again, the new apps are not added to apps.txt, which in turn doesn't allow me to install-app to my site.

**Comment by revant** [comment]
run configuration job/container

https://github.com/frappe/frappe_docker/blob/a7aae8a000b7ba4253768731087e7323e4aeed47/pwd.yml#L38-L57

Execut following command using worker image/container and correct mounted volume. It will add all apps from `apps` directory to `apps.txt`

```
ls -1 ../apps > apps.txt
```

In helm chart it is done here https://github.com/frappe/helm/blob/c0fc7f085493c9dfffda9f914604484dc9b45e36/erpnext/templates/job-configure-bench.yaml#L45
