### ISSUE TITLE
Install HR module 

### ISSUE THREAD

**Issue by ShinNgao12** [frappe/frappe_docker#959]
- Hello, I newbe in erpnext. 
- I am using version 14 for SINGLE SERVER and I know: "HR module is separated from base in update 14". When I read the documentation for installing HRMS app. But when install ERPNext, I only see install erpnext app. 
- So I want to hnow how to add HRMS app with erpnext app when install ERPNext  
PS: I try to install bench-frappe in backend container and use bench command but It not working.

**Comment by zvijayakumar** [comment]
@revant Official documentation link is not longer valid. Can you guide on installing HRMS module on ERPNext 14.

**Comment by revant** [comment]
Docs: https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
Forum: https://discuss.frappe.io/t/container-builds/99916/2
