### ISSUE TITLE
Got packet bigger than 'max_allowed_packet' when dumping

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#966]
When I do `bench backup` in the backend container for my DB (around 1 GB) I have this:

```
mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' when dumping table
```

It works with me when I mount `/etc/mysql/conf.d/` and edit `max_allowed_packet` to a higher number

Any idea to make it configurable without mounting configurations?

**Comment by revant** [comment]
Check documentation for mariadb docker https://hub.docker.com/_/mariadb

**Comment by sdfateh** [comment]
@revant why close? that does not help!

The issue is with the bench backup command which relies on the MariaDB client configurations in the bench container, and the edit must be in the backend container not in MariaDB!

**Comment by revant** [comment]
hope someone else answers.

I feel it's part of MariaDB configuration and depends on which mariadb you use.

under helm chart it's bitnami/Mariadb, under this setup it's official root container Mariadb. AWS RDS will be different.

https://github.com/frappe/bench/wiki/MariaDB-conf-for-Frappe you can refer this configuration for mariadb.

initially there was Mariadb configuration in file. it complicates things, I had to answer issues on how to mount files in containers, things about file permissions and ownership.

**Comment by revant** [comment]
labelled it as question because I feel it's related to Mariadb configuration. I feel it's not a bug with frappe_docker.

my suggestion is to solve it for yourself and add it in troubleshoot docs. the generated files are not stored in git repo anyway. you can modify your generated files to use advance configuration.

**Comment by sdfateh** [comment]
@revant 

I know exactly where the problem is, and the problem is in the MariaDB client configuration, the only solution is to modify it either through the worker's dockerfile, through a persistent volume in which the configuration is placed, or through something similar to Configurator Service in compose.

Since they are changing things, I think the most appropriate solution is the configurator.
Currently, I have used persistent volume, and I will try something like a configurator, I will send a PR in both cases.

**Comment by saru2020** [comment]
I'm facing this issue, whats's the solution for this?
