### ISSUE TITLE
How to Create Container?

### ISSUE THREAD

**Issue by creative-paramu** [frappe/frappe_docker#973]
I was running this below commands:
1.sudo docker-compose up -d
ERROR: Missing mandatory value for "image" option interpolating frappe/frappe-worker:${FRAPPE_VERSION:?No Frappe version set} in service "configurator": No Frappe version set
2.sudo docker-compose start
ERROR: Missing mandatory value for "image" option interpolating frappe/frappe-worker:${FRAPPE_VERSION:?No Frappe version set} in service "configurator": No Frappe version set
3.sudo docker exec -it frappe bash 
Error: No such container: frappe

How To solve this error Please Anyone known share your ideas.

**Comment by revant** [comment]
```
wget https://raw.githubusercontent.com/frappe/frappe_docker/main/pwd.yml -O compose.yml
docker compose -p frappe-bench up -d
```
- visit `http://localhost:8080` after 5-10 minutes. If you visit before that it'll show "site not found" or "internal server error"
- edit compose.yml to change passwords for database and administrator.
- understand the compose and inter connections for all services listed. If you understand that you can set the containers up anywhere
