### ISSUE TITLE
Limit IP for ERPNext

### ISSUE THREAD

**Issue by ShinNgao12** [frappe/frappe_docker#974]
Hello, 
I want to allow the devices which use my office's IP can be login ERPNext (not restrict access). I don't see any document about it..
Please help me.

Regards

**Comment by revant** [comment]
This is not related to containers.

Check Documentation for adding / updating User, https://docs.erpnext.com/docs/v14/user/manual/en/setting-up/users-and-permissions/adding-users#28-security-settings
