### ISSUE TITLE
frappe-assets should be renamed

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_docker#98]
frappe-assets/erpnext-assets name is incorrect, as the container does not only serve static assets, but it also proxies request. This is very confusing. I recommend renaming "assets" to "webserver"

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/pull/84#issuecomment-584086640

You can send a refactor PR please.

"frappe-nginx" "frappe-proxy"? frappe-webserver can be confused with gunicorn server?

**Comment by revant** [comment]
Moving discussion to pr
