### ISSUE TITLE
bench --site all list-apps doesn't show some app but available in apps.txt

### ISSUE THREAD

**Issue by owyah** [frappe/frappe_docker#983]
## Description of the issue
- Stock menu doesn't show in sidebar menu 
- `bench --site all list-apps` doesn't show some app but available in apps.txt
## Steps to reproduce the issue

1. I have installed ERPNext using docker-compose with this source: https://raw.githubusercontent.com/frappe/frappe_docker/main/pwd.yml
2. The problem is stock menu doesn't show in sidebar
3. I tried to check using Module Def (/app/module-def) and the stock is available
4. When I click the stock (/app/module-def/Stock) ERPNext doesn't show in App Name list

### Observed result

1. I enter to backend container, and add this command: `bench --site all list-apps`. It show frappe and payments only
2. when I add this command: `cat apps.txt`, it show frappe, payments and erpnext

### Expected result
Stock menu is showing up
### Stacktrace / full error message if available

I did not found any error message yet

**Comment by revant** [comment]
in pwd.yml the single site which is created is set to default using currentsite.txt.

--site will not affect the command is default site is set

**Comment by owyah** [comment]
> ## Description of the issue
> * Stock menu doesn't show in sidebar menu
> * `bench --site all list-apps` doesn't show some app but available in apps.txt
> 
> ## Context information (for bug reports)
> ## Steps to reproduce the issue
> 1. I have installed ERPNext using docker-compose with this source: https://raw.githubusercontent.com/frappe/frappe_docker/main/pwd.yml
> 2. The problem is stock menu doesn't show in sidebar
> 3. I tried to check using Module Def (/app/module-def) and the stock is available
> 4. When I click the stock (/app/module-def/Stock) ERPNext doesn't show in App Name list
> 
> ### Observed result
> 1. I enter to backend container, and add this command: `bench --site all list-apps`. It show frappe and payments only
> 2. when I add this command: `cat apps.txt`, it show frappe, payments and erpnext
> 
> ### Expected result
> Stock menu is showing up
> 
> ### Stacktrace / full error message if available
> I did not found any error message yet

so how to solve number 4. When I click the stock (/app/module-def/Stock) ERPNext doesn't show in App Name list? or should I remove `-set-default ` ?
