### ISSUE TITLE
socket.io version mismatch between server and client

### ISSUE THREAD

**Issue by khoran** [frappe/frappe_docker#994]
## Description of the issue
The socket.io client will not connect to the socket.io server in production mode. I eventually discovered that the frappe app provides the client with socket.io version 4.5.1, but the frappe-socketio container was using socket.io version 2.5.0, and the two are not compatible. This can be seen in images/socketio/package.json, where the socket.io version given is "^2.4.0". Npm seems to install 2.5.0, but neither is compatible with 4.5.1 which frappe 14.11 (at least) is providing to the client. 

Upon changing images/socketio/package.json to set the socket.io version to 4.5.1 and rebuilding the frappe-socketio container, websockets are again working.

## Steps to reproduce the issue

1. Deploy a production erpnext install following docs/single-server-example.md
2. Create a new site
4. On home page, open "inspect" in browser, view websockets. 

### Observed result
No websockets are opened as is. Even long polling is not working.

### Expected result
websocket connection should be established

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
We'll have to maintain 2 package.json or have some acrobatics done so version-13 can use `^2.4.0` and version-14 can use `^4.5.1`
