### ISSUE TITLE
Missing `VOLUME` declaration for exposed directories

### ISSUE THREAD

**Issue by moltar** [frappe/frappe_docker#997]
## Description of the issue

When deploying Docker containers to AWS ECS, and using EFS mounts, the files from the directories `/home/frappe/frappe-bench/{sites,sites/assets}` are not copied to the mounted dir.

## Context information (for bug reports)

Explanation of the issue: https://github.com/aws/containers-roadmap/issues/863

## Steps to reproduce the issue

1. Deploy a Fargate Task with an EFS mounted as `/home/frappe/frappe-bench/sites`
2. Log into ECS container
3. Do an `ls` inside `/home/frappe/frappe-bench/sites`

### Observed result

Empty dir

### Expected result

Files from the image to be copied into the mounted dir.

### Stacktrace / full error message if available

```
N/A
```

## Solution

Define volumes inside `Dockerfile`:

```Dockerfle
VOLUME ["/home/frappe/frappe-bench/sites"]
```

**Comment by revant** [comment]
Please send PR, I'll merge.

**Comment by revant** [comment]
there are no files in `sites` directory by default.

configure.py or bench set-config creates the common_site_config.json. the container with these commands should run separately as init containers or as configure containers if init is already done.

apps.txt is created by configure.py or `ls -1 ../apps > apps.txt`

sites/assets are mounted separate from nginx container.
they need to be deleted and recreated on update or run a populate-assets container that'll copy new assets in volume.

if adding VOLUME solves your problem then do add it in needed Dockerfiles and send PR.

**Comment by moltar** [comment]
Ok, thanks for the explanation.

> there are no files in sites directory by default.

✅ 

> apps.txt is created by configure.py or ls -1 ../apps > apps.txt

✅ 

> sites/assets are mounted separate from nginx container.

Question about this.

Why does the backend then even need these assets? Aren't they served exclusively by nginx?

**Comment by moltar** [comment]
Thanks, will close for now then.
