### ISSUE TITLE
Add wheel to avoid warnings

### ISSUE THREAD

**Issue by moltar** [frappe/frappe_docker#999]
Wondering if the solution outlined here can be added to the bench image?

https://discuss.erpnext.com/t/deprecation-pycountry-is-being-installed-using-the-legacy-setup-py-install-method-because-it-does-not-have-a-pyproject-toml/96079/4?u=_m0

https://github.com/frappe/frappe_docker/blob/main/images/bench/Dockerfile

**Comment by revant** [comment]
bench image is for easy development and builds, we can add anything that is needed. Just send PR.

**Comment by revant** [comment]
Can you add it here and check if it solves the issue?

https://github.com/frappe/frappe_docker/blob/7b5eac5d53b6ce7d7fd48d069c329ec3906db490/images/bench/Dockerfile#L101-L102

If that works we'll add it in image.

**Comment by revant** [comment]
will be fixed in #1032 using upstream bench which added wheel installation as part of init
